### ISSUE TITLE
letter transposition

### ISSUE THREAD

**Issue by JeffreySarnoff** [HowardHinnant/date#103]
```julia
tai_time counts physical seconds continuously like utc_itme
                                                       ^^
```
in [tz.html under tai_clock](https://howardhinnant.github.io/date/tz.html#tai_clock)

**Comment by HowardHinnant** [comment]
Thanks!

https://github.com/HowardHinnant/date/commit/e04ec9aa805ed7f9802dd271443991751a8590fc
