### ISSUE TITLE
splitting the tz database downloading logic

### ISSUE THREAD

**Issue by jkhoogland** [HowardHinnant/date#104]
Hi Howard,
thanks again for this very nice library.

I have two related questions.
I could not find anything in the issues mailing lists related to this.

1/ There is an enormous amount of logic in the tz library, that deals with downloading the `tzdata` files etc.  This is obviously useful, but orthogonal to the core logic.
All the logic on downloading, untarring, and unzipping has nothing to do with the tz logic, i would say...

It seems natural to separate this out.
It gives the user the flexibility to handle the updating of the `tzdata` automatically via your library,
or have some seperate process that handles this, independently of the tz library.

2/ Related to this, it would be nice to be able to specify the location of the `tzdata` directory programmatically. Currently it is all hardcoded in the code. Either being able to specify the path in `get_tzdb` or `reload_tzdb`, or being able to specify an environment variable with the path would be very useful.

I am curious to your thoughts on this ?
Regards
Jiri

**Comment by HowardHinnant** [comment]
Hi Jiri,

Thanks for your feedback.

1/  All of the download logic is under `#if HAS_REMOTE_API`.  Compiling with `-DHAS_REMOTE_API=0` will ensure that none of this logic gets compiled when you compile tz.cpp, leaving open the door for any other process (manual or automated) to manage the IANA database.

Are there shortcomings in controlling this aspect with the `HAS_REMOTE_API` flag?

2/  There exists a flag called `INSTALL` that you can `-D` on the command line and whatever that expands to will be the location of the `tzdata` directory.  Is this not sufficient?  Are you wanting to change the location of the database at run time?

**Comment by jkhoogland** [comment]
Hi,

1/ yes, I use HAS_REMOTE_API=0 to switch of the downloading logic.
It is more that I feel that the core library functionality should not be put together with all the remote logic.
Now I understand that you want to keep everything tight and not have too many files around,
but it seems like a natural and clean separation, having something like `tz_io.{h,cpp}`.

2/ Yes, I use INSTALL at the moment, but when I distribute a library to clients, I don't want to force them to a specific hardcoded path to tzdata. If there is a environment variable that can set, it would allow the user to use, whatever their path is etc..

Regards
Jiri

**Comment by HowardHinnant** [comment]
Hi Jiri,

https://github.com/HowardHinnant/date/commit/634b84eb609e73a6997c7e7e8ae6dbbad6446b53

introduced:
````
void set_install(const std::string& install);
````
But I haven't documented it yet.  Does this work your point 2/ ?

**Comment by jkhoogland** [comment]
Hi Howard,
looks good, one question regarding thread-safety. 
Should the function set_install have a lock ?
Regards
Jiri

**Comment by HowardHinnant** [comment]
Good question.  If you use this function after first access, it will have no impact, unless you `reload_tzdb()` afterward.   Another way of saying this, is that use of this function is fragile.  A mutex won't make it safe, and it isn't foolproof to use without a mutex either.  Really its only safe use is to use prior to accessing the database the first time, or prior to accessing `reload_tzdb()` to move the database to a new location.  And if multiple threads are trying to read or write it at the same time, I really have no clue what the semantics should be.

It's a global.  I recommend setting it at compile time.

**Comment by HowardHinnant** [comment]
I believe this has been addressed now.
