### ISSUE TITLE
Can not compile with Visual Studio 2015 since commit 0cfa783b148e5ed25690d1276bda3c33aec7f61c

### ISSUE THREAD

**Issue by BTNC** [HowardHinnant/date#106]
Hi,

I includ data.h in my Visual Studio 2015 project without using it, and I get many compilation errors (see attached file). Compile errors start to appear since commit [0cfa783b148e5ed25690d1276bda3c33aec7f61c](https://github.com/HowardHinnant/date/commit/0cfa783b148e5ed25690d1276bda3c33aec7f61c). [The previous commit](https://github.com/HowardHinnant/date/commit/44e0480087a6bcf98ba7d09f3b8e6ba64948b892) can be compiled without any error.

[compile_error.txt](https://github.com/HowardHinnant/date/files/636099/compile_error.txt)

I am not sure what's wrong with latest data.h with vs2015.

Thanks,

**Comment by HowardHinnant** [comment]
Thank you for the detailed report.  That really helps me track things down.

I believe this will fix it.  If it doesn't, please let me know:

https://github.com/HowardHinnant/date/commit/2216bfbe44ca4a7368c5ac2950125b36e5f609f2

**Comment by BTNC** [comment]
Thank you, it works!
