### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by WscriChy** [HowardHinnant/date#107]
I am making a port for FreeBSD. Many new changes have happened since 2.0.0. Could you, please, make a new release (minor or major does not matter)?

**Comment by HowardHinnant** [comment]
Sure, thanks for your help!  There are some formatting/parsing issues I'm trying to land at the moment.  Can it wait a week?

**Comment by WscriChy** [comment]
Sure, I am looking forward.

**Comment by HowardHinnant** [comment]
2.1.0 Released.
