### ISSUE TITLE
Allowing custom allocator and normalizing template parameter order

### ISSUE THREAD

**Issue by gaspardpetit** [HowardHinnant/date#108]
Hi,

First thanks for this fantastic initiative.

At the moment, I cannot use date.h and tz.h in my project because it does not allow me to customize the allocator. For example:

	template <class CharT, class Traits, class Duration>
	void to_stream(std::basic_ostream<CharT, Traits>& os, const CharT* fmt, const sys_time<Duration>& tp)
	{
		const std::string abbrev("UTC");
		CONSTDATA std::chrono::seconds offset{0};
		to_stream(os, fmt, local_time<Duration>{tp.time_since_epoch()}, &abbrev, &offset);
	}

Generates a std::string with default allocator. I changed this function like this:

	template <class CharT, class Traits, class Duration, class Alloc = std::allocator<CharT>>
	void to_stream(std::basic_ostream<CharT, Traits>& os, const CharT* fmt, const sys_time<Duration>& tp)
	{
		const std::basic_string<CharT, Traits, Alloc> abbrev("UTC");
		CONSTDATA std::chrono::seconds offset{0};
		to_stream(os, fmt, local_time<Duration>{tp.time_since_epoch()}, &abbrev, &offset);
	}

This works for most functions, however some have a Trait and some don't, for example:

	template <class CharT, class Duration>
	std::basic_string<CharT>format(const std::locale& loc, const CharT* fmt, const zoned_time<Duration>& tp)
	{
		std::basic_ostringstream<CharT> os;
		os.imbue(loc);
		to_stream(os, fmt, tp);
		return os.str();
	}

Needs to be rewritten as 

	template <class CharT, class Duration, class Traits = std::char_traits<CharT>, class Alloc = std::allocator<CharT>>
	std::basic_string<CharT> format(const std::locale& loc, const CharT* fmt, const zoned_time<Duration>& tp)
	{
		std::basic_ostringstream<CharT> os;
		os.imbue(loc);
		to_stream(os, fmt, tp);
		return os.str();
	}

Although this is backward compatible, notice how the template arguments are in different order : CharT, Duration, Traits, Alloc vs CharT, Traits, Duration, Alloc.  The proper fix in my opinion would be to use the same order everywhere, but this breaks backward compatibility.  I would personally use CharT, Duration, Traits, Alloc order since most people will want to just change ChartT and Duration.

Let me know if you are interested in a patch for this - I would rather submit it than have a local alteration to this lib.  Points to decide are:

 - Are you 'ok' exposing the allocator so it can be customized?
 - Are you 'ok' changing the order of the template parameters for consistency?

Cheers,

Gaspard

**Comment by HowardHinnant** [comment]
Treating the temporary string "UTC" with a custom allocator isn't very motivating as every modern implementation of `std::string` will place "UTC" on the stack (won't use the allocator).

Your suggestion for the other `format` overloads isn't as clear since the `Alloc` parameter is ignored.  Can you clarify?

The goal of the current design is that `to_stream` would be the low-level performance API, and `format` is more or less nothing but a convenience wrapper around `to_stream`.

**Comment by gaspardpetit** [comment]
Agreed, "UTC" was a bad example - but oddly enough, Visual Studio 2015 will allocate a 16 byte `std::_Container_proxy ` in the heap when compiling in "debug" even for an empty `std::string`.

However I agree that the custom allocator could be limited to the low level API - but this low level API would still require some changes. For example:

	template <class CharT, class Traits, class Duration>
	void
	to_stream(std::basic_ostream<CharT, Traits>& os, const CharT* fmt,
			  const local_time<Duration>& tp, const std::string* abbrev = nullptr,
			  const std::chrono::seconds* offset_sec = nullptr)


Would be 

	template <class CharT, class Duration, class Traits = std::char_traits<CharT>, class Alloc = std::allocator<CharT>>
	void
	to_stream(std::basic_ostream<CharT, Traits>& os, const CharT* fmt,
			  const local_time<Duration>& tp, const std::basic_string<CharT, Traits, Alloc>* abbrev = nullptr,
			  const std::chrono::seconds* offset_sec = nullptr)

And in that function

	throw std::logic_error(std::basic_string<CharT, Traits>("bad value for modified: ") + char(modified));

Would be:

	throw std::logic_error(std::basic_string<CharT, Traits, Alloc>("bad value for modified: ") + char(modified));

In my case, I would also want the << and >> operators, and would probably end up wanting to expose an API similar to yours using my allocator - so that's about 3000 lines of code I have to copy/paste and keep up to date just so these functions have an extra Alloc template parameter that is otherwise harmless to those who will use the default one.

`parse` would need minor changes as well since it uses a `std::string` for `temp_abbrev` and expects `basic_strings` with standard allocator as parameters.  

I would personally push for support for custom allocators everywhere (I have a changelist for it and it's not that terrible), but I could limit a pull request to just the `parse` and `to_stream` if you prefer.

**Comment by HowardHinnant** [comment]
Changing `abbrev` in the `to_stream` function to `basic_string<CharT, Traits, Alloc>` implies changing the type of `abbrev` in `sys_info`: https://howardhinnant.github.io/date/tz.html#sys_info .  Is that your intent?  The source of strings that fill `sys_info.abbrev` is the IANA timezone database which has no "non-char" data for abbreviations.

On the second change, `std::logic_error` does not have a constructor taking the type you propose.

**Comment by gaspardpetit** [comment]
Good points.  

I will fork and do the various changes I have in mind - once all unit tests are passing and the changes are clear, I will show them to you and you can decide if you integrate them or not.  At the moment, this is what I would like to do:

 - Custom allocator
 - Static TZDB (from cpp instead of external file - while I agree it's better to rely on external data that can be updated, this does not fit my use case at all and for me it only slows down startup). For this change, I will try to make the tz functions accept a TZDB type so that I can use arrays and string_views instead of std::vector and std::strings. 
 - Checks for eof during parsing since malformed dates easily cause crashes here on Windows.

I'll get back to you when these changes are done and unit tests are passing and you can decide if you want to integrate them.

**Comment by HowardHinnant** [comment]
Ok, thanks.

**Comment by gaspardpetit** [comment]
Update on my efforts... 

- Custom allocator has a pull request (https://github.com/HowardHinnant/date/pull/138)
- Static TZDB is actually quite challenging... it is huge...! I am giving up for now.
- Checks on eof do not seem to be an issue anymore with the latest code. I haven't had a chance to look at what changed, but I could not reproduce my crashes on the latest master branch.

**Comment by HowardHinnant** [comment]
Fixed by https://github.com/HowardHinnant/date/commit/f4292e6aca78a1f18b582debe15926ed37ce5da0
