### ISSUE TITLE
date::get_windows_zones_install() defined but not used

### ISSUE THREAD

**Issue by tgy** [HowardHinnant/date#115]
First of all thanks for this super cool library! 💟 

I am building a project using CMake that uses it and I get the following warning when building.

```
[ 25%] Building CXX object CMakeFiles/date.dir/thirdparty/date/tz.cpp.o
/home/toogy/p/freedom/freedom/tools/thirdparty/date/tz.cpp:266:1: 
warning: ‘const string& date::get_windows_zones_install()’ defined but not used
[-Wunused-function]
 get_windows_zones_install()
 ^~~~~~~~~~~~~~~~~~~~~~~~~
[ 50%] Linking CXX static library libdate.a
[ 50%] Built target date
```

I am using `g++ (GCC) 6.2.1 20160830` as my compiler and the last GitHub version of the library.

**Comment by HowardHinnant** [comment]
Thanks!

Addressed by https://github.com/HowardHinnant/date/commit/659cdca5dcffeb98b908421bff1fc3579d0d83b7

**Comment by tgy** [comment]
I discovered your library because you answered one of my question on StackOverflow, so thank YOU! 🥇
