### ISSUE TITLE
SIGABRT under Linux when /home/<username>/Downloads doesn't exist

### ISSUE THREAD

**Issue by tgy** [HowardHinnant/date#119]
Using the last git version, after being able to compile a program using the library, I get the following SIGABRT:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Timezone database version "2016j" did not install correctly
           to "/home/toogy/Downloads/tzdata"
```

After creating a folder in my home directory it worked.

**Comment by HowardHinnant** [comment]
I presume "/home/toogy/Downloads/" exists and you have permission to write to it?

**Comment by tgy** [comment]
Oh I see, thanks!
