### ISSUE TITLE
No LICENSE.txt or similar

### ISSUE THREAD

**Issue by MCGallaspy** [HowardHinnant/date#121]
There is no license file in the base directory! Can you please add one? I think it is conventional. I had a panicked moment before I looked at the source files where I thought there was no license at all!

**Comment by HowardHinnant** [comment]
Will this do?

https://github.com/HowardHinnant/date/commit/ce67ee0997664535b66c64e7813cd309d5e1d64f

Thanks for your interest in this library.

**Comment by MCGallaspy** [comment]
That should do!
