### ISSUE TITLE
Compiler error - missing constructor

### ISSUE THREAD

**Issue by reesegj** [HowardHinnant/date#126]
Hi Howard,

I'm working on getting the date library to compile with one of the Borland compilers, which is essentially Clang 3.3 . I get a number of errors (see attached file) which seem to be the same error - no matching constructor, but within different classes.  It looks like a conversion operator to local_days may be missing.

Any suggestions?

Thanks.

Greg Reese 

[messages.txt](https://github.com/HowardHinnant/date/files/761004/messages.txt)

**Comment by HowardHinnant** [comment]
Hi Greg,

It sounds like this explicit operator is not kicking in:

https://github.com/HowardHinnant/date/blob/master/date.h#L797

This should allow an explicit conversion from `year_month_weekday_last` to `local_days`.

The line numbers for date.h in your error messages aren't matching up to the current date.h, so I'm not positive which line of date.h is triggering the error.  It would help if I knew which line date.h(4243) is referring to.

**Comment by HowardHinnant** [comment]
I've got a theory, but I'll need your help to test it out.

On this line:
https://github.com/HowardHinnant/date/blob/master/date.h#L4611
replace the `{}` that are used to construct the `local_days` with `()`:
````
auto start = local_days((y - years{1})/date::dec/thu[last]) + (mon-thu);
````
This _may_ correct the error.  Earlier compilers have a few bugs associated with the use of `{}`.  If my theory is right, this will need to be done in several places in date.h.  I'll need you to test this out for me.  I'd be happy to accept a PR if this fixes the issue.  Or I can do the work myself, but I'll have no way to test it, so we may need a few iterations to get it right.  Either way is fine with me (assuming I'm on the right track).

**Comment by reesegj** [comment]
Hi Howard,
Sorry, the line numbers are off. Attached is a file with the correct line numbers. These correspond to date.h in the 2.1.0 release. In the snippet

`
if (command)

           {
                if (modified == CharT{})
                {
                    auto ld = floor<days>(tp);
                    auto y = year_month_day{ld + days{3}}.year();
                    auto start = local_days{(y - years{1})/date::dec/thu[last]} + (mon-thu);
                    if (ld < start)
                        --y;
                    if (*fmt == CharT{'G'})
                        os << y;
`
line 4235 is the line that starts with 

` auto start = local_days{... `

Thanks.

Greg Reese

[messages.txt](https://github.com/HowardHinnant/date/files/761155/messages.txt)

**Comment by reesegj** [comment]
Hi Howard,

> On this line:
https://github.com/HowardHinnant/date/blob/master/date.h#L4611
replace the {} that are used to construct the local_days with ():

auto start = local_days((y - years{1})/date::dec/thu[last]) + (mon-thu); 

Yes, that did make the error go away!

>  If my theory is right, this will need to be done in several places in date.h. I'll need you to test this out for me.

No problem, just send me the corrections or a corrected file.

>  I'd be happy to accept a PR if this fixes the issue. 

Sorry, what's a "PR"?

Greg Reese

**Comment by HowardHinnant** [comment]
"PR" is "pull request".  Don't worry about it, I think I can hit this with one shot, but we'll see... ;-)

**Comment by HowardHinnant** [comment]
Ok, tip-of-trunk (https://github.com/HowardHinnant/date/commit/5c09ae73f2e9520588938fc705cd33471a8dd3f4) will hopefully get you going.  If it doesn't, just let me know.

**Comment by reesegj** [comment]
Howard,

With 5c09ae7, all of the *.pass.cpp files in the date_test folder compiled except for parse.pass.cpp. The errors are in the attached file.

I'm pretty new to Github so please let me know if I'm not doing this error-correction process correctly. Also, is there a way to comment on a specific comment in an issue thread, does a comment just get tacked on to the end of the thread?

Thanks.
Greg
[messages.txt](https://github.com/HowardHinnant/date/files/761359/messages.txt)

**Comment by HowardHinnant** [comment]
I'm learning too.  I think it is just one continuous thread.  But you can quote by putting a `>`
> at the front of a line.

Right, looks like the same issue in the test.  It's my policy to not patch the tests for compiler bugs, but to just let them fail.  It is good to know where and how the different compilers will fail.  For this issue, it is a "safe" failure in that if you use `{}` in your code, you'll get a compile-time error, not a run-time error.  Just remember that the fix is to use `()` instead.

Thanks much for bringing this issue to my attention.

**Comment by reesegj** [comment]
[tz messages.txt](https://github.com/HowardHinnant/date/files/761740/tz.messages.txt)
[iso week messages.txt](https://github.com/HowardHinnant/date/files/761741/iso.week.messages.txt)

Hi Howard,
I ran the other two test suites and got a few of the same errors but in different header files. See attached.
Greg

**Comment by HowardHinnant** [comment]
Thanks Greg.  Just pushed a fix for iso_week.h.  Checked all the other files this time, but didn't see any more (besides tests).

**Comment by reesegj** [comment]
Howard,
No more problems in the headers. Thanks for the quick responses!
Greg
