### ISSUE TITLE
unresolved external symbol errors when trying a tz example on vs2015 update 3

### ISSUE THREAD

**Issue by BTNC** [HowardHinnant/date#127]
Hi,

I got below unresolved external symbol errors when trying out [the current local time example](https://github.com/HowardHinnant/date/wiki/Examples-and-Recipes#localtime) with visual studio 2015 update3.

error LNK2019: unresolved external symbol "private: struct date::sys_info __thiscall date::time_zone::get_info_impl(class std::chrono::time_point<struct std::chrono::system_clock,class std::chrono::duration<__int64,struct std::ratio<1,1> > >)const " (?get_info_impl@time_zone@date@@ABE?AUsys_info@2@V?$time_point@Usystem_clock@chrono@std@@V?$duration@_JU?$ratio@$00$00@std@@@23@@chrono@std@@@Z) referenced in function "public: struct date::sys_info __thiscall date::time_zone::get_info<class std::chrono::duration<__int64,struct std::ratio<1,10000000> > >(class std::chrono::time_point<struct std::chrono::system_clock,class std::chrono::duration<__int64,struct std::ratio<1,10000000> > >)const " (??$get_info@V?$duration@_JU?$ratio@$00$0JIJGIA@@std@@@chrono@std@@@time_zone@date@@QBE?AUsys_info@1@V?$time_point@Usystem_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0JIJGIA@@std@@@23@@chrono@std@@@Z)

error LNK2019: unresolved external symbol "class date::time_zone const * __cdecl date::current_zone(void)" (?current_zone@date@@YAPBVtime_zone@1@XZ) referenced in function _main

Sincerely,

**Comment by HowardHinnant** [comment]
Hi BTNC,

The definition of this symbol is in tz.cpp.  You must compile this source along with the rest of your program to access it.  Full instructions are located at:

https://howardhinnant.github.io/date/tz.html#Installation

Please let me know if you continue to have this or any other problems.  I'm happy to help.

**Comment by BTNC** [comment]
Sorry I missed the installation part of the document. I followed the instructions by adding tz.cpp into my program, and downloading the tzdata files. It just works! Thank you!
