### ISSUE TITLE
timezones and leap seconds

### ISSUE THREAD

**Issue by JaapAap** [HowardHinnant/date#128]
For my application I need leap seconds, but no time zones. While these concepts (at least to me) seem to be unrelated, in the current implementation, these are considered part of the same 'database' although they are stored in different files.

To me, it make sense to separate out the leap seconds part and allow it to be used independently from the time zones part. This might have some consequences for the way the database would have to be treated (as I suppose it would conceptually become two separate databases that happen to be downloaded/updated in a single go). Any thoughts?

**Comment by HowardHinnant** [comment]
I will give that some thought, thanks.

One thing you could do immediately, is edit tz.cpp here:

https://github.com/HowardHinnant/date/blob/master/tz.cpp#L2849-L2853

Remove every file but `"leapseconds"`.  Then you'll be good to go.

**Comment by JaapAap** [comment]
Thanks Howard, sounds easy enough as a work-around for the moment.

**Comment by JaapAap** [comment]
On a related note: as I only work in UTC time, would there be a way to 'format' a utc_time (with correct behaviour during leap seconds)?

**Comment by HowardHinnant** [comment]
See the example in this section:  https://howardhinnant.github.io/date/tz.html#gps_clock

The example includes printing out a `utc_time` during a leap second.  Is that formatting sufficient?

**Comment by JaapAap** [comment]
The printing here is in a format that is not quite the one needed (I would rather need an ISO-8601 like representation). While it would be easy enough to change the output format of operator<<, it would still lack the full control that the 'format' functions provide for system time. Duplicating the `format(const CharT* fmt, const sys_time<Duration>& tp)` (or rather the underlying to_stream function) to make it operate on `utc_time` would require copy-pasting large amounts of code, as very minor changes would be needed. Before I start giving this a try, I would appreciate your opinion on there being an easier way. If not, would this be something of use to the library (I can give some refactoring a shot I suppose)?

**Comment by HowardHinnant** [comment]
I see, thanks.  I don't see an elegant solution right away.  I will give this more thought.  Perhaps a primitive that takes a `utc_time<D>` and returns a `year_month_day` and `time_of_day<D>` would be helpful.

**Comment by HowardHinnant** [comment]
Ok, here's what I'm thinking.  Seeking feedback:
````
template <class Duration>
struct civil_time
{
    year_month_day        ymd;
    time_of_day<Duration> time;
};

template <class Duration>
civil_time<Duration>
to_civil_time(const utc_time<Duration>& t)
{
    using namespace std::chrono;
    using duration = typename std::common_type<Duration, seconds>::type;
    auto const& leaps = get_tzdb().leaps;
    auto tp = sys_time<duration>{t.time_since_epoch()};
    if (tp >= leaps.front())
    {
        auto const lt = std::upper_bound(leaps.begin(), leaps.end(), tp);
        tp -= seconds{lt-leaps.begin()};
        if (tp < lt[-1])
        {
            if (tp >= lt[-1].date() - seconds{1})
            {
                auto const dp = floor<days>(tp);
                auto time = make_time(tp-dp);
                time.seconds() += seconds{1};
                return {dp, time};
            }
            else
                tp += seconds{1};
        }
    }
    auto const dp = floor<days>(tp);
    return {dp, make_time(tp - dp)};
}
````
So now you can say something like:
````
#include "tz.h"
#include <iostream>

int
main()
{
    using namespace date;
    using namespace std::chrono;
    auto u = to_utc_time(sys_days{2015_y/jul/1} - 500ms) + 1s;
    auto ct = to_civil_time(u);
    std::cout << u << '\n';
    std::cout << ct.ymd << 'T' << ct.time << '\n';
}
````
Which outputs:
````
2015-06-30 23:59:60.500
2015-06-30T23:59:60.500
````
And the streaming operator for `utc_time` can be simplified to:
````
template <class CharT, class Traits, class Duration>
std::basic_ostream<CharT, Traits>&
operator<<(std::basic_ostream<CharT, Traits>& os, const utc_time<Duration>& t)
{
    auto ct = to_civil_time(t);
    return os << ct.ymd << ' ' << ct.time;
}
````
If this pans out, `to_civil_time` could be overloaded for all of the clocks.

I haven't yet given this sufficient thought to act on it.  I just wanted to give readers of this issue an update, and something to give feedback on.

**Comment by JaapAap** [comment]
Would you also consider providing a
`format(const std::locale& loc, const CharT* fmt, const civil_time<Duration>& tp)` and
`to_stream(std::basic_ostream<CharT, Traits>& os, const CharT* fmt, const civil_time<Duration>& tp)` 
(and possibly build the current local_time versions that currently do the heavy lifting on top of it)?

**Comment by HowardHinnant** [comment]
I will explore that possibility, thanks.

**Comment by HowardHinnant** [comment]
The
````
to_stream(std::basic_ostream<CharT, Traits>& os, const CharT* fmt, const civil_time<Duration>& tp)
````
route is looking promising to me.

 I'm currently thinking that `civil_time<Duration>` will be a `namespace detail` class as I think it will only be useful for parsing and formatting, and I fear if I make it part of the API, people will think it is a good storage data structure (it isn't).  That being said, if people really want it, they can yell at me until I pull it out of `detail`.  This also means `to_civil_time` as described above won't exist.  That logic will be embedded in the `to_stream` overloads on `utc_time` et al.  The streaming operator for `utc_time` can just call `format` with `"%F %T"`.

I also think `parse` will get the same treatment.  This will make `utc_time`, `tai_time` and `gps_time` fully interoperable with `parse` and `format`.  And I'm going to do the same with `year_month_day` too.

At least that's the current plan.  I won't really know if it is going to work until I get it coded up.  I'm currently seeing no backwards compatibility issues, just more functionality.  Not sure how fast this will happen.  May take a week or two (this is a weekends project for me).

**Comment by HowardHinnant** [comment]
https://github.com/HowardHinnant/date/commit/e9d36c6200acf8c601d9ee77c7e60cbd2de08aff allows you to `format` `utc_time`.  Formatting for `tai_time` and `gps_time` will come later.

**Comment by HowardHinnant** [comment]
With https://github.com/HowardHinnant/date/commit/ffc8cd0a3b8d88a3ad9ee3a4a33ea218928011e1 both `format` and `parse` are available for all of `year_month_day`, `utc_time`, `tai_time` and `gps_time`.

**Comment by JaapAap** [comment]
I am now looking into the leapsecond implementation - trying to limit the amount of changes required to tz.h/tz.cpp. I noticed that the current implementation only supports positive leapseconds - while negative leapseconds are unlikely to be introduced, they are supported by the database format. Would support for these eventually be considered?

**Comment by HowardHinnant** [comment]
Only if required.  If they are required, I'll have 6 months notice to fix it, provided whatever calamity that is causing a negative leap second hasn't already killed me (e.g. giant astroid strike).  Otherwise I consider it a non-problem.

**Comment by HowardHinnant** [comment]
Closing as this is addressed with https://github.com/HowardHinnant/date/commit/ffc8cd0a3b8d88a3ad9ee3a4a33ea218928011e1
