### ISSUE TITLE
Custom formatted input/output?

### ISSUE THREAD

**Issue by ecorm** [HowardHinnant/date#13]
Should the date library provide facilities for outputting and parsing date-times in customizable formats? This would be very useful for integrating with a UI, or for transmission over the wire.

For custom output, one could provide a function similar to [`std::strftime`](http://en.cppreference.com/w/cpp/chrono/c/strftime), except that it takes a `std::chrono::time_point` and outputs to a `std::ostream`. For example:

```c++
namespace date
{
    template <typename C, typename D>
    std::ostream& format( std::ostream& out, const std::string& format, const std::time_point<C,D>& tp );
}
```

where `format` would contain specifiers used by `std::strftime`.

For custom input, we could have:

```c++
namespace date
{
    template <typename C, typename D>
    std::istream& parse( std::istream& in, const std::string& format, std::time_point<C,D>& tp );
}
```

Perhaps it's possible to make use of the POSIX function [`strptime`](http://pubs.opengroup.org/onlinepubs/007908799/xsh/strptime.html) (where available) to implement the proposed `parse` function.

We could also draw inspiration from [Boost.DateTime Input/Output](http://www.boost.org/doc/libs/release/doc/html/date_time/date_time_io.html). Their API seems a lot more complicated than what I propose, which makes me think there are probably many subtleties I am currently ignorant about.

I absolutely loathe C++ locales and would personally prefer a direct way to customize date-time output and parsing.

**Comment by HowardHinnant** [comment]
I've been giving this issue some though lately.  On the https://github.com/HowardHinnant/date/wiki/Boost-datetime-Examples-Translated wiki page, for some of the examples, I showed that the parsing and formatting could match whatever boost does, with just a small amount of code/knowledge of C++ streams.

This is leading me to believe that a parsing/formatting date lib could (and should) be layered non-intrusively on top of date.h rather than be part of it (just like tz.h).  Indeed, there might even be multiple designs and implementations of such parsing/formatting date utilities.  By keeping it separate I think we keep the lower-level date API simple, and demonstrate that you can build anything you want on top of it.

**Comment by ecorm** [comment]
Oh cool, I had not seen the new wiki page you referred to. Thanks for providing those examples!

**Comment by ecorm** [comment]
If the intent is for `date` to eventually become part of the C++ standard, then perhaps it's worth considering what formatting/parsing facilities are provided by competing languages. C#/.NET has `DateTime.ToString(IFormatProvider)` and `DateTime.Parse(String, IFormatProvider)`, while Java has `java.time.format.DateTimeFormatter`.

The parsing and formatting facilities could, like you suggest, be layered on top of `date.h` and be provided in a separate header, say, `dateio.h`.

**Comment by HowardHinnant** [comment]
Feedback and/or porting patches welcome:

http://howardhinnant.github.io/tz.html#Formatting
https://github.com/HowardHinnant/date/commit/e8f95dddb74057d38509ccbe7537f50c7f892962

**Comment by galik** [comment]
I suppose [std::get_time](http://en.cppreference.com/w/cpp/io/manip/get_time) and [std::put_time](http://en.cppreference.com/w/cpp/io/manip/put_time) could be a model to piggy-back off.
```cpp
class put_date_t
{
	day_point dp;
	const char* fmt;

public:
	put_date_t(day_point dp, const char* fmt)
	: dp(dp), fmt(fmt) {}

	friend
	std::ostream& operator<<(std::ostream& os, const put_date_t& pd)
	{
		auto timer = day_point::clock::to_time_t(pd.dp);
		std::tm tmb = *std::localtime(&timer); // not thread-safe
		return os << std::put_time(&tmb, pd.fmt);
	}
};

inline
put_date_t put_date(day_point dp, const char* fmt)
{
	return {dp, fmt};
}

int main()
{
	std::cout << put_date(2016_y/jul/mon[1], "%Y-%m-%d") << '\n';
}
```

**Comment by HowardHinnant** [comment]
Yes, pretty much.  To tell you the truth I completely forgot about the `std::put_time` manipulator.  But this is all encompassed by these very few lines of code:

https://github.com/HowardHinnant/date/blob/master/tz.h#L764-L773

The "special sauce" added by `date::format` is a little extra love for `%S`, `%T`, `%z` and `%Z`.  `%S`, `%T` are enhanced to handle fractional seconds.  And `%z` and `%Z` are intercepted to take data from the this timezone library as opposed to letting the OS handle it.  This has two consequences:

1.  We can handle more than the two timezones: UTC and local.
2.  If the IANA timezone database gets updated, this code will learn about it as soon as you update your local copy (which happens automatically on the experimental branch auto_download).  This is opposed to waiting for your vendor/OS to update the tzdata files.  This timeliness assures that this output will always be consistent with the rest of the tz.h library.

**Comment by HowardHinnant** [comment]
Closing.  Formatting is now fully handled here:
http://howardhinnant.github.io/date/tz.html#format
And parsing is now handled here:
http://howardhinnant.github.io/date/tz.html#parse
