### ISSUE TITLE
Days in gps_time

### ISSUE THREAD

**Issue by JaapAap** [HowardHinnant/date#131]
What would be the envisioned way to set a gps_time from a year,month, day and time-of-day? It seems that year_month_day currently always represents a system time?

**Comment by HowardHinnant** [comment]
That's correct.  You have to go through `sys_time` and use `to_gps_time`, which in turn will fiddle with the seconds.

**Comment by JaapAap** [comment]
Thanks, I understand. As a matter of fact, I want to avoid the fiddling as the year,month etc. are referring to the GPS timescale already

**Comment by JaapAap** [comment]
If I understand well, I would help when the `to_days `method of the `year_month_day` class would be exposed.

**Comment by HowardHinnant** [comment]
It actually is already exposed by the conversions to `sys_days` and `local_days`.  You could write a little helper function that takes in a `local_time`, and turns that into a `gps_time` like this:
````
template <class Duration>
date::gps_time<Duration>
interpret_as_gps(const date::local_time<Duration>& lt)
{
    using namespace date;
    return gps_time<Duration>{lt.time_since_epoch()} -
            (sys_days(year{1980}/jan/sun[1]) - sys_days(year{1970}/jan/1));
}
````
Lightly tested with this:
````
int
main()
{
    using namespace date;
    using namespace std;
    using namespace std::chrono;
    cout << to_gps_time(sys_days{2017_y/feb/14} + 9h + 3min + 2s) << '\n';
    cout << interpret_as_gps(local_days{2017_y/feb/14} + 9h + 3min + 20s) << '\n';
}
````
which outputs:
````
2017-02-14 09:03:20
2017-02-14 09:03:20
````

**Comment by JaapAap** [comment]
Thanks for that. I must admit that I misunderstood the 'local_time' concept as being 'not related to a particular clock' as I associate the term with 'utc shifted in accordance with the geographic location'. You are correct in that is indeed the concept I tried to capture. I read your documentation and I understand the choice  of name, and it still feels strange to use it with different clocks in a situation where geographic location is not involved at all.

**Comment by HowardHinnant** [comment]
I'll admit that it is a bit of a hack to use `local_time` for this.  One could also use `sys_time`, but then you run a larger risk of accidentally confusing a `sys_time` meant for `interpret_as_gps` and a `sys_time` meant to represent UTC.  Another route would be to create a conversion from `year_month_day` to `gps_days`, but I'd like to not make things that tedious for calendar authors.

**Comment by JaapAap** [comment]
Yes, I understand. Wouldn't the latter conversion essentially be the 'raw' `to_days` method though?

**Comment by HowardHinnant** [comment]
Yes, the exact same math.  Just the wrong units (a duration instead of a time_point).

**Comment by HowardHinnant** [comment]
Fwiw, here's a global `to_days` you could write:
````
inline
date::days
to_days(date::year_month_day ymd)
{
    return date::local_days{ymd}.time_since_epoch();
}
````
