### ISSUE TITLE
UTC and time_zones

### ISSUE THREAD

**Issue by JaapAap** [HowardHinnant/date#132]
I would like to define a time scale (clock) based on (UTC time + N hours), essentially equal to UTC in some predefined time zone. Is this possible at all? It seems that all `zoned` stuff is bases on sys_time? When defining a custom clock (which is easy enough for the most part) I run into the issue that the leap seconds in the new time scales are not applied at 0:00 which makes it hard to build upon some of the existing routines for UTC.

**Comment by HowardHinnant** [comment]
You could build something akin to `zoned_time`, which is essentially a `pair<const time_zone*, sys_time<Duration>>` with lipstick  Just sub in `utc_time<Duration>` for `sys_time<Duration>`.  The only tricky part is that `time_zone` itself traffics in `sys_time` instead of `utc_time`.  Therefore every place where you want to query a `time_zone` with a `utc_time`, you would first have to convert that `utc_time` to `sys_time` with `to_sys()`. 

With that converted-to `sys_time` I would recommend just getting the `sys_info` with `get_info`, and that gives you access to the offset, abbreviation, etc.  Then add the offset to your `utc_time` directly, instead of to your `sys_time`.  See `time_zone::to_local` for example code.  The result of your `utc_time + offset` would be a `local_time` (so the compiler keeps you from getting confused in your code).

You could either define your own timezones, or there are `"Etc/GMT+1"` (et al) timezones in the IANA database.  One thing to be careful of is that `Etc/GMT+1` means offset `-1h` instead of `+1h`.  To get offset `+1h` you need `"Etc/GMT-1"` (its weird).

**Comment by JaapAap** [comment]
Thanks again Howard. Actually, technically I would have no need to query the tz database as the times I am dealing with are not defined wrt a location, but rather as an offset to UTC. Is my impression correct that the current use cases all assume using the database, or would it be possible to plug in the offset somehow?

**Comment by HowardHinnant** [comment]
You could do something as simple as a `struct {utc_time<Duration>, chrono::hours}` that returned a `local_time<Duration>` to represent the offset time, or you could even template on a `int` if the offset is always known at compile-time (with the `int` being the offset in hours).  In this latter case, you could also create a new clock, templated on `int`, and now all of your offset `time_point`s have distinct types. That would be great for type safety, but it means you always have to know your "timezone" at compile time.

It sounds like you can stay away from the database for everything but leap second insertion dates (`"leapseconds"`).

**Comment by HowardHinnant** [comment]
I've recently modified `zoned_time` to have a second defaulted template parameter:
```c++
template <class Duration, class TimeZonePtr = const time_zone*>
class zoned_time;
```
This allows you to create a `zoned_time` with a custom pointer to a `date::time_zone`, or a custom pointer to your custom time zone, or you can even have your custom time zone act as its own pointer by having it implement `operator->() const {return this;}`.

At the very least your custom time zone must support `to_local(date::sys_time<Duration> tp)` and `to_sys(date::local_time<Duration> tp)`.  In addition, if you would like your custom `zoned_time` to be formatable it must also implement `get_info(date::sys_time<Duration> st)`.

Below is an example custom time zone which simply supports fixed offsets from UTC at a precision of minutes.
```c++
#include "tz.h"

class OffsetZone
{
    std::chrono::minutes offset_;

public:
    explicit OffsetZone(std::chrono::minutes offset)
        : offset_{offset}
        {}

    template <class Duration>
        auto
        to_local(date::sys_time<Duration> tp) const
        {
            using namespace date;
            using namespace std::chrono;
            using LT = local_time<std::common_type_t<Duration, minutes>>;
            return LT{(tp + offset_).time_since_epoch()};
        }

    template <class Duration>
        auto
        to_sys(date::local_time<Duration> tp) const
        {
            using namespace date;
            using namespace std::chrono;
            using ST = sys_time<std::common_type_t<Duration, minutes>>;
            return ST{(tp - offset_).time_since_epoch()};
        }

    template <class Duration>
        date::sys_info
        get_info(date::sys_time<Duration> st) const
        {
            using namespace date;
            using namespace std::chrono;
            return {sys_seconds::min(), sys_seconds::max(), offset_,
                    minutes{0}, offset_ >= minutes{0} ? "+" + date::format("%H%M", offset_)
                                          : "-" + date::format("%H%M", -offset_)};
        }

    const OffsetZone* operator->() const {return this;}
};

#include <iostream>

int
main()
{
    using namespace date;
    using namespace std::chrono;
    auto now = floor<milliseconds>(system_clock::now());
    zoned_time<milliseconds, OffsetZone> ztm4{OffsetZone{-4h}, now};
    zoned_time<milliseconds, OffsetZone> ztp4{OffsetZone{+4h}, now};
    std::cout << now << " +0000\n";
    std::cout << ztm4 << '\n';
    std::cout << ztp4 << '\n';
}
```
This just output for me:
```
2017-09-10 17:26:54.154 +0000
2017-09-10 13:26:54.154 -0400
2017-09-10 21:26:54.154 +0400
```

**Comment by HowardHinnant** [comment]
This is now an example in the tz doc: https://howardhinnant.github.io/date/tz.html#Examples
