### ISSUE TITLE
Parsing UTC times

### ISSUE THREAD

**Issue by socantre** [HowardHinnant/date#133]
Does this library provide a way of parsing a formatted time to get a `utc_time` without losing leap seconds? E.g. parsing "2016-12-31T23:59:60Z" to get a value after "2016-12-31T23:59:59Z" and before "2017-01-01T00:00:00Z".

**Comment by HowardHinnant** [comment]
No, but I plan on adding that capability within a week (likely this coming weekend).

**Comment by HowardHinnant** [comment]
With https://github.com/HowardHinnant/date/commit/e9d36c6200acf8c601d9ee77c7e60cbd2de08aff you can now `parse` `utc_time` as you describe above.
````
#include "tz.h"
#include <cassert>
#include <iostream>
#include <sstream>

int
main()
{
    using namespace date;
    using namespace std;
    using namespace std::chrono;
    istringstream in{"2016-12-31T23:59:59Z "
                     "2016-12-31T23:59:60Z "
                     "2017-01-01T00:00:00Z"};
    utc_seconds t0, t1, t2;
    in >> parse("%FT%TZ", t0) >> parse("%FT%TZ", t1) >> parse("%FT%TZ", t2);
    assert(!in.fail());
    assert(t0 < t1 && t1 < t2);
    cout << t0 << '\n' << t1 << '\n' << t2 << '\n';
}
````
Output:
````
2016-12-31 23:59:59
2016-12-31 23:59:60
2017-01-01 00:00:00
````

**Comment by HowardHinnant** [comment]
Just nailing this down a little further:
````
assert(t0 + 1s == t1);
assert(t1 + 1s == t2);
assert(t0 + 2s == t2);
````
