### ISSUE TITLE
Specify tzdata install directory at runtime.

### ISSUE THREAD

**Issue by ecorm** [HowardHinnant/date#134]
We would like to able to set the `tzdata` install directory at runtime.

Currently, using `-DINSTALL` will "bake" the tzdata directory location into the built library. This is too inflexible for us.

I see that there's an undocumented `detail::set_install(const std::string& s)` function that sets the install directory. Is it possible to make this function accessible via the public API?

**Comment by HowardHinnant** [comment]
Yes, in fact there is already a `date::set_install(const std::string& s)` function.  It is undocumented, but someone else requested it too.  The only thing missing is the documentation and I will try to get that done soon.

**Comment by ecorm** [comment]
Ah, sorry, I missed the existing issue. Yes, it would address our problem, and it would be nice (but not required) if we can specify a relative path. We can always use `boost::filesystem` to convert a relative path to an absolute one in our application (we're already heavily dependent on Boost).

You may close this issue as a duplicate of #99.

**Comment by ecorm** [comment]
Oops, I see now that #99 is a pull request.

**Comment by HowardHinnant** [comment]
Yes, #99 is a PR, but its functionality has already been pulled.  I've left it open to remind myself that I need to get the documentation taken care of.
