### ISSUE TITLE
Macro names should have a prefix

### ISSUE THREAD

**Issue by ecorm** [HowardHinnant/date#135]
There is currently no scheme that prevents this library's preprocessor macros from clashing with existing ones in an application. One in particular that really concerns me is the `INSTALL` macro.

I think a `DATE_` prefix is too generic and could still lead to name clashes. I suggest one of the following as a prefix:

* `P0355_`
* `DATE_P0355_`
* `P0355_DATE_`

We could use `HINNANT_DATE_`, but that might appear a bit narcissistic to some. :wink: 

P.S. "P0355" is the document number for the C++ proposal to add `date` and `tz` to the standard library.

**Comment by HowardHinnant** [comment]
Have you actually experienced a clash?  For backwards compatibility reasons I don't want to change these without strong motivation.

**Comment by ecorm** [comment]
I haven't experienced any clashes because everyone else is nice enough to use macro prefixes in their libraries. Think of it as "herd immunity". :smile:

I'm sorry for not following the evolution of this library more closely; I could have made this suggestion much sooner.

You could define new prefixed macros alongside your old ones, and deprecate the old ones (however, this could lead to messy preprocessor logic). Later, after everyone had the chance to transition, you can remove the old, unprefixed macros.

**Comment by HowardHinnant** [comment]
I hope to make this library obsolete by getting it into the C++ standard. ;-)  Then this will be a non-issue.  If that doesn't work out, and if people do experience clashes, then we can act on it.

**Comment by maximilianriemensberger** [comment]
I actually just expedierend a clash of the NOEXCEPT macro with cxx_function. Pretty painful since it means I need to maintain a fork of either date or cxx_function.

**Comment by HowardHinnant** [comment]
David just fixed it on his end: https://github.com/potswa/cxx_function/commit/f32510e51fbdd35e55d41fecdc0931fad6a26986

**Comment by pitrou** [comment]
I also experienced a clash of the NOEXCEPT macro with the `utfcpp` library, FTR.

**Comment by ecorm** [comment]
I just need your `date.h` for my C++11 library. I'm considering just embedding it (with a copy of its licence and link to this project) after running a script that `sed`s out all the clashable macros. I'll make it so that the users of my library can override the embedded `date.h` with their own (in case there are urgent bug fixes that they need).

Despite this minor inconvience, I'm still grateful for this library and all the work you've put into it. :+1:
