### ISSUE TITLE
ISO zulu time format

### ISSUE THREAD

**Issue by raulbocanegra** [HowardHinnant/date#147]
Hi, 

I am using date 2.1.0 on Windows 10 with Visual Studio 2015 Update 3.
I am parsing a date time string with [ISO Zulu format](https://en.wikipedia.org/wiki/ISO_8601#UTC). I mean "%FT%TZ".
I am using the following code:
```
std::string format = "%FT%TZ";
std::string datetime = "2017-2-15T13:13:13Z";
std::istringstream input(datetime);
date::sys_seconds tp;
input >> date::parse(format, tp);
if (input.fail())
{
    std::cout << "Error parsing!" << std::endl;
}
else
{
    std::cout << "Parsed correctly!" << std::endl;
}
```

The code above prints "Parsed correctly!" which is ok, but if I remove de 'Z' from the datetime string it does not fail when I think it should.

Here are different outputs depending on the input.

case | datetime | output
---- |--------- | -------
1 | "2017-2-15T13:13:13Z" | "Parsed correctly!"
2 | "2017-2-15 13:13:13Z" | "Error Parsing!"
3 | "2017-2-15T13:13:13 " | "Error Parsing!"
4 | "2017-2-15T13:13:13" | "Parsed correctly!"

Case 1 it's ok, case 2 and 3 lacks 'T' and 'Z' respectively (note the ending whitespace), it should report error and it does, so it's ok too.
But case 4 does not have the ending 'Z' required by the format string and it does not fail.
Is this a bug or am I taking some wrong assumptions?

Thanks for your work! :)

**Comment by HowardHinnant** [comment]
Thanks for the excellent bug report!

Fixed: https://github.com/HowardHinnant/date/commit/2f8997d3ed1aa846233592d65e0778b54f3cb727
