### ISSUE TITLE
request for year_month_day arithmetic with days

### ISSUE THREAD

**Issue by reesegj** [HowardHinnant/date#149]
Howard,

I think it would be very useful to be able to add and subtract a days type with a year_month_day and also to be able to increment and decrement a year_month_day by a day. For example:

// all resulting values are year_month_day type
auto today = floor<days>(system_clock::now()); // today as year_month_day
auto deadline = today + 5_d; // deadline is 5 days from today
auto project_start = today - 20_d; // project started 20 days ago
++today; // move forward one day
--today; // move back one day

Thanks.
Greg Reese

**Comment by HowardHinnant** [comment]
Hi Greg,

Thanks for the suggestion.  Here is why that feature is absent:

https://github.com/HowardHinnant/date/wiki/FAQ#day_arithmetic

**Comment by reesegj** [comment]
Thanks Howard.
Greg

---------------------------------------------------------------------------------------------------
Greg Reese, Ph.D.
63 Upham Hall
Miami University
Oxford, OH  45056
(513)529-1411 (Voice)
(513)529-3765 (FAX)
greg.reese@miamioh.edu
