### ISSUE TITLE
Compilation Errors on MSVC 2017 for UWP App

### ISSUE THREAD

**Issue by WedgetailDevelopment** [HowardHinnant/date#156]
I have tried to compile tz.h / tz.cpp in Visual Studio 2017 Community, within a Universal Windows Application [UWP], however I get the following compile errors and warnings:

`
tz.cpp(164): error C3861: 'CoTaskMemFree': identifier not found
tz.cpp(178): error C2065: 'KF_FLAG_DEFAULT': undeclared identifier
tz.cpp(178): error C3861: 'SHGetKnownFolderPath': identifier not found
tz.cpp(192): error C2065: 'FOLDERID_ProgramFiles': undeclared identifier
tz.cpp(200): error C2065: 'FOLDERID_Downloads': undeclared identifier

tz.cpp(265): warning C4273: 'date::set_install': inconsistent dll linkage
tz.h(765): note: see previous definition of 'set_install' (compiling source file Libraries\Timezone\tz.cpp)
tz.cpp(1378): warning C4273: 'date::time_zone::time_zone': inconsistent dll linkage
tz.h(372): note: see previous definition of '{ctor}' (compiling source file Libraries\Timezone\tz.cpp)
tz.cpp(1401): warning C4273: 'date::time_zone::add': inconsistent dll linkage
tz.h(395): note: see previous definition of 'add' (compiling source file Libraries\Timezone\tz.cpp)
tz.cpp(1692): warning C4273: 'date::time_zone::adjust_infos': inconsistent dll linkage
tz.h(396): note: see previous definition of 'adjust_infos' (compiling source file Libraries\Timezone\tz.cpp)
tz.cpp(1863): warning C4273: 'date::time_zone::get_info_impl': inconsistent dll linkage
tz.h(399): note: see previous definition of 'get_info_impl' (compiling source file Libraries\Timezone\tz.cpp)
tz.cpp(1869): warning C4273: 'date::time_zone::get_info_impl': inconsistent dll linkage
tz.h(400): note: see previous definition of 'get_info_impl' (compiling source file Libraries\Timezone\tz.cpp)
tz.cpp(1894): warning C4273: 'date::time_zone::get_info_impl': inconsistent dll linkage
tz.h(401): note: see previous definition of 'get_info_impl' (compiling source file Libraries\Timezone\tz.cpp)
tz.cpp(1959): warning C4273: 'date::operator <<': inconsistent dll linkage
tz.h(393): note: see previous definition of '<<' (compiling source file Libraries\Timezone\tz.cpp)
tz.cpp(2016): warning C4273: 'date:: link:: link': inconsistent dll linkage
tz.h(546): note: see previous definition of '{ctor}' (compiling source file Libraries\Timezone\tz.cpp)
tz.cpp(2026): warning C4273: 'date::operator <<': inconsistent dll linkage
tz.h(554): note: see previous definition of '<<' (compiling source file Libraries\Timezone\tz.cpp)
tz.cpp(2038): warning C4273: 'date::leap::leap': inconsistent dll linkage
tz.h(568): note: see previous definition of '{ctor}' (compiling source file Libraries\Timezone\tz.cpp)
tz.cpp(2051): warning C4273: 'date::operator <<': inconsistent dll linkage
tz.h(599): note: see previous definition of '<<' (compiling source file Libraries\Timezone\tz.cpp)
tz.cpp(2773): warning C4273: 'date::reload_tzdb': inconsistent dll linkage
tz.h(764): note: see previous definition of 'reload_tzdb' (compiling source file Libraries\Timezone\tz.cpp)
tz.cpp(2784): warning C4273: 'date::get_tzdb': inconsistent dll linkage
tz.h(763): note: see previous definition of 'get_tzdb' (compiling source file Libraries\Timezone\tz.cpp)
tz.cpp(2791): warning C4273: 'date::locate_zone': inconsistent dll linkage
tz.h(773): note: see previous definition of 'locate_zone' (compiling source file Libraries\Timezone\tz.cpp)
tz.cpp(2822): warning C4273: 'date::operator <<': inconsistent dll linkage
tz.h(761): note: see previous definition of '<<' (compiling source file Libraries\Timezone\tz.cpp)
tz.cpp(2901): warning C4273: 'date::current_zone': inconsistent dll linkage
tz.h(779): note: see previous definition of 'current_zone' (compiling source file Libraries\Timezone\tz.cpp)`

Is there any instructions on dealing with these issues?

**Comment by HowardHinnant** [comment]
The first error looks like I'm missing:
````
#include <Objbase.h>
````

If you could add that to tz.h just before line 12, and tell me what happens, I would be most grateful.

**Comment by WedgetailDevelopment** [comment]
Inserting `#include <objbase.h>` at line 112 fixed the first error.  

The other errors still remain however.

**Comment by HowardHinnant** [comment]
Thanks.  I don't have a windows machine to test on.  I depend on volunteers to write and maintain this code.  If you have any suggestions on how to fix these errors, I will gladly accept a P/R from you which includes your copyright added to the changed files.

**Comment by UliKu** [comment]
When `_WIN32` is defined the library assumes per default that you are consuming the library from another DLL and defines `#define DATE_API __declspec(dllimport)`. If you are including the cpp file directly into your project you can just define `DATE_BUILD_LIB` for not using any of the dllimport/dllexport definitions.

**Comment by HowardHinnant** [comment]
Thank you!  That sounds like something I should put in the installation instructions.

**Comment by WedgetailDevelopment** [comment]
Thanks UliKu, your `#define DATE_BUILD_LIB` removed all the warning messages.

Howard, for the folder access messages, the Windows 10 Universal Windows Program 'sand boxed' environment has removed access to the shell32.dll.  

The following will compile around the issue.  However I have not tested the functions to see if they will actually allow you to access the files in the locations.

```
Insert at Line 173
#ifdef __cplusplus_winrt // Windows 10 UWP (Universal Windows Program) / c++/cx detection

// The Windows UWP StorageFolder^ returns either a "Platform String", or will return a std::wstring with the ->Data() member.

#include <codecvt>
std::string WideToNarrow(std::wstring wstr) {
	using convert_typeX = std::codecvt_utf8<wchar_t>;
	std::wstring_convert<convert_typeX, wchar_t> converterX;
	return converterX.to_bytes(wstr);
}

// UWP Apps file storage is more restricted than WIN32 Apps.  
// See  https://docs.microsoft.com/en-us/windows/uwp/files/file-access-permissions

// Usually something like "c:\Program Files\[App Name]".
static
std::string
get_program_folder()
{
	using namespace Windows::Storage;
	StorageFolder^ ProgramFolder = Windows::ApplicationModel::Package::Current->InstalledLocation;
	return WideToNarrow(ProgramFolder->ToString()->Data());
}

// For UWP Application, the downloaded file would be more appropriate in the Applications Local folder
static
std::string
get_download_folder()
{
	using namespace Windows::Storage;
	StorageFolder^ LocalFolder = ApplicationData::Current->LocalFolder;
	return WideToNarrow(LocalFolder->ToString()->Data());
}



#else	  // WIN 32
```


and a corresponding `#endif` around the new line 240.

**Comment by HowardHinnant** [comment]
Unfortunately, after working on another feature, I've changed tz.cpp enough that I'm having trouble following these directions.  I would be most grateful for a pull request, or a patch against the current master branch.
