### ISSUE TITLE
not working; crashes with system_error

### ISSUE THREAD

**Issue by sanjayverma1** [HowardHinnant/date#158]
bash-3.2$ /opt/rh/devtoolset-2/root/usr/bin/g++ -std=c++11 t_trade_date.cpp -I./ tz.cpp -lcurl -o t_trade_date
bash-3.2$ ./t_trade_date
Current UTC: 2017-05-31 14:48:27.608415000
terminate called after throwing an instance of 'std::system_error'
  what():  Unknown error 18446744073709551615
Aborted (core dumped)

[t_trade_date.txt](https://github.com/HowardHinnant/date/files/1041914/t_trade_date.txt)

**Comment by HowardHinnant** [comment]
Thanks for the report.  I see nothing wrong with your code, and I'm not reproducing the crash on macOS.  Can you by any chance post the stack dump?  I'm not positive how to tell you to retrieve it on linux.

**Comment by sanjayverma1** [comment]
Could be specific to redhat AS5 (64 bits). I am using gcc 4.8.2. Stack trace is attached.
[stack_trace.txt](https://github.com/HowardHinnant/date/files/1041999/stack_trace.txt)

**Comment by HowardHinnant** [comment]
Shot in the dark:  Add to your compile-command: `-lpthread`.

**Comment by sanjayverma1** [comment]
If you shoot this well in the dark, wonder how well will you do in the light :) That worked!
Thanks a lot.
