### ISSUE TITLE
Compilation error with -DUSE_OS_TZDB (Ubuntu 17.04)

### ISSUE THREAD

**Issue by charno** [HowardHinnant/date#159]
Hi,

Thanks for this excellent library. For an embedded system I wanted to try the newly added ability to use the system timezone database, so I don't have to manage two sets of basically the same data.

When compiling (no matter if cross compiling or using the system-installed gcc) I get some compilation errors:
```
>>> g++ -DUSE_OS_TZDB -c tz.cpp
tz.cpp: In function ‘void date::reverse_bytes(T&)’:
tz.cpp:1455:56: error: ‘memmove’ is not a member of ‘std’
     unsigned char* bytes = static_cast<unsigned char*>(std::memmove(std::addressof(t),
                                                        ^~~
tz.cpp:1455:56: note: suggested alternative:
In file included from tz.cpp:129:0:
/usr/include/string.h:46:14: note:   ‘memmove’
 extern void *memmove (void *__dest, const void *__src, size_t __n)
              ^~~~~~~
tz.cpp: In member function ‘date::sys_info date::time_zone::load_sys_info(std::vector<date::detail::transition>::const_iterator) const’:
tz.cpp:1810:37: error: operands to ?: have different types ‘const sys_seconds {aka const std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int> >}’ and ‘date::sys_days {aka std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<int, std::ratio<86400l, 1l> > >}’
     r.end = i != transitions_.end() ? i->timepoint : sys_days(year::max()/max_day);
             ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tz.cpp:1810:37: note:   and each type can be converted to the other
``` 
(g++ (Ubuntu 6.3.0-12ubuntu2) 6.3.0 20170406)

The first (memmove) error can easily be fixed by `#incldue <cstring>`. For the other error, I could not find an easy fix.

Do I make a mistake with compiling? I just cloned the whole repository and then ran `g++ -DUSE_OS_TZDB -c tz.cpp`, did I miss anything? If I omit the `USE_OS_TZDB` define, the compilation works fine.

Thank you
charno

**Comment by HowardHinnant** [comment]
Thanks for this report!

This sounds like a compiler bug, but one which we can easily work around.  Can you try this?

````
    r.end = i != transitions_.end() ? i->timepoint : sys_seconds(sys_days(year::max()/max_day));
````

I.e. explicitly convert the `sys_days` to `sys_seconds`.  If that works, I'll push these fixes right away.

**Comment by charno** [comment]
Thanks for writing and maintaining :)

With your proposed fix and the `#include <cstrings>` compilation is successful.

**Comment by HowardHinnant** [comment]
Thanks!  Fixed: https://github.com/HowardHinnant/date/commit/cc81c9ea503f843501a7c71fb871fcf104f732b0
