### ISSUE TITLE
minimum g++ requirement

### ISSUE THREAD

**Issue by allidev** [HowardHinnant/date#162]
I am using g++ 4.9.4 on some platforms (i.e. Ubuntu 14.0.4.1), and when I build the date library, it complains:
date.h:6102:25: error: ‘const class std::time_get<char>’ has no member named ‘get’
                         f.get(is, 0, is, err, &tm, command, fmt+1);
However, if I switch to g++ 5.4.0 on Ubuntu 16.04.4, this error message disappears. Can one build date using g++ 4.9.4?

**Comment by HowardHinnant** [comment]
Sorry, `time_get` is required.  If you want you could try to #ifdef out the uses of `time_get` (and `time_put`).  This would mean things like %a, %A, %b, %B would not work.  Only the formatting and parsing that did not depend on the locale would work (such as %F and %T).

**Comment by remyabel** [comment]
@allidev I don't use Ubuntu, but you should be able to use `ubuntu-toolchain-r-test` to get a newer version of GCC. Or better yet, read this: https://gcc.gnu.org/wiki/InstallingGCC

**Comment by HowardHinnant** [comment]
If you compile the latest master with `-DONLY_C_LOCALE` this will now remove dependence on `std::time_get` and `std::time_put`.  However I have not been able to test on g++ 4.9.4.
