### ISSUE TITLE
Windows Build

### ISSUE THREAD

**Issue by dorpxam** [HowardHinnant/date#165]
Hello,

I attempt to use this great work on microsoft platform but I have a build problem.

> OS : Windows 10 (64bits)
> IDE : Visual Studio 2017 Community (vc15)

My `main.cpp` is based on your TimeZone conference slide examples:

```
#include <iostream>
#include "tz.h"

void test()
{
	using namespace std;
	using namespace date;
	//auto tz = date::locate_zone("America/Los_Angeles");
	//auto tz = date::current_zone();
	cout << make_zoned("America/Los_Angeles", sys_days{ 2016_y / sep / 20 } +23h + 45min) << '\n';
}

int main (int argc, char** argv)
{
	test();
	system("pause");
	return EXIT_SUCCESS;
}
```

Visual Studio build is configured using the `DATE_BUILD_LIB` preprocessor, static linking (`MT`), and ISO c++14 (`/std::c++14`) language support. For instance, in debug build and without forgetting to include the file `tz.cpp` in the files to be built obviously (otherwise links errors appear).

I've a little bunch of build error (sorry, in french):

```
1>tz.h(977): error C2065: 'duration' : identificateur non déclaré
1>tz.h(977): error C2923: 'date::local_time' : 'duration' n'est pas un argument de type modèle valide pour le paramètre 'Duration'
1>tz.h(978): error C2039: 'operator unknown-type' : n'est pas membre de 'date::zoned_time<Duration>'
1>tz.h(978): error C2447: '{' : en-tête de fonction manquant (liste formelle à l'ancien format ?)
1>tz.h(984): error C2065: 'duration' : identificateur non déclaré
1>tz.h(984): error C2923: 'date::sys_time' : 'duration' n'est pas un argument de type modèle valide pour le paramètre 'Duration'
1>tz.h(985): error C2039: 'operator unknown-type' : n'est pas membre de 'date::zoned_time<Duration>'
1>tz.h(985): error C2447: '{' : en-tête de fonction manquant (liste formelle à l'ancien format ?)
```
All seem related to the line duration alias define line 279 in tz.h:
```
template <class Duration>
class zoned_time
{
public:
    using duration = typename std::common_type<Duration, std::chrono::seconds>::type;
```
Visual Studio does not have the same freedom over the scope of aliases than some other Unix compiler. That can be solved by force the scope in line 977 and 984 like that:

```
template <class Duration>
inline
zoned_time<Duration>::operator local_time<zoned_time::duration>() const
{
    return get_local_time();
}

template <class Duration>
inline
zoned_time<Duration>::operator sys_time<zoned_time::duration>() const
{
    return get_sys_time();
}
```
Note that we don't need to specify the template that cause an build error.

Now, another error come from `tz.cpp` line 3291:
```
tz.cpp(3291): error C3861: 'load_timezone_mappings_from_xml_file' : identificateur introuvable
that mean that 'load_timezone_mappings_from_xml_file' is not found.
```
This is _normal_ since this function is hidden, it is part of the code under the preprocessor `HAS_REMOTE_API`.
```
#ifdef _WIN32
    std::string mapping_file = get_install() + folder_delimiter + "windowsZones.xml";
    db.mappings = load_timezone_mappings_from_xml_file(mapping_file);
    sort_zone_mappings(db.mappings);
#endif // _WIN32
```
Because, `load_timezone_mappings_from_xml_file` is used to load specific zones database for windows, I think this method need to be visible. By putting a (temporary) copy of this method outside the `HAS_REMOTE_API` preprocessor, `tz.cpp` build fine.

At this moment, the `C:\Users\xxxxxx\Downloads\tzdata` directory contain the tzdata's (tzdata2017b) and the `windowsZones.xml` but an exception is throw from parsing the `windowsZones.xml`:
```
Error loading time zone mapping file "C:\Users\maxprod\Downloads\tzdata\windowsZones.xml" 
at line 236: Unexpected mapping record found. 
A xml mapZone or comment attribute or mapTimezones closing tag was expected.
```
But the `windowsZones.xml` look good at this line (line 236 is the blank line between the two zones):
```
<!-- (UTC-03:00) Montevideo -->
<mapZone other="Montevideo Standard Time" territory="001" type="America/Montevideo"/>
<mapZone other="Montevideo Standard Time" territory="UY" type="America/Montevideo"/>
			
<!--  (UTC-03:00) Punta Arenas  -->
<mapZone other="Magallanes Standard Time" territory="001" type="America/Punta_Arenas"/>
<mapZone other="Magallanes Standard Time" territory="AQ" type="Antarctica/Palmer"/>
<mapZone other="Magallanes Standard Time" territory="CL" type="America/Punta_Arenas"/>
```
By removing the blank line (236), I got a new error in line 505 (blank line), I do the same, got the line 758 (another blank line) and the parse work fine. I imagine these lines contained invisible bad characters. Weird.

Now, my application test work and I get the result:
```
2016-09-20 16:45:00
where I need to get (from your slide example)
2016-09-20 16:45:00 PDT
```
I need more investigation on the library and will build the test directory right now. I will be back soon with more informations, I hope theses informations help you to adjust the windows compatibility.

**Comment by HowardHinnant** [comment]
Your report is extremely thorough and helpful.  Thanks!  Would you prefer to submit a pull request, or would you prefer that I do the patch?  Either way is fine with me.  If you submit a P/R, I encourage you to add your copyright to all of the files you modify (encouraged but not required).

**Comment by HowardHinnant** [comment]
On `windowsZones.xml`:  I just downloaded the latest version, and it looks like this new version has 3 tabs followed by a newline on the lines you call out.  My best guess is that `load_timezone_mappings_from_xml_file` is not tolerant of non-empty lines that contain nothing but whitespace, and should be.

**Comment by dorpxam** [comment]
You're right for the `WindowsZones.xml`.

**My contribution**
I'm thinking of using your test directory (using `Catch` - a powerfull single header  unit tester) in order to be able to test the code under windows before making any changes to the code. I would test theses changes under `Linux Mint` before submitting a push request because it is not about making the code functional on one side and not more on the other. I will test the project with VS2015 with/without C++11 support too.

**Simplify cross-platform building**
Concerning the project itself, I have more questions/suggestions to submit. The first one has already been lifted and concerns Cmake. Cmake can be advantageous in many points, even as part of a single header project. For example, for the installation of third-party dependencies (tz database) but also for the compilation of examples and tests sub-projects.

**Pre-parsing**
For reasons of unification and code speed, it would be (in terms of design) more interesting to create a small console application that takes as input the timezone data as currently form/source, but transform them into a file header where the useful data are directly accessible as a classic structure (`std::map` or `std::vector` or anything needed), thus avoiding third-party file parsing at runtime. I've read (and test myself) that the parsing is a little slow at runtime.

**Fully Single-Header**
The process of data recovery can be done dynamically with cmake, as well as the dynamic compilation (directly under cmake, it seems to me possible) of a standard console application that creates the file `tz_database.hpp` on the fly and generates a "ready to be used" project. Notez que cela permet aussi de simplifier le code `tz.h` et `tz.cpp` afin de le rendre single header like `date.h`.

Sorry if my english is a little convoluted but the french is my mother langage.

**Comment by HowardHinnant** [comment]
Your english is far better than my french. :-)

**Comment by HowardHinnant** [comment]
I am hopeful that this commit addresses the problems you've exposed:

https://github.com/HowardHinnant/date/commit/bee4f27d4ab99d5edbdeb14c157bb28f084137ad

Thanks!

**Comment by dorpxam** [comment]
I come back soon (this week) on the project after a upgrade of my OS (win10 pro / new linux distro). In the worst case, if the patch does not work, I would correct the parser myself. 

Friendly.

**Comment by HowardHinnant** [comment]
Great!  Good luck with your upgrade!
