### ISSUE TITLE
how to have a variable for local time returned by make_zoned

### ISSUE THREAD

**Issue by sanjayverma1** [HowardHinnant/date#168]
I want to create a local time variable once for the current zine zone and then use it when needed to get current local time and format it. In all the examples I can find the code creates and uses that variable right there i.e. "auto x = make_zoned(...)". I cannot declare auto as a class member or a global. No matter what type I declare for the return type of make_zoned I cannot compile.

Can you please provide an example.

**Comment by HowardHinnant** [comment]
`zoned_time<D>` is templated on a duration (e.g. `std::chrono::seconds`).  So you can choose what precision you want to hold a `zoned_time`, and then use that.  If you want to use seconds, there also exists a type alias for `zoned_time<seconds>` called `zoned_seconds`.

For example:
````
struct A
{
    date::zoned_time<std::chrono::milliseconds> zt_;
};
````
