### ISSUE TITLE
Unused variable warnings: GCC, -Wall, -DNDEBUG, load_version(), tz.cpp

### ISSUE THREAD

**Issue by neuraleskimo** [HowardHinnant/date#170]
First, thank you Howard and friends for this excellent library!

When building using GCC with -Wall and -DNDEBUG set, I get unused variable warnings for all four variables defined in load_version(). The warnings are generated for the four variables declared in load_version() [as of today, lines 1656-1659].

This function simply appears to read and discard the header from the timezone database. The variables appear to exist simply to be checked by the asserts that follow. However, when building in release mode (-DNDEBUG) with -Wall, GCC generates unused variable warnings (as expected) because the asserts are compiled out.

One simple solution would be to disable those warnings for this specific section of code, which I would be happy to commit. However, I am not sure that is the right thing to do. Using asserts certainly saves a few instructions in release mode, but is this a run-time or logic error? The current code assumes a logic error. If one considers this a run-time error, then "... = inf.get(); if (...) throw ..." seems a better solution. 

Thoughts, advice, criticism, curse words, etc.?

**Comment by neuraleskimo** [comment]
My bad... copy-and-paste error... I meant load_header()

**Comment by HowardHinnant** [comment]
Thanks!

I consider it a logic error.  If we're reading one of these files and it isn't a TZIF file, its a bug that needs to be fixed before continuing.

Fixed: https://github.com/HowardHinnant/date/commit/e0c962a8ce8ebbee63a40b9557124d259759ac3c

**Comment by neuraleskimo** [comment]
Thanks for the extremely quick response and fix!
