### ISSUE TITLE
Error while compiling with INSTALL on linux

### ISSUE THREAD

**Issue by Marvelsoft** [HowardHinnant/date#171]
We have downloaded and extracted IANA database and tried to use custom install location. We got a compilation error:
```
../date/tz.cpp: In function ‘std::__cxx11::string get_download_folder()’:
../date/tz.cpp:228:37: error: ‘expand_path’ was not declared in this scope
     return expand_path("~/Downloads");
``                                     ^
```
By moving definition of get_download_folder() into !INSTALL guard scope we solved the problem.

Is this proper solution?

**Comment by HowardHinnant** [comment]
Yes, sorry about that.  Would you like to submit a pull request with this fix?  Or I can fix it.  If you submit a PR, you are encouraged to add your name to the copyright list of tz.cpp.

**Comment by Marvelsoft** [comment]
Will do, thank you.

**Comment by HowardHinnant** [comment]
It looks like this will make the `#    ifndef INSTALL` region empty, and thus that `#ifndef` is simply not needed.

**Comment by Marvelsoft** [comment]
So I guess I will leave to you to fix it.

Thank you once again.

**Comment by HowardHinnant** [comment]
Thanks for reporting this!

Fixed: https://github.com/HowardHinnant/date/commit/0c8b1f596785e89c59ff151b5bacc41c8db05e38
