### ISSUE TITLE
Exception on date::parse

### ISSUE THREAD

**Issue by rbocanegra** [HowardHinnant/date#172]
Hi!

If I try to convert a string to epoch with an invalid string it thows an exception instead of setting the failbit of the input stream.

If I run the following snippet:
```
std::string str = "2017-07-23 14:55:"; // note it lacks seconds
std::string format = "%F %T";
std::istringstream input(str);
date::sys_seconds tp;
input >> date::parse(format, tp);
if (input.fail()) 
{
    std::cout << "<ERROR!> while trying to convert the specified format!\n";
}
else
{
    auto epoch = tp.time_since_epoch().count();
    std::cout << "Epoch: " << epoch;
}        
```
An exception "invalid stold argument" is thrown and nothing is printed on the console.
On the other hand if I use "2017-07-23 14:55" (without seconds and ':') it sets the failbit without exception and outputs the error message.

I have had a look at the code (date.h) and it seems that in the `read_long_double` function the local `buf` string it's not being checked if it is empty before calling `std::stold`.

I can submit a PR if you want.

**Comment by HowardHinnant** [comment]
Thanks for the report!  I'm reproducing it as well.

PR's always welcome.  You are encouraged to add your name to the copyright list of any files you change.

We also need to survey the code to see if this type of bug is lurking elsewhere.

**Comment by HowardHinnant** [comment]
I've done a brief survey and don't see this bug repeated elsewhere.  If you get a chance to do such a sweep, a second set of eyes never hurts. :-)

**Comment by HowardHinnant** [comment]
Here's my recommended fix:
````
--- a/date.h
+++ b/date.h
@@ -5334,7 +5334,10 @@ read_long_double(std::basic_istream<CharT, Traits>& is, unsigned m = 1, unsigned
             break;
     }
     if (count < m)
+    {
         is.setstate(std::ios::failbit);
+        return 0;
+    }
     return std::stold(buf);
 }
````
This just avoids the call to `stold` if the minimum number of digits isn't parsed.

**Comment by rbocanegra** [comment]
Hi Howard,
I fixed it with the following:
```
@@ -5310,7 +5310,7 @@ read_long_double(std::basic_istream<CharT, Traits>& is, unsigned m = 1, unsigned
     }
     if (count < m)
         is.setstate(std::ios::failbit);
-    return std::stold(buf);
+    return buf.empty() ? 0.0 : std::stold(buf);
 }
```
I used a different condition, not sure if `buf` is always empty when `count < m`. I could make a PR with either of the fixes you prefer.

**Comment by HowardHinnant** [comment]
Thanks for working on this!

Try your test with this modified input:
````
std::string str = "2017-07-23 14:55:.";
````
(I've added a `.`)

**Comment by rbocanegra** [comment]
Now I'm sure `buf` is not always empty when `count < m`. ;) Thanks!

**Comment by rbocanegra** [comment]
Feel free to do the PR, you implemented the right solution in the end. :-)

**Comment by HowardHinnant** [comment]
I'm easy either way.  But I'm trying to encourage people to contribute to this library.  You found the bug and developed a good test for it.

**Comment by rbocanegra** [comment]
Don't worry, I'm pleased to contribute, but I feel weird to put my name on the copyright on a fix that is yours. :-)

**Comment by HowardHinnant** [comment]
No worries, thanks.  Fixed: https://github.com/HowardHinnant/date/commit/606737112777d4e0457da4700da011cd38ed6ea1
