### ISSUE TITLE
Support for time_point + offset

### ISSUE THREAD

**Issue by d-frey** [HowardHinnant/date#173]
Some use-cases (for example trying to implement/use [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt)) require a time_point with a UTC offset. An offset is not a time-zone as several time-zones can share the same offset. What I'm asking for is a layer in between `sys_time`/`local_time` and `zoned_time`, maybe called `offset_time`.

It would be nice to have support for `offset_time` in `date.h`, as `tz.h` requires `tz.cpp` (hence not being suitable for a header-only library) and the latter also carries quite some overhead which offset-based timestamps don't need.

**Comment by HowardHinnant** [comment]
I'll give it some thought.  However this might be better written in user-code as a new type of clock, say `offset_clock` or something like that.  It is very little code.  And there is no one correct way to write it.  For example is the offset a compile-time constant that the `offset_clock` is templated on?  This would make each `time_point<offset_clock<offset>>` different types so they can't be easily mixed up.  Or you could make the offset a run time property of `offset_clock`, and provide inter convertibility between time_points with different offsets.

**Comment by d-frey** [comment]
Thank you, if I can help in any way, let me know.

My use-case requires a run-time offset. I'll play with your idea and see where it'll lead me, but I think it should be a part of a more standardized part of the library as I'm going to expose this type to the users of my library (an extended JSON-library that can handle date, time, timestamps, ... as native types). I don't really want to add custom types if there is something more common available that users will already know.

**Comment by d-frey** [comment]
One thing that "clicked" in my head is that a time_point is really a duration relative to a "fixed" reference point in time. Now, `clock` might be the wrong name for the first template parameter of `time_point`, given that `local_t` is not really a clock already. It is an unspecified abstract reference point that later needs to be combined with an actual reference point (UTC, TAI, GPS, ...) to make sense.

Anyways, if I follow this thought, I could create an offset_clock with a fixed offset given as a template parameter as you suggested. However, I can not create an offset_clock which stores a runtime-value for the offset, as the `time_point` will not store an instance of a clock, it just uses the clock as a template parameter.

Is it too far of a stretch to think that the clock should be more like an allocator, meaning that a `time_point` should store an instance of a clock (of course optimized away if the clock class is an empty class)? The clock could then store its own data (like an adjustable offset towards UTC) and some methods should be used to route conversions through it. (or should this be done elsewhere?)

> Or you could make the offset a run time property of offset_clock, and provide inter convertibility between time_points with different offsets.

Without the `time_point` storing an instance of the clock, I do not see how the above would be possible. Did you have some other design in mind that I do not see?

**Comment by HowardHinnant** [comment]
You are correct about run-time offsets.  All time_points would be the same type (same clock), and thus time_points with different offsets could get confused with one another.

Another area to explore would be a `offset_zone` or `offset_time_zone`.

**Comment by HowardHinnant** [comment]
This is still in the prototype stage (and not committed), but the following program just ran for me:
````
#include "tz.h"
#include <iostream>

class OffsetZone
{
    std::chrono::minutes offset_;

public:
    explicit OffsetZone(std::chrono::minutes offset)
        : offset_{offset}
        {}

    template <class Duration>
        date::local_time<typename std::common_type<Duration, std::chrono::minutes>::type>
        to_local(date::sys_time<Duration> tp) const
        {
            using namespace date;
            using namespace std;
            using namespace std::chrono;
            using LT = local_time<common_type_t<Duration, minutes>>;
            return LT{(tp + offset_).time_since_epoch()};
        }
};

int
main()
{
    using namespace date;
    using namespace std::chrono;
    OffsetZone tz{-4h};
    zoned_time zt = {&tz, system_clock::now()};
    std::cout << zt.get_local_time() << '\n';
}
````
I've templated `zoned_time` on `TimeZone`, with a default `TimeZone` of `date::time_zone`.

This is taking advantage of C++17's template deduction guides, but the idea can be back-ported to `make_zoned`.

**Comment by d-frey** [comment]
This stores a pointer to the `OffsetZone`, so it is not embedded in the `zoned_time`. Obviously, this doesn't really work as a value type.

Maybe instead of embedding the clock in the `time_point` class (which would be problematic as it is already standardized) you could have a "time point with an offset provider". And by offset provider, I mean that it could be:

* "no offset" (maybe not needed if you treat it as a fixed compile-time offset of 0)
* fixed compile-time offset (by minutes, or ever milliseconds if one really wants to)
* fixed run-time offset (my use-case)
* dynamic offset due to daylight saving time
* scaled offset (wouldn't that be nice for satellites that have to work with time dilation? ;)

with a class like:

```cpp
template<typename OffsetProvider>
class time_point_offset : Offs
{
};
```

**Comment by d-frey** [comment]
One more thing about the `offset_time`: Those parts that don't depend on the TZ database could go into `date.h` as header-only, including fixed compile-time and run-time offsets.

**Comment by HowardHinnant** [comment]
`zoned_time` as it is today stores a pointer to a `time_zone`.  And `time_zone`s are singletons in the application.  All I'm doing is allowing the client to write alternative time zones that behave the same way as the built-in `time_zone`s.  Having `zoned_time` expose a different API when switching between `time_zone` and a user-written time zone would be confusing.

**Comment by d-frey** [comment]
Understood, but the API wouldn't have to change. You just would have

```cpp
template<typename Duration>
using zoned_time = offset_time<Duration, time_zone_provider>;
```

where the `time_zone_provider` stores the pointer and provides a common API. All of your existing code/design can be preserved, you just get new options.

**Comment by HowardHinnant** [comment]
I'm not crazy about saying that `zoned_time` _is a_ `OffsetProvider`.  It seems more open to errors (such as implicit `zoned_time` to `time_zone_provider` conversions), and more complicated than the simple "pair of time zone and sys_time" model of the current `zoned_time`.

I'm currently experimenting with:
````
template <class Duration, class TimeZonePtr = const time_zone*>
class zoned_time
````
I.e. templating on the time zone pointer type.  This allows customization of the way the time zone is stored.  For example I have a `zoned_time<seconds, unique_ptr<OffsetZone>>` example working.

Here I'm envisioning `OffsetZone` as user-written code, not library supplied.  Here's the complete class:
````
class OffsetZone
{
    std::chrono::minutes offset_;

public:
    explicit OffsetZone(std::chrono::minutes offset)
        : offset_{offset}
        {}

    template <class Duration>
        date::local_time<typename std::common_type<Duration, std::chrono::minutes>::type>
        to_local(date::sys_time<Duration> tp) const
        {
            using namespace date;
            using namespace std;
            using namespace std::chrono;
            using LT = local_time<common_type_t<Duration, minutes>>;
            return LT{(tp + offset_).time_since_epoch()};
        }

    template <class Duration>
        date::sys_time<typename std::common_type<Duration, std::chrono::minutes>::type>
        to_sys(date::local_time<Duration> tp) const
        {
            using namespace date;
            using namespace std;
            using namespace std::chrono;
            using ST = sys_time<common_type_t<Duration, minutes>>;
            return ST{(tp - offset_).time_since_epoch()};
        }

    template <class Duration>
        date::sys_info
        get_info(date::sys_time<Duration> st) const
        {
            using namespace date;
            using namespace std::chrono_literals;
            return {sys_seconds::min(), sys_seconds::max(), offset_,
                    0min, offset_ >= 0min ? "+" + date::format("%H%M", offset_)
                                          : "-" + date::format("%H%M", -offset_)};
        }
};
````
It doesn't support everything `time_zone` does, nor does it need to.  One just doesn't instantiate those parts of `zoned_time` you don't need, such as use of `locate_zone` or `choose::earliest`.

**Comment by HowardHinnant** [comment]
Ah, and give `OffsetZone` this member:
````
    const OffsetZone* operator->() const {return this;}
````
And then `zoned_time<seconds, OffsetZone>` works too.

**Comment by HowardHinnant** [comment]
```c++
template <class Duration, class TimeZonePtr = const time_zone*>
class zoned_time;
```
is now on the master branch.
