### ISSUE TITLE
Distinct types for date / time / timestamp

### ISSUE THREAD

**Issue by d-frey** [HowardHinnant/date#174]
Question: I want to support four different types within my library.

1. A pure date (`local_days` seems to be that)
2. A pure time (`time_of_day<...>` seems to fit?)
3. A generic timestamp without any UTC offset or time zone (`local_time<...>`?)
4. A generic timestamp with a UTC offset.

Even without the 4th bullet point, the overload set I ended up with seems strange. Some points I wonder about:

* `local_days` is still a timestamp (`time_point`) with a low resolution.

* `sys_days` is also an option to allow implicit conversion from `year_month_day`, etc. - shouldn't the latter convert to `local_days` implicitly and only explicitly to `sys_time`?

* `time_of_day` is a field type. This seems inconsistent. Is there a serial type for this purpose that I missed? Should it exist? (Note that I can't just use a `time_point` and leave the date at 1970-01-01 as this will not create a distinct type that I can overload for...)

*  The 3rd item requires me to reduce the set of matching types with SFINAE to make sure it doesn't interferes with `local_days`. I went for "seconds or better", but I'm unsure if this is a good idea.

Any advice on how to achieve distinct types that can be properly overloaded and that still retain the convenience from the rest of `<chrono>` and `date.h` is appreciated.

My test/example code so far:

```cpp
#include <array>
#include <chrono>
#include <iostream>
#include <type_traits>
#include <utility>

#include "date.h"

using namespace std::chrono;
using namespace date;

template< typename T >
using is_seconds_or_less = std::enable_if_t< std::ratio_less_equal< typename T::period, seconds::period >::value >;

void f( sys_days v )
{
   std::cout << "date (s): " << v << std::endl;
}

void f( local_days v )
{
   std::cout << "date (l): " << v << std::endl;
}

template< typename T >
void f( time_of_day< T > v )
{
   std::cout << "time (l): " << v << std::endl;
}

template< typename T >
is_seconds_or_less< T > f( sys_time< T > v )
{
   std::cout << "timestamp (s): " << v << std::endl;
}

template< typename T >
is_seconds_or_less< T > f( local_time< T > v )
{
   std::cout << "timestamp (l): " << v << std::endl;
}

int main()
{
   f( 2017_y / 07 / 11 );
   f( 2017_y / jul / wed[ 2 ] );
   f( local_days{ 2017_y / 07 / 13 } );
   f( local_days{ 2017_y / jul / wed[ last ] } );

   f( time_of_day< microseconds >{ 1h + 2min + 3s + 4ms + 5us } );

   f( system_clock::now() );

   f( sys_days{ 2017_y / 07 / 12 } + 1h + 2min + 3s + 4ms + 5us );
   f( local_days{ 2017_y / 07 / 12 } + 1h + 2min + 3s + 4ms + 5us );
}
```

**Comment by HowardHinnant** [comment]
`local_days` is a good type for a pure date.  Other possibilities include `year_month_day`, or any other full calendar type.

I suggest a `chrono::duration` for a pure time.  It is easier and more efficient to do arithmetic on it.  If you want to make it type-safe from other durations, you  could wrap it up.

`local_time<D>` is a good "zone-less" timestamp.

`sys_time<D>` is a good UTC timestamp.

Yes, having calendar types implicitly convert to `local_days` instead of `sys_days` would be another good design.  It is the way it is mainly because `local_time` is a relatively late addition to this library.

`time_of_day` is a somewhat awkward type that I'm not particularly happy with.  It is very convenient to build format and parse on top of, but not for a lot else (imho).  Still, many clients want a helper just to get hours, minutes and seconds out of a duration, so I'm hesitant to rip it out.

Your overload solution is quite similar to mine shown here:

https://github.com/HowardHinnant/date/blob/master/date.h#L4147-L4167

**Comment by d-frey** [comment]
Storing the time of day in a duration does not feel right to me. The time of day is not a duration, it is a duration relative to the begin of an unspecified/any day, hence it should be a `time_point` where the clock is an abstract notion of "begin of day". Or, as in #173, it could also be a time of day with an offset (I've seen something like that in the wild).

It is different than other clocks as it should be some kind of a wrap-around clock. If the clock itself could influence its conversion from and to others, this could be doable. Or maybe it is not even needed? An `ok()`-method for a `time_point`-instance might also be an idea. I'm just playing with ideas... :)

This also means that I'd expect (intuitively) that `time_of_day` is a serial type that is just a `time_point`, maybe with a special clock.

You also mentioned that you are not too happy with the current `time_of_day`. Maybe that is partly cause by the name being slightly inconsistent with other field types. Other field type names are derived from their individual fields, so how about renaming the current `time_of_day` to `hour_minute_second_frac`? With short-cuts if you like:

```cpp
template< typename Duration >
struct hour_minute_second_frac { ... };
// ...plus specializations if needed...

using hour = hour_minute_second_frac< hours >;
using hour_minute = hour_minute_second_frac< minutes >;
using hour_minute_second = hour_minute_second_frac< seconds >;
using hour_minute_second_millis = hour_minute_second_frac< milliseconds >; // name ok? maybe leave this out
// ...
```

**Comment by HowardHinnant** [comment]
That's a good suggestion, thanks.

**Comment by HowardHinnant** [comment]
`time_of_day` has been renamed by the std committee to `hh_mm_ss`.

**Comment by HowardHinnant** [comment]
Closing.  The design phase of this library is now locked down and tracking the draft C++20 spec:  http://eel.is/c++draft/#time
