### ISSUE TITLE
User-defined operator for year_month_day

### ISSUE THREAD

**Issue by d-frey** [HowardHinnant/date#175]
While playing with your library, I came up with this:

```cpp
template< std::size_t N, char C, char... Cs >
struct pick : pick< N - 1, Cs... >
{
};

template< char C, char... Cs >
struct pick< 0, C, Cs... >
   : std::integral_constant< char, C >
{
};

template< char C >
struct digit
   : std::integral_constant< unsigned, C - '0' >
{
   static_assert( ( C >= '0' ) && ( C <= '9' ), "invalid digit" );
};

template< char... Cs >
year_month_day operator""_date()
{
   static_assert( sizeof...( Cs ) == 10, "invalid length" );
   constexpr const year y{ digit< pick< 0, Cs... >::value >::value * 1000 + digit< pick< 1, Cs... >::value >::value * 100 + digit< pick< 2, Cs... >::value >::value * 10 + digit< pick< 3, Cs... >::value >::value };
   static_assert( pick< 4, Cs... >::value == '\'', "invalid format" );
   constexpr const month m{ digit< pick< 5, Cs... >::value >::value * 10 + digit< pick< 6, Cs... >::value >::value };
   static_assert( m.ok(), "invalid month" );
   static_assert( pick< 7, Cs... >::value == '\'', "invalid format" );
   constexpr const day d{ digit< pick< 8, Cs... >::value >::value * 10 + digit< pick< 9, Cs... >::value >::value };
   static_assert( d.ok(), "invalid day" );
   constexpr const year_month_day result{ y / m / d };
   static_assert( result.ok(), "invalid date" );
   return result;
}
```

which allows you to put these literals into you source:

```
2017'07'12_date
```

Feel free to add something like that to your library if you feel it might be useful / more readable.

The same technique could also be used to allow

```
10'05'23.23145_time
```

but it's a bit more complicated because of the fractional part. (If you are interested I could write some code for that as well...)

**Comment by HowardHinnant** [comment]
That's pretty cool!  I'm not sure if it should be added or not, but I will definitely play around with it and consider it.

If others reading this have opinions on if this should be added or not, please feel free to express your opinions here.

**Comment by HowardHinnant** [comment]
I admire the cleverness of this code.  However I don't think it is a good fit to integrate into the lib because it isn't significantly better than the existing syntax for date and time literals, and I can't find a motivation for introducing more ways to express literals.

All that being said, this is pretty cool code and I strongly suspect it is going to pop up again, possibly in a completely unrelated context! :-)
