### ISSUE TITLE
Warning while compiling with INSTALL on linux

### ISSUE THREAD

**Issue by Marvelsoft** [HowardHinnant/date#176]
Hi Howard,

This issue is related to the one previously reported in [#171](https://github.com/HowardHinnant/date/issues/171) and closed by commit https://github.com/HowardHinnant/date/commit/0c8b1f596785e89c59ff151b5bacc41c8db05e38 .
Now we have unused function warning.
```cpp
../date/tz.cpp:222:1: warning: ‘std::__cxx11::string get_download_folder()’ defined but not used [-Wunused-function]
get_download_folder()
 ^
```
We have solved this by getting back removed `#ifndef INSTALL`. We will create a pull request so you can decide what to do.

Regards

**Comment by HowardHinnant** [comment]
Fixed: https://github.com/HowardHinnant/date/commit/a828109809136a3cbc8d76bb173d4b943e3c2a04

Thanks!
