### ISSUE TITLE
year_month_day can not add days().

### ISSUE THREAD

**Issue by denchat** [HowardHinnant/date#178]
`auto ymd1 = jan/31/2017 + years(1); //ok`
`auto ymd2 = jan/31/2017 + months(1); // ok`
`auto ymd3 = jan/31/2017 + days(1); // not compiled`

Or is this normal?

**Comment by HowardHinnant** [comment]
This is normal.  You can convert `jan/31/2017` to `sys_days` or `local_days` and then add `days` to it:
````
auto ymd3 = sys_days{jan/31/2017} + days{1};
````
This results in a `sys_days`, if you want it as a `year_month_day` you can:
````
year_month_day ymd3 = sys_days{jan/31/2017} + days{1};
````
The reason is efficiency.  The serial<->field conversions are where the expense comes in and so the library puts you in control as to where and how often those conversions take place.  This is described in more detail here: https://github.com/HowardHinnant/date/wiki/FAQ#day_arithmetic

**Comment by HowardHinnant** [comment]
Oh, I should add:  If you have some `year_month_day` object that you know is "early in the month" and you just want to bump it a day without going to the expense of converting it to serial and back, you can also:
````
auto ymd2 = ymd.year()/ymd.month()/(ymd.day() + days{1});
````
This of course does not overflow checking.  It is literally just adding 1 to the day field.  If you overflow the month (e.g. jan/32), you will get the same thing as:  `jan/32/2017`.

The conversion to serial and back never overflows the month.  Indeed, the conversion to serial will accept `jan/32/2017` and convert it back as `feb/1/2017`.

**Comment by denchat** [comment]
Shouldn't `days()` be called `sd_days()` (or with any other prefix) instead? To implicitly hint that its usage is not the same as `months()` and `years()`. Well, second thought, maybe that `sd_days()` would be less "pretty" though.

**Comment by HowardHinnant** [comment]
Nope.  `days` is a `chrono::duration`, just like `seconds`, `nanoseconds` and `hours`.  Durations are "time point neutral."

**Comment by denchat** [comment]
Is the reason that the operators are not provided because the implicit conversions between year_month_weekday and year_month_day would make the operators provided implicitly "expensive"?

**Comment by HowardHinnant** [comment]
No.  It is to remind the programmer that if he is going to be doing a lot of day-oriented arithmetic, `year_month_day` is not a good data structure for that.  Use a `sys_time<D>` or `local_time<D>` instead.

**Comment by denchat** [comment]
I think that's the kind of explicit explanation I need! Thank you.
