### ISSUE TITLE
12 hour time is not properly handled in the stream parser

### ISSUE THREAD

**Issue by trink** [HowardHinnant/date#182]
From the cppcon 2016 TZ presentation slides:
```cpp
  local_time<milliseconds> local_tp;
  istringstream in{"Tue, Sep 20 2016 at 5:15:37.002 PM"};
  in >> parse("%a, %b %d %Y at %I:%M:%S %p", local_tp);
  cout << local_tp << '\n';
```
outputs `2016-09-20 00:15:37.002` instead of `2016-09-20 17:15:37.002`

**Comment by HowardHinnant** [comment]
I'm guessing you've got a parse failure, and the output is random.  Can you `assert(!in.fail());` after the parse?

**Comment by HowardHinnant** [comment]
Fwiw, I'm not reproducing your results on clang/libc++.  But this call is going to be using your std::lib's `std::get_time` for the `%a`, `%b`, `%I` and `%p` so there could be a non-portable issue there.  Which std::lib are you using? (platform and version).

**Comment by trink** [comment]
I added the assertion, there was no parse failure.
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
GLIBCXX_3.4.21

**Comment by HowardHinnant** [comment]
This looks like gcc's bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=71367

But you exposed a bug in date.h too.  I'm not setting `failbit` when I should.  So I'll get that fixed, thanks.

**Comment by HowardHinnant** [comment]
Now with `failbit`:  https://github.com/HowardHinnant/date/commit/a034eeed23aa7dc86f95e713c4b1e5332bc4a407

**Comment by trink** [comment]
Confirmed, thank you.
