### ISSUE TITLE
Compilation errors with Visual Studio 2013

### ISSUE THREAD

**Issue by pauluap** [HowardHinnant/date#183]
I did see issue #24 but the things covered in that issue seem to have been resolved.

In the thread for that issue, it was said that date.h does not include any user defined literals.  I have an UDF error message so I believe things have changed since then.

I'm getting those errors:
```

>D:\git\site_controller\external\date/date.h(3716): error C2610: 'date::detail::time_of_day_storage<std::chrono::duration<_Rep,_Period>,hour>::time_of_day_storage(void) throw()' : is not a special member function which can be defaulted
1>          exception specification is not allowed
1>          D:\git\site_controller\external\date/date.h(3778) : see reference to class template instantiation 'date::detail::time_of_day_storage<std::chrono::duration<_Rep,_Period>,hour>' being compiled
1>D:\git\site_controller\external\date/date.h(4084): error C2610: 'date::time_of_day<Duration>::time_of_day(void) throw()' : is not a special member function which can be defaulted
1>          exception specification is not allowed
1>          D:\git\site_controller\external\date/date.h(4095) : see reference to class template instantiation 'date::time_of_day<Duration>' being compiled
1>D:\git\site_controller\external\date/date.h(4182): error C2059: syntax error : 'bad suffix on number'
```
This is for commit a034eee 

I'm willing to assist if a clear plan develops

**Comment by HowardHinnant** [comment]
Thanks for the report!  Yeah, I need people such as yourself to help me keep the VS-2013 port going.  Your help is much appreciated.

I would love to have you test a fix and then submit a PR.  If you do this, you are encouraged to add your name to the list of copyright holders for all files you modify.

For the first two errors, I'm guessing we could just #ifdef our way around it, for example:

```
#if !defined(_MSC_VER) || _MSC_VER >= 1900
    CONSTCD11 time_of_day_storage() NOEXCEPT = default;
#else
    CONSTCD11 time_of_day_storage() = default;
#endif
```
Or if VS-2013 doesn't like that, maybe:
```
   time_of_day_storage() {};
```
For the third error we should use:
```
    year_month_day        ymd{year{0}/0/0};
```
