### ISSUE TITLE
Default constructor of date::year_month_weekday makes call to implicitly deleted constructor

### ISSUE THREAD

**Issue by pauluap** [HowardHinnant/date#187]
The code

```date::year_month_weekday ymwd;```

does not compile because the `date::weekday_indexed` member of `date::year_month_weekday` declares constructors, but not a default one, so the default constructor is implicitly deleted, thus `date::year_month_weekday` is not default constructable.

**Comment by HowardHinnant** [comment]
Fixed: https://github.com/HowardHinnant/date/commit/4ae416f06a461776f9e4b2aecbdd1d66f89673d1
Thanks!
