### ISSUE TITLE
Windows build needs NOMINMAX

### ISSUE THREAD

**Issue by davidhunter22** [HowardHinnant/date#19]
The tz.cpp file include Windows.h. I would be good to
#define NOMINMAX
before this include to avoid Windows.h defining min and max macros
It would also be faster if
#define WIN32_LEAN_AND_MEAN
was defined as well

**Comment by gmcode** [comment]
Hi David, thanks for your feedback. I have submitted a pull request #21 that should address your comments.

**Comment by HowardHinnant** [comment]
https://github.com/HowardHinnant/date/pull/21 has been merged.
