### ISSUE TITLE
apple-clang linker errors

### ISSUE THREAD

**Issue by acgetchell** [HowardHinnant/date#190]
Using the canonical example for tz.h:

https://github.com/acgetchell/CDT-plusplus/blob/fix-segfault/src/localtime.cpp

I get linker errors with apple clang:

[2/25] Linking CXX executable localtime
FAILED: localtime 
: && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -O3 -DNDEBUG -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/localtime.dir/src/localtime.cpp.o  -o localtime  /usr/local/lib/libmpfr.dylib /usr/local/lib/libgmp.dylib /usr/local/lib/libCGAL_Core.12.0.0.dylib /usr/local/lib/libCGAL.12.0.0.dylib /usr/local/lib/libboost_thread-mt.dylib /usr/local/lib/libboost_system-mt.dylib /usr/local/lib/libboost_chrono-mt.dylib /usr/local/lib/libboost_date_time-mt.dylib /usr/local/lib/libboost_atomic-mt.dylib /usr/local/lib/libCGAL_Core.12.0.0.dylib /usr/local/lib/libCGAL.12.0.0.dylib /usr/local/lib/libboost_thread-mt.dylib /usr/local/lib/libboost_system-mt.dylib /usr/local/lib/libboost_chrono-mt.dylib /usr/local/lib/libboost_date_time-mt.dylib /usr/local/lib/libboost_atomic-mt.dylib /usr/local/lib/libtbb.dylib /usr/local/lib/libtbbmalloc.dylib && :
Undefined symbols for architecture x86_64:
  "date::current_zone()", referenced from:
      _main in localtime.cpp.o
  "date::time_zone::get_info_impl(std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> > >) const", referenced from:
      std::__1::basic_ostream<char, std::__1::char_traits<char> >& date::to_stream<char, std::__1::char_traits<char>, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l> >, date::time_zone const*>(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, date::zoned_time<std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l> >, date::time_zone const*> const&) in localtime.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by HowardHinnant** [comment]
It looks like you need to add date/tz.cpp to your build.

**Comment by acgetchell** [comment]
Thank you for the reply. If I've completed your directions successfully, I added the other files per your instructions here: https://github.com/acgetchell/CDT-plusplus/blob/fix-segfault/CMakeLists.txt

And I get these errors:

[3/26] Linking CXX executable localtime
FAILED: localtime 
: && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -O3 -DNDEBUG -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/localtime.dir/src/localtime.cpp.o CMakeFiles/localtime.dir/src/date/tz.cpp.o  -o localtime  /usr/local/lib/libmpfr.dylib /usr/local/lib/libgmp.dylib /usr/local/lib/libCGAL_Core.12.0.0.dylib /usr/local/lib/libCGAL.12.0.0.dylib /usr/local/lib/libboost_thread-mt.dylib /usr/local/lib/libboost_system-mt.dylib /usr/local/lib/libboost_chrono-mt.dylib /usr/local/lib/libboost_date_time-mt.dylib /usr/local/lib/libboost_atomic-mt.dylib /usr/local/lib/libCGAL_Core.12.0.0.dylib /usr/local/lib/libCGAL.12.0.0.dylib /usr/local/lib/libboost_thread-mt.dylib /usr/local/lib/libboost_system-mt.dylib /usr/local/lib/libboost_chrono-mt.dylib /usr/local/lib/libboost_date_time-mt.dylib /usr/local/lib/libboost_atomic-mt.dylib /usr/local/lib/libtbb.dylib /usr/local/lib/libtbbmalloc.dylib && :
Undefined symbols for architecture x86_64:
  "_curl_easy_cleanup", referenced from:
      date::remote_version() in tz.cpp.o
      date::remote_download(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in tz.cpp.o
  "_curl_easy_init", referenced from:
      date::curl_init() in tz.cpp.o
  "_curl_easy_perform", referenced from:
      date::remote_version() in tz.cpp.o
      date::remote_download(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in tz.cpp.o
  "_curl_easy_setopt", referenced from:
      date::remote_version() in tz.cpp.o
      date::remote_download(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in tz.cpp.o
  "_curl_global_init", referenced from:
      date::curl_init() in tz.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by acgetchell** [comment]
Just to make sure it wasn't extra cruft in my project, I forked your repo, and added a CMakeLists.txt and the sample file here:

https://github.com/acgetchell/date

The results are:

┌─[adam][hapkido][±][master → origin ✓][~/date]
└─▪ mkdir build && cd build
┌─[adam][hapkido][±][master → origin ✓][~/date/build]
└─▪ cmake -G Ninja ..
-- The C compiler identification is AppleClang 8.1.0.8020042
-- The CXX compiler identification is AppleClang 8.1.0.8020042
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/adam/date/build
┌─[adam][hapkido][±][master → origin ?:1 ✗][~/date/build]
└─▪ cmake --build .
[2/2] Linking CXX executable localtime
FAILED: localtime 
: && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++   -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/localtime.dir/localtime.cpp.o  -o localtime   && :
Undefined symbols for architecture x86_64:
  "date::current_zone()", referenced from:
      _main in localtime.cpp.o
  "date::time_zone::get_info_impl(std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> > >) const", referenced from:
      date::sys_info date::time_zone::get_info<std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l> > >(std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l> > >) const in localtime.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

**Comment by HowardHinnant** [comment]
You're missing linking against `libcurl`.  I'm a CMake flunky, so I don't know how to fix it in CMake.  But on the command line I just add `-lcurl`.

**Comment by HowardHinnant** [comment]
Here is a SO answer showing how to get `libcurl` with CMake: https://stackoverflow.com/a/30215307/576911

**Comment by acgetchell** [comment]
Thanks so much for the help, it's working now.

(Now I just have to learn how to get AppVeyor to find curl.lib).
