### ISSUE TITLE
where is day_point?

### ISSUE THREAD

**Issue by juandent** [HowardHinnant/date#194]
Hi,

This is probably a silly question but in previous versions of date I used date::day_point which now I cannot find anywhere!

??
Regards,
Juan Dent

**Comment by juandent** [comment]
Never mind - I looked at the previous version of date.h and found the definition of day_point which now is called sys_days. I wasn't expecting an API change - that's what threw me out!
Regards,
Juan

**Comment by HowardHinnant** [comment]
Yeah, sorry about that.  It was painful to change the API, but it turned out to be really necessary.  That should be worst of it, but if you stumble across anything else, I'm happy to help you port to the current version.
