### ISSUE TITLE
Compiler Error with GCC 6.3.0-18

### ISSUE THREAD

**Issue by neuraleskimo** [HowardHinnant/date#196]
When building the latest code from the repo, I get the following error:
"date-master/tz.cpp:1905:22: error: passing ‘const std::vector<date::leap>’ as ‘this’ argument discards qualifiers [-fpermissive]"

Some hopefully useful info:
    gcc 6.3.0-18
    Debian 9.0
    -std=c++14
    -DUSE_OS_TZDB

Of course, let me know if you need any more info.If I get some time this weekend, I will look more closely.

**Comment by HowardHinnant** [comment]
Thanks much for the bug report!  Testing a fix now.  Should push it in the next 10min or so.

**Comment by HowardHinnant** [comment]
Fixed: https://github.com/HowardHinnant/date/commit/272d487b3d490126e520b67fe76bbb2e67226c07
