### ISSUE TITLE
Dynamic location for tzdata

### ISSUE THREAD

**Issue by akimd** [HowardHinnant/date#198]
We're building a piece of software which bundles its dependencies, and find its bits and pieces at runtime based on its path.  I would like to ship a version of tzdata in our tarball, but I don't see how I can tell the tz lib where the data is.  There is `INSTALL`, but it's compile time.  What is the recommended way to give the library the location of tzdata?

I don't want to enable the automatic download feature.

Thanks!

**Comment by akimd** [comment]
I didn't look hard enough to find `set_install`.  Sorry.

**Comment by HowardHinnant** [comment]
No problem.  It is good for me to know that `set_install` is being used.
