### ISSUE TITLE
How to obtain date::sys_time from odbc timestamp struct

### ISSUE THREAD

**Issue by bangusi** [HowardHinnant/date#199]
I have an odbc timestamp that I want to convert to `date::sys_time`.
The odbc struct is declared as ( documented here https://docs.microsoft.com/en-us/sql/odbc/reference/appendixes/c-data-types)

```
struct tagTIMESTAMP_STRUCT {  
   SQLSMALLINT year;  
   SQLUSMALLINT month;  
   SQLUSMALLINT day;  
   SQLUSMALLINT hour;  
   SQLUSMALLINT minute;  
   SQLUSMALLINT second;  
   SQLUINTEGER fraction;
} TIMESTAMP_STRUCT
```
I want the value in iso format e.g. "`2016-12-11 15:43:22.0999919`"

**Comment by HowardHinnant** [comment]
From what I read in the documentation, `fraction` is a count of `nanoseconds` after the `second`.  So the natural `std::chrono::time_point` to hold this value has duration `nanoseconds`:  `date::sys_time<std::chrono::nanoseconds>`.

Here is a function that takes a `tagTIMESTAMP_STRUCT` and converts it to `date::sys_time<std::chrono::nanoseconds>`:
```
date::sys_time<std::chrono::nanoseconds>
to_sys_time(const tagTIMESTAMP_STRUCT& ts)
{
    using namespace date;
    using namespace std::chrono;
    return sys_days{year{ts.year}/ts.month/ts.day} +
           hours{ts.hour} + minutes{ts.minute} + seconds{ts.second} +
           nanoseconds{ts.fraction};
}
```
This could be used like this:
```
int
main()
{
    std::cout << date::format("%F %T\n", to_sys_time({2016, 12, 11, 15, 43, 22, 99991900}));
}
```
which outputs:
```
2016-12-11 15:43:22.099991900
```
This isn't quite what you asked for.  It contains two more decimal digits of precision than what you want.  This can be fixed with:
```
using windows_file_duration = std::chrono::duration<long long, std::ratio<1, 10'000'000>>;

int
main()
{
    std::cout << date::format("%F %T\n", std::chrono::time_point_cast<windows_file_duration>(to_sys_time({2016, 12, 11, 15, 43, 22, 99991900})));
}
```
This truncates the nanosecond-precision output of `to_sys_time` to `100ns`-precision prior to formatting, resulting in:
```
2016-12-11 15:43:22.0999919
```

**Comment by bangusi** [comment]
It works. Thanks.

**Comment by bangusi** [comment]
Bear with me. I want to go back and forth. So I came up with this function to convert my sys_time to odbc timestamp It seems to work but there is quite a bit of code and am wondering if this is the most efficient way to do it. The function will be called potentially millions of times inside a loop. .. reading data from a database.

```
TIMESTAMP_STRUCT fromTimestamp2(const date::sys_time<std::chrono::nanoseconds>& tp)
{
	date::sys_days dp = date::floor<date::days>(tp);
	date::year_month_day the_date = date::year_month_day{ dp };
	TIMESTAMP_STRUCT tm;
	tm.year = (int)the_date.year();
	tm.month = (unsigned)the_date.month();
	tm.day = (unsigned)the_date.day();

	date::time_of_day<std::chrono::nanoseconds> the_time = date::make_time(tp - dp);
	tm.hour = the_time.hours().count();
	tm.minute = the_time.minutes().count();
	tm.second = the_time.seconds().count();
	tm.fraction = the_time.subseconds().count();

	return tm;
}
```

**Comment by HowardHinnant** [comment]
Yes, that looks good to me.  I would've made a few stylistic changes, such as using `auto` for `the_time`, but that won't impact performance.
