### ISSUE TITLE
Multiprecision support

### ISSUE THREAD

**Issue by JaapAap** [HowardHinnant/date#200]
As my application has a need for picosecond resolution, I am using the library with multiprecision integers with the following types:  
```
using mp_int128_t = boost::multiprecision::int128_t;
using mp_duration_t = std::chrono::duration<mp_int128_t, std::pico>
```
I noticed that on some occasions, this doesn't play well with the library. In particular, conversion from string, such as:

`date::to_utc_time<mp_duration_t>("20170101T120000.00","%FT%T%z")`

does not compile  - I think due to the lack of a std::common_type specialization, choking on the line that converts a long-double representation to a `mp_duration_t` one:

`s = round<Duration>(duration<long double>{S})`

I currently use a workaround that translates the string into a nanosecond-resolution duration first, but was just wondering whether it would be possible for the library to support multiprecision resolution?

**Comment by HowardHinnant** [comment]
I think I can get support down to femtoseconds, but not using `boost::multiprecision` in its current form.  I'm experimenting with clang's `__int128_t` as the representation.  The ability to cast from `long double` when parsing is currently a key component.

Even `std::chrono::duration<__int128_t, std::pico>` isn't working on the current master.  But I'm experimenting and testing fixes to get that working, and will likely commit those changes later today.

**Comment by HowardHinnant** [comment]
I've just pushed https://github.com/HowardHinnant/date/commit/481771ef5e991ad620775b1b9365f8c27f6ff076
This adds support down to 128 bit femtosecond precision using a compiler's built-in 128bit integral extension type.  For example:
```
#include "date.h"
#include <iostream>
#include <sstream>

using picoseconds = std::chrono::duration<__int128_t, std::pico>;
using femtoseconds = std::chrono::duration<__int128_t, std::femto>;

inline
picoseconds
operator"" _ps(unsigned long long x)
{
    return picoseconds{x};
}

inline
femtoseconds
operator"" _fs(unsigned long long x)
{
    return femtoseconds{x};
}

int
main()
{
    using namespace date;
    using namespace std;
    using namespace std::chrono;
    istringstream in{"20170101T120059.000000000000001"};
    sys_time<femtoseconds> tp;
    in >> parse("%Y%m%dT%H%M%S", tp);
    std::cout << format("%F %T\n", tp);
}
```
Output:
```
2017-01-01 12:00:59.000000000000001
```
Use of `attoseconds` will fail at compile-time.  I could get it to compile, but I can't get it to reliably round trip through `parse` and `format` without dropping bits (not enough precision in a long double to do so).  So it is best that use of `attoseconds` fails at compile time.

You will continue to get compile-time errors using `boost::multiprecision::int128_t` as the representation as this type does not interoperate with long double.
