### ISSUE TITLE
Fails to get current timezone on FreeBSD

### ISSUE THREAD

**Issue by atkawa7** [HowardHinnant/date#201]
![image](https://user-images.githubusercontent.com/5673828/30232881-2e5f4a9e-94a7-11e7-9618-11bddd08212d.png)

![image](https://user-images.githubusercontent.com/5673828/30232778-a7e24e9e-94a6-11e7-95d5-a61f1cc4ca03.png)

The library experts `/etc/localtime` to be a symbolic link. However on FreeBSD it is not. If you look at the image above it is an actual `tzfile`. To get the timezone in this case we might have to parse the file. Here is my output to zdump

![image](https://user-images.githubusercontent.com/5673828/30233030-de3755ba-94a7-11e7-8238-120db4597590.png)

**Comment by HowardHinnant** [comment]
Do you have a file called /var/db/zoneinfo, and if so, what does it contain?

**Comment by atkawa7** [comment]
Yes I do. Here is the output
![image](https://user-images.githubusercontent.com/5673828/30233981-348ce942-94ae-11e7-9d05-207ebc086b0e.png)

**Comment by atkawa7** [comment]
@HowardHinnant See my fix based on your question #202

**Comment by HowardHinnant** [comment]
That looks excellent, thanks!  I presume you've tested it out and are happy with it.

**Comment by atkawa7** [comment]
@HowardHinnant  Yes I have tested it;
![image](https://user-images.githubusercontent.com/5673828/30234615-bddd27fc-94b3-11e7-9b9a-81a3fc8c9a46.png)

**Comment by HowardHinnant** [comment]
I'll get your P/R merged in short order.  First priority is dinner... ;-)

**Comment by atkawa7** [comment]
@HowardHinnant 👍 :)

**Comment by HowardHinnant** [comment]
Merged: https://github.com/HowardHinnant/date/commit/5f01382e248d77e1c207620e400096ce33837159

Thanks!
