### ISSUE TITLE
CHAR_BIT not defined for GCC 6.3.0

### ISSUE THREAD

**Issue by neuraleskimo** [HowardHinnant/date#204]
Building with GCC 6.3.0 fails on date.h line 1046 because the CHAR_BIT macros isn't found. It appears that limits.h is included in the headers of some implementations, but not GCC 6.3.0. The fix is simply include climits (of limits.h if you prefer).

I submitted PR #203 with a fix.

**Comment by HowardHinnant** [comment]
Merged: https://github.com/HowardHinnant/date/commit/ef6d53595de9bda548c4d705f40ab6bc8eaba1e9

Thanks!

**Comment by neuraleskimo** [comment]
No, thank you for all of your hard work this and years of work on C++.
