### ISSUE TITLE
Is it possible to use Boost's implementation of chrono?

### ISSUE THREAD

**Issue by pauluap** [HowardHinnant/date#209]
I found out that in VS2013, Microsoft's implementation of std::chrono is not standard compliant.  Importantly, steady_clock is inherited from system_clock, which implies that steady_clock is actually NOT monotonic nor steady.

This is referenced in Microsoft Connect
https://connect.microsoft.com/VisualStudio/feedback/details/753115/

I use both steady_clock and system_clock in my project, and I very much require steady_clock to be monotonic and steady.

I do not have the option of moving to a newer version of VS or any other compiler for that matter since my final product needs to be linked against VS2013 libraries that are out of my control.

My question is:  Is it possible to somehow replace std::chrono with boost::chrono?  Or am I stuck with forking and producing a boost-specific version of the date library (hopefully blindly replacing std::chrono with boost::chrono will do it)

**Comment by HowardHinnant** [comment]
It looks to me like the `system_clock` may be ok but that their `steady_clock` is the buggy item.  The date library doesn't use `steady_clock` at all, only `system_clock`.  Can you roll your own `steady_clock`?  <chrono> lets you make custom clocks, and it isn't difficult.  This would allow you to continue to use date (which uses `std::chrono::system_clock`, and you just change all your calls to `std::chrono::steady_clock` to `my_steady_clock`.

**Comment by pauluap** [comment]
That's a good idea.  I started going down the fork route but got caught up in `operator<<` trouble.  Your suggestion looks to be the cleaner way and enables me to select a particular implementation of `steady_clock` without messing with external libraries.

I'll look into implementing `my_steady_clock` QueryPerformanceCounter since rdtsc doesn't seem to be steady (though it is monotonic).

Well... thinking about it some more, I probably can use `std::chrono::system_clock` AND `boost::chrono::steady_clock`.  If that works, that might be the simplest path forward

Thanks!

**Comment by HowardHinnant** [comment]
Why didn't I think of that! :-)

**Comment by pauluap** [comment]
Oh man...  Yes, using `std::chrono::sytem_clock` and `boost::chrono::steady_clock` does work in principle.

In practice, I found it annoying that `std::chrono::duration<Rep, Period>` and `boost::chrono::duration<Rep2, Period2>` were of different types.  I have a pretty big codebase, and I didn't want to go down the path of fixing things up.

At first I thought I could do with free functions to implement `operator+()` and friends, but I got stuck on `boost::chrono::time_point::operator+=` because it wasn't templated.

I then tried deriving from `std::chrono::time_point` but that just required too much code and screwed `operator<<`

Next attempt was deriving from `std::chrono::duration` but that just ended up being the same.

Ultimately, the solution for me ended being much simpler, so I'm adding it here if anyone else runs in the same problem.

Going back to your original suggestion, I ended up creating my own clock, inherited from `boost::chrono::steady_clock` with the only difference being that `now()` returns `std::chrono::duration`
```
#include <chrono>
#include <boost/chrono.hpp>

namespace MySteadyClock {

class steady_clock : public boost::chrono::steady_clock
{
public:
    typedef boost::chrono::steady_clock                        super;
    typedef super::rep                                         rep;
    typedef std::ratio<super::period::num, super::period::den> period;
    typedef std::chrono::duration<rep, period>                 duration;
    typedef std::chrono::time_point<steady_clock, duration>    time_point;

    static time_point now()
    {
        auto tp = super::now();
        return time_point{} + duration{tp.time_since_epoch().count()};
    }

    static time_point now(boost::system::error_code & ec)
    {
        auto tp = super::now(ec);
        return time_point{} + duration{tp.time_since_epoch().count()};
    }
};

} 
```

**Comment by HowardHinnant** [comment]
You're a pioneer with the scars to prove it! ;-)
