### ISSUE TITLE
MinGW cross compilation problem

### ISSUE THREAD

**Issue by tagunil** [HowardHinnant/date#211]
I've tried to cross compile tz.cpp with Linux-hosted MinGW-w64 and bumped into case sensitivity problems. MinGW-supplied headers like windows.h and shlobj.h have lowercase names, so includes like <Windows.h> and <ShlObj.h> cause errors on Linux host. Is there any reason to use mixed-case names of Windows headers?

**Comment by HowardHinnant** [comment]
I actually have no idea.  I have no access nor familiarity with either Windows nor Linux-hosted MinGW-w64.  I depend upon people such as yourself to keep that port going.

**Comment by tagunil** [comment]
Replacing <Windows.h> with <windows.h> and so on works for me.

**Comment by HowardHinnant** [comment]
Would you like to submit a P/R?  Or would you prefer that I make this change?  I won't be able to test it.

**Comment by tagunil** [comment]
I'll submit a PR.

**Comment by tagunil** [comment]
Thank you.
