### ISSUE TITLE
Runtime error on MacOS 10.13

### ISSUE THREAD

**Issue by acgetchell** [HowardHinnant/date#213]
Presumably this is an issue with MacOS 10.13, as it worked on 10.12 [last week](https://travis-ci.org/acgetchell/CDT-plusplus/builds/278197454).

I can compile my code here:

https://github.com/acgetchell/CDT-plusplus

Your date time library is a [subrepo](https://github.com/ingydotnet/git-subrepo) in src/date:

https://github.com/acgetchell/CDT-plusplus/tree/master/src/date

Running the compiled code generates the following error:

~~~
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: default/America/Los_Angeles not found in timezone database
Abort trap: 6
~~~

**Comment by HowardHinnant** [comment]
What command line are you using to compile with / what macros have you set?

<aside> I had a coworker warn me just yesterday not to update to 10.13 as it kept crashing his machine (not tz-related).

**Comment by acgetchell** [comment]
I run a [script](https://github.com/acgetchell/CDT-plusplus/blob/master/build.sh) which executes the following:

~~~
rm -rf build/
mkdir build && cd build
cmake -G Ninja -DGMOCK_TESTS:BOOL=ON -DCMAKE_BUILD_TYPE=Release ..
cmake --build .
~~~

**Comment by HowardHinnant** [comment]
So just to confirm, you have not changed `USE_OS_TZDB` from its default value of `0`?

**Comment by acgetchell** [comment]
No.

https://github.com/acgetchell/CDT-plusplus/search?utf8=✓&q=USE_OS_TZDB&type=

**Comment by HowardHinnant** [comment]
Ok, interesting.  Now the question is:  How is `default/` getting prepended to `America/Los_Angeles`?  The tz lib is correct that "default/America/Los_Angeles" isn't in the database.  But "America/Los_Angeles" is.  In your code to form time zone names, is there some manipulation you're doing that might prepend the "default/"?  Can you reproduce this symptom in a small HelloWorld?

**Comment by acgetchell** [comment]
Here's an example:

https://github.com/acgetchell/tz-example

Here's the results:

┌─[adam][hapkido][±][master ✓][~/tz-example]
└─▪ cmake -G Ninja .
-- The C compiler identification is AppleClang 9.0.0.9000037
-- The CXX compiler identification is AppleClang 9.0.0.9000037
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/adam/tz-example
┌─[adam][hapkido][±][master ?:5 ✗][~/tz-example]
└─▪ cmake --build .
[3/3] Linking CXX executable tz_example
┌─[adam][hapkido][±][master ?:8 ✗][~/tz-example]
└─▪ ./tz_example 
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: default/America/Los_Angeles not found in timezone database
Abort trap: 6

**Comment by HowardHinnant** [comment]
Ah!  `current_zone()` is implicated.  Looking...

**Comment by HowardHinnant** [comment]
Ok, I'm going to need your help on debugging this one since I don't have 10.13 loaded yet.

1.  Does /etc/localtime exist, and if so, what does `ls -l /etc/localtime` output?

**Comment by acgetchell** [comment]
~~~
┌─[adam][hapkido][/etc]
└─▪ ls -l /etc/localtime 
lrwxr-xr-x  1 root  wheel  45 Sep 25 12:36 /etc/localtime -> /var/db/timezone/zoneinfo/America/Los_Angeles
~~~

**Comment by HowardHinnant** [comment]
Ok, thanks.  That helps a lot.  I'm working on a fix.  But I'll need you to test it for me before I put it on master.

**Comment by acgetchell** [comment]
Awesome!

**Comment by HowardHinnant** [comment]
I'm close to a push.  But be forewarned that since you've grabbed master, there's been a directory restructuring:  headers are now in date/include/date and tz.cpp is now in date/src.

**Comment by HowardHinnant** [comment]
Ok, just pushed https://github.com/HowardHinnant/date/tree/high_sierra  If you can confirm this works for you, I'll merge it on to master.  Thanks!

**Comment by acgetchell** [comment]
Doesn't work.

https://github.com/acgetchell/tz-example/commit/31ede2bf772919c6d473940c95ff90a972c7959c

Note that with new directory structure, the includes in tz.cpp have to be modified:

https://github.com/acgetchell/tz-example/commit/31ede2bf772919c6d473940c95ff90a972c7959c#diff-ebc6b09ad17fcc1d67e12519e32bc5a7

Also, in using a git subrepo I verified that I had checked out your high_sierra branch:

~~~
┌─[adam][hapkido][±][master → origin U:2 ✗][~/tz-example]
└─▪ ./build.sh 
-- The C compiler identification is AppleClang 9.0.0.9000037
-- The CXX compiler identification is AppleClang 9.0.0.9000037
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/adam/tz-example/build
[3/3] Linking CXX executable tz_example
┌─[adam][hapkido][±][master → origin U:3 ✗][~/tz-example]
└─▪ ll
total 1144
drwxr-xr-x@  12 adam  staff     384 Sep 25 18:11 .
drwxr-xr-x+ 106 adam  staff    3392 Sep 25 15:08 ..
drwxr-xr-x   17 adam  staff     544 Sep 25 18:11 .git
-rw-r--r--    1 adam  staff      56 Sep 25 18:01 .gitignore
drwxr-xr-x    8 adam  staff     256 Sep 25 18:11 .idea
-rw-r--r--    1 adam  staff     209 Sep 25 18:08 CMakeLists.txt
drwxr-xr-x   10 adam  staff     320 Sep 25 18:11 build
-rwxr-xr-x    1 adam  staff      91 Sep 25 18:03 build.sh
drwxr-xr-x    8 adam  staff     256 Sep 25 15:09 cmake-build-debug
drwxr-xr-x    8 adam  staff     256 Sep 25 18:05 date
-rw-r--r--    1 adam  staff     219 Sep 25 18:10 main.cpp
-rwxr-xr-x    1 adam  staff  565396 Sep 25 15:11 tz_example
┌─[adam][hapkido][±][master → origin U:3 ✗][~/tz-example]
└─▪ ./tz_example 
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: default/America/Los_Angeles not found in timezone database
Abort trap: 6
┌─[adam][hapkido][±][master → origin U:3 ✗][~/tz-example]
└─▪ cd date/
┌─[adam][hapkido][±][high-sierra U:1 ✗][~/tz-example/date]
└─▪ gs
On branch high_sierra
Your branch is up-to-date with 'origin/high_sierra'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   src/tz.cpp

no changes added to commit (use "git add" and/or "git commit -a")
~~~

Which I matched against your changes directly:

https://github.com/HowardHinnant/date/commit/1df9453d915e37988ac7e9b0abef233b35cecd86

https://github.com/acgetchell/tz-example/blob/master/date/src/tz.cpp

**Comment by HowardHinnant** [comment]
The "usual" pattern is to make your `-I<prefix>/date/include`.  And to make your include directives `#include <date/tz.h>`

**Comment by acgetchell** [comment]
Ah, okay, I fixed that with a line in CMakeLists.txt.

Thanks!

**Comment by HowardHinnant** [comment]
So how does it work for you?  Can I merge to master?

**Comment by acgetchell** [comment]
Oh, it doesn't work yet.

~~~
┌─[adam][hapkido][±][high-sierra ✓][~/tz-example/date]
└─▪ gs
On branch high_sierra
Your branch is up-to-date with 'origin/high_sierra'.

nothing to commit, working tree clean
┌─[adam][hapkido][±][high-sierra ✓][~/tz-example/date]
└─▪ cd ..
┌─[adam][hapkido][±][master → origin ↓1 ✓][~/tz-example]
└─▪ ./build.sh 
-- The C compiler identification is AppleClang 9.0.0.9000037
-- The CXX compiler identification is AppleClang 9.0.0.9000037
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/adam/tz-example/build
[3/3] Linking CXX executable tz_example
┌─[adam][hapkido][±][master → origin ↓1 ✓][~/tz-example]
└─▪ ./tz_example 
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: default/America/Los_Angeles not found in timezone database
Abort trap: 6
~~~

**Comment by acgetchell** [comment]
... but let me check that somehow I'm not just using the old code even though I've checked out your high_sierra branch.

**Comment by HowardHinnant** [comment]
Interesting that you got the exact same diagnostic.

**Comment by acgetchell** [comment]
Yes, that's what made me want to make sure I wasn't somehow just running your old code, e.g. CMake was checking out the master branch of the repo behind my back. Perhaps you'd like some other early adopter to confirm, but I think if you `git clone https://github.com/acgetchell/tz-example.git` the same results will obtain.

**Comment by HowardHinnant** [comment]
Ok, thanks.  I will continue to investigate this.  I've got a spare box I'm updating to 10.13 right now.  But it is late in my day I'm not likely to resolve this within the next few hours.

Hang tight and I will get this fixed soon!

**Comment by acgetchell** [comment]
Thank you!

It's very useful to have accurate time when quantizing spacetime.

**Comment by HowardHinnant** [comment]
Fixed on master by https://github.com/HowardHinnant/date/commit/22a229af9106c032949f9a87a9a4fd9cc667a1ee

Thanks for reporting this and your help in tracking it down.

**Comment by acgetchell** [comment]
Thank you so much for the rapid fix!
