### ISSUE TITLE
test failuer in parse.pass.cpp

### ISSUE THREAD

**Issue by galik** [HowardHinnant/date#217]
In the test suit `parse.pass.cpp` fails the assertion on **line 48**:
```cpp
    {
        // correct abbreviation
        std::istringstream in{"Sun 2016-12-11"};
        sys_days tp;
        in >> parse("%A %F", tp);
        assert(!in.fail());
        assert(!in.bad());
        assert(!in.eof());
        assert(tp == 2016_y/12/11);
    }
```
The documentation suggests that, on reading, both `'%a'` and `'%A'` should be able to read in short and long weekday names.

https://howardhinnant.github.io/date/date.html#from_stream_formatting

But, in my tests, `'%a'` can only read short week names (like `Sun`) and `'%A'` can only read in long week names (like `Sunday`).

```cpp    
{
	std::istringstream in{"Sun 2016-12-11"};
	sys_days tp;
	in >> parse("%a %F", tp); // PASS
}
{
	std::istringstream in{"Sun 2016-12-11"};
	sys_days tp;
	in >> parse("%A %F", tp); // FAIL!!
}
{
	std::istringstream in{"Sunday 2016-12-11"};
	sys_days tp;
	in >> parse("%a %F", tp); // FAIL!!
}
{
	std::istringstream in{"Sunday 2016-12-11"};
	sys_days tp;
	in >> parse("%A %F", tp); // PASS
}
```

**Comment by HowardHinnant** [comment]
This is a gcc libstdc++ bug (and maybe VS bug too, I don't recall for sure).  You can work around this bug by compiling with `-DONLY_C_LOCALE`.  This flag disables all use of your platform's locale, even its C locale, and this lib takes on that responsibility, but using only a built-in equivalent of the "C" locale.

**Comment by HowardHinnant** [comment]
This is now a FAQ: https://github.com/HowardHinnant/date/wiki/FAQ#week_day_parse_bug
