### ISSUE TITLE
date::parse seems very slow

### ISSUE THREAD

**Issue by bangusi** [HowardHinnant/date#218]
I am calling date::parse inside a tight loop ( reading date time as string from a database) . It is very slow. It appears I am spending most time in date::parse. 
The code is like this ( obviously not the entire code but the basic logic)
```
typedef date::sys_time<std::chrono::nanoseconds> TausiTimestamp;
while(next_row())
{
	std::wistringstream ss{ get<std::wstring>(db_resultset, index) };
	TausiTimestamp val;
	ss >> date::parse(L"%F %T", val);
}
```
Is there a quicker alternative to parsing date from string?
I was wondering if one can use boost::spirit to parse a date from std::string

Environment: Windows 7, Visual Studio 2017. Compiling x64. Unicode enabled.

**Comment by HowardHinnant** [comment]
You can save a little bit of time by reusing your `ss` instead of reconstructing it each iteration:
```c++
typedef date::sys_time<std::chrono::nanoseconds> TausiTimestamp;
std::wistringstream ss;
while(next_row())
{
    ss.clear();
    ss.str( get<std::wstring>(db_resultset, index) );
    TausiTimestamp val;
    ss >> date::parse(L"%F %T", val);
}
```
If that's still too slow, you can start dropping down a few levels of abstraction:

*  Move to `from_stream` (https://howardhinnant.github.io/date/date.html#sys_seconds).  I doubt this will save you much time, but it is the next level down:
```c++
typedef date::sys_time<std::chrono::nanoseconds> TausiTimestamp;
std::wistringstream ss;
while(next_row())
{
    ss.clear();
    ss.str( get<std::wstring>(db_resultset, index) );
    TausiTimestamp val;
    date::from_stream(ss, L"%F %T", val);
}
```
This can save the construction and destruction of a `L"%F %T"` `wstring`, though I would expect such a short string to fit within the short string buffer, and thus be very fast to construct/destruct.

* The next level down is to start implementing your own parse that hardwires in the `"%F %T"` format, possibly reading directly from your `wstring`.  You would parse `int`s and then convert those `int`s to a `year_month_day` and `duration`, and then convert that to a `TausiTimestamp`.  And it won't get any faster than that.  That conversion to `TausiTimestamp` is wicked fast.

**Comment by bangusi** [comment]
I will attempt the third option because the first did not yield much improvement

**Comment by HowardHinnant** [comment]
You've got a lot of options with the third option:

1.  What precision?  Full nanoseconds?
2.  Do you need to check for errors?

I just completed a dirt-simple option 3 that only did seconds precision with absolutely no error checking.  I present it in the hopes it will be helpful to you.  Add as much precision and error checking as you want.  It is clocking in around 17ns if the cache is hot.
```c++
#include "date/date.h"
#include <iostream>
#include <sstream>
#include <string>
#include <vector>

int
parse_int(const char* b, const char* e)
{
    int i = 0;
    for (; b != e; ++b)
        i = 10*i + (*b - '0');
    return i;
}

date::sys_seconds
my_parse(const std::string& str)
{
    // yyyy-mm-dd hh:MM:ss
    // 0123456789012345678
    using namespace std;
    using namespace std::chrono;
    using namespace date;
    int y = parse_int(str.data() + 0,  str.data() + 4);
    int m = parse_int(str.data() + 5,  str.data() + 7);
    int d = parse_int(str.data() + 8,  str.data() + 10);
    int h = parse_int(str.data() + 11, str.data() + 13);
    int M = parse_int(str.data() + 14, str.data() + 16);
    int s = parse_int(str.data() + 17, str.data() + 19);
    return sys_days{year{y}/m/s} + hours{h} + minutes{M} + seconds{s};
}

int
main()
{
    std::vector<std::string> strings;
    using namespace std::chrono;
    using namespace date;
    auto t = floor<seconds>(system_clock::now());
    constexpr auto N = 1'000'000;
    for (auto i = 0; i < N; ++i, t += 1s)
        strings.push_back(format("%F %T", t));
    std::vector<date::sys_seconds> dates;
    dates.reserve(strings.size());
    auto t0 = steady_clock::now();
    std::istringstream in;
    for (const auto& s : strings)
        dates.push_back(my_parse(s));
    auto t1 = steady_clock::now();
    std::cout << (t1 - t0)/strings.size() << '\n';
}
```

**Comment by bangusi** [comment]
This is super. 
1) I want nanoseconds precision
2) I can enforce the input to be of the format 'yyyy-mm-dd hh24:mi:ss.f'

**Comment by HowardHinnant** [comment]
*Always* 9 `f` digits?  If so that simplifies things, otherwise you have to check for fewer digits and normalize it.  If always 9 `f` digits, then just skip over the `.`, parse an `int` from the next 9 chars, and add that to what I have with ` ... + nanoseconds{ns}`.

**Comment by bangusi** [comment]
Yes, always 9 f digits.

**Comment by HowardHinnant** [comment]
Ok, if that's too slow you are SOL. ;-)

**Comment by bangusi** [comment]
It is much better. 
Thanks.
