### ISSUE TITLE
date::format can return incorrect value

### ISSUE THREAD

**Issue by crusader-mike** [HowardHinnant/date#219]
date::format() looks like this:
```
    std::basic_ostringstream<CharT> os;
    to_stream(os, fmt, tp);
    return os.str();
```

if you get an exception while pushing data into stringstream (e.g. std::bad_alloc) -- it will be 'eaten' by stream and we will end up with incorrect/incomplete result. That is unless I miss something obvious here...

**Comment by HowardHinnant** [comment]
Do you have a recommendation?

**Comment by crusader-mike** [comment]
I'd avoid using iostreams, if possible. Otherwise -- set related bits in `exceptions()` mask and check if given iostream operation can fail for other reasons (besides exception) and (if true) -- add extra check on stream state before calling `str()`.

**Comment by HowardHinnant** [comment]
I'm seriously thinking about rewriting this in terms of `fmt` (https://github.com/fmtlib/fmt/tree/std), especially if that lib continues to advance in the LEWG.  That would be a good time to revisit this issue.

**Comment by crusader-mike** [comment]
seems like a good idea

**Comment by crusader-mike** [comment]
actually, I take it back -- he has the same problem with lost exceptions (when iostream's op<< magic gets used):
```
// Formats a value.
template <typename Char, typename ArgFormatter_, typename T>
void format_arg(BasicFormatter<Char, ArgFormatter_> &f,
                const Char *&format_str, const T &value) {
  internal::MemoryBuffer<Char, internal::INLINE_BUFFER_SIZE> buffer;

  internal::FormatBuf<Char> format_buf(buffer);
  std::basic_ostream<Char> output(&format_buf);
  output << value;

  BasicStringRef<Char> str(&buffer[0], buffer.size());
  typedef internal::MakeArg< BasicFormatter<Char> > MakeArg;
  format_str = f.format(format_str, MakeArg(str));
}
```

**Comment by HowardHinnant** [comment]
So does `std::complex`.  I was actually a little surprised to see that `std::ostringstream` doesn't check its own flags prior to return from `str()`.

**Comment by HowardHinnant** [comment]
We can't repeal without replacing. ;-)

**Comment by crusader-mike** [comment]
It is a popular misconception. Repealing is as simple as passing a "from date X consider following articles void: [...list of articles that introduced feature being repealed...]" and letting lawyers to figure out state of related standard after application of that change.
;-)

**Comment by crusader-mike** [comment]
FYI -- fmt lib got fixed

**Comment by HowardHinnant** [comment]
Is this what you're referring to? https://github.com/fmtlib/fmt/commit/2c077dd44224606994f2a5569b4839324d0e3d26

**Comment by crusader-mike** [comment]
yep. though on second thought -- what if T's op<< explicitly sets bad/fail bit instead of throwing an exception?

**Comment by HowardHinnant** [comment]
If `clear` or `setstate` is used to set a bit that is turned on with `exceptions`, an `ios_base::failure` is thrown.

**Comment by crusader-mike** [comment]
Omg, who comes up with this "logic"? Nevermind then...

**Comment by HowardHinnant** [comment]
I'll put that logic into each of the four `format` functions: https://github.com/HowardHinnant/date/blob/master/include/date/date.h#L5632  Clients can override that decision by using `to_stream` directly if they want.

**Comment by HowardHinnant** [comment]
Done: https://github.com/HowardHinnant/date/commit/f328d8c84a96339870c9bbde34e87e436a21b7e5
