### ISSUE TITLE
Export of time symbols on Visual Studio

### ISSUE THREAD

**Issue by davidhunter22** [HowardHinnant/date#22]
Unless some other mechanism is used to generate an exports table some classes and free functions in the time zone code need some Windows __declspec(dllexport)/__declspec(dllimport) stuff added. Note that in principle this could also support making symbols non public on clang/GCC if there are internal implementation functions or classes that should not really be made visible to users of the library.

I am intending to generate a pull request for this shortly.

**Comment by HowardHinnant** [comment]
Does https://github.com/HowardHinnant/date/commit/ea1717e8ab0c6dd1099720e100e6af18bf320579 completely address this issue?

**Comment by HowardHinnant** [comment]
Closing with the assumption that this has been addressed.  If it has not, please feel free to re-open.
