### ISSUE TITLE
performance question

### ISSUE THREAD

**Issue by crusader-mike** [HowardHinnant/date#220]
I scanned over the code a bit a stumbled upon `msl()` family of functions. They look like they could benefit from some love. For example this doesn't seem to be very efficient (even with small string optimization):
```
    return std::basic_string<CharT>(1, '[') + to_string<CharT>(R::num) + CharT{']'};
```

am I missing something?

**Comment by HowardHinnant** [comment]
To get the best performance, turn on C++14 (or higher).  This particular line of code is just a C++11 workaround for lack of good `constexpr` support.  In C++14 this all happens at compile-time.

**Comment by crusader-mike** [comment]
I see... Thanks you.

One note -- for MSVC constexpr gets used starting from MSVC 2017. C++14 showed up in MSVC 2015. Unless there are other reasons you may want to include MSVC2015 into the club:
```
// MSVC
#  if _MSC_VER < 1910
//   before VS2017
#    define CONSTDATA const
#    define CONSTCD11
#    define CONSTCD14
#    define NOEXCEPT _NOEXCEPT
#  else
//   VS2017 and later
#    define CONSTDATA constexpr const
#    define CONSTCD11 constexpr
#    define CONSTCD14 constexpr
#    define NOEXCEPT noexcept
#  endif
```

**Comment by HowardHinnant** [comment]
If you can show VS-2015 works, I'm happy to change this.  (I don't have VS to test against).  But it is the way it is because of bug reports that VS-2015's constexpr wasn't up to the job.

**Comment by crusader-mike** [comment]
... but then you'll have to discriminate between VS-2015 updates. Not worth the effort.

Thank you.
