### ISSUE TITLE
Using Chrono on embedded systems

### ISSUE THREAD

**Issue by vballworld** [HowardHinnant/date#222]
Hey Howard -- I came across your Chrono talk from CppCon 2016 and couldn't find an email to reach out so figured I'd try to reach you here. Thank you for building Chrono, it looks awesome!

How would I go about using Chrono for an embedded system? How does Chrono know that a single tick of my processor equates to 2ns? (or however fast the processor ticks) 

Currently I have a "timer" var (u32) that is incremented every systick interrupt (every ~1ms) so this tells me how many ms has passed since the system has been on. Would the best way to use Chrono be to continue to use this "timer" var, and simply convert the timer var into a Chrono ms type? Or should "timer" var be replaced w/ a Chrono ms type from the beginning? Or rather, is there a way to directly link the values from the microprocessor's timer register to a Chrono time type?

Thanks again!

**Comment by HowardHinnant** [comment]
Hi,

Fwiw, howard.hinnant@gmail.com

I would create a clock that implements `now` by reading from your timer register:
```
#include <chrono>
#include <cstdint>

struct clock
{
    using rep        = std::uint32_t;
    using period     = std::milli;
    using duration   = std::chrono::duration<rep, period>;
    using time_point = std::chrono::time_point<clock>;
    static constexpr bool is_steady = true;

    static time_point now()
    {
        return time_point{duration{"asm to read timer register"}};
    }
};
```
Adjust `period` to whatever speed your processor ticks at (but it does have to be a compile-time constant).  Above I've set it for 1 tick/ms.  Here is how it should read for 1 tick == 2ns:
```
   using period = std::ratio<1, 2'000'000'000>;
```

**Comment by HowardHinnant** [comment]
Note that with the above suggestion, your `clock::duration` will be unsigned, and thus prone to error if you subtract a later `time_point` from an earlier one.  You can either live with that danger, or make `clock::rep` a signed type, and sacrifice either range or space.
