### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by morinim** [HowardHinnant/date#223]
In the "Implementation" section of the https://howardhinnant.github.io/date/date.html file:

> **Implementation**
>
> This entire library is implemented in a single header: [date.h](https://github.com/HowardHinnant/date/blob/master/date.h) and is open source. 

The link to the `date.h` header should be changed in:

> https://github.com/HowardHinnant/date/blob/master/include/date/date.h

There could be other broken links due to the [change to directory structure](https://github.com/HowardHinnant/date/pull/210).

**Comment by HowardHinnant** [comment]
Fixed: https://github.com/HowardHinnant/date/commit/b3a55312ce0f08db64d781959d56cbaf967e3439

Thanks!
