### ISSUE TITLE
Is it possible to cut a new release ?

### ISSUE THREAD

**Issue by jkhoogland** [HowardHinnant/date#225]
Hi Howard,
would it be possible to cut a new release in the near future ?
Thanks
Jiri

**Comment by HowardHinnant** [comment]
Sure, I'll do that in the next few days.

**Comment by jkhoogland** [comment]
Great thanks,
much appreciated,
Jiri

**Comment by HowardHinnant** [comment]
Keeping this open as a reminder to myself to make it happen. :-)

**Comment by HowardHinnant** [comment]
_Now_ it can be closed. :-)  https://github.com/HowardHinnant/date/releases/tag/2.3
