### ISSUE TITLE
Shouln't the =default constructors be constexpr?

### ISSUE THREAD

**Issue by viboes** [HowardHinnant/date#227]
I don't know if this has a sense, but shouldn't the =default constructors be constexpr?

https://github.com/HowardHinnant/date/blob/fa6529a2fccc4076e30b0e5ae0b5aaf7ff57ab49/include/date/date.h#L404

Note that duration =default constructor is constexpr.

http://en.cppreference.com/w/cpp/chrono/duration/duration

**Comment by HowardHinnant** [comment]
They _are_ `constexpr`, just implicitly:

https://wandbox.org/permlink/suLOiYUpYhFSxXrx

The [specification](https://howardhinnant.github.io/date/d0355r5.html#time.calendar.weekday) is intended to enforce that via the exposition only data member and the `= default` declaration.  I could add the `constexpr` to the specification if that would make it clearer.  They are also `noexcept` (implicitly).

**Comment by viboes** [comment]
I didn't know that the `=default` implementation could be implicitly `constexpr`. Do you have a link to the standard.

I would follow whatever style is used in the standard.

In the standard I'm seen:

```c++
// 23.17.5.1, construct/copy/destroy
constexpr duration() = default;
```
Maybe we need a guideline in the standard.

**Comment by viboes** [comment]
Please, be free to close this issue as `worksforme`.
