### ISSUE TITLE
Problem with zonelet operator= on MS build

### ISSUE THREAD

**Issue by davidhunter22** [HowardHinnant/date#23]
Zone::zonelet marks the assignment operator as deleted. Zone has a member variable std::vector<zonelet> zonelets_. The problem is that the standard states that some containers like vector may require and assignment opererator. Sadly unlike the clang and GCC standard libraries the Visual Studio one does actually require one. Personally I think this is a terrible mistake, forcing all classes you may want to stick in a vector to have assignment is horrible for things like thread safety. Anyway I'm not sure the best way to fix this, other than obviously implementing the assignment which in my code I tend to do only on Windows using an #ifdef. This means the Clang build will check that the assignment operator is not being used anywhere else.

**Comment by HowardHinnant** [comment]
If you can reduce this down to a HelloWorld today and mail it too me (today), I can physically put it under Stephan Lavavej's nose. (I'm in meetings with him today).  Maybe we can get it fixed...

**Comment by davidhunter22** [comment]
Sent you a mail. I will investigate why the VS build seems to want to instantiate vector<zonelet> assigment.

**Comment by HowardHinnant** [comment]
I believe this will address the problem:
https://github.com/HowardHinnant/date/commit/db9f0d19ba4af7a123b24bc5a4ad577c2340dda8
If it does not, please feel free to reopen this issue.
