### ISSUE TITLE
make_zoned bug in 2.3 with VS2015 SP3 ?

### ISSUE THREAD

**Issue by jkhoogland** [HowardHinnant/date#230]
Hi,
I stumbled onto something that looks like a bug in the latest release 2.3(see below)
This works fine on OSX and various linux builds, but fails to compile on windows 10, VS2015 SP3.

I could not figure out what could be causing this yet, 
has anybody experienced something like this on their side and found a solution yet ?

Thanks
Jiri

```
std::string toStringLocal( const std::string& fmt )
{
    using namespace date;
    auto const utcTime = std::chrono::system_clock::now();
    auto const localTime = make_zoned( current_zone(), time_point_cast<milliseconds>( utcTime ) );
    return format( fmt, localTime );
}
```

On compiling I get the following compilation error:

```
error C2665: 'date::make_zoned': none of the 3 overloads could convert all the argument types 
.../Date/tz.h(1643): note: could be 'date::zoned_time<std::chrono::duration<__int64,std::milli>,const date::time_zone *> date::make_zoned<std::chrono::milliseconds>(const std::string &,const std::chrono::time_point<std::chrono::system_clock,std::chrono::milliseconds> &)'
...: note: while trying to match the argument list '(const date::time_zone *, std::chrono::time_point<std::chrono::system_clock,std::chrono::milliseconds>)'
```

**Comment by HowardHinnant** [comment]
I suspect I need to `#ifdef` out the constraints on those `make_zoned` overloads.  That should be easy enough.  Could you confirm what value your `_MSC_VER` is?  Thanks.

**Comment by jkhoogland** [comment]
MSVC++ 14.0 _MSC_VER == 1900 (Visual Studio 2015)

**Comment by HowardHinnant** [comment]
Thanks!  Could you test out the vs branch for me?

https://github.com/HowardHinnant/date/tree/vs

It works for me.  If it works for you I'll merge that into master.

**Comment by jkhoogland** [comment]
Hi Howard,
Phenomenal! It solved the problem.
Thanks for the speedy turnaround!
Regards
Jiri

**Comment by HowardHinnant** [comment]
Thanks!  I've merged this on to master.

Fixed: https://github.com/HowardHinnant/date/commit/e12f7c66f0b8c554298dc0c82c3d41e2c4b4c53b
