### ISSUE TITLE
Seperating timezones and leap seconds

### ISSUE THREAD

**Issue by JaapAap** [HowardHinnant/date#237]
I noticed that there have been some changes allow runtime refreshment of the timezone database. For my application, I need no timezones, but leap seconds are crucial. Internet access is not guaranteed, but leap seconds information is available from a GPS timing receiver. 

I just wonder what at this moment the thoughts are on the possibility of separating the concepts (as the leapseconds are essentially unrelated to the timezones) and allowing the use of only leapseconds (I did see the phrase 'don't pay for what you don't need' being coined)? I realize I have asked before but the recent developments give me some hope that this might be addressed at some point, possibly including options to update the leapseconds database programmatically from the application.

**Comment by HowardHinnant** [comment]
I need an expert such as yourself with access to a GPS timing receiver to design and test things out on.  I unfortunately don't have a GPS timing receiver, and I'm ignorant of the way to access the leap seconds information.

My hope is that `gps_clock::now()` could be implemented to read directly from the GPS timing receiver, and then that would be the primary source of time for that implementation, with other clocks getting their time from `gps_clock` (much like is down now but from `system_clock`).  However that is an untested thought at this time.

**Comment by Erroneous1** [comment]
If we kept a list of leap second times that could be set with something like `void set_leaps(std::vector<utc_seconds>)` and read with `const std::vector<utc_seconds>& get_leaps()` that could be set by the various TZ implementations automatically, would that suffice? Then for converting from utc to gps we'd just do an upper_bound, get the distance from beginning, and add/subtract that many seconds. `set_leaps` would sort the vector just to be sure, or consider unsorted vectors UB.

**Comment by HowardHinnant** [comment]
Such a `vector` exists in the current code.  It is read-only except by the implementation (which currently sets it either from the IANA text database or the IANA sic-compiled binaries, depending on how `USE_OS_TZDB` is set).

It can be inspected like so:
```c++
#include "date/tz.h"
#include <iostream>

int
main()
{
    using date::operator<<;
    for (const auto& leap : date::get_tzdb().leaps)
        std::cout << leap << '\n';
}
```
which currently outputs:
```
1972-07-01 00:00:00  +
1973-01-01 00:00:00  +
1974-01-01 00:00:00  +
1975-01-01 00:00:00  +
1976-01-01 00:00:00  +
1977-01-01 00:00:00  +
1978-01-01 00:00:00  +
1979-01-01 00:00:00  +
1980-01-01 00:00:00  +
1981-07-01 00:00:00  +
1982-07-01 00:00:00  +
1983-07-01 00:00:00  +
1985-07-01 00:00:00  +
1988-01-01 00:00:00  +
1990-01-01 00:00:00  +
1991-01-01 00:00:00  +
1992-07-01 00:00:00  +
1993-07-01 00:00:00  +
1994-07-01 00:00:00  +
1996-01-01 00:00:00  +
1997-07-01 00:00:00  +
1999-01-01 00:00:00  +
2006-01-01 00:00:00  +
2009-01-01 00:00:00  +
2012-07-01 00:00:00  +
2015-07-01 00:00:00  +
2017-01-01 00:00:00  +
```

**Comment by JaapAap** [comment]
@ point 1: The GPS navigation data contains information on the day (given in weeks + day) of either the last leap second introduced (when there are no announced/future leap seconds), or the next (announced) leap second.

I am not an expert in this area, but I think that GPS timing when made available to PCs is typically used to enhance the accuracy of the PC clock, so effectively the system time becomes GPS time.

@point 2: I am currently using `date::get_tzdb().leaps` with a `const_cast` in order to add new leap seconds programmatically (with some minor tweaks made to the code to allow setting leap seconds at a given `sys_day` rather than strings). I have some concerns on thread safety when writing new leap seconds in this manner.  

Note that the leap seconds database change in incremental ways, as past leap seconds will never change. In this sense, there is no need to 'version' the database as is the case for timezones, which could be another good reason to treat the two separately, although I understand that the versioning also helps to solve the thread safety issue?

**Comment by HowardHinnant** [comment]
Would you be able to make your modifications to this lib publicly available so I can view them in more detail?  This would be for the purpose of deciding what, if any, changes I should make.  And if those changes should impact the ongoing standardization effort of this lib.

**Comment by HowardHinnant** [comment]
Closing. The design phase of this library is now locked down and tracking the draft C++20 spec: http://eel.is/c++draft/#time
