### ISSUE TITLE
Library doesn't build with Visual Studio 2013

### ISSUE THREAD

**Issue by ivanp2015** [HowardHinnant/date#24]
Hi, I was trying to use the library with Visual Studio 2013, and it just doesn't build. 
It would be nice if library could work with non-cutting-edge compilers.

**Comment by HowardHinnant** [comment]
What are the first three compile time errors?

I can't promise support, but if it is easy and obvious, there is also no reason to exclude support.

**Comment by ivanp2015** [comment]
Unlikely it is easy and obvious. VC++ 2013 doesn't support noexcept, operator "", some compile-time constant expressions, union members with non-trivial constrcutors and many other things...

**Comment by ivanp2015** [comment]
All that you hardly make use.

**Comment by ivanp2015** [comment]
You may download & install VC++2013 Community Edition, it's free and try yourself...

**Comment by ivanp2015** [comment]
I have it with final Update 5. Still doesn't help.

**Comment by HowardHinnant** [comment]
I don't have access to a Windows computer.

**Comment by ivanp2015** [comment]
it's easy - you can subscribe into Windows Insider Profram - beta testers of Windows. Then install this beta Windows into virtualbox, then install visual studio on that windows. all this is for free...

**Comment by davidhunter22** [comment]
I just did a few experiments and in the current structure this seems pretty hard. However most of the issues seem to be in the CuteAPI layer which is almost all impossible to do on VS 2013 because of no user defined operators. My own feeling on this is that all the "cute" stuff should be split into a separate header, so one header for core and one for cute, I would love to see this regardless of VS 2013 but it may make VS 2013 support much simpler for the core portion. I am happy to have a go at this split if it's considered useful.

**Comment by ivanp2015** [comment]
Yes, that may be the way to go. Thank you. But in fact personally I was looking for the TZ related functionality. Will the TZ functionality be available as core part, not the cute api?

**Comment by davidhunter22** [comment]
The TZ stuff uses date although I suspect it would be quit easy to change to use something a bit simpler and not use the date classes, at least in the lower level portions of the code. In fact the TZ stuff was what made me initially look at this library. 

BTW any reason you don't use VS 2015. Once a couple of other issues are merge like the declspec stuff it will build on 2015.

**Comment by HowardHinnant** [comment]
I'm quite certain VS-2013 has user defined operators.

**Comment by ivanp2015** [comment]
I'm stick to VS2013 die to "official" / "corporate" reasons, and can't change this at the moment, so let it not be the question of discussion.

**Comment by ivanp2015** [comment]
Howarf, you are right, actually I was meaning "user defined literals." . Here what's happening: I've create new console application project in the VS and just added your libary files to the project, and here is what I get:

1>d:\proexp\_proexp\libdatetest\libdatetest\date.h(108): error C3646: 'noexcept' : unknown override specifier
1>d:\proexp\_proexp\libdatetest\libdatetest\date.h(109): error C3646: 'noexcept' : unknown override specifier
1>d:\proexp\_proexp\libdatetest\libdatetest\date.h(111): error C3646: 'noexcept' : unknown override specifier
.......

Well, I replace "noexcept" with _NOEXCEPT (occurs 600 times!!!) (predefined in VC++) to go on somehow, and the next thing I do get is following:
1>d:\proexp\_proexp\libdatetest\libdatetest\date.h(740): warning C4091: 'inline ' : ignored on left of 'int' when no variable is declared
1>d:\proexp\_proexp\libdatetest\libdatetest\date.h(740): error C2143: syntax error : missing ';' before 'namespace'

This is about inline namespaces. Not supported as well.

Then user-defined literal add their penny:

1>d:\proexp\_proexp\libdatetest\libdatetest\date.h(743): error C2833: 'operator string' is not a recognized operator or type
1>d:\proexp\_proexp\libdatetest\libdatetest\date.h(743): error C2143: syntax error : missing ';' before 'newline'
1>d:\proexp\_proexp\libdatetest\libdatetest\date.h(743): error C2059: syntax error : 'newline'

**Comment by ivanp2015** [comment]
Another issue will be that VC++2013 won;t compile this:

template <class Duration>
struct classify_duration
{
    static CONSTDATA classify value =
        Duration{1} >= days{1}                 ? classify::not_valid :
        Duration{1} >= std::chrono::hours{1}   ? classify::hour :
        Duration{1} >= std::chrono::minutes{1} ? classify::minute :
        Duration{1} >= std::chrono::seconds{1} ? classify::second :
                                                 classify::subsecond;
};

**Comment by ivanp2015** [comment]
So you need to change into multiple classify_diration specializations.

**Comment by HowardHinnant** [comment]
Ok, thanks for the detailed report.

**Comment by ivanp2015** [comment]
I've managed to fix build on VS2013. Pleasesee my recent pull request.

**Comment by tomy2105** [comment]
I believe I've detected a flaw in VS2013 fix. Please see my recent pull request. Thanks.
