### ISSUE TITLE
Why not support 'year_month_day += days(N)'? 

### ISSUE THREAD

**Issue by sewenew** [HowardHinnant/date#251]
`year_month_day` has `+=` operator overload for `years` and `months`.  Is there any special reason that we CANNOT add `days` to `year_month_day`? Thanks!

**Comment by HowardHinnant** [comment]
Yes.  It is a matter of the library making expensive operations look cheap.  Like if we added `operator[](size_t)` to `std::list`.  It would be easy to implement.  But it would tend to cause people to write slow code.

If you want to add `days` to a a `year_month_day`, you need to convert it to `sys_days` (or `local_days`) first, then add the days, then if you want, convert it back to `year_month_day`.

Here is an article that goes into a little more detail and demonstrates that giving everything day-oriented arithmetic can result in code that runs twice as slow:

https://github.com/HowardHinnant/date/wiki/FAQ#day_arithmetic

Conversion between `year_month_day` and `sys_days` is the expensive part of this library ("expensive" is an exaggerated term here, but means expensive compared to an add or subtract).  This library helps you minimize those conversions by putting you in control of when they happen.

**Comment by sewenew** [comment]
Thanks for your reply! It makes sense!
