### ISSUE TITLE
timezone detection fails for US/Eastern

### ISSUE THREAD

**Issue by paresy** [HowardHinnant/date#252]
I have the following timezone set (America/New_York has the same error):

`/etc/localtime -> /usr/share/zoneinfo/US/Eastern`

Calling date::current_zone() will yield the following error:

`posixrules not found in timezone database`

How to reproduce the error:

```
wget https://data.iana.org/time-zones/releases/tzdata2017c.tar.gz
tar xf tzdata2017c.tar.gz
```

Build the follow code (test.cpp) in the same folder

```
#include <iostream>
#include "date/tz.h"

int main()
{
  date::set_install(".");
  date::current_zone();
  return 0;
}
```

Compile the program:

`g++ test.cpp src/tz.cpp -Iinclude -lcurl`

Run the program

`./a.out`

**Comment by HowardHinnant** [comment]
`current_zone()` is unfortunately very platform dependent (different implementation on every platform).  Which OS (including version) are you running on?  Also what does `git log -1` say for you?

I can tell you what is happening, but not why or how to fix it yet.  `current_zone()` somehow decides the string name of your current time zone, and then looks it up.  For some reason it is deciding your time zone is "posixrules" instead of "US/Eastern".  And then it gets an error when it tries to look up "posixrules".

**Comment by paresy** [comment]
Hi,

it's a plain Debian Stretch system. I just grabbed it with a docker pull debian:stretch and installed build-essential and git.

```
commit 87ed7f83cf66a8b5ffdc8b280668b14b1c0286b9
Author: Howard Hinnant <howard.hinnant@gmail.com>
Date:   Mon Nov 27 12:44:21 2017 -0500

    Correct IANA data download URL
```

If i use Europe/Berlin then everything is fine. If i can assist any further just let me know.

**Comment by paresy** [comment]
Maybe this helps? I have no idea why debian makes this symlink.

```
root@99c3868e5e95:/usr/share/zoneinfo/US# ls -l /usr/share/zoneinfo/US
total 0
lrwxrwxrwx 1 root root 20 Apr  6  2017 Alaska -> ../America/Anchorage
lrwxrwxrwx 1 root root 15 Apr  6  2017 Aleutian -> ../America/Adak
lrwxrwxrwx 1 root root 18 Apr  6  2017 Arizona -> ../America/Phoenix
lrwxrwxrwx 1 root root 18 Apr  6  2017 Central -> ../America/Chicago
lrwxrwxrwx 1 root root 21 Apr  6  2017 East-Indiana -> ../America/Fort_Wayne
lrwxrwxrwx 1 root root 13 Apr  6  2017 Eastern -> ../posixrules
lrwxrwxrwx 1 root root 19 Apr  6  2017 Hawaii -> ../Pacific/Honolulu
lrwxrwxrwx 1 root root 18 Apr  6  2017 Indiana-Starke -> ../America/Knox_IN
lrwxrwxrwx 1 root root 18 Apr  6  2017 Michigan -> ../America/Detroit
lrwxrwxrwx 1 root root  9 Apr  6  2017 Mountain -> ../Navajo
lrwxrwxrwx 1 root root 22 Apr  6  2017 Pacific -> ../America/Los_Angeles
lrwxrwxrwx 1 root root 22 Apr  6  2017 Pacific-New -> ../America/Los_Angeles
lrwxrwxrwx 1 root root 17 Apr  6  2017 Samoa -> ../Pacific/Midway
```

**Comment by HowardHinnant** [comment]
Oh.... S*#!...

`New_York -> ../posixrules` says it all.  The lib is following the symlink for New_York all the way down to posixrules, and interpreting that as the name of our current time zone.

There _might_ be a way to fix this, but it will require experimenting on your part.

See the `current_zone()` function here: https://github.com/HowardHinnant/date/blob/master/src/tz.cpp#L3633-L3744

This is a grab bag of different things the lib uses to try to figure out the name of the current time zone.  The first thing it does is follow the `/etc/localtime` symlink.  If that symlink doesn't work, then it tries something else.

I'm counting 5 different things it tries before giving up.

If on your system, another one of the techniques works, (besides the first which gives the wrong answer), maybe we could reorder these attempts.

**Comment by paresy** [comment]
AFAIK reordering will not help.

```
root@99c3868e5e95:/# readlink /etc/localtime
/usr/share/zoneinfo/US/Eastern
root@99c3868e5e95:/# realpath /etc/localtime
/usr/share/zoneinfo/posixrules
root@99c3868e5e95:/#
```

We could switch from realpath to readlink. Though we would need to verify that it does not break MacOS or other BSD systems.

**Comment by paresy** [comment]
MacOS should not be a problem. Can you remember which BSD unix your comment referred to? FreeBSD is handled differently further below.

```
MacBook:/$ readlink /etc/localtime 
/var/db/timezone/zoneinfo/Europe/Berlin
MacBook:/$ realpath /etc/localtime 
/private/var/db/timezone/tz/2017c.1.0/zoneinfo/Europe/Berlin
```

**Comment by HowardHinnant** [comment]
No, the only part of this I wrote is the macOS part, as that is all I have to experiment with.  I can try `readlink`.

**Comment by HowardHinnant** [comment]
How does this work for you?  https://github.com/HowardHinnant/date/commit/13e1d5eb85b19d51c7bd27684b8c9b43bf4db88f

**Comment by paresy** [comment]
Your patch works flawlessly for Debian. But it breaks on MacOS, because we are already using realpath for the tz_dir, which is then different from the one in readlink. I therefore added an ifdef for Apple.

How about this? https://github.com/paresy/date/commit/34186354865ee849658ffc525e48c24ccebdb53b

This works for MacOS and Debian.

**Comment by HowardHinnant** [comment]
That's very amusing, as I tested on macOS! :-)  I tested on very lightly on Sierra, but not at all on High Sierra.  I'll want to figure out what's going on before I push this to master, but that shouldn't be hard.  And it is good to know we definitely have a path forward that works on both now!

Ideally I'd like to convert all uses of realpath to readlink on all platforms, including the computation of tz_dir (one less thing for the reader to have to know about).  But if we need to keep macOS on realpath, it isn't that big of a deal.

**Comment by paresy** [comment]
You are right. I am on High Sierra. 

readlink should definitly work on macOS if you touch the tz_dir detection part which is already specific to Apple. 

Hint: Please include the realpath -> readlink typo in the error message. See https://github.com/paresy/date/commit/34186354865ee849658ffc525e48c24ccebdb53b#diff-b6db5e3c83c32a0f14d8870ca15a7b8fR3669  :)

**Comment by HowardHinnant** [comment]
Ok, hopefully this makes all the platforms happy: https://github.com/HowardHinnant/date/commit/c2e139ef53ec7bc5cbacb0ee667513b4799358ee

**Comment by ecorm** [comment]
`date::current_zone()` is failing for me on an ARM-based buildroot system where the symlinks look like this:

```
$ cd /etc
$ ls -l localtime 
lrwxrwxrwx    1 root     root            29 Mar 12 07:12 localtime -> ../usr/share/zoneinfo/Etc/UTC

$ cd /usr/share/zoneinfo/
$ ls -l
total 56
lrwxrwxrwx    1 root     root            12 Mar 12 07:12 Africa -> posix/Africa
lrwxrwxrwx    1 root     root            13 Mar 12 07:12 America -> posix/America
lrwxrwxrwx    1 root     root            16 Mar 12 07:12 Antarctica -> posix/Antarctica
lrwxrwxrwx    1 root     root            12 Mar 12 07:12 Arctic -> posix/Arctic
lrwxrwxrwx    1 root     root            10 Mar 12 07:12 Asia -> posix/Asia
lrwxrwxrwx    1 root     root            14 Mar 12 07:12 Atlantic -> posix/Atlantic
lrwxrwxrwx    1 root     root            15 Mar 12 07:12 Australia -> posix/Australia
lrwxrwxrwx    1 root     root            12 Mar 12 07:12 Brazil -> posix/Brazil
lrwxrwxrwx    1 root     root             9 Mar 12 07:12 CET -> posix/CET
lrwxrwxrwx    1 root     root            13 Mar 12 07:12 CST6CDT -> posix/CST6CDT
lrwxrwxrwx    1 root     root            12 Mar 12 07:12 Canada -> posix/Canada
lrwxrwxrwx    1 root     root            11 Mar 12 07:12 Chile -> posix/Chile
lrwxrwxrwx    1 root     root            10 Mar 12 07:12 Cuba -> posix/Cuba
lrwxrwxrwx    1 root     root             9 Mar 12 07:12 EET -> posix/EET
lrwxrwxrwx    1 root     root             9 Mar 12 07:12 EST -> posix/EST
lrwxrwxrwx    1 root     root            13 Mar 12 07:12 EST5EDT -> posix/EST5EDT
lrwxrwxrwx    1 root     root            11 Mar 12 07:12 Egypt -> posix/Egypt
lrwxrwxrwx    1 root     root            10 Mar 12 07:12 Eire -> posix/Eire
lrwxrwxrwx    1 root     root             9 Mar 12 07:12 Etc -> posix/Etc
```

Changing `sniff_realpath` to search for "posix" in the string fixes it for me:

```
static
bool
sniff_realpath(const char* timezone)
{
    using namespace std;
    char rp[PATH_MAX+1] = {};
    if (realpath(timezone, rp) == nullptr)
        throw system_error(errno, system_category(), "realpath() failed");
    auto result = extract_tz_name(rp);
    //return result != "posixrules";
    return result.find("posix") == decltype(result)::npos;
}
```
This should still work when the result is "posixrules".

Perhaps checking that the string _begins with_ "posix" (instead of containing it) would be more prudent. That is: `return result.find("posix") != 0;`

**Comment by paresy** [comment]
I opted to fix this issue inside of buildroot (they changed the folder layout with Buildroot 2021.02). That's the patch i apply before running make:

```
diff -ur a/package/tzdata/tzdata.mk b/package/tzdata/tzdata.mk
--- a/package/tzdata/tzdata.mk	2020-08-26 21:07:57.000000000 +0200
+++ b/package/tzdata/tzdata.mk	2020-08-27 16:54:38.000000000 +0200
@@ -41,18 +41,13 @@
 define TZDATA_INSTALL_TARGET_CMDS
 	$(INSTALL) -d -m 0755 $(TARGET_DIR)/usr/share/zoneinfo
 	cp -a $(HOST_DIR)/share/zoneinfo/* $(TARGET_DIR)/usr/share/zoneinfo
-	cd $(TARGET_DIR)/usr/share/zoneinfo; \
-	for zone in posix/*; do \
-	    ln -sfn "$${zone}" "$${zone##*/}"; \
-	done
 	$(TZDATA_SET_LOCALTIME)
 endef
 
 define HOST_TZDATA_BUILD_CMDS
 	(cd $(@D); \
 		for zone in $(TZDATA_ZONELIST); do \
-			$(ZIC) -b fat -d _output/posix $$zone || exit 1; \
-			$(ZIC) -b fat -d _output/right -L leapseconds $$zone || exit 1; \
+			$(ZIC) -b fat -d _output $$zone || exit 1; \
 		done; \
 	)
 endef

```

**Comment by jjerphan** [comment]
I also get a similar error on Windows with [the adapation of the packaging of `tzdata` from conda-forge](https://github.com/conda-forge/tzdata-feedstock).
