### ISSUE TITLE
How to use POSIX-style environment variable `TZ`

### ISSUE THREAD

**Issue by trueroad** [HowardHinnant/date#258]
I'd like to use POSIX-style environment variable `TZ`.

i.e.
`JST-9`
`PST8PDT`
`CST-9:30CDT`
`EST+5EDT,M3.2.0/2,M11.1.0/2`
etc.

instead of
`Asia/Tokyo`
`America/Los_Angeles`
`America/New_York`
`Australia/Adelaide`
etc.

POSIX's `tz_set ()`, `localtime ()`, and `strftime ()` functions can handle `TZ=JST-9` etc.
With the functions, time zone can be switched as follows depending on the environment variable `TZ`.

```
$ TZ=JST-9 date
Thu Nov 30 23:58:54 JST 2017

$ TZ=PST8PDT date
Thu Nov 30 06:59:11 PST 2017

$ TZ=CST-9:30CDT date
Fri Dec  1 00:29:22 CST 2017

$ TZ=EST+5EDT,M3.2.0/2,M11.1.0/2 date
Thu Nov 30 09:59:34 EST 2017
```

But, with `date.h` and `tz.h`, If I understand correctly,

+ `current_zone ()` does not use the environment variable `TZ`.
+ `locate_zone ()` cannot handle POSIX-style TZ format (like `JST-9` etc.)

How do I realize to handle the POSIX-style environment variable `TZ` like `date` command by using `date.h` and `tz.h`?

**Comment by HowardHinnant** [comment]
There is currently no code to parse the POSX-style format.

It is possible that such a feature could be incorporated by taking advantage of the "custom time zone" facility as described in https://howardhinnant.github.io/date/tz.html#Examples .  However that example doesn't demonstrate POSIX-style time zones, only fixed-offset timezones.

**Comment by HowardHinnant** [comment]
I've just added a new header `"date/ptz.h"`:
https://github.com/HowardHinnant/date/commit/c7e5a4d08e4dfddbc1235047d54d3d8f96e8bc0f

This creates a custom time zone named `Posix::time_zone` which can be constructed with a posix-style time zone string, and used with `zoned_time`.  See the comments at the top of `"date/ptz.h"` for more details.

This header is intended to be both something practical that you can use, and just an example of a way to build a custom time zone for this library.  Please feel free to take this example and build on it in whatever way is beneficial to you.

I've made it header-only just to make it easy to experiment with.  But some of those functions are too long to inline and would benefit from placing them in a source file.  They've been defined outside their class declarations in order to make it easier to move them to a .cpp.

The error checking for the parsing of the posix string is done with exceptions.  If exceptions aren't good for you, modify `throw_invalid` to do whatever you need it to.  This function currently throws a `std::runtime_error` with a `what()` that describes exactly what went wrong in the parse.

**Comment by trueroad** [comment]
Great!
I'd like to simultaneously support both format `JST-9` and `Asia/Tokyo` because many standard commands like `date` support it.
I've create integrated time zone class for support it.
It seems to work fine.

Thank you.

source
```c++
#include <exception>
#include <iostream>
#include <string>

#include <cstdlib>

#include "include/ptz.h"

class integrated_timezone
{
private:
  enum class Type { tzdb, posix };
  Type type_;

  const date::time_zone *tzdb_timezone_;
  const Posix::time_zone *posix_timezone_ = nullptr;

  const std::string default_zone = "UTC0";

  void set_timezone (const std::string& name)
  {
    type_ = Type::tzdb;
    try
      {
	tzdb_timezone_ = date::locate_zone (name);
      }
    catch (std::runtime_error)
      {
	type_ = Type::posix;
	try
	  {
	    posix_timezone_ = new Posix::time_zone (name);
	  }
	catch (std::exception) // ! std::runtime_error
	  {
	    posix_timezone_ = new Posix::time_zone (default_zone);
	  }
      }
  }

  void set_timezone (void)
  {
    char *env_tz = std::getenv ("TZ");
    if (env_tz)
      {
	set_timezone (env_tz);
      }
    else
      {
	type_ = Type::tzdb;
	try
	  {
	    tzdb_timezone_ = date::current_zone ();
	  }
	catch (std::runtime_error)
	  {
	    set_timezone (default_zone);
	  }
      }
  }

public:
  integrated_timezone (const std::string& name)
  {
    set_timezone (name);
  }

  integrated_timezone ()
  {
    set_timezone ();
  }

  ~integrated_timezone ()
  {
    if ( posix_timezone_ != nullptr)
      delete posix_timezone_;
  }

  template <class Duration>
  date::local_time<typename
		   std::common_type<Duration, std::chrono::seconds>::type>
  to_local(date::sys_time<Duration> tp) const
  {
    switch (type_)
      {
      case Type::tzdb:
	return tzdb_timezone_->to_local (tp);
      case Type::posix:
	return posix_timezone_->to_local (tp);
      }
    throw std::runtime_error ("integrated_timezone::to_local: unknown type");
  }

  template <class Duration>
  date::sys_info
  get_info(date::sys_time<Duration> st) const
  {
    switch (type_)
      {
      case Type::tzdb:
	return tzdb_timezone_->get_info (st);
      case Type::posix:
	return posix_timezone_->get_info (st);
      }
    throw std::runtime_error ("integrated_timezone::get_info: unknown type");
  }
};

int main ()
{
  integrated_timezone itz;

  date::zoned_time<std::chrono::system_clock::duration, integrated_timezone*>
    zt{&itz, std::chrono::system_clock::now ()};

  std::cout << "zoned_time:" << std::endl
	    << "    " << zt << std::endl;
  std::cout << "RFC3339 (zoned):" << std::endl
	    << "    " << date::format ("%FT%T%z", zt) << std::endl;

  auto st = zt.get_sys_time ();
  std::cout << "RFC3339 (UTC):" << std::endl
	    << "    " << date::format ("%FT%T%z", st) << std::endl
	    << "    " << date::format ("%FT%TZ", st) << std::endl;
  return 0;
}
```

result
```
$ ./prog-ptz
zoned_time:
    2017-12-04 21:11:49.181605500 JST
RFC3339 (zoned):
    2017-12-04T21:11:49.181605500+0900
RFC3339 (UTC):
    2017-12-04T12:11:49.181605500+0000
    2017-12-04T12:11:49.181605500Z

$ TZ=GMT0 ./prog-ptz
zoned_time:
    2017-12-04 12:12:13.569169100 GMT
RFC3339 (zoned):
    2017-12-04T12:12:13.569169100+0000
RFC3339 (UTC):
    2017-12-04T12:12:13.569169100+0000
    2017-12-04T12:12:13.569169100Z

$ TZ=Asia/Tokyo ./prog-ptz
zoned_time:
    2017-12-04 21:12:26.094061500 JST
RFC3339 (zoned):
    2017-12-04T21:12:26.094061500+0900
RFC3339 (UTC):
    2017-12-04T12:12:26.094061500+0000
    2017-12-04T12:12:26.094061500Z

$ TZ=foobar ./prog-ptz
zoned_time:
    2017-12-04 12:12:34.378892000 UTC
RFC3339 (zoned):
    2017-12-04T12:12:34.378892000+0000
RFC3339 (UTC):
    2017-12-04T12:12:34.378892000+0000
    2017-12-04T12:12:34.378892000Z

$ unset TZ

$ ./prog-ptz
zoned_time:
    2017-12-04 12:12:49.271411400 UTC
RFC3339 (zoned):
    2017-12-04T12:12:49.271411400+0000
RFC3339 (UTC):
    2017-12-04T12:12:49.271411400+0000
    2017-12-04T12:12:49.271411400Z

$
```
