### ISSUE TITLE
 Obtaining a time_point from y/m/d h:m:s components

### ISSUE THREAD

**Issue by ajneu** [HowardHinnant/date#262]
Regarding this recipe from the wiki:
[Link](https://github.com/HowardHinnant/date/wiki/Examples-and-Recipes#time_point_to_components)

```cpp
using namespace std::chrono;
using namespace date;
// Component values (as obtained from an UI form, for example)
int y=2015, m=7, d=30, h=12, min=34, s=56;
auto ymd = year(y)/m/d; // Yields a year_month_day type
if (!ymd.ok())
    throw std::runtime_error("Invalid date");
system_clock::time_point tp = sys_days(ymd) +
                           hours(h) + minutes(min) + seconds(s);
```

I believe this is UTC, right?
How can I get this to work, for my timezone, so that:
```cpp
std::cout << date::make_zoned(date::current_zone(), tp) << std::endl;
```
gives me back exactly the same date and time, i.e.
`2015-07-30 12:34:56.000000000 xxxx` (with `xxxx` showing my timezone).

I believe this is important, but unfortunately seems missing from the [Examples-and-Recipes](https://github.com/HowardHinnant/date/wiki/Examples-and-Recipes#time_point_to_components)

**Comment by ajneu** [comment]
```cpp
    {
        using namespace std::chrono;
        using namespace date;
        // Component values (as obtained from an UI form, for example)
        int y=2015, m=7, d=30, h=12, min=34, s=56;
        auto ymd = year(y)/m/d; // Yields a year_month_day type
        if (!ymd.ok())
            throw std::runtime_error("Invalid date");
        auto ymd_local = local_days{ymd};
        system_clock::time_point tp = make_zoned(current_zone(), ymd_local + hours(h) + minutes(min) + seconds(s)).get_sys_time();
    }
```

The following should do it, as far as I can see...

**Comment by HowardHinnant** [comment]
You're exactly correct on all counts.  Subbing in `local_days` for `sys_days` is all that is required.

**Comment by ajneu** [comment]
Thanks.

I suggest changing the top part of this [wiki-entry](https://github.com/HowardHinnant/date/wiki/Examples-and-Recipes#time_point_to_components)

to:

```cpp
struct DateTime {    // hold date/time, to be converted to time_point
    int year;
    int month;
    int day;
    int hour = 0;
    int min  = 0;
    int sec  = 0;
};

enum ZoneSelect {local, utc};  // interpret date/time as being from current timezone, or from utc

// convert date/time to time_point (last argument specifies if date/time is interpreted as being from current timezone, or from utc)
std::chrono::system_clock::time_point datetime_to_timepoint(const DateTime &dt, ZoneSelect zone_select = utc)
{
    using namespace std::chrono;
    using namespace date;

    auto ymd = year(dt.year)/dt.month/dt.day; // year_month_day type
    if (!ymd.ok()) { throw std::runtime_error("Invalid date"); }

    return ((zone_select == utc)
            ?                              sys_days(ymd) + hours(dt.hour) + minutes(dt.min) + seconds(dt.sec)
            : make_zoned(current_zone(), local_days{ymd} + hours(dt.hour) + minutes(dt.min) + seconds(dt.sec)).get_sys_time()
            );
}

int main()
{
    DateTime datetime{2015, // year
                      7,    // month
                      30,   // day
                      12,   // hour
                      34,   // min
                      56};  // sec

    // convert date/time (interpreted as utc) to time_point
    std::chrono::system_clock::time_point tp = datetime_to_timepoint(datetime, utc);
    std::cout << "datetime taken as UTC: " << date::make_zoned("UTC",                tp) << std::endl;
    std::cout << "                       " << date::make_zoned(date::current_zone(), tp) << std::endl;

    // convert date/time (interpreted as being from current timezone) to time_point
    tp = datetime_to_timepoint(datetime, local);
    std::cout << "datetime taken as from current zone: " << date::make_zoned(date::current_zone(), tp) << std::endl;
    std::cout << "                                     " << date::make_zoned("UTC",                tp) << std::endl;
}
```

(Unfortunately it does seem a bit verbose... looking at it now...)

**Comment by ajneu** [comment]
PS:
* Any quick way of saying `date::make_zoned("UTC",                tp)` without dragging in the string `"UTC"`?
* Am I seeing it correctly, that there is no enum for the library, that I can use for utc?
(I'm using my own `enum ZoneSelect` above)

**Comment by HowardHinnant** [comment]
There's no enum for `"UTC"`, however `sys_days{whatever} + whatever durations` _is_ a UTC time stamp, and you can `format` directly from it and `parse` directly into it (including `"%Z"` and `"%z"`).  If all you need is UTC, you don't even need the tz.h header.

If you're using other time zones in addition to UTC, you can look up "UTC" once and save it if you're concerned about lookup times:

```c++
auto utc_tz = date::locate_zone("UTC");  // lookup once and store here
...
auto zt = date::make_zoned(utc_tz, tp);  // no lookup here
```

**Comment by HowardHinnant** [comment]
I was just passing by my desk an hour ago and hadn't taken a good look at your code.  Everything I told you before you obviously already knew.  Your code looks exactly right! :-)

The wiki is actually publicly writable!  Feel free to insert a new item right next to the existing one, or just add or modify the existing one.  I believe what is there actually predates the time zone library (which came later).  Your example would make a great addition.

**Comment by ajneu** [comment]
> The wiki is actually publicly writable! Feel free to insert a new item right next to the existing one, or just add or modify the existing one. 

Ok, I've noted down something, that I hope will help people who want to go from date/time to `time_point`. In fact there's a kind of round-trip:
```
date/time variable -> time_point -> print date/time
```

https://github.com/HowardHinnant/date/wiki/Examples-and-Recipes#time_point_to_components
