### ISSUE TITLE
documentation: "The modified commands %Ez and %Ez parse a : between"

### ISSUE THREAD

**Issue by baslr** [HowardHinnant/date#263]
https://github.com/HowardHinnant/date/blob/16c5f5885f8d6b70d3a7df057e9eed30babeafc9/date.html#L7848

Why the double `%Ez`?

**Comment by HowardHinnant** [comment]
Good catch!  The second `%Ez` should be `%Oz`.  The same type-o is in three places.  Thanks, fixed!

https://github.com/HowardHinnant/date/commit/d6ae81acb392e58f34d94e9c0067744a9379bed5
