### ISSUE TITLE
Parsing with %T accepts "00:99:100" but not "00:100:99"

### ISSUE THREAD

**Issue by amasciotta** [HowardHinnant/date#267]
If I parse the string `"00:99:100"` and then write it out again in a string, I correctly get `"01:40:40"`, but with the string `"00:100:90"` the parsing fails (failbit in the stream is set).

**Comment by HowardHinnant** [comment]
The default maximum field width for minutes (`%M`) is 2.  However that can be overridden with a width specifier on the `%M` command:
```c++
#include "date/tz.h"
#include <iostream>
#include <sstream>

int
main()
{
    std::istringstream in{"00:100:90"};
    std::chrono::seconds s;
    in >> date::parse("%H:%3M:%S", s);
    if (in.fail())
        std::cout << "failed\n";
    else
        std::cout << date::format("%T\n", s);
}
```
Output:
```
01:41:30
```
See: https://howardhinnant.github.io/date/date.html#from_stream_formatting for more details.
