### ISSUE TITLE
CMake for v2.3

### ISSUE THREAD

**Issue by r-darwish** [HowardHinnant/date#268]
I'm maintaining the [Conan](http://conanio.readthedocs.io/en/latest/) pacakge for date. Currently, the 2.3 version of the package only packs the header files, as the CMake file isn't included in v2.3. Is it possible that you release v2.3.1 that contains a CMake?

**Comment by HowardHinnant** [comment]
Sure.  There are two CMake-related P/R's open.  Could you review them and recommend acceptance/rejection/modification?  With those P/R's processed, I'll release.

**Comment by r-darwish** [comment]
Sure thing. I'll review them. Thanks!

**Comment by jkhoogland** [comment]
Hi Howard,

Before you cut a release,
I would like to add the various bits I referred to in https://github.com/HowardHinnant/date/issues/18 

I would like to do this *after* the other two modifications to the cmake logic are merged.
Cheers
Jiri

**Comment by r-darwish** [comment]
I'll take a look at that as well.

**Comment by jkhoogland** [comment]
great, much appreciated.

**Comment by r-darwish** [comment]
@HowardHinnant 

Now that all cmake issues were resolved, I managed to successfully build 2.3 with our current CMake. However, I can't open a pull request for a branch that doesn't exist in this repository. Can you please create a branch called `2.3.x` on the top the `2.3` tag?

**Comment by HowardHinnant** [comment]
Version 2.4 has been released.
