### ISSUE TITLE
Error when /etc/localtime is a real file

### ISSUE THREAD

**Issue by r-darwish** [HowardHinnant/date#269]
The comment [here](https://github.com/HowardHinnant/date/blob/master/src/tz.cpp#L3646) states correctly that `/etc/localtime` may be either a link or a real file. However, the if statement only checks if `/etc/localtime` is a link.

**Comment by HowardHinnant** [comment]
`current_zone()` is a hodgepodge of algorithms that has grown experimentally over time.  This function is truly a study in evolution.  What works is kept, and nothing is added unless it solves a problem.  Each platform seems to have its own unique way of determining the current time zone, and on some platforms (such as macOS) that algorithm is also mutating with release version.

I don't mind changing the comments to better reflect the code.  But the code should only be changed if we have a platform where we can test that the change solves a problem without breaking other platforms.

`current_zone()` is some of the most non-portable code I've ever seen, making it an excellent candidate for standardization.

**Comment by r-darwish** [comment]
The recommended practice for setting timezones in Docker containers is to mount `/etc/localtime` into the container, which causes it to appear as a real file inside the container even if it is a symlink on the host. The current behaviour causes `tz` to throw an exception when ran inside a container.

**Comment by HowardHinnant** [comment]
If you've got a such a platform to experiment with, you're much more qualified to write a P/R to support it than I am. ;-)  P/R's welcome, and thank you!

**Comment by r-darwish** [comment]
Will do :)

**Comment by shanematley** [comment]
I'm having a similar problem, also involving docker containers. Have you had a chance to look at this @r-darwish? If not I may get around to it myself, bit I wouldn't want to start if you've got a P/R imminent.

**Comment by remyabel** [comment]
Mounting `/etc/localtime` isn't really the recommended approach. There isn't any way to get the timezone data (i.e, "America/New_York") from the file itself. The recommended approach is to install `tz_data` and create a symlink. See this [example](https://github.com/moby/moby/issues/12084#issuecomment-299813445):

```
FROM ubuntu:latest

ENV TZ Asia/Kuala_Lumpur

RUN echo $TZ > /etc/timezone && \
    apt-get update && apt-get install -y tzdata && \
    rm /etc/localtime && \
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
    dpkg-reconfigure -f noninteractive tzdata && \
    apt-get clean
```

Checking if `/etc/localtime` isn't sufficient because the information you need is simply not in the file itself.

**Comment by HowardHinnant** [comment]
Will reopen if someone still has a problem and has code to make it right.
