### ISSUE TITLE
undefined reference to `__imp_CoTaskMemFree', when compiled using MinGW GCC 7.2 on Windows.

### ISSUE THREAD

**Issue by denchat** [HowardHinnant/date#272]
Trying to compile this code using MinGW GCC 7.2 on Windows 10 64-bit:

    #include "date/tz.h"
    #include <iostream>
    
    int main()
    {
        using namespace date;
        using namespace std::chrono;
        auto t = make_zoned(current_zone(), system_clock::now());
        std::cout << t << '\n';
    }

I gets this errors:    

    C:\Users\[user]\AppData\Local\Temp\ccbbCrWF.o:tz.cpp:(.text+0x343c): undefined reference to `__imp_CoTaskMemFree'
    C:\Users\[user]\AppData\Local\Temp\ccbbCrWF.o:tz.cpp:(.text+0x34f3): undefined reference to `__imp_CoTaskMemFree'
    collect2.exe: error: ld returned 1 exit status

Then I found this [thread](https://github.com/halide/Halide/issues/2306) had the same issue

    C:/msys64/mingw64/lib/libLLVMSupport.a(Path.cpp.obj):(.text+0x936): undefined reference to `__imp_CoTaskMemFree'

They fixed by add `-lole32` for Windows linker. 

Perhaps this could be stated in the documentation?

**Comment by HowardHinnant** [comment]
Done, thanks! https://github.com/HowardHinnant/date/commit/fb048ec928231fa7233c4b0519e9689637575a88
