### ISSUE TITLE
Initialization order race between locate_zone and tz_dir

### ISSUE THREAD

**Issue by lava** [HowardHinnant/date#275]
When linking statically against `tz.o` and creating a global variable that holds a time zone, i.e.

    const date::time_zone* s_utc_zone = date::locate_zone("UTC");

It can happen that initialization of `s_utc_zone` happens *before* the `const std::string tz_dir` defined in `tz.cpp` is initialized. However, `locate_zone()` eventually calls into `init_tzdb()`, where it is expected that `tz_dir` is already initialized.

I'm not sure if this is a bug or if I'm just mis-using the library, but in the latter case it should probably at least be documented that time-zone related functionality shall only be used after all static constructors of the library are finished.

As a slightly related aside, I'm also wondering how a user would configure a custom timezone database directory? The default one happens to be correct on my system, but I can easily imagine systems where it would be located in a non-default location, e.g. on another partition to save space or in a custom sysroot. The glibc provides the `TZ` and `TZDIR` environment variables as customization points, are there plans to add a similar mechanism to this library?

**Comment by HowardHinnant** [comment]
Thanks for the report.  I'll make turn `tz_dir` into a function-local static, and that ought to solve the initialization order problem.  I will get that done today, and post here when it is done.

When using `USE_OS_TZDB=1`, the goal is to support each OS in its shipping configuration.

To support custom time zone databases, `USE_OS_TZDB=0` is used, and one can place the text version of the IANA database anywhere you want, and point to that with `INSTALL`.  You can also choose to either place the db there manually, or have the library check on first use and install it automatically.  This latter option also checks the tzdb version number and installs updates automatically.  There's also an option for programmatically updating to a new tzdb manually after first use.

**Comment by lava** [comment]
So you're planning to keep the mechanism (i.e. compile-time macros) for the standardized version? Recompiling date is no big deal as it is just a single file, but recompiling the standard library seems a bit heavy just to read time zone data from a custom location.

Or do you plan to leave it implementation-defined and expect that implementors will add a system-specific mechanism for that on top of the tz proposal?

**Comment by HowardHinnant** [comment]
Sorry I didn't get this fixed yesterday as promised.  Crazy day...

For the standardized version there will be no macros and the vendor is in charge of supplying the tzdb, and keeping it up to date and correct for each platform he services.  There (hopefully) will be the ability for the vendor to update the tzdb without rebooting the machine, and the application will be able to detect and request that this update be applied to the application without shutting the application down.  All customization of time zones will have to take place via the `TimeZonePtr` template parameter of [`zoned_time`](https://howardhinnant.github.io/date/tz.html#zoned_time).  [Here is an example](https://howardhinnant.github.io/date/tz.html#Examples) of that (search for "Custom time zone").

**Comment by HowardHinnant** [comment]
Sorry for the slow response on this.  Fixed by https://github.com/HowardHinnant/date/commit/55289f0d73b51b21ed02ec27114384ebd7b94d6c
