### ISSUE TITLE
Infinite range of dates with a stride of one month from a given date

### ISSUE THREAD

**Issue by gnzlbg** [HowardHinnant/date#282]
Hi @HowardHinnant ,

I wanted to solve the calendar example using `date` and `range-v3` and was wondering how to implement this:

I want to create an infinite range of dates with a stride of one month from a given date. 

- Is there an iterator for that in the library?

In the mean time I came with my own implementation which kind of works, but "fails" if, e.g., my start date is the 29th February of a leap year. I can work around that, but wanted to know if there is a solution to this problem that's actually considered to be the "right" one. For example, reading the [Boost.DateTime `date_iterator`](http://www.boost.org/doc/libs/1_31_0/libs/date_time/doc/date_iterators.html) docs, it says:

> `month_iterator`: Iterate month_offset months. There are special rules for handling the end of the month. These are: if start date is last day of the month, always adjust to last day of the month. if date is beyond the end of the month (eg: jan 31 + 1 month) adjust back to end of month.

But these rules seem a bit ad hoc. 

- Is there a source of "truth" (ISO?) that talks about how to properly increment a date by a month?

**Comment by HowardHinnant** [comment]
Hi @gnzlbg ,

This library contains no iterators.  However (as you've obviously already done), iterators can be built on top of it.

An _infinite_ range will be problematic, as this library does have a finite range.  The range on `year` is [-32767, 32767].  The rationale for that range is that it is storable in 16 bits, and is already larger than the valid range of the civil calendar itself.

On the handling of month arithmetic:  There is no "truth", sorry.  And different libraries have different policies. Some (as you've noted) truncate to the end of the month, while others will overflow into the next month.  This library has adopted a somewhat neutral policy, pushing that decision back to you.

If you add a month to `2018/jan/31`, you will get `2018/feb/31` (this has type `year_month_day`).  There is a member function call `.ok()` on `year_month_day` that you can call at any time.  It normally returns true, but if you call it on `2018/feb/31` it will return false.  Nevertheless, you can continue to operate with this "not ok" date if you choose.  For example you can add another month, resulting in `2018/mar/31`, and the result will return true for `ok()`.

Thus you can implement your own policy by checking `ok()`, and acting on that result (or not).  For example if you add `months` to a `year_month_day` and the result is `!ok()`, you can set that result to `result.year()/result.month()/last` which will truncate the value to the last day of the month (like boost).  Or you could overflow into the next month by converting the result to a `sys_days`, and then back into a `year_month_day`.  This is [described in more detail in the wiki](https://github.com/HowardHinnant/date/wiki/Examples-and-Recipes#normalize).  Or you could just ignore the `!ok()` and propagate it along in your computations.

**Comment by gnzlbg** [comment]
> An infinite range will be problematic,

Indeed, I forgot to mention that by infinite I meant "up to the last representable date" (I guess I did not meant infinite at all, sorry about that).

> This library has adopted a somewhat neutral policy, pushing that decision back to you.

Thanks for trusting me on this, I definitely know what I am doing :D 

Jokes aside, thanks for the explanation, the library does allow me to implement whatever policy I want or need, which is neat. I'll check the wiki out. 

Have a nice day!
