### ISSUE TITLE
iOS run-time error: Could not get current timezone

### ISSUE THREAD

**Issue by allidev** [HowardHinnant/date#283]
I am running date library on a project of mine on iOS. It has the following error message:
Could not get current timezone. It seems the error comes from current_zone() function. Has anybody tested the library on iOS devices? From the comments within the current_zone() function, it is not clear which code segment is for iOS devices.

**Comment by HowardHinnant** [comment]
People have run this library on iOS in the past.  I have not personally done so.

Does your project have any differences from those specified for iOS under https://howardhinnant.github.io/date/tz.html#Installation ?

**Comment by allidev** [comment]
I have followed the instructions and still no luck. In my understanding, the current_zone() function will try to find the timezone info on local device: in the case of iOS, the file is located at /var/db/timezone/zoneinfo. First, this path is not in the possible choices in the current_zone() function. Even as I add this path, I still can't read the first line of this file to get the local zone info. I found [this](https://www.reddit.com/r/jailbreak/comments/3ll1rf/tutorial_solution_how_to_fix_broken_timezone_in/), hope it is helpful.

**Comment by HowardHinnant** [comment]
Fixed with https://github.com/HowardHinnant/date/commit/6941691de451d4951bfdbebf2ff13501bcd8ed4d
