### ISSUE TITLE
Feature Request: Standalone tzdb Fetcher/Parser

### ISSUE THREAD

**Issue by paulreimer** [HowardHinnant/date#287]
Love the library, and the very clear/concise CppCon talks as well.

Personally, I wish that that it was easier to pull out the tzdb fetch + parse portions and use them separately (or ideally, a separate library or sub-component of this library). I am on an embedded platform (but I do have access to `libcurl`), however I am not able to use C++ iostreams and in fact will never need the formatting features of this library.

It seems like this library tackles at least three separate uses (fetching/parsing the TZDB, datetime arithmetic, and datetime formatting/presentation), but they are all fairly coupled at the moment. Personally, I need the TZDB fetching/parsing, and ideally the arithmetic, but not the formatting. But that doesn't seem possible at the moment.

**Comment by paulreimer** [comment]
In fact the #1 thing for me is just the TZDB parser (seems odd to couple it to `curl` anyway, although that happens to be what I'm already using) so if it is easier to extract just the tzdb *parser* into a separate component, that would solve my immediate use-case.

**Comment by HowardHinnant** [comment]
I have been giving serious thought to rewriting the format/parse I/O with generic iterators instead of streams so that one can work directly with buffers.  However it is a big job and I haven't had the time to do it yet.  This part of the library is 100% templated, so if you don't instantiate it, it will not appear in your code.  However your tools would have to at least be able to parse the templates.

The current tzdb parser is built on top of fstream at the moment, and for the immediate future, I have no plans to rewrite that to be on top of C file I/O.  That could be a deal-breaker for you.  But if you can use the tzdb parser as is, there's nothing to stop you from using it without using the datetime parsing/formatting.

**Comment by paulreimer** [comment]
OK fair enough! Yup, I was hoping to use buffers and/or `string_view`s also (I have a FS but would prefer to use buffers directly, even just feeding lines to the parser).

Unfortunately use of iostreams is a dealbreaker on my target, some of us still wish for 640k (flash space).

**Comment by paulreimer** [comment]
I have a non-portable `tzset` available but I was hoping to use this library. I only need one timezone for my application, anyway, though. I can write a parser to fetch the tzdb URL pretty easily, also.

So, let's say I can get `std::localtime`s (and anything in `<chrono>`, of course), and as you say, if I avoid instantiating the stream-using formatting templates, I should still be able to use the date arithmetic (& dmy, etc). How would I best do that? Are there some examples or tests that cover that (getting a `time_t` from an external source, and/or building a timezone object manually?)

I really prefer your API, especially since it is so easy on native hosts I'd prefer to carry it across to embedded also.

**Comment by paulreimer** [comment]
Aw heck, even `#include <sstream>` (anywhere; used or not) pulls in the works, there must be some globals.

Well. So I really need just the arithmetic. I think if the formatting templates are decoupled, as you say, then I should be able to `#ifdef` them out (i.e. anything `*stream`).

And then I would need a viable way to use time zones without a tzdb (or manually building a tzdb without a parser).

Am I barking up the wrong tree here? Date-time math seems like crypto to me: leave it to the pros. But maybe I should just fork?

**Comment by HowardHinnant** [comment]
I'm surprised `#include <sstream>` is harmful.  `#include <iostream>` *is* harmful (brings in globals).  But I would not think the same of `<sstream>`.

There's a custom time zone example described here:  https://howardhinnant.github.io/date/tz.html#Examples

That technique is used to its fullest for this Posix time zone example:  https://github.com/HowardHinnant/date/blob/master/include/date/ptz.h

When going with these custom time zone examples, there's no need to pull in src/tz.cpp which is nearly all about just parsing the IANA tzdb.  A custom time zone may be sufficient for your application (I of course have no way of knowing that for sure).

If you really have to go back to the fundamentals (and I hope you don't), this entire library is built on top of the calendrical arithmetic here:  http://howardhinnant.github.io/date_algorithms.html

Those algorithms don't include time zone stuff, just mapping between a count of days and year/month/day.  But the syntax and type safety is lousy without something like date.h sitting on top of it.

**Comment by paulreimer** [comment]
Agreed, I want the type system and custom literals as much as the algorithms (and ideally keeping the same API to make porting easy from platforms where iostreams are OK).

And, you are right about `<iostream>` vs `<sstream>`, I had them both and iostream did the damage. But instantiating a `stringstream` brings in all the bloat again. Oh well.

So, in terms of re-using what I can, I can make a PR to this repo that `#ifdef`s out anything referring  to streams (if you would accept that PR or something like it), or I can just fork and strip out anything I am unable to use in the new repo. Thoughts on that?

**Comment by HowardHinnant** [comment]
My best guess is that if you simply don't use anything to do with streams (and don't `#include <iostream>`), then the compiler won't instantiate any code related to streams.  Lack of use of `date::parse` and `date::format`, and `operator<<` should be very close to your ideal.

**Comment by paulreimer** [comment]
You are correct, sir! So, all my UTC needs are met. That's awesome.

I had seen the custom timezone example above but it wasn't quite sophisticated enough for my needs (I need at least DST-awareness). I see the parser in `tz.cpp` is driving `Rules` etc, so perhaps I can adapt that to my needs, or if you can recommend a place to start extending from?

**Comment by paulreimer** [comment]
(to be clear, I would make my own tz.cpp that "does the things" needed for a minimal implementation of a single timezone)

**Comment by HowardHinnant** [comment]
Posix time zones may be right for you:

http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap08.html#tag_08_03

(search for "TZ")

This allows for one DST start date and one DST end date per year, by one rule that never changes (e.g. 2nd Sunday in March at 2am local time).  This doesn't allow for a full history going back in time that would include details such as changing which Sunday things happen on.  Nor does it allow for future changes without a recompile.  But if a POSIX time zone would work, I already have it coded here:

https://github.com/HowardHinnant/date/blob/master/include/date/ptz.h

**Comment by HowardHinnant** [comment]
Working example with POSIX time zone:
```c++
#include "date/ptz.h"
#include <iostream>

int
main()
{
    using namespace date;
    using namespace std::chrono;
    using TimeZone = date::zoned_time<system_clock::duration, Posix::time_zone>;
    for (auto t = local_days{sun[1]/nov/2016} + 1h - 1min;
            t <= local_days{sun[1]/nov/2016} + 2h + 30min; t += 30min)
    {
        try
        {
            auto zt = TimeZone{Posix::time_zone{"EST5EDT,M3.2.0,M11.1.0"}, t};
            std::cout << zt << "\n\n";
        }
        catch (const std::exception& e)
        {
            std::cout << e.what() << "\n\n";
        }
    }
}
```
This _does not_ require compiling/linking to `tz.cpp` or `curl`.  The program iterates through a recent time zone change in the eastern US, 30min at a time, and demonstrates unique mappings _and_ ambiguous mappings.

The output is:
```
2016-11-06 00:59:00.000000 EDT

2016-11-06 01:29:00.000000 is ambiguous.  It could be
2016-11-06 01:29:00.000000 EDT == 2016-11-06 05:29:00.000000 UTC or
2016-11-06 01:29:00.000000 EST == 2016-11-06 06:29:00.000000 UTC

2016-11-06 01:59:00.000000 is ambiguous.  It could be
2016-11-06 01:59:00.000000 EDT == 2016-11-06 05:59:00.000000 UTC or
2016-11-06 01:59:00.000000 EST == 2016-11-06 06:59:00.000000 UTC

2016-11-06 02:29:00.000000 EST
```

**Comment by paulreimer** [comment]
Excellent. That will do it. I'm going to want leap-seconds and historical eventually but this is non-critical code.

My inclination is to avoid parsing the IANA data directly anyway, and transform/compact the DB into something like a flatbuffer, and host this elsewhere. So my (eventual, ideal) parser would be different from tz.cpp anyway. There may come a time when I need to drive the machinery to build a tzdb object, but I think the POSIX type above should cover it for a while.

Thanks for your help and for the great library! Which was well-prepared for all these use-cases.

**Comment by paulreimer** [comment]
Hmm, I'm not able to get the above example to work for me.

Seems that `decltype(zt)` above would be
`date::zoned_time<std::chrono::duration<long long int, std::ratio<1ll, 1000000000ll> >`

I wasn't expecting that ratio parameter and it seems to be breaking compatibility with `zoned_seconds`. I'm just trying to get the example below working with Posix::time_zone.

https://github.com/HowardHinnant/date/wiki/Examples-and-Recipes#converting-to-a-tm

**Comment by HowardHinnant** [comment]
Ah, I believe what you're experiencing is an implicit truncation between `system_clock::duration` (on your system that's nanoseconds), and `seconds`.  The compiler isn't willing to do this truncation of precision (information) without your explicit consent.

Where I have `using TimeZone = date::zoned_time<system_clock::duration, Posix::time_zone>;` instead say `using TimeZone = date::zoned_time<seconds, Posix::time_zone>;` and see if that fixes your problem.  This tells the library you want to traffic in seconds instead of nanoseconds.

**Comment by paulreimer** [comment]
OK, I can confirm that it works when I change the `duration` to `seconds`. And seems like it works also when I change the types/templates to `system_clock::duration`.

I replaced the line from the Ccompatibility example thusly:
```
time_of_day<typename decltype(tp)::duration> tod{lt - ld};
```

**Comment by HowardHinnant** [comment]
Looks good.  This lib (and chrono) put you in charge of the precision.  Implicit conversions are allowed from coarse to fine.  But lossy conversions from fine to coarse are compile-time errors.  If you really want to do that, there is explicit syntax to make it happen.

**Comment by paulreimer** [comment]
I expect I'll stay at the highest/native precision available. But otherwise I think I have already found `floor` for when it comes up (I needed it above, to instantiate with `seconds`).
