### ISSUE TITLE
Compile error: to_utc_time used before declaration

### ISSUE THREAD

**Issue by rsto** [HowardHinnant/date#289]
Using the current master branch (6941691), I get a compile error when attempting to parse a time-stamp string into utc_seconds:

    ./include/date/tz.h:2506:1: note: 'to_utc_time' should be declared prior to the call site 
    to_utc_time(const sys_time<Duration>& t)

The code failing to compile is taken from your example in [issue#133](https://github.com/HowardHinnant/date/issues/133#issuecomment-282526448) how to parse leap second timestamps:

    #include "date/tz.h"
    #include <cassert>
    #include <iostream>
    #include <sstream>

    int
    main()
    {
        using namespace date;
        using namespace std;
        using namespace std::chrono;
        istringstream in{"2016-12-31T23:59:59Z "
                         "2016-12-31T23:59:60Z "
                         "2017-01-01T00:00:00Z"};
        utc_seconds t0, t1, t2;
        in >> parse("%FT%TZ", t0) >> parse(" %FT%TZ", t1) >> parse(" %FT%TZ", t2);
        assert(!in.fail());
        assert(t0 < t1 && t1 < t2);
        cout << t0 << '\n' << t1 << '\n' << t2 << '\n';
    }
 (I've just changed the #include path and added the two spaces in the parse format for t1 and t2, otherwise the parser would have failed).

I compile from the root of the checked out Git repo with

    $ c++ -std=c++14 -I./include main.cpp src/tz.cpp -lcurl

The errors show up on both OS X (LLVM) and x64 Linux (GCC):

    $ c++ --version
    Apple LLVM version 8.1.0 (clang-802.0.42)
    Target: x86_64-apple-darwin17.3.0

    $ g++ --version
    g++ (Debian 6.3.0-18) 6.3.0 20170516

When I reorder the declaration of `from_stream` in tz.h ([tz.h#L1946](https://github.com/HowardHinnant/date/blob/master/include/date/tz.h#L1946)) to be after the declaration of `to_utc_time` I can compile cleanly in my experimental fork ([see](https://github.com/rsto/date/commit/57e86edebbddd61a26c3688774bf162fc22d23ee)).

I'm very much a beginner to C++ and this most probably is me not compiling with the right flags?

In any case, thanks for this wonderful library!

**Comment by HowardHinnant** [comment]
This looks like my bad at first glance.  I'll investigate and get this fixed today!  I probably just need some forward declarations.

**Comment by HowardHinnant** [comment]
Fixed with https://github.com/HowardHinnant/date/commit/3b8372f4fa9b8c7efc3f51a9c1c25ae2c55153b6

Thanks much for reporting this!
