### ISSUE TITLE
Library is declared to be C++11 compatible, but uses std::quoted which is C++14

### ISSUE THREAD

**Issue by ivanp2015** [HowardHinnant/date#29]
Library is declared to be C++11 compatible, but uses std::quoted which is C++14 without proxying for C++11. http://en.cppreference.com/w/cpp/io/manip/quoted

**Comment by ivanp2015** [comment]
fix available in the my recent pull request for the vs2013 build

**Comment by jkhoogland** [comment]
In addition in the test code, some time literals are used.
https://github.com/HowardHinnant/date/blob/master/test/tz_test/validate.cpp

**Comment by xvan** [comment]
Agree, the tests should replace literals like 10h should be replaced by std::chrono::hours(10) to be C++11 compliant

**Comment by HowardHinnant** [comment]
Now fixed.
