### ISSUE TITLE
Date diff in days

### ISSUE THREAD

**Issue by marcovc** [HowardHinnant/date#290]
How can I achieve this?:

    auto d1 = year{2016}/10/6;
    auto d2 = year{2016}/1/6;
    std::cout << (d1-d2) << std::endl;

Thanks!

**Comment by HowardHinnant** [comment]
Hi @marcovc!

All you need to do is convert the `year_month_day` types to `sys_days` any time prior to the subtraction.  The difference will have type `days` (a `chrono::duration`) and will stream out if there is a `using namespace date` in scope, or a `using date::operator<<` (to find the streaming operator for `chrono::duration`.

Stylistically I prefer `2016_y` over `year{2016}`, but they are equivalent to each other both in semantics and in performance.
```c++
#include "date/date.h"
#include <iostream>

int
main()
{
    using namespace date;
    sys_days d1 = 2016_y/10/6;
    sys_days d2 = 2016_y/1/6;
    std::cout << (d1-d2) << '\n';
}
```
Output:
```
274[86400]s
```
That means 274 units, where each unit is 86400s.  Or 274 days.

**Comment by marcovc** [comment]
Ah! I knew it should be easy :)

Thank you for this library, it was really missing!
Marco

**Comment by HowardHinnant** [comment]
Rationale for why `year_month_day` won't do day-oriented arithmetic:  https://github.com/HowardHinnant/date/wiki/FAQ#day_arithmetic

**Comment by marcovc** [comment]
I see... Sorry I missed the FAQ..

**Comment by HowardHinnant** [comment]
No problem!  I'm happy to know this lib is useful. :-)
