### ISSUE TITLE
Is it thread-safe to call time_zone's public methods?

### ISSUE THREAD

**Issue by sewenew** [HowardHinnant/date#292]
I'm writing a helper function to convert a system clock time point to local date:

`auto local_time = date::current_zone()->to_local(tp);`

However, `date::current_zone` is NOT a cheap operation, since it needs to do some file operation to locate current zone info.

So I decide to reuse `date::current_zone()` result by defining a static variable inside the helper function:

`static auto zone = date::current_zone();`

In this way, `date::current_zone` will only be called once. However, this helper function might be called in multiple threads. So my question is that **is it thread-safe to call `time_zone::to_local` and other `time_zone`'s member functions in a multi-threading environment**?

**Comment by HowardHinnant** [comment]
Yes.
