### ISSUE TITLE
Rename tags

### ISSUE THREAD

**Issue by egorpugin** [HowardHinnant/date#293]
Hi!

Could you please be more specific in git tags?
Now we have: `v2.4`, `2.3`, `v2.2`, `2.1.0`, `v2.0.0`, `v1.0.0`.
This completely brokes my machinery stuff.

Thank you.

**Comment by HowardHinnant** [comment]
Sorry, I will try to stick with the vx.x format.

**Comment by egorpugin** [comment]
Well, now we have `v2.4.1` again.
Maybe you could stick to `vx.x.x`? Even for `v2.5.0`?

**Comment by HowardHinnant** [comment]
Sorry.  In two years you can just say `std::chrono`.

**Comment by egorpugin** [comment]
That is great! Great job, thank you and all contributors! :)
But if you could be a bit more predictive in tag naming... :)
Just a friendly reminder. I can live with different tags and do 1-2 symbols fixes when new date arrives.
