### ISSUE TITLE
Cannot compile with Intel compiler

### ISSUE THREAD

**Issue by janoliver** [HowardHinnant/date#298]
Hi, trying to use the great `date.h` with the Intel compiler (for me it's Version 17) results in the following errors:
```
#include <iostream>
#include "date.h"

int main() {
    std::cout << "Hello World!\n";
    return 0;
}
```

`icpc -std=gnu++11 -cxxlib=/path/to/gcc -o hello hello.cpp`
```

In file included from hello.cpp(2):
date.h(3398): error: expression must have a constant value
                      Duration{1} >= std::chrono::minutes{1} ? classify::minute :
                              ^
          detected during:
            instantiation of class "date::detail::classify_duration<Duration> [with Duration=std::chrono::hours]" at line 3501
            processing of template argument list for "date::detail::time_of_day_storage" based on template argument <std::chrono::hours> at line 3854
            instantiation of class "date::time_of_day<Duration> [with Duration=std::chrono::hours]" at line 3885
....
```
Any chance you can make `date.h` compatible to the Intel compiler? Or could I work around the issue with some compiler flag maybe?

**Comment by HowardHinnant** [comment]
Intel must be using an old std::lib that has not yet put `constexpr` on the `chrono::duration` constructors.

Nevertheless, this looks like a pretty old version of date.h too, and this problem might already be fixed at tip-of-trunk.  Could you try the latest?  Thanks.

**Comment by janoliver** [comment]
Yes, it works fine with the version in `master`. Thank you!
