### ISSUE TITLE
compile error on CentOS 7.3 with GCC 4.8.5

### ISSUE THREAD

**Issue by audiA3** [HowardHinnant/date#299]
when compile the date-master/test/date_test/parse.pass.cpp with :
[lic@localhost date_test]$ g++  -std=c++11 parse.pass.cpp -I../../include/date/  -o parse

It failed with following output information:

In file included from parse.pass.cpp:25:0:
../../include/date/date.h: In instantiation of ‘std::basic_istream<_CharT, _Traits>& date::from_stream(std::basic_istream<_CharT, _Traits>&, const CharT*, date::sys_time<Duration>&, std::basic_string<CharT, Traits, Alloc>*, std::chrono::minutes*) [with Duration = std::chrono::duration<int, std::ratio<86400l, 1l> >; CharT = char; Traits = std::char_traits<char>; Alloc = std::allocator<char>; date::sys_time<Duration> = std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<int, std::ratio<86400l, 1l> > >; std::chrono::minutes = std::chrono::duration<int, std::ratio<60l> >]’:
../../include/date/date.h:7233:74:   required from ‘std::basic_istream<_CharT, _Traits>& date::operator>>(std::basic_istream<_CharT, _Traits>&, const date::parse_manip<Parsable, CharT, Traits, Alloc>&) [with Parsable = std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<int, std::ratio<86400l, 1l> > >; CharT = char; Traits = std::char_traits<char>; Alloc = std::allocator<char>]’
parse.pass.cpp:37:32:   required from here
../../include/date/date.h:4347:5: error：Converting from initialization list to ‘date::weekday’  will use explicit constructor ‘constexpr date::weekday::weekday(unsigned int)’
     fields() = default;
     ^
../../include/date/date.h:7162:20: Note: the first method to be generated here ‘date::fields<Duration>::fields() [with Duration = std::chrono::duration<long int>]’
     fields<CT> fds{};

can anybody give me some suggest to fix this issue?

**Comment by HowardHinnant** [comment]
My first recommendation would be to upgrade your gcc.  gcc-4.8.5 isn't quite up to handling C++11.

However I think you can work around this by changing line 4347 of date.h from:
```c++
    fields() = default;
```
to:
```c++
    fields() {}
```

**Comment by audiA3** [comment]
thanks a lot for your reply. I have upgrade the gcc and everything goes well.
