### ISSUE TITLE
Parse %T accepts out-of-range minutes, inconsistent with hrs/sec

### ISSUE THREAD

**Issue by staylor774** [HowardHinnant/date#300]
Parsing a date with `%T` fails if hours/seconds equal 99 (as I expect), but it succeeds if minutes equal 99.

```
Format: "%FT%TZ"
2017-10-30T99:35:50.123456Z  // Succeeds
2017-10-30T15:99:50.123456Z  // Fails
2017-10-30T15:35:99.123456Z  // Succeeds
```

I've traced it to this line in date.h:
`fds.tod = time_of_day<Duration>(hours{h} + minutes{min});`

The `+` operator wraps around the minutes when they get added to the hours. The seconds value doesn't have this problem because it's treated separately.

Because of wrapping minutes, `time_of_day_storage::in_conventional_range()` passes error checking:
`m_ < std::chrono::hours{1}`

It would be great to have consistent behaviour with error checking in parsing. (Unfortunately I can't submit PRs due to corporate restrictions, and I'm out of my depth here anyway.)

Great library, love your work!

**Comment by HowardHinnant** [comment]
Nice catch, thanks!

Fixed: https://github.com/HowardHinnant/date/commit/43d8a4eab0294ecd95834627d20f23030fea7e8d
