### ISSUE TITLE
Fallback case for when OS timezone data is not available

### ISSUE THREAD

**Issue by cbeck88** [HowardHinnant/date#310]
Hi, we are using date library in our firmware now, and we are pleased with it, it given us a very nice alternative to the problematic POSIX api. We have configured the library to use OS time zone database, as we cannot make curl calls on our device.

However, we have a problem which is that sometimes when e.g. bringing up the system on new hardware, we haven't necessarily installed time zone data in the OS yet.

We would like to be able to catch the exception thrown from `discover_tz_dir` here: https://github.com/HowardHinnant/date/blob/master/src/tz.cpp#L339
and then proceed with a generic UTC timezone.

Unfortunately, AFAICT the "default_zone" which is provided here: https://github.com/HowardHinnant/date/blob/master/include/date/tz.h#L296
requires a call to `locate_zone` which in turn initializes the time zone database through `discover_tz_dir`.

Is it possible that we can catch this exception and then continue to use the library with some kind of "default" UTC timezone with no offset, even if there is no OS time zone database?

Intuitively I would imagine that this is possible, if the default timezone object is declared to be a constant with UTC offset of zero.

It's my understanding that in POSIX, while the `localtime` function may fail if there is no timezone information, the `gmtime` function doesn't fail in this way, giving me an effective fallback. I could fallback to `gmtime` when `date` throws an exception also, but I'd prefer not to have to do that.

**Comment by HowardHinnant** [comment]
I find myself wondering if `<ptz.h>` could help:

https://github.com/HowardHinnant/date/blob/master/include/date/ptz.h

This is a custom time zone modeled after POSIX time zones that construct from a string.  UTC is constructed with "UTC0" (abbreviation followed by offset).  The downside is that `zoned_time<Duration, TimeZonePtr>` is a different type when using a custom time zone.  But with C++17 template deduction guides, the source code isn't too bad.  Here's a HelloWorld:
```c++
#include "date/ptz.h"
#include "date/tz.h"
#include <cstring>
#include <iostream>
#include <exception>

int
main()
{
    using namespace date;
    using namespace std::chrono;
    try
    {
        auto zt = zoned_time{current_zone(), system_clock::now()};
        std::cout << format("%F %T %Z\n", zt);
    }
    catch (const std::exception& e)
    {
        if (std::memcmp(e.what(), "Timezone database not found", 27) != 0)
            throw;
        auto zt = zoned_time{Posix::time_zone{"UTC0"}, system_clock::now()};
        std::cout << format("%F %T %Z\n", zt);
    }
}
```
If this is unable to find a IANA database, it will throw an exception and then output the current time in UTC.

**Comment by cbeck88** [comment]
Thanks, this is very helpful!
