### ISSUE TITLE
Duration stream extraction

### ISSUE THREAD

**Issue by cstratopoulos** [HowardHinnant/date#318]
In the documentation for the `operator<<` overload for `duration` types (or `[time.duration.io]`), a mechanism is described by which `duration` objects can be inserted to a stream as their count followed by the result of `detail::get_units` (or "exposition-only" `get_units`). So for example `std::chrono::seconds{60}` is inserted as `"60s"`. 

My question is whether an "inverse" of this operation (spiritually like an `operator<<`) can be performed by a call to `from_stream`. The basic functionality would be, given `std::chrono::seconds s`, to have `s.count() == 60` when `s` is somehow extracted from `"60s"`. The advanced functionality would be to have, e.g., `s.count() == 3600` when `s` is somehow extracted from `"1h"`. 

I didn't see any mention of unit suffixes in the format specifiers (`[time.format]`). Maybe this is out of the scope of `from_stream` functions though?

**Comment by HowardHinnant** [comment]
I actually wrote `operator>>` for `duration`s several years ago.  It was pretty ugly, and I've intentionally omitted it.  That's not to say it couldn't be added in the future.  But I'm no longer confident that I can currently get it right.

The `operator<<` for `duration`s is (I perceive) a greater need just for debugging purposes (I do a lot of temporary printing for debugging).  So there's no flexibility, and you just get what you get.

For parsing purposes, I'm hopeful that `parse` using `%T`, `%H`, `%M` and `%S` combined with `duration`s will be sufficiently flexible to meet the parsing needs of durations.  But those admittedly are not a great fit for parsing the format emitted by `operator<<` for `duration`s.

**Comment by cstratopoulos** [comment]
That makes sense about `operator<<` as a low-effort debugging option, and I can imagine `operator>>` would indeed be a mess to write! 

This just came up in my work on a JSON serialization library where I plan to support two-tiered serialization of `duration` objects (`time_point` similarly): a compact default, with opt-in use of `to_stream`/`from_stream` with a provided format string. I was considering `operator<<` output as the `duration` default, but `duration::count` is probably a better approach for a variety of reasons.

So thank you for the reply, I will close this issue as you've answered my question.

P.S., congrats on the recent Jacksonville vote!
