### ISSUE TITLE
to_stream mishandles %h with -DONLY_C_LOCALE=1

### ISSUE THREAD

**Issue by timsong-cpp** [HowardHinnant/date#319]
This [line](https://github.com/HowardHinnant/date/blob/e7e1482087f58913b80a20b04d5c58d9d6d90155/include/date/date.h#L4629) means that `%h` is treated as equivalent to `%B` rather than `%b`.

    os << month_names().first[tm.tm_mon+12*(*fmt == 'b')];

**Comment by HowardHinnant** [comment]
Thanks!

**Comment by HowardHinnant** [comment]
Fixed by: https://github.com/HowardHinnant/date/commit/0125d330ab3aa288fb42397c7adadf48cb07ee43
