### ISSUE TITLE
to_stream: %e (and %Oe when -DONLY_C_LOCALE=1) pads with os.fill()

### ISSUE THREAD

**Issue by timsong-cpp** [HowardHinnant/date#320]
The spec says that `%e` pads with a space, but `to_stream` doesn't call `os.fill()` for `e`, so it instead pads with whatever `os.fill()` happens to be.

**Comment by HowardHinnant** [comment]
Ok, thanks.  Will fix.

**Comment by HowardHinnant** [comment]
Fixed by: https://github.com/HowardHinnant/date/commit/0125d330ab3aa288fb42397c7adadf48cb07ee43
