### ISSUE TITLE
test/parse.pass.cpp fails in line 48

### ISSUE THREAD

**Issue by Siesh1oo** [HowardHinnant/date#323]
Is this expected behavior? If not, what is the recommended approach to debug the issue?

```
// gcc version 7.3.0 (Debian 7.3.0-12) 

parse.pass.cpp:48
48	        assert(!in.fail());
(gdb) l
43	    {
44	        // correct abbreviation
45	        std::istringstream in{"Sun 2016-12-11"};
46	        sys_days tp;
47	        in >> parse("%A %F", tp);
48	        assert(!in.fail());
49	        assert(!in.bad());
50	        assert(!in.eof());
51	        assert(tp == 2016_y/12/11);
52	    }
(gdb) print tp
$1 = {__d = {__r = 0}}
```

**Comment by HowardHinnant** [comment]
This represents a bug in gcc's `time_get` functionality.  Parsing `%a` and `%A` should parse the full or abbreviated weekday name without regard to case.  gcc's `time_get` doesn't do that.  A workaround is to compile with `-DONLY_C_LOCALE=1`.  This causes the date library to ignore the std::lib`s locale support, and use its own.  But this also limits you to use only the equivalent of the  "C" locale.

**Comment by Siesh1oo** [comment]
Thank you. I assume this has already been reported upstream?

As I noticed in other tickets cmake is not the default build system. What is the "right" way to build the testsuite and pass these flags?
