### ISSUE TITLE
from_stream flags have odd interdependencies

### ISSUE THREAD

**Issue by timsong-cpp** [HowardHinnant/date#326]
- If I have %G or %g in the format string, I have to also have both %V and a weekday-parsing flag.
- If I have both %Y and (%U or %W) in the format string, I have to also have a weekday-parsing flag.

even if I have a %F in the format string so that it can parse the full date information from there.

Intended?

**Comment by HowardHinnant** [comment]
Just so that there is no misunderstanding in the issue/question you're asking, could you provide a test case?  Thanks.

**Comment by timsong-cpp** [comment]
https://wandbox.org/permlink/pmsHMwhiMqC03TNI

```
%F %G | 2018-04-05 2018 | failed
%F %g | 2018-04-05 18 | failed
%F %G %V | 2018-04-05 2018 14 | failed
%F %g %V | 2018-04-05 18 14 | failed
%F %G %V %u | 2018-04-05 2018 14 4 | success
%F %g %V %u | 2018-04-05 18 14 4 | success
%F %U | 2018-04-05 13 | failed
%F %W | 2018-04-05 14 | failed
%F %U %u | 2018-04-05 13 4 | success
%F %W %u | 2018-04-05 14 4 | success
%F %V | 2018-04-05 14 | success
```

**Comment by HowardHinnant** [comment]
I see where you're going with this, and I think I can code it.  And I think it is worth it.  But can you help me write the spec for it?

**Comment by timsong-cpp** [comment]
Sure, I'd be happy to.

**Comment by HowardHinnant** [comment]
I'm thinking something along the lines of "parsing into a type must fill every field of that type, and duplicate parsing of a field must parse consistent information."  But that's pretty horrible standard-eze.

**Comment by timsong-cpp** [comment]
My first thought was something like "If there exists exactly one value of the parseable type that is consistent with all the information parsed, the result is that value; otherwise, the parse fails" (insufficient information = multiple values; inconsistent information = no such value exists), but that would at the very least need some caveats (e.g., we don't want to support "year+week number+day" even though that is enough to designate a unique date).

**Comment by HowardHinnant** [comment]
Ok, poke this with a sharp stick: https://github.com/HowardHinnant/date/commit/cdb4b276d973bf2875aa3fc516b4a73dc306476b

**Comment by timsong-cpp** [comment]
Poked: https://wandbox.org/permlink/tQn16MSzNG0VLERp

**Comment by HowardHinnant** [comment]
Try #next:  https://github.com/HowardHinnant/date/commit/b48a18a1d9f5e36cdfe109069d59671947aa07e3

**Comment by HowardHinnant** [comment]
Fixed by https://github.com/HowardHinnant/date/commit/d53db7a1cb61dc2651374e5b9660ed07e6d28358

Thanks.
