### ISSUE TITLE
Duplicated flags in from_stream

### ISSUE THREAD

**Issue by timsong-cpp** [HowardHinnant/date#327]
...doesn't set failbit (and appears to use the value parsed from the last occurrence) unless the duplicated flag is %Z. Intended?

**Comment by HowardHinnant** [comment]
Just so that there is no misunderstanding in the issue/question you're asking, could you provide a test case?  Thanks.

**Comment by HowardHinnant** [comment]
You write the most wicked tests! ;-)

**Comment by HowardHinnant** [comment]
I'm about to commit a fix to this and other errors you've pointed out.  What I'm about to commit outputs the following for this test:
```
%F %T %Z %z %F | 2018-04-15 18:39:19 UTC +0000 2018-04-15 | 2018-04-15 18:39:19
%F %T %Z %z %T | 2018-04-15 18:39:19 UTC +0000 18:39:19 | 2018-04-15 18:39:19
%F %T %Z %z %I | 2018-04-15 18:39:19 UTC +0000 06 | 2018-04-15 18:39:19
%F %T %Z %z %Z | 2018-04-15 18:39:19 UTC +0000 UTC | 2018-04-15 18:39:19
%F %T %Z %z %z | 2018-04-15 18:39:19 UTC +0000 +0000 | 2018-04-15 18:39:19
%F %T %Z %z %I %p | 2018-04-15 18:39:19 UTC +0000 06 PM | 2018-04-15 18:39:19
%F %T %Z %z %I %p %p | 2018-04-15 18:39:19 UTC +0000 06 PM PM | 2018-04-15 18:39:19
%F %T %Z %z %I %p %I %p | 2018-04-15 18:39:19 UTC +0000 06 PM 06 PM | 2018-04-15 18:39:19
%F %T %Z %z %F | 2018-04-15 18:39:19 UTC +0000 2019-05-16 | failed
%F %T %Z %z %T | 2018-04-15 18:39:19 UTC +0000 19:40:20 | failed
%F %T %Z %z %I | 2018-04-15 18:39:19 UTC +0000 07 | 2018-04-15 18:39:19
%F %T %Z %z %Z | 2018-04-15 18:39:19 UTC +0000 UTC | 2018-04-15 18:39:19
%F %T %Z %z %z | 2018-04-15 18:39:19 UTC +0000 +0000 | 2018-04-15 18:39:19
%F %T %Z %z %I %p | 2018-04-15 18:39:19 UTC +0000 07 PM | failed
%F %T %Z %z %I %p %p | 2018-04-15 18:39:19 UTC +0000 07 PM PM | failed
%F %T %Z %z %I %p %I %p | 2018-04-15 18:39:19 UTC +0000 07 PM 07 PM | failed
```
I believe this output is correct, despite the "failed" on the last several lines.  For each of those lines, the repeated flag has parsed a different, or inconsistent value.  Do you concur?

**Comment by timsong-cpp** [comment]
`%F %T %Z %z %I | 2018-04-15 18:39:19 UTC +0000 07 | 2018-04-15 18:39:19` should also fail: `%I` parsed an inconsistent 12-hour time. But yes, those final lines are meant to test the handling of inconsistent values.

**Comment by HowardHinnant** [comment]
Fixed by: https://github.com/HowardHinnant/date/commit/d53db7a1cb61dc2651374e5b9660ed07e6d28358

Thanks.
