### ISSUE TITLE
where is examples?

### ISSUE THREAD

**Issue by qiuchengw** [HowardHinnant/date#328]
I am totally lost in tons of c++ templates, and lost in tons of documents, it's just a MESS!
I want to use the code, and do not want to be an expert! 
why not just give a simple useful examples ?

**Comment by HowardHinnant** [comment]
https://github.com/HowardHinnant/date/wiki/Examples-and-Recipes

**Comment by qiuchengw** [comment]
wow, my bad, apologize。 and thanks very much！
