### ISSUE TITLE
Docs: time_of_day::subseconds()

### ISSUE THREAD

**Issue by rbock** [HowardHinnant/date#33]
Hi,

I believe there is a documentation error for time_of_day:

In `time_of_day<std::chrono::duration<Rep, Period>>`, instead of 
```C++
   constexpr std::chrono::precision subseconds() const noexcept;
```
it should be
```C++
   constexpr precision subseconds() const noexcept;
```

And instead of 
```C++
constexpr std::chrono::seconds time_of_day<std::chrono::duration<Rep, Period>>::subseconds() const noexcept;
```
it should be something like
```C++
constexpr
std::chrono::duration<Rep, Period>
time_of_day<std::chrono::duration<Rep, Period>>::subseconds() const noexcept;
```

Best,

Roland

**Comment by HowardHinnant** [comment]
Thanks!
Fixed in:
https://github.com/HowardHinnant/HowardHinnant.github.io/commit/3e4faf1fbecd2fb224773ada3e79f1e41ea6fd75
