### ISSUE TITLE
Parsing only %Y-%m into time_point

### ISSUE THREAD

**Issue by ChrisBFX** [HowardHinnant/date#332]
I'm running into a similar problem as described in #253 

In our application the user can specify the format used for parsing (for importing time series from csv-files). Unfortunately sometimes the time is only specified with a year-month or even only a year so a simple `from_stream(...., time_point)` fails.

In #253 you said:
> if the library can't unambiguously form the count that lives inside of tp, it will set failbit in the stream in and not modify tp.

Which confuses me, as for me `%Y-%m-%d` is as unambiguous as `%Y-%m`, but the former just assumes `%Y-%m-%d 00:00:00`.
I agree that parsing to a year_month_day should fail if the day or month is not specified, but would it be a problem to change `from_stream(,,sys_time<Duration>& tp,..)` so it doesn't uses `fds.ymd.ok()` but checks `fds.ymd.day().ok()` and assumes `1` if it fails?

**Comment by HowardHinnant** [comment]
The problem I face is that some people want to flag it as an error if they ask for a day-resolution `time_point` is only month-resolution is parsed.  And others (such as yourself) want to default the day spec if it is missing.

Currently there is only "built-in" syntax for the former and not that latter.  I have not come up with an intuitive syntax to do both.

When the current `parse` semantics don't do what you want, the current workaround is to drop down a level and parse `int`s, and then convert those `int`s into the calendrical or chronological types you desire.

**Comment by ChrisBFX** [comment]
Thx for the quick response.

So then why is it ok to parse into local_seconds without specifying the time of day? That seems to be inconsistent.

Yeah finding a default which works for everybody is probably not possible.

Would you advise to use the  `date::fields<duration>` overload directly, which seems to allow me to write my own logic after parsing? I guess it is only an internal function as it is not documented?

**Comment by HowardHinnant** [comment]
I've been waffling on documenting `date::fields<duration>` (and its `from_stream` overload).  Your experience (positive or negative) would be good feedback as to if I should.

On `local_seconds`:  When we get into `chrono::time_point`s, one can assert that (for example):
```
assert(local_days{days{1}} == local_seconds{hours{24}});
```
I.e. The precision has a natural truncation property that actually works in code.  It is literally the same things as `assert(milliseconds{1} == microseconds{1000})`.

But the same is not true of say `year_month` and `year_month_day`.  It is ambiguous as to which day in a month `year_month` refers to.  It might be the first, it might be all of them.

I suppose I could have made `year_month` implicitly convert to and compare equal with y/m/1.  But I didn't and I'm having trouble vocalizing why except to say I think some people would have found it surprising.  It might have led to some run-time errors in ways analogous to other troublesome implicit conversions we deal with, such as between `int` and `unsigned`.

**Comment by asbumste** [comment]
Was the idea that %T can be natural truncated changed? The below used to work, but I recently added the current date.h to my project to solve the original problem in this thread and now have lost this functionality.

```
std::istringstream time_stream = {"2019-05-01 12:00"}; // or "2019-05-01" or "2019-05-01 12"
std::chrono::system_clock::time_point tp;
time_stream >> date::parse("%F %T", tp);
```

**Comment by HowardHinnant** [comment]
No, because some people want the error when %T isn't fully matched.

Here's a way for you to regain your functionality:
```
#include "date/date.h"
#include <iostream>
#include <sstream>

// Parse "%F %H:%M", "%F %H" or "%F"
std::chrono::system_clock::time_point
my_parse(std::string s)
{
    std::istringstream time_stream{std::move(s)};
    std::chrono::system_clock::time_point tp;
    time_stream >> date::parse("%F %H:%M", tp);
    if (time_stream.fail())
    {
        time_stream.clear();
        time_stream.seekg(0);
        time_stream >> date::parse("%F %H", tp);
    }
    if (time_stream.fail())
    {
        time_stream.clear();
        time_stream.seekg(0);
        time_stream >> date::parse("%F", tp);
    }
    return tp;
}

int
main()
{
    using date::operator<<;
    std::cout << my_parse("2019-05-01") << '\n';
    std::cout << my_parse("2019-05-01 12") << '\n';
    std::cout << my_parse("2019-05-01 12:15") << '\n';
    std::cout << my_parse("2019/05/01 12:15") << '\n';
}
```
Output:
```
2019-05-01 00:00:00.000000
2019-05-01 12:00:00.000000
2019-05-01 12:15:00.000000
1970-01-01 00:00:00.000000
```

**Comment by asbumste** [comment]
Alright, good to know.

Thanks for the solution.
