### ISSUE TITLE
Warning with gcc 8.1 on date.h

### ISSUE THREAD

**Issue by sergeken** [HowardHinnant/date#337]
When compiling with the latest gcc and all warnings the following warning is produced:
/usr/local/include/date/date.h:6017:34: warning: conversion from ‘int’ to ‘char’ may change value [-Wconversion]
`             *e++ = CharT(u % 10) + CharT{'0'};
`                    ~~~~~~~~~~~~~~^~~~~~~~~~~~
/usr/local/include/date/date.h: In instantiation of ‘void date::detail::read(std::basic_istream<_CharT, _Traits>&, int, Args&& ...) [with CharT = char; Traits = std::char_traits<char>; Args = {const char&}]’:

changing the line with the following silences the error.
`             *e++ = static_cast<CharT>(CharT(u % 10) + CharT{'0'});
`

**Comment by HowardHinnant** [comment]
Thanks!  I'll get that in soon.

**Comment by daggilli** [comment]
This is still not fixed.

**Comment by HowardHinnant** [comment]
Thanks for the ping.
