### ISSUE TITLE
bool std::uncaught_exception()’ is deprecated in C++17

### ISSUE THREAD

**Issue by sergeken** [HowardHinnant/date#338]
When enabling std++17 all lines having
`std::uncaught_exception()
`

generates the following warnings

```
/home/serge/githubs/date/include/date/date.h:988:75: warning: ‘bool std::uncaught_exception()’ is deprecated [-Wdeprecated-declarations]
         if ((this->flags_ & std::ios::unitbuf) && !std::uncaught_exception() &&
                                                    ~~~~~~~~~~~~~~~~~~~~~~~^~
In file included from /usr/include/c++/8.1.0/utility:79,
                 from /usr/include/c++/8.1.0/algorithm:60,
                 from /home/serge/githubs/date/include/date/date.h:42,
                 from /home/serge/githubs/date/include/date/tz.h:108,
                 from /home/serge/githubs/date/include/date/tz_private.h:31,
                 from /home/serge/githubs/date/src/tz.cpp:86:
/usr/include/c++/8.1.0/exception:102:8: note: declared here
   bool uncaught_exception() _GLIBCXX_USE_NOEXCEPT __attribute__ ((__pure__));

``` 
A quick workaround is to add the following to CMakeLists.txt
`add_definitions(-Wno-deprecated)
`

An alternative is to have a conditional compilation checking for __cplusplus >= 201703 and use int uncaught_exceptions() instead.

**Comment by tim-weis** [comment]
Similarly, when compiling with Visual Studio 2017, the following deprecation warning ([Compiler Warning (level 3) C4996](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4996)) is issued:

>     date.h(1032): error C4996: 'std::uncaught_exception': warning STL4006: std::uncaught_exception() is deprecated in C++17. It is superseded by std::uncaught_exceptions(), plural. You can define _SILENCE_CXX17_UNCAUGHT_EXCEPTION_DEPRECATION_WARNING or _SILENCE_ALL_CXX17_DEPRECATION_WARNINGS to acknowledge that you have received this warning.

The workaround (as spelled out in the error message) is to define either the `_SILENCE_CXX17_UNCAUGHT_EXCEPTION_DEPRECATION_WARNING` or `_SILENCE_ALL_CXX17_DEPRECATION_WARNINGS` preprocessor symbols. Although I side with @sergeken and would prefer a cleaner solution.

**Comment by HowardHinnant** [comment]
Thanks.  I've set `_SILENCE_CXX17_UNCAUGHT_EXCEPTION_DEPRECATION_WARNING` here: https://github.com/HowardHinnant/date/commit/de6a03d337dcd617a121254f700979086889c0a4 so that at least one problem is solved.

**Comment by tim-weis** [comment]
@HowardHinnant I'm not sure this is a good idea. With this being a header, introducing a preprocessor symbol now leaks into surrounding code. Using the [push_macro](https://docs.microsoft.com/en-us/cpp/preprocessor/push-macro) and [pop_macro](https://docs.microsoft.com/en-us/cpp/preprocessor/pop-macro) pragmas can prevent that, although I don't know, when exactly the warning is generated, so this may not be a solution after all.

Then again, maybe this isn't something that needs to be solved in the library at all. Visual Studio can be configured to properly set the `__cplusplus` preprocessor symbol (though doing so leads to another error).

**Comment by HowardHinnant** [comment]
I don't have a VS compiler to experiment and test with.  If you can submit a PR with a tested solution, it would be much appreciated.

**Comment by tim-weis** [comment]
I fumbled something together, that works with Visual Studio, essentially wrapping all C++ Standard Library includes in date.h inside a push/pop macro brace:

    #if defined(_MSC_VER) && !(__cplusplus >= 201703)
    #  pragma push_macro("_SILENCE_CXX17_UNCAUGHT_EXCEPTION_DEPRECATION_WARNING")
    #  define _SILENCE_CXX17_UNCAUGHT_EXCEPTION_DEPRECATION_WARNING
    #endif
    
    #include <cassert>
    ...
    #include <type_traits>

    #if defined(_MSC_VER) && !(__cplusplus >= 201703)
    #  pragma pop_macro("_SILENCE_CXX17_UNCAUGHT_EXCEPTION_DEPRECATION_WARNING")
    #endif

It fixes the deprecation warning, while still keeping the preprocessor symbol confined to this region of code. I can wrap that up in a PR, yet I feel it's just so very clumsy.

All the more, since a clean solution appears to exist. I did investigate, why using the `/Zc:__cplusplus` compiler option did eventually fail. In case `__cplusplus >= 201703`, the symbol `HAS_STRING_VIEW` is defined. That causes the `#if`-branch to get compiled for the `zoned_time` constructor in [tz.h](https://github.com/HowardHinnant/date/blob/de6a03d337dcd617a121254f700979086889c0a4/include/date/tz.h#L1376). Copying the Visual Studio specific conditionals from the `#else` branch seems to fix the compiler error. Although I don't know why, or even what `template<class Duration, class TimeZonePtr> template<class, class>` means.

Personally. I'd prefer to get those `zoned_time` constructors compatible with Visual Studio.

**Comment by crusader-mike** [comment]
@HowardHinnant, I ran into the same issue while moving y company's codebase to C++17. Do you mind if I modify `date.h` (and submit a pull request) along these lines:
```
#if defined(_MSC_VER) && (!defined(__clang__) || (_MSC_VER < 1920))     <---------- 1920 is MSVC2019
// MSVC
#  define _SILENCE_CXX17_UNCAUGHT_EXCEPTION_DEPRECATION_WARNING
#  if _MSC_VER < 1910
```

and 

```
#undef _SILENCE_CXX17_UNCAUGHT_EXCEPTION_DEPRECATION_WARNING
```
at the very bottom
?

**Comment by crusader-mike** [comment]
@HowardHinnant, aren't you are supposed to use `>=` [here](https://github.com/HowardHinnant/date/blob/8a563041fa65146531249ed557a6839809488521/include/date/date.h#L136)? Quote:
```
#ifndef HAS_UNCAUGHT_EXCEPTIONS
#  if __cplusplus > 201703   <--- here
#    define HAS_UNCAUGHT_EXCEPTIONS 1
#  else
#    define HAS_UNCAUGHT_EXCEPTIONS 0
#  endif
#endif  // HAS_UNCAUGHT_EXCEPTIONS
```

@tim-weis, @sergeken after line mentioned above is fixed -- you can use `/Zc:__cplusplus` [option](https://devblogs.microsoft.com/cppblog/msvc-now-correctly-reports-__cplusplus/) to force MSVC2017+ to generate `__cplusplus` macro properly and everything should just work. Eventually `/Zc:__cplusplus` will become ON by default.

This would allow Howard to remove `_SILENCE_CXX17_UNCAUGHT_EXCEPTION_DEPRECATION_WARNING` macro completely and problem of "leaking macro" will go away.

**Comment by HowardHinnant** [comment]
I am purposefully using the deprecated `uncaught_exception` in C++17.  Set `HAS_UNCAUGHT_EXCEPTIONS=1` in your build if you would like to use `uncaught_exceptions` instead.
