### ISSUE TITLE
default ctor for date types ?

### ISSUE THREAD

**Issue by jkhoogland** [HowardHinnant/date#34]
Hi,
thanks for the great library.

I noticed that there are no default constructors for the various date types.
The issue comes up with serialization logic for example.

I assume you had a reason for not adding them,
but having for example year_month_date have a default ctor to say 1970/1/1 would be nice to have.

Is this something you might add ?
Thanks
Jiri

**Comment by HowardHinnant** [comment]
Thanks for the nice words.

My rationale to-date for not having them (for example for `year_month_day`) is:

*  The default constructor would not be higher performance than the `{y, m, d}` constructor.
*  It is difficult to choose a value for the default constructed object that is not surprising.
*  It is easy to supply a "default value" of your own choosing for different situations.

For an example of the latter:
````
#include "date.h"
#include <iostream>
#include <fstream>

void
input(std::istream& is, date::year_month_day& x)
{
    int y, m, d;
    is >> y >> m >> d;
    // Don't modify x if the read failed
    if (!is.fail())
        x = date::year{y}/m/d;
}

int
main()
{
    std::ifstream infile("test.dat");
    while (infile)
    {
        using namespace date::literals;
        auto a_date = jan/0/0;  // initialize to !ok()
        input(infile, a_date);
        if (a_date.ok())
            std::cout << a_date << '\n';
        else
            break;
    }
}
````
In this example I want to "default" the date to something that is `!ok()`.  If the de-serialization works, it should set it to something that is `ok()`.

I have not yet come across a compelling use case where I really do need default constructors.  And `new`ing arrays of things is not compelling in modern C++ (use `vector` instead).

I am open to being shown compelling use cases for default constructors for these types:  Use cases that demonstrate advantages that will outweigh the disadvantage of having a surprising default value no matter what gets chosen.

**Comment by jkhoogland** [comment]
Thanks for the elaborate clarification.
Fair enough, I will try to make up some examples.
