### ISSUE TITLE
Compile error for target: testit

### ISSUE THREAD

**Issue by kunaltyagi** [HowardHinnant/date#340]
## Error
```c++
/root/date/test/tz_test/zoned_time.pass.cpp: In function 'int main()':
/root/date/test/tz_test/zoned_time.pass.cpp:135:9: error: static assertion failed
         static_assert(!is_constructible<zoned_seconds, sys_time<milliseconds>>{}, "");
         ^~~~~~~~~~~~~
/root/date/test/tz_test/zoned_time.pass.cpp:172:9: error: static assertion failed
         static_assert(!is_constructible<zoned_time<days>, zoned_seconds>{}, "");
```

## Expected:
No errors in compilation

## Build Env details
* Docker: ```debian:stretch```
*  cmake version: ```3.11.20180522```-ge6a32f (installed from source, branch master)
* g++ version: (Debian ```6.3.0-18```+deb9u1) 6.3.0 20170516 (apt install build-essential)
* Command run: ```cmake ../ && cmake --build . --target testit -- -j4```
* No source modifications

## Notes
Default clang ```3.8.1-24``` is more verbose with the errors but that might be because of it not implementing the ```--std=c++17``` in its entirety

**Comment by HowardHinnant** [comment]
Looks like a bug in gcc's libstdc++ for 6.3: https://wandbox.org/permlink/Vc8NbDVKIBeGg6JF

Looks like it is fixed in 7.3: https://wandbox.org/permlink/d2VWqMg4uWkngYrX

**Comment by kunaltyagi** [comment]
Thanks! BTW, can we setup a travis to get a compiler compatibility matrix? Makes sense for a header only library to know which versions of the compiler it is working as intended.

Bug in compiler is usually not the first thing that comes to my mind when I see compilation errors. Such information in the README would be very helpful even if it's not via a CI

**Comment by HowardHinnant** [comment]
Perhaps I should add this issue to the [FAQ](https://github.com/HowardHinnant/date/wiki/FAQ).

I'm a bit allergic to travis.  What I'm really trying to do is get the std::lib implementors to take over this library.  Aiming for C++20, and you'll just be able to change `date::` to `std::chrono::`.

**Comment by HowardHinnant** [comment]
The library (mostly) works back to gcc-5.0.  But there's always bugs in every piece of software.  In every compiler.  In every std::lib, and even this this library.

My policy in the test suite for this library is to not paper over bugs in compiler and std::lib implementations.  This policy has led to bug fixes in compilers and std::lib implementations, such as the test failure you've noted.  Most bugs, including the one you noted, will be a compile-time failure, not a run-time failure.  So you can continue to use this lib with gcc-6.3 without worry.

If you hit a problem, it will almost certainly be revealed at compile-time.  If it isn't obvious how to work around such a problem, just ping me and I'll be happy to help.
