### ISSUE TITLE
Gregorian'ness of Year fields needs to be clearer

### ISSUE THREAD

**Issue by eyalroz** [HowardHinnant/date#343]
It is not easy enough for the lay user to figure out whether date::year values (or year fields in other values) are [Gregorian](https://en.wikipedia.org/wiki/Year_zero) (i.e. 1 BC is followed by 1 AD),[ ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) (i.e. 1 AD is year 1, 1 BC is year 0) or something else.

I would have hoped to see that in docs, and in a bunch of comments, and I don't...

**Comment by HowardHinnant** [comment]
Fixed in the docs, thanks: https://github.com/HowardHinnant/date/commit/0543e00b88693bde831266ea3a31ec28761fe5f8
