### ISSUE TITLE
weekday can't be converted to string using format function

### ISSUE THREAD

**Issue by pmalakul** [HowardHinnant/date#345]
std::cout << "Test format(): " << format("%a %Y-%m-%d %H:%M:%S", floor<milliseconds>(system_clock::now()));

terminate called after throwing an instance of 'std::__ios_failure'
  what():  basic_ios::clear: iostream error

%a or %A can not be used.

**Comment by HowardHinnant** [comment]
Thank you!

Fixed: https://github.com/HowardHinnant/date/commit/c7b69d949a8fd7426eed0b0e96ee4a7f57259c3c
