### ISSUE TITLE
year_day?

### ISSUE THREAD

**Issue by rbock** [HowardHinnant/date#35]
Hi,

Looking over the code I would like to rewrite with your date library, I wondered if there should be a `year_day` type, representing the nth day in a year?

Also, looking at https://en.wikipedia.org/wiki/ISO_8601, it might make sense to add

`year_week`
`year_week_day`

Best,

Roland

**Comment by HowardHinnant** [comment]
For the ISO week date calendar, see:

http://howardhinnant.github.io/iso_week.html
https://github.com/HowardHinnant/date/blob/master/iso_week.h

As for `year_day`, this sounds like another calendar system (like iso_week), but is so trivial to do with date.h that I'm not sure it is worth the API (new API requires more learning curve).  Here is a decent spec for it:

https://en.wikipedia.org/wiki/Ordinal_date

Here's the conversion from `year_month_day` to `year_day`:
````
auto y = ymd.year();
auto daynum = day_point{ymd} - day_point{ymd.year()/jan/1} + days{1};
````
And here's the conversion back to `year_month_day`:
````
auto ymd = year_month_day{day_point{y/jan/1} + daynum - days{1}};
````
Perhaps this is good example code to add to https://github.com/HowardHinnant/date/wiki/Examples-and-Recipes ?

**Comment by rbock** [comment]
Thanks for the links to iso_week! Missed that somehow.

I agree, that it makes more sense to add the ordinal date to the examples and recipes.

**Comment by HowardHinnant** [comment]
Easy to miss.  I just recently added it.  The wiki is public writable.  Would you like to add that example?  Dress it up however you want.

**Comment by rbock** [comment]
Sure, I can try to come up with a reasonable example :-)

**Comment by HowardHinnant** [comment]
Nice job!

**Comment by DavisVaughan** [comment]
If anyone else stumbles across this issue and wants a `year_yearday` calendar type, I've implemented an ordinal calendar in `ordinal.h` here https://github.com/r-lib/clock/blob/master/inst/include/date/ordinal.h
