### ISSUE TITLE
time_of_day from string

### ISSUE THREAD

**Issue by erosh** [HowardHinnant/date#358]
Hi. 
I tried to find any way to create time_of_day from simple string like "19:01:21" but hadn't succeeded.
For my purposes I made a workaround like:
`const auto time = date::make_time(parse_unsigned_time(str));`

I think it would be useful to have a kind of
`template <class CharT, class Traits>
 auto make_time(std::basic_istream<CharT, Traits>& is, const CharT* fmt)`

**Comment by HowardHinnant** [comment]
Here's one way you can do this:
```c++
template <class CharT, class Traits>
auto
make_time(std::basic_istream<CharT, Traits>& is, const CharT* fmt)
{
    std::chrono::seconds t;
    is >> date::parse(fmt, t);
    return date::make_time(t);
}
```

**Comment by erosh** [comment]
Oh, great. Thanks
