### ISSUE TITLE
MinGW support

### ISSUE THREAD

**Issue by pausag** [HowardHinnant/date#36]
Unfortunately, the library cannot currently be compiled with **MinGW** due do the lack of the `<codecvt>` header support. Could you please add support for this? As far as I am concerned, this is needed only to convert UTF16 to UTF8 and back for filenames and timezone names. I am also intended to try to find a workaround myself. Any feedback or hints from your side would be highly appreciated though.

**Comment by HowardHinnant** [comment]
I don't have a Windows box to develop on, but I am open to contributions from those who do.  I note that gcc-5.x supports `<codecvt>`.  Does the latest MinGW support gcc-5.x?  If so, that might be the easiest workaround.

**Comment by HowardHinnant** [comment]
Closing as this issue is over a year old and I don't see a fix on the horizon.  Please feel free to reopen if you believe that would be valuable.
