### ISSUE TITLE
Time-Zone counter using date library

### ISSUE THREAD

**Issue by eulphean** [HowardHinnant/date#360]
Hi Howard,

I'm making a small countdown application that counts down till a future date. I'm trying to incorporate multiple time zones and how they'd countdown to a certain date. Due to the nature of the time differences, one city with a certain time zone might reach the countdown sooner than the other city. However, I'm unable to work with zoned_time to calculate the difference between the future time and the local time in a time-zone. Here's what I have. 

struct tm futureTime;
int days, hours, minutes, seconds, milliseconds; 

void createFutureTime() {
  // January 5th, 2037, 12:00AM
  futureTime.tm_year = 2037 - 1900; // Years after year (1900)
  futureTime.tm_mon = 0;
  futureTime.tm_mday = 5; // Day of the month
  futureTime.tm_hour = 0; // Hours after midnight
  futureTime.tm_min = 0; // Minutes after 0
  futureTime.tm_sec = 0; // Seconds after 0
}

void calculateTimeDiff();   
  // Future time.
  auto future = chrono::system_clock::from_time_t(mktime(&futureTime));
 
  // Time in Sao_Paulo
  auto zone = locate_zone("America/Sao_Paulo");
  auto sp = date::make_zoned(zone, floor<chrono::milliseconds>(chrono::system_clock::now()));
  auto localTime = floor<chrono::milliseconds>(sp.get_local_time());

  // This doesn't work and gives me an error. 
  auto diff = chrono::duration_cast<chrono::milliseconds>(future - localTime); 
  
  // Time seperation
  auto distance = diff.count();
  
  // Formulaes to convert milliseconds to Days, Hours, Minutes, Seconds, and Milliseconds.
  days = floor(distance / (1000 * 60 * 60 * 24));
  hours = floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
  minutes = floor((distance % (1000 * 60 * 60)) / (1000 * 60));
  seconds = floor(distance % (1000 * 60) / 1000);
  milliseconds = 1000 - distance % 1000;
}

How do I calculate a difference between the current time and future time using this library? If I use sp.get_sys_time(), that returns the UTC time and the difference from per say Chicago or SaoPaulo, both would be the same. The difference needs to be calculated from local_time but I'm not sure how to convert it into the right format to make duration_cast accept that. Any ideas?

**Comment by Erroneous1** [comment]
`futureTime` is a `struct tm` which should really either be a `date::sys_seconds` or `date::local_seconds` depending on whether you want to count down to a specific time UTC or a local clock time (see https://howardhinnant.github.io/date/tz.html#loc_vs_sys). `struct tm` should really only be used when you need to interact with APIs that require one.

If the time zone is known when you make futureTime then you should probably even construct it as a `zoned_time` when you make it so you don't have to convert it every time you want to see how long is left:
```c++
date::sys_time<std::chrono::milliseconds>
createFutureTime(const date::time_zone* zone = locate_zone("America/Sao_Paulo"))
{
    return date::make_zoned(
        zone,
        date::local_days{2037_y / date::jan / 5},
        date::choose::earliest);
}

static const auto future = createFutureTime();
```
Review https://howardhinnant.github.io/date/date.html and https://en.cppreference.com/w/cpp/chrono/duration to see all of the various time structures. For instance, you have hard coded math for pulling time values out of `std::chrono::milliseconds`. Try this for that part:
```c++
auto diff = date::floor<std::chrono::milliseconds>(std::chrono::system_clock::now() - future)
auto days = date::floor<date::days>(diff); //This might be negative if future is in the past
auto hours = date::floor<std::chrono::hours>(diff %= days);
auto minutes = date::floor<std::chrono::minutes>(diff -= hours);
auto seconds = date::floor<std::chrono::seconds>(diff -= minutes);
auto milliseconds = diff - seconds;
```

This is all psuedo code but should give you a place to start.

**Comment by HowardHinnant** [comment]
@Erroneous1 makes some very good comments, which I'll try not to repeat.  I just want to add a little more.

To emphasize, you do not have a single `futureTime`.  You have one per each `time_zone`.  Once you decide on a `time_zone`, I advise computing the `futureTime` in that `time_zone`, and then converting it to UTC and do the time difference in UTC.  This algorithm will count "physical seconds" (well neglecting leap seconds which aren't predictable into the future).  If you instead do the difference in `local_time`, then your countdown will experience discontinuities as you count down over daylight saving boundaries.

**Comment by eulphean** [comment]
Thanks @HowardHinnant & @Erroneous1 for your quick feedback. My countdown timer with multiple timezones is working smoothly now.

**Comment by eulphean** [comment]
🙏 🙏 🙏

Thanks for the example!
