### ISSUE TITLE
AM/PM parsing issue.

### ISSUE THREAD

**Issue by p-groarke** [HowardHinnant/date#365]
Using master branch, MSVC in c++17 mode.

I am trying to parse a date in the following format `05/28/2018 07:00:00 PM`.
The parsing works, except for the `%p` portion. Here is a quick example.
```
	const char* parse_me = "05/28/2018 07:00:00 PM";
	const char* date_format = "%m/%d/%Y %T %p";

	std::istringstream iss{ parse_me };
	date::sys_seconds s;
	iss >> date::parse(date_format, s);

	printf("parse result : %s\n", date::format(date_format, s).c_str());
```
The output is,
```
parse result : 05/28/2018 07:00:00 AM
```
Any idea what could cause this? I tried lower case `pm` but that didn't do the trick. Thank you.

**Comment by p-groarke** [comment]
It seems the AM/PM designations must be concatenated with `%T`. Parsing the following works `05/28/2018 07:00:00PM`. Is there any reason why this is so? It would be nice to support arbitrary positions of `%p`.

You may close this.

**Comment by HowardHinnant** [comment]
The problem is that `%T` is equivalent to `%H:%M:%S` and `%H` is the 24-hour format.   If you replace `%T` with `%I:%M:%S`, you will get the desired result.

**Comment by p-groarke** [comment]
Works like a charm :) Thank you!
