### ISSUE TITLE
Provide the database as an input stream

### ISSUE THREAD

**Issue by kivadiu** [HowardHinnant/date#368]
I would like to embed the database into my program at compile time. If I cat all required files and remove all comments, its only 156 kb which can be less than 25 kb when compressed.
```
#!/bin/bash
(
  for f in africa antarctica asia australasia backward etcetera europe pacificnew northamerica southamerica systemv leapseconds; do
    cat $f
  done
) | grep -v "^#.*" | grep -v "^$"
```

For this to work, I would need an option to load the database from a `std::istream`.

What do you think of that? I am ready to make a PR if you give me some ideas of what's the best to modify.

Regards

**Comment by HowardHinnant** [comment]
Your requirement is a bit ambiguous:  `std::istream` can't be used at compile-time.  You can only use it to load data at run-time.

But I get that you would like an alternative tzdb.  You can get part way there just by using the uncompressed-but-comment-free form as your database.  Just do that part and point INSTALL toward wherever you put it, and you're good to go, except you'll need the version file too (just a few more bytes).

To go further than that, you might look at the possibility of providing a user-defined custom database.  If you look at [Custom time zone](https://howardhinnant.github.io/date/tz.html#Examples), there is a tiny example of how to insert your own timezone into this library.

(Here)[https://github.com/HowardHinnant/date/blob/master/include/date/ptz.h] is a much more complex example that models the complete POSIX timezone spec.  Neither of these does exactly what you want.  However they do demonstrate that one can do a great deal of customization in this area.

**Comment by kivadiu** [comment]
I expressed my-self badly. What I meant by compile-time was that I could include the whole database in a binary array. And then at runtime, I can read it with std::istream. What I would like is no file at all, everything in the binary.

**Comment by HowardHinnant** [comment]
Another option that is already available is compiling with  `-DUSE_OS_TZDB`.  With this option the "zic-compiled" form of the tzdb is read from the files.  On non-Windows platforms, the OS typically supplies this for you, though there is nothing stopping you from compiling your own and using it.

In this form, the data is a binary-formatted list of transition points for each time zone.  It typically loads more quickly.  On macOS, the Apple-supplied files take up about 94Kb on disk.  I'm not sure of the size on linux systems.

You can learn more about using the zic compiler at https://www.iana.org/time-zones

At this time I am not prepared to support a 3rd format for the tzdb.
