### ISSUE TITLE
GCC 5.3.1 (Linux x86_64) -pedantic-errors  breaks: error: ISO C++ does not support '__int128' for 'type name'

### ISSUE THREAD

**Issue by galik** [HowardHinnant/date#37]
Simply including the header produces the error when compiling with `-pedantic-errors` flag:
```cpp
#include "date/date.h"

int main()
{

}
```

> 
> g++ -std=c++14 -pedantic-errors -Wall -Wextra -Wfatal-errors     -O0 -g3 -D DEBUG -o bin/testcpp src/testcpp.cpp 
> In file included from src/testcpp.cpp:1:0:
> src/date/date.h:821:26: error: ISO C++ does not support '__int128' for 'type name' [-Wpedantic]
>                           __int128
>                           ^
> compilation terminated due to -Wfatal-errors.
> 

If I remove the `-pedantic-errors` flag it compiles

**Comment by HowardHinnant** [comment]
Thanks for the report.  I'm not seeing a similar symptom with clang.

I don't have a gcc environment to experiment with.  Would you like to create a patch using `#pragma GCC diagnostic push`/`pop` tools wrapped around this piece of code?  Here are the docs:

https://gcc.gnu.org/onlinedocs/gcc/Diagnostic-Pragmas.html

If you would rather not, that's fine.  I can work on this too.  But I am encouraging public participation in maintaining and improving this library, and this sounds like a good improvement to me.

**Comment by galik** [comment]
Sure I just added a PR.

**Comment by HowardHinnant** [comment]
Sweet, thanks.  Looks pretty good to me.  I'm going to let it mellow just for a little while to give others a chance to look at it.

**Comment by HowardHinnant** [comment]
Merged.
