### ISSUE TITLE
7 tests failed out of 66 on MSVC 2017

### ISSUE THREAD

**Issue by DmitriiKrasilnikov** [HowardHinnant/date#370]
Hello! I started using the date library and after building and running the tests I found that some tests failed. Here is a list of tests that failed with a detailed description of the errors:

``` 89% tests passed, 7 tests failed out of 66

  Total Test time (real) =  63.15 sec

  The following tests FAILED:
         15 - date_test_pass_range_test (Failed)
         35 - date_test_pass_parse_test (Failed)
         47 - date_test_pass_year_month_test (Failed)
         48 - date_test_pass_year_month_day_test (Failed)
         49 - date_test_pass_year_month_day_last_test (Failed)
         50 - date_test_pass_year_month_weekday_test (Failed)
         51 - date_test_pass_year_month_weekday_last_test (Failed)
```

1.  **test\date_test\format\range.pass.cpp**
<img width="803" alt="screen shot 2018-08-07 at 10 56 33" src="https://user-images.githubusercontent.com/42147841/43764111-2f14eb3a-9a35-11e8-8bbd-cf2bf40ab9a7.png">

2. **test\date_test\parse.pass.cpp**
<img width="837" alt="screen shot 2018-08-07 at 10 57 25" src="https://user-images.githubusercontent.com/42147841/43764140-4dc6f532-9a35-11e8-804f-19fc743e88e2.png">

3. **test\date_test\year_month.pass.cpp**
<img width="747" alt="screen shot 2018-08-07 at 10 44 42" src="https://user-images.githubusercontent.com/42147841/43764190-72a3346a-9a35-11e8-92be-f3866507423b.png">

4. **test\date_test\year_month_day.pass.cpp**
<img width="735" alt="screen shot 2018-08-07 at 10 48 33" src="https://user-images.githubusercontent.com/42147841/43764211-85e852d0-9a35-11e8-9fe0-cded367434eb.png">

5. test\date_test\year_month_day_last.pass.cpp
<img width="733" alt="screen shot 2018-08-07 at 10 49 50" src="https://user-images.githubusercontent.com/42147841/43764227-983cb1ce-9a35-11e8-9644-f8ecd76d6ee6.png">

6. **test\date_test\year_month_weekday.pass.cpp**
<img width="733" alt="screen shot 2018-08-07 at 10 49 50" src="https://user-images.githubusercontent.com/42147841/43764243-a71d2336-9a35-11e8-80be-6e2cae79507b.png">

7. **test\date_test\year_month_weekday_last.pass.cpp**
<img width="832" alt="screen shot 2018-08-07 at 10 54 11" src="https://user-images.githubusercontent.com/42147841/43764283-be3c20bc-9a35-11e8-880a-3a0814e084eb.png">

**Environment:**
OS Windows 10 running under the virtual machine Parallels Desktop:
<img width="1097" alt="screen shot 2018-08-07 at 11 40 00" src="https://user-images.githubusercontent.com/42147841/43764646-aa109450-9a36-11e8-9642-d0206f35f562.png">

**Host system:** 
MacBook Pro (Retina, 15-inch, Mid 2015) with MacOS Sierra 10.12.6:
<img width="589" alt="screen shot 2018-08-07 at 11 37 01" src="https://user-images.githubusercontent.com/42147841/43764504-435f2c6c-9a36-11e8-964f-01268ffd9114.png">

**Comment by kivadiu** [comment]
Just tested on linux x86_64 with g++ 8.1 and the latest commit 6b51ca8271741f0530b08fe742e94a4de6a76e78.
Only one test fails:
./date_test_pass_parse_bin 
date_test_pass_parse_bin: /home/fred/Devel/Git/PR/date/test/date_test/parse.pass.cpp:48: void test_a(): Assertion `!in.fail()' failed.
Aborted (core dumped)

**Comment by HowardHinnant** [comment]
I believe this is a bug in the gcc libstdc++ `time_get` facet.  One can use `-DONLY_C_LOCALE=1` to work around it.

**Comment by kivadiu** [comment]
> I believe this is a bug in the gcc libstdc++ `time_get` facet. One can use `-DONLY_C_LOCALE=1` to work around it.

I just tried to run the tests with LC_ALL=en_US.UTF-8 but I still get the same issue.

**Comment by HowardHinnant** [comment]
That's because LC_ALL=en_US.UTF-8 does not avoid the bug in gcc's std::lib.

**Comment by kivadiu** [comment]
> That's because `LC_ALL=en_US.UTF-8` does not avoid the bug in gcc's std::lib.

OK, then where should we add `-DONLY_C_LOCALE=1`? Should it be only for g++?

**Comment by kivadiu** [comment]
OK, thanks. It just makes it difficult when submitting a PR to know if all tests pass. But I guess you can test on your side with another compiler.

**Comment by kivadiu** [comment]
I confirm that:
- the tests pass with clang 6.0
- the tests pass with g++ 8.1.0 and -DONLY_C_LOCALE=1
