### ISSUE TITLE
How to get local years/months/days from a local_time object

### ISSUE THREAD

**Issue by NeroBurner** [HowardHinnant/date#371]
I'm trying to use tz.h to fix a bug in ViewTouch https://github.com/ViewTouch/viewtouch/issues/52

There I have a year in localtime and an offset in seconds from the local year. I got to the point where I can create a `local_time<seconds>` object from those two data points.

```cpp
    int saved_years= 2017;
    int saved_seconds = 2678400; // 1 month
    local_time<seconds> t1 = local_time<days>{date::year(saved_years) / January / 1} + std::chrono::seconds(saved_seconds);
```

How do I get the local years and the offset in seconds back? I did not see anything to get the local year.

I would do something like the following, but the `t1.years()` won't work and I haven't found another way
```cpp
    int restored_years = t1.years();
    auto t0 = local_time<days>{date::year(restored_years) / January / 1};
    int restored_seconds = duration_cast<seconds>(t1 - t0).count();
```

**Comment by HowardHinnant** [comment]
Here's how.  It's a little different than other date libs:
```c++
#include "date/tz.h"
#include <iostream>

int
main()
{
    using namespace date;
    int saved_years= 2017;
    int saved_seconds = 2678400; // 1 month
    auto t1 = local_days{year(saved_years) / January / 1} + std::chrono::seconds{saved_seconds};

    // Get local fields back from t1
    auto ld = floor<days>(t1);                  // local_days == local_time<days>
    year_month_day ymd{ld};                     // year_month_day has year, month and day fields
    auto y = ymd.year();                        // 2017
    std::cout << "y = " << y << '\n';           // y = 2017
    auto s = t1 - local_days{y / January / 1};  // seconds{2678400}
    std::cout << "s = " << s << '\n';           // s = 2678400s
}
```
Basically it is all about converting between chronological types (`chrono::time_point`s) and calendrical types (e.g. `year_month_day`).  You can convert between day-precision time_points and `year_month_day` to get access to the year, month and day fields.  And you can subtract day-precision time_points from seconds-precision time_points to recover an offset in seconds.

**Comment by NeroBurner** [comment]
thanks for the fast and detailed answer :+1:
