### ISSUE TITLE
How to convert year_month_day to sys_days?

### ISSUE THREAD

**Issue by juandent** [HowardHinnant/date#375]
Please help me here - I haven't been able convert year_month_day to sys_days. I recall sys_days was represented by an integer and that's what I need to store in a database.

Thanks,
Juan

**Comment by HowardHinnant** [comment]
```
sys_days sd = ymd;  // ymd has type year_month_day
```
If that's not working can you show an example program?

**Comment by juandent** [comment]
For purposes of storing a sys_days in a database (like in the form of an integer) what methods can I use for this?

Thanks,
Juan

**Comment by HowardHinnant** [comment]
`date::sys_days` is a typedef for the `std::chrono` type: `time_point<system_clock, duration<int, ratio<86400>>>`.  So you can say:  `sd.time_since_epoch().count()` and that gives you an integer that is the count of days since 1970-01-01.

**Comment by juandent** [comment]
great! and if I want to use another epoch?

**Comment by HowardHinnant** [comment]
I recommend creating one clock per epoch, following the design in tz.h.
