### ISSUE TITLE
get weekday index from weekday

### ISSUE THREAD

**Issue by NeroBurner** [HowardHinnant/date#378]
I'm trying to replicate the "days since Sunday" behaviour as defined by ctime for wday [1] with date.h

In the C++20 draft for `std::chrono::weekday` the unsigned operator is defined [2]. With it it should be possible to get the stored index of the weekday object
```cpp
date::local_time<std::chrono::seconds> t_;
date::weekday wd{date::floor<date::days>(t_)};
unsigned wd_idx = static_cast<unsigned>(wd);
return static_cast<int>(wd_idx);
```

In the date.h library this function is currently missing. I have not found a way to get the stored integer in range of 0 to 6 to represent the days elapsed since Sunday

Is there another way to implement this? If not is a PR implementing this function in date.h welcome?

[1] http://www.cplusplus.com/reference/ctime/tm/
[2] https://en.cppreference.com/w/cpp/chrono/weekday/operator_unsigned

edit: hacky workaround
```cpp
    if (wd == date::Sunday)
    {
        return 0;
    } else if (wd == date::Monday)
    {
        return 1;
    } else if (wd == date::Tuesday)
    {
        return 2;
    } else if (wd == date::Wednesday)
    {
        return 3;
    } else if (wd == date::Thursday)
    {
        return 4;
    } else if (wd == date::Friday)
    {
        return 5;
    } else if (wd == date::Saturday)
    {
        return 6;
    } else
    {
        assert(false);
    }
```

**Comment by HowardHinnant** [comment]
Hi @NeroBurner,

The current date.h is an experiment that clients have asked me to run in preparation to recommend changes for the C++20 draft.  I'm about ready to abandon those changes, but that won't come without a fight.

The way to emulate `unsignd{wd}` in the current date.h is:

```c++
return (wd - Sunday).count();
```

The motivation for the current date.h is that a significant group of people are very upset that `Sunday` is considered to be the first day of the week in the [0, 6] mapping system, as opposed to the ISO mapping of [1, 7] -> [Monday, Sunday].  So the current date.h hides the underlying mapping by accepting both mappings in `weekday`'s constructor, and removing the conversion from `weekday` to `unsigned`.

The downside of this is that the conversion is now both unintuitive, and carries a performance penalty.

I would value any further comment you might have on this subject.

**Comment by HowardHinnant** [comment]
Additional information.  The performance penalty isn't huge.  But it is significant.

Here's the optimized assembly to support returning `unsigned{wd}` directly:

```
	movzbl	%dil, %eax
```

And here is what it takes to return `(wd - Sunday).count();`

```
	movzbl	%dil, %ecx
	imull	$37, %ecx, %edx
	shrl	$8, %edx
	movl	%ecx, %eax
	subb	%dl, %al
	shrb	%al
	addb	%dl, %al
	shrb	$2, %al
	movb	$7, %dl
	mulb	%dl
	subb	%al, %cl
	movzbl	%cl, %eax
```

The latter doesn't add any branches or memory cache hits, but it does add a significant percentage increase in cpu cycles.  One would never notice it in the occasional conversion from `weekday` to `unsigned`, but it could potentially become significant in an application which did a lot of `weekday` to `unsigned` conversions within a context of little other work.  The latter leaves room for a lower level abstraction which is a fundamental design flaw (imho).

**Comment by NeroBurner** [comment]
I'd keep the [0,6] range starting with Sunday. With this std::chrono::weekday can be a direct replacement for tm.wday from `<ctime>`

I agree that the current way in date.h to get the weekday (`(wd - Sunday).count();`) is rather unintuitive. I wasn't able to get to this workaround even after directly reading the header `date.h` with the weekday implementation

**Comment by NeroBurner** [comment]
I spoke with a college of mine and he prefers the workaround `(wd - Sunday).count();`

His reasoning is, that this makes it more explicit on the client side code, no assumption on when the week starts is needed. There is no implementation dependent behavior.

If no `operator unsigned` would be added to date.h and also be removed in the C++20 draft, then I would recommend to document this conversion somewhere as it is not totally obvious (at least for me)

> The latter doesn't add any branches or memory cache hits

Why are there no branches. operator- has a ternary operator. Shouldn't that introduce a branch?
```cpp
days
operator-(const weekday& x, const weekday& y) NOEXCEPT
{
    auto const wdu = x.wd_ - y.wd_;
    auto const wk = (wdu >= 0 ? wdu : wdu-6) / 7;
    return days{wdu - wk * 7};
}
```

as another remark, the operator- function would break if the compiler decided `unsigned - unsigned -> unsigned` instead of `unsigned - unsigned -> int`. By enforcing the unsigned conversion the `wd - sunday` workaround fails
```cpp
    auto const wdu = static_cast<unsigned>(x.wd_ - y.wd_);
```
For reference:
> A prvalue of an integer type other than bool, char16_t, char32_t, or wchar_t whose integer conversion rank (4.13) is less than the rank of int can be converted to a prvalue of type int if int can represent all the values of the source type; otherwise, the source prvalue can be converted to a prvalue of type unsigned
  int.

https://stackoverflow.com/a/48372826

as I understand it **can be** ie. not not always be the case to be `int`

**Comment by HowardHinnant** [comment]
> I spoke with a college of mine ...

lol.  This is one of those issues that is going to split people 50/50.

Maybe named conversions:  One for `c_encoding` and another for `iso_encoding` would solve the performance problem.

> Why are there no branches. operator- has a ternary operator. Shouldn't that introduce a branch?

Because optimizers have gotten smarter than I am, and I'm not _that_ good at reading assembly.  I can tell from the assembly that there is no branch.  The branch is simulated with bit-twiddling, but I'm not sure of the exact algorithm in this case.

> as another remark, the operator- function would break if 

Yeah, this could happen if `sizeof(unsigned char) == sizeof(int)`.  I don't claim to be ported to such a platform, but a std::lib vendor for this lib would definitely have to deal with that should they claim to support it.

Thanks for your feedback.

**Comment by NeroBurner** [comment]
@HowardHinnant I've opened a PR with `c_encoding` and `iso_encoding`, if you decide that these functions would be a good idea :)

> Because optimizers have gotten smarter than I am

Yes, my brain compiler lags far behind current computer based compilers ^^

> Thanks for your feedback.

You're welcome :) and thanks for the awesome date.h (and tz) library!
