### ISSUE TITLE
Tests fail on C++11

### ISSUE THREAD

**Issue by NeroBurner** [HowardHinnant/date#382]
With C++11 enabled some of the tests fail, because of non-constexpr functions
```
/usr/src/app/test/iso_week/year_weeknum_weekday.pass.cpp:101:5: error: non-constant condition for static assertion
     static_assert(x1.year() == 2015_y, "");
```

I found the following tests to be failing, and I suspect a few more
- `target date_test_pass_month_day_bin`
- `date_test_pass_weekday_bin`
- `iso_week_pass_op_div_survey_bin`
- `iso_week_pass_weekday_bin`

Failing builds can be seen here:
- gcc C++11: https://travis-ci.org/NeroBurner/date/jobs/424083247
- clang C++11: https://travis-ci.org/NeroBurner/date/jobs/424083250

For reference builds with C++14 (with string_view disabled) are compiling:
- gcc C++14: https://travis-ci.org/NeroBurner/date/jobs/424083248
- clang C++14: https://travis-ci.org/NeroBurner/date/jobs/424083251

The results are with https://github.com/HowardHinnant/date/pull/379 applied, otherwise C++17 always was enabled for me

**Comment by HowardHinnant** [comment]
The library is designed to fail gracefully as compilers and standards lack functionality.  However the tests are designed to highlight, not hide these failures.

**Comment by NeroBurner** [comment]
we could add a property to the tests, that they are expected to fail in C++11 context

https://stackoverflow.com/questions/30155619/expected-build-failure-tests-in-cmake#30191576
