### ISSUE TITLE
VS2017 - C++17 - Compilation failure

### ISSUE THREAD

**Issue by igiagkiozis** [HowardHinnant/date#383]
Hi, 

When compiling with VS2017 using the C++17 standard compilation of the date.h file fails. This has to do with the min and max macros being already defined and then the compiler gets confused when it sees the '.. year min()/max() ..' functions. My solution is to use the (almost standard) sequence
```
#ifdef WIN32
#define NOMINMAX
#undef min
#undef max
#endif
```
After that all works as expected. If anyone is aware of a more elegant or practical solution I'd love to hear it.

**Comment by beached** [comment]
The nefarious part is that because it is a macro it invades my namespaces.  And I forget about it before I run into it again.

**Comment by HowardHinnant** [comment]
Yeah.  MS has been dealing with this issue for decades.  I would've bet they would've been voted out of business a long time ago on this one issue alone.  But <sigh> that explains why they're rich and I'm not... ;-)

**Comment by igiagkiozis** [comment]
Well, if its of any consolation date.h et al. are used quite a bit in finance; so your creations are 'in the money' ;)
