### ISSUE TITLE
Relative time format

### ISSUE THREAD

**Issue by dkourilov** [HowardHinnant/date#384]
Hi,

I am trying to parse app-specific relative date format with this library.
The format is `%j+%H:%M:%S`, which I want to parse to seconds.
First part (`%j`) is a day, relative to, say, beginning of epoch, and next (`%H:%M:%S`) is time.

I was expecting that following code will produce correct results:
```
    using namespace std::chrono;
    using namespace date;
    std::istringstream stream{"1+01:02:03"};
    seconds t;
    stream >> parse("%j+%H:%M:%S", t);

    assert(!stream.fail());
    assert(!stream.bad());
    assert(t == days{1} + hours{1} + minutes{2} + seconds{3});
``` 

However, very last assert fails. Hope I am missing something.

**Comment by dkourilov** [comment]
Also, if I omit last assert, and try to output parsed `std::chrono::seconds` with default formatter, it will be converted to `3723s`, which basically tells me that `%j` was silently ignored along the way.

The behaviour is not good at all. Invalid (unprocessable) format specified from library's point of view should be reported, at least as an exception.

**Comment by dkourilov** [comment]
Thank you Howard - this syntax wasn't obvious from the docs. Probably I must have been investing more time into it. Hopefully it will become more fool-proof in future to avoid misunderstandings like I had.

P.S. For you list of projects using the library - we're actively using it at https://routinghub.com in our VRP (Vehicle Routing Problem) API. We parse user's time zone info as well as delivery time windows in different formats, and I personally as well as our dev team found your development much more usable than G's cctz library which we discarded some time ago. 

We've just started to implement relative time format, as it's handy for certain use cases, hence the question. Once again thanks for returning to us so quickly.

**Comment by HowardHinnant** [comment]
Oh, cool!  Just added you guys to the README.

Keep the feedback coming.  Maybe there's a way to improve the behavior for this particular issue.  I'm not sure, but will keep thinking about it.  Or maybe it just needs improved documentation.

**Comment by dkourilov** [comment]
Another point to mention, a `parse` call with usual `%H:%M:%S` format will happily accept `10:00` as a valid value. While it is possible to check input stream consumed bytes via `tellg` and compare it with input length, it's also not obvious at all. An obvious would be a return status indicator, telling that parsing of defined format failed (`:%S` missed in the example above).

**Comment by HowardHinnant** [comment]
For me:

```
    #include "date/date.h"
    #include <cassert>
    #include <iostream>
    #include <sstream>

    int
    main()
    {
        using namespace date;
        using namespace std;
        using namespace std::chrono;
        std::istringstream stream{"10:00"};
        seconds t;
        stream >> parse("%H:%M:%S", t);

        assert(!stream.fail());
        assert(!stream.bad());
        cout << t << '\n';
    }
```

The output is:

```
Assertion failed: (!stream.fail()), function main, file test.cpp, line 16.
```

**Comment by dkourilov** [comment]
Sorry Howard, my fault. Our own incorrectly written test lead me to this conclusion. Thank you for explaining it.

**Comment by HowardHinnant** [comment]
I forgot to comment on this issue that I made '%j' work with durations with this commit: https://github.com/HowardHinnant/date/commit/591f572b670d27311361b9b6b933cbcfced55560 (both formatting and parsing).
