### ISSUE TITLE
with gcc 8.2.0 parse.pass.cpp fails at line 48

### ISSUE THREAD

**Issue by binnacle** [HowardHinnant/date#388]
FYI

```
date_test_pass_parse_bin: /w/gpl/cpp20-date-20180915/test/date_test/parse.pass.cpp:48: void test_a(): Assertion `!in.fail()' failed.

  {
    // correct abbreviation
    std::istringstream in{"Sun 2016-12-11"};
    sys_days tp;
    in >> parse("%A %F", tp);
    assert(!in.fail());   # throws here
    assert(!in.bad());
    assert(!in.eof());
    assert(tp == 2016_y/12/11);
  }
```

gcc 8.2.0 along with prerequisites built on old distro, should not matter but if not reproducible contact me as needed for details

Thank you for your great contribution!

**Comment by HowardHinnant** [comment]
Here are the gcc bug reports that cause this failure:

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=78714
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=86967
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=71557

They can be worked around in date.h if you are ok with being limited to the "C" locale by compiling date.h with `-DONLY_C_LOCALE=1`.  This flag circumvents use of the std::time_get` facet and rolls its own in date.h.

This is a common enough report that I should probably include this information in comments in parse.pass.cpp.

**Comment by binnacle** [comment]
Thank you for the workaround, though I'm a new user and have not yet reached a need for the impacted parse() behavior.  Searched here but missed closed tickets, thought perhaps it was a problem related to the target system libraries or a gcc 8.2 regression.

A comment in either the unit test or the script would help save others trouble going forward, perhaps hold this ticket open till one is in place.

Congratulations on date.h being voted into ++20, really like using it!

**Comment by Tachi107** [comment]
This workaround shouldn't be needed when using GCC 12 or later, since the three libstdc++ bugs got fixed in that version.

But trying to run the tests, some of them still fail, namely `test_c`, `test_Ip` and `test_p`.

Is this a bug in date's `%c` and `%p` handling, or is libstdc++ still buggy?

**Comment by Tachi107** [comment]
It seems that for the `%c` test, if I use a `tp` variable of type `std::chrono::seconds` instead of `sys_seconds`, the parsing completes successfully

**Comment by Tachi107** [comment]
For the record, the `%c` test also fails when using C++20's `std::chrono::parse()`

**Comment by HowardHinnant** [comment]
Jonathan Wakely just found and fixed this one.  See the comments under https://stackoverflow.com/a/79015753/576911.

**Comment by Tachi107** [comment]
What a coincidence! Nice to know this is mostly fixed, and will be
completely fixed soon. Thanks for letting me know.

Are you aware of whether this will fix the %p issue as well?

**Comment by HowardHinnant** [comment]
Looks like it is fixed in gcc-14: https://gcc.godbolt.org/z/c1fzb16zz

**Comment by Tachi107** [comment]
Yeah, it is fixed when using std::chrono::parse, but not with date::parse.

    $ cat main.cpp
    #include <cassert>
    #include <chrono>
    #include <iostream>
    #include <sstream>
    #include <date.h>

    int main() {
        using std::chrono::hours;
        using std::chrono::minutes;
        using std::chrono::seconds;
        using date::sys_time;
        using date::sys_days;
        using date::parse;
        using namespace date::literals;

        {
            std::istringstream in{"2016-12-11 11pm"};
            sys_time<hours> tp;
            in >> parse("%F %I%p", tp);
            assert(!in.fail());
            assert(!in.bad());
            assert(tp == sys_days{2016_y/12/11} + hours{23});
        }
        {
            std::istringstream in{"1986-12-01 01:01:01 pm"};
            sys_time<seconds> tp;
            in >> parse("%Y-%m-%d %I:%M:%S %p", tp);
            assert(!in.fail());
            assert(!in.bad());
            assert(tp == sys_days{1986_y/12/01} + hours{13} + minutes{01} + seconds{01});
        }
        {
            std::istringstream in{"1986-12-01 01:01:01"};
            sys_time<seconds> tp;
            in >> parse("%Y-%m-%d %I:%M:%S", tp);
            // The test will fail because %I needs the %p option to shows if it is AM or PM
            assert(in.fail());
    	}
    }

    $ g++ -std=c++17 -Iinclude/date main.cpp && ./a.out
    a.out: main.cpp:24: void test_p(): Assertion `tp == sys_days{2016_y/12/11} + hours{23}' failed.
    [1]    2184 IOT instruction  ./a.out

**Comment by Tachi107** [comment]
Here's a compiler-explorer link: <https://gcc.godbolt.org/z/1noWPMYYa>

**Comment by HowardHinnant** [comment]
Workaround:  Compile with `-DONLY_C_LOCALE`, demo: https://gcc.godbolt.org/z/h111YTj9a.  The downside is that only the "C" locale will be available to the date lib.

**Comment by Tachi107** [comment]
I'm of course aware of that :)

The point was that I'd like to build *without* only the C locale now that the libstdc++ are fixed, and '%p' is the only blocker.

Since '%p' works with std::chrono::parse but not date::parse, it looks to me that this is a bug in the date library.

**Comment by HowardHinnant** [comment]
Here's the code: https://github.com/HowardHinnant/date/blob/master/include/date/date.h#L7181-L7191. It forwards the parse to the `std::time_get` facet, checking both `tm_hour` and the stream error state for results.  I'm open to suggestions.
