### ISSUE TITLE
test/testit fails under GCC 

### ISSUE THREAD

**Issue by galik** [HowardHinnant/date#39]
When running `CXX=g++ ./testit` getting many errors because GCC doesn't like the brace syntax for casting primitive types.

``` cpp
unsigned{w}; // fails to compile
```

Changing to parenthesis syntax solves this.

``` cpp
unsigned(w); // compiles fine
```

Additionally there was one failure because `class year` does not declare one of its decrement operators `constexpr` .

This is solved by making it `CONSTCD14 year& operator--()    NOEXCEPT;`

But I assume more than just that operator should be made `CONSTCD14`?

**Comment by HowardHinnant** [comment]
Which version of gcc?  And which `year` test?

**Comment by galik** [comment]
Sorry I meant to include that information, here is the end of the log after removing the compiler errors:

    /home/galik/dev/date/test/tz_test/zone.pass.cpp failed to compile
    Compile line was: g++ -std=c++14 -I/home/galik/dev/date -Wall zone.pass.cpp
    failed 1 tests in /home/galik/dev/date/test/tz_test
    ****************************************************
    Results for /home/galik/dev/date/test:
    using g++ (GCC) 5.3.1 20151207 (Red Hat 5.3.1-2)
    Copyright (C) 2015 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    with -std=c++14  -I/home/galik/dev/date -Wall  
    ----------------------------------------------------
    sections without tests   : 0
    sections with failures   : 2
    sections without failures: 2
                           +   ----
    total number of sections : 4
    ----------------------------------------------------
    number of tests failed   : 12
    number of tests passed   : 69
                           +   ----
    total number of tests    : 81
    ****************************************************

**Comment by galik** [comment]
It would appear that it is when the operator is mrked `explicit` that `GCC` has a problem with braces.
```cpp
struct A
{
	operator unsigned() const { return 1U; }
};

struct ExplicitA
{
	explicit operator unsigned() const { return 1U; }
};

int main()
{
	A a;
	ExplicitA explicit_a;

	auto u1 = unsigned(a); // okay
	auto u2 = unsigned{a}; // okay

	auto explicit_u1 = unsigned(explicit_a); // okay
	// auto explicit_u2 = unsigned{explicit_a}; // fail

	std::cout << "u1: " << u1 << '\n';
	std::cout << "u2: " << u2 << '\n';
	std::cout << "explicit_u1: " << explicit_u1 << '\n';
//	std::cout << "explicit_u2: " << explicit_u2 << '\n';
}
```

**Comment by HowardHinnant** [comment]
I'm seeing that as well.  I would prefer to keep the braces.  The tests are also there to demonstrate preferred syntax.  But perhaps this will do:

http://melpon.org/wandbox/permlink/xvZwDT1oiDLtjbGN

**Comment by HowardHinnant** [comment]
On the other hand, a bug report into gcc might also be in order here...

**Comment by HowardHinnant** [comment]
No need, found it: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=63999

**Comment by HowardHinnant** [comment]
Are you only seeing the `unsigned{a}` error under iso_week?  If not, can you point to a specific test?

**Comment by galik** [comment]
I had to make many changes to make the error go away. But appears to be `iso_week` and `tz_test` that have the issue.

From the log file:

    grep 'failed to compile' testit.log 
    /home/galik/dev/date/test/iso_week/last.pass.cpp failed to compile
    /home/galik/dev/date/test/iso_week/lastweek_weekday.pass.cpp failed to compile
    /home/galik/dev/date/test/iso_week/op_div_survey.pass.cpp failed to compile
    /home/galik/dev/date/test/iso_week/weekday.pass.cpp failed to compile
    /home/galik/dev/date/test/iso_week/weeknum.pass.cpp failed to compile
    /home/galik/dev/date/test/iso_week/weeknum_weekday.pass.cpp failed to compile
    /home/galik/dev/date/test/iso_week/year_lastweek.pass.cpp failed to compile
    /home/galik/dev/date/test/iso_week/year_lastweek_weekday.pass.cpp failed to compile
    /home/galik/dev/date/test/iso_week/year.pass.cpp failed to compile
    /home/galik/dev/date/test/iso_week/year_weeknum.pass.cpp failed to compile
    /home/galik/dev/date/test/iso_week/year_weeknum_weekday.pass.cpp failed to compile
    /home/galik/dev/date/test/tz_test/zone.pass.cpp failed to compile

**Comment by galik** [comment]
Of course tests that were designed to fail through other means may have this problem hiding and masking real bugs.

**Comment by galik** [comment]
Addendum: Please ignore the `tz_test` in the above list that filed for a different reason.

In fact that test fails for `clang++ v3.7.0` also:

    ./testit
    passed 1 tests in /home/galik/dev/date/test
    passed 63 tests in /home/galik/dev/date/test/date_test
    passed 16 tests in /home/galik/dev/date/test/iso_week
    zone.pass.cpp:14:5: error: static_assert failed ""
        static_assert( is_nothrow_move_assignable<Zone>{}, "");
        ^              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    /home/galik/dev/date/test/tz_test/zone.pass.cpp failed to compile
    Compile line was: clang++ -std=c++14 -I/home/galik/dev/date -Wall zone.pass.cpp
    failed 1 tests in /home/galik/dev/date/test/tz_test
    ****************************************************
    Results for /home/galik/dev/date/test:
    using clang version 3.7.0 (tags/RELEASE_370/final)
    Target: x86_64-redhat-linux-gnu
    Thread model: posix
    with -std=c++14  -I/home/galik/dev/date -Wall  
    ----------------------------------------------------
    sections without tests   : 0
    sections with failures   : 1
    sections without failures: 3
                           +   ----
    total number of sections : 4
    ----------------------------------------------------
    number of tests failed   : 1
    number of tests passed   : 80
                           +   ----
    total number of tests    : 81
    ****************************************************

**Comment by HowardHinnant** [comment]
The `is_nothrow_move_assignable<Zone>{}` test will start passing in gcc-6.  It is failing because libstdc++'s `std::string` move assignment operator is not noexcept.  Your clang is using gcc's libstdc++ std::lib.

http://howardhinnant.github.io/container_summary.html

This could be fixed by manually defining the `Zone` move assignment operator (as is already done for VS-2013) *and* marking these manual members `noexcept`.

**Comment by HowardHinnant** [comment]
Closing.  It is now the policy of this project to not fix the test suite for bugs in the compiler or std::lib implementation.  However the library itself will be backported to older compilers and libraries when practical.  The failing date::tests serve as a reminder as what doesn't work on the older platforms.
