### ISSUE TITLE
suggestion:  include hash function for date::year_month_day etc.

### ISSUE THREAD

**Issue by binnacle** [HowardHinnant/date#390]
No default hash function appears to exist for date::year_month_day and I was unable to quickly create a std::unordered_set or std::unordered_map container with such objects as the key.  Actually gave up and applied a RB-tree std::set since it made no difference for the situation at hand.

Searched web and code and could not find discussion or implementation regarding default hash functions and am so opening this ticket in case it is helpful.

**Comment by kivadiu** [comment]
You are lucky because Howard Hinnant is a specialist of hashing. Have you looked at his excellent idea presented [here](https://www.youtube.com/watch?v=Njjp_MJsgt8)?
OK, this will not help you for your immediately...

**Comment by binnacle** [comment]
I was thinking more in terms of the 2a standards track feature set.  If the requirement was O(1)-or-so performance I could write a hash function in an hour or two (crafting one with a decent probability distribution requires some thought), but this was not the case.  A rational approach is to select hash containers when strong ordering is not needed, which is why a set of default hashers could be a nice addition.

**Comment by binnacle** [comment]
Allow me to add that calendar support is my favorite ++20 feature.  I do not write template libraries so constraints and concepts are for me abstract.  Date manipulation is part of my daily workflow and having high quality support a pleasure.  Olson's and Eggert's code is great (have used it gratefully for years), but the interface unwieldy.

**Comment by HowardHinnant** [comment]
I wish I could give you a high quality and convenient answer.  Unfortunately I can't.  The best I can say is that you can get 3 integral values out of `year_month_day`, and you should use those to form your hash for `year_month_day`.  For example you might use `boost::hash_combine` to mix them.  I'm not a fan of this approach.  But what I recommend requires a considerable amount of infrastructure:

https://github.com/HowardHinnant/hash_append

Conceptually this is easy if you have a hash algorithm that has "updating functionality":  I.e., a hash algorithm composed of 3 phases:

1.  Initialize the hash (possibly with a seed).
2.  Update the hash with bytes.  This can be done with multiple calls to feed different arrays of bytes to the algorithm.
3.  Finalize the algorithm to obtain the hash.

Most modern hash algorithms have these three phases.  But `std::hash` isn't set up to make it easy for you to take advantage of modern hash algorithms.  My `hash_append` library provides an infrastructure to adopt most any modern (3 phase) hashing algorithm, and wrap it up in a functor you can give to the unordered containers.  It even makes it easy to switch which modern hashing algorithm you're using.

It has been adopted by several libraries (e.g. Bloomberg's BDE).  But it has not been adopted by the C++ committee.

**Comment by binnacle** [comment]
Thank you for the suggestions, though I would lean toward normalizing the date components along the lines of concatenating YMD minimum bits or Y\*12\*31+M\*31+D and running it  through GCC std::_Hash_bytes() or std::hash<uint32_t>.

Anyway what I'm attempting to suggest is that since date.h has been accepted for the standard, it might be doable to submit, as a matter of compromise practicality, the addition to \<functional\> std::hash of specializations for the several calendar types such as chrono:::year_month_date.  While perhaps not pretty, a bit of incrementalism there will render combining std::unordered_set or unordered_map with the new calendar types a low-resistance option.

**Comment by HowardHinnant** [comment]
If you go with the normalization route (which is a good idea), instead convert the `year_month_day` to `sys_days` and then get the integral out of that.  `sys_days` _is_ the normalization you're approximating.
```
int i = sys_days{ymd}.time_since_epoch().count();
// now hash i
```

**Comment by binnacle** [comment]
Thank you, will take your advice when my moment arrives to write a std::hash\<std::year_month_day\>.

But to my point. . .It is an exciting achievement for your fine work to have achieved the level of success it has.  I encourage you to consider drafting a standards proposal for the aforementioned hash functions (or nudging someone you know who is well positioned to do so).  Thus the new \<chrono\> calendar feature will be all the more useful.  No need to reply, but please consider it.  Thank you again, I really like it!
