### ISSUE TITLE
weekday cannot be converted to unsigned int

### ISSUE THREAD

**Issue by mjwach** [HowardHinnant/date#391]
At https://howardhinnant.github.io/date/date.html#weekday I see "weekday has explicit conversions to and from unsigned," which seems to indicate that I should be able to do this:

    date::weekday wd(4);
    unsigned int i = static_cast<unsigned int>(wd);

But I cannot.  There appears to be no conversion operator from weekday to any kind of integer.  I see such operators in some other types I'm using (year, month, and day) but not one in weekday.

**Comment by HowardHinnant** [comment]
Yes, sorry about that.  This is an area of active design disagreement among a few people.  There was disagreement as to whether the conversion to unsigned should follow the C/Posix/C++ mapping from `tm`:  [Sun, Sat] -> [0, 6], or the ISO mapping:  [Mon, Sun] -> [1, 7].  So I removed that conversion, but it can be regained by the following formula:

**[Sun, Sat] -> [0, 6]**
```
unsigned u = (wd - Sunday).count();
```

**[Mon, Sun] -> [1, 7]**
```
unsigned u = (wd - Monday).count() + 1;
```

This experiment has not been entirely satisfactory, and I am likely to merge the following PR very soon:  https://github.com/HowardHinnant/date/pull/380 which adds these `weekday` member functions:

```
constexpr unsigned c_encoding() const noexcept;
constexpr unsigned iso_encoding() const noexcept;
```

Sorry for the turmoil.  In the interim I recommend the use of the algorithms above.

**Comment by mjwach** [comment]
Ah okay.  Thank you, that way of doing it is good enough for my little project!

**Comment by HowardHinnant** [comment]
https://github.com/HowardHinnant/date/pull/380 merged.

**Comment by HunterZ** [comment]
Not sure if this will be seen, but the documentation at https://howardhinnant.github.io/date/date.html#weekday does not appear to have been updated to mention `c_encoding()` / `iso_encoding()`, so I too was confused about it mentioning supporting conversion to `unsigned` but not actually documenting any API for accomplishing this.

**Comment by HowardHinnant** [comment]
Thanks!  Fixed: https://github.com/HowardHinnant/date/commit/84b983a15eb497cd67c183f3ae5fc1c8c710e1d7
