### ISSUE TITLE
operator<< badly formats the date when the locale is not C

### ISSUE THREAD

**Issue by kivadiu** [HowardHinnant/date#392]
The `operator<<` badly formats dates when the locale is not the `C` locale.
I see 2 problems:
1. the year is output with thousand separator
2. the thousand separator in the French locale is wrong: it corresponds to the separator in the `ISO 8859-1` not `UTF-8` as required by the locale.

Note that I am on linux using either g++ 8.2.0 or clang++ 6.0.1.

This attached program shows the issue:
[date_to_stream_with_locale.cpp.gz](https://github.com/HowardHinnant/date/files/2387861/date_to_stream_with_locale.cpp.gz)

The output shows on the first line the string and on the second line the string with non ASCII characters as hexadecimal:
```
C:
  2018-06-15
  2  0  1  8  -  0  6  -  1  5 
en_US.UTF-8:
  2,018-06-15 -> this is wrong, we should not have the , in the middle of 2018
  2  ,  0  1  8  -  0  6  -  1  5 
fr_FR.UTF-8:
  2�018-06-15
  2  e2 0  1  8  -  0  6  -  1  5 
```
 -> same issue here + the fact that the separator is `E2` which corresponds to `ISO-8859-1` and not `UTF-8`.

As a conclusion, I think that issue 2 is not really an issue as what we just want is to remove the thousand separator. So issue 1 is really the problem here.

**Comment by lkpcampion** [comment]
same issue on MSVC (2017)

**Comment by HowardHinnant** [comment]
Fixed by https://github.com/HowardHinnant/date/commit/09d90a8b5edb6475542cea67d3d0efd7bf37ee78

Thanks!
