### ISSUE TITLE
No arithmetic operators for month_day

### ISSUE THREAD

**Issue by sibecker** [HowardHinnant/date#396]
The month_day type does not support arithmetic operations such as addition and subtraction, yet they are for the other similar types: year_month_day, year_month, year, month and day.

It seems to me that `month_day operator+(month_day, months)` and `month_day operator+(month_day, days)` are well defined by element-wise addition.  The result may or may not be `ok()` but that doesn't seem to stop me adding 3 months to November or subtracting 8 days from day{2} on the types month and day.

Are these operators deliberately omitted (and if so, why) or just something that slipped through the net?  I can see that defining the difference between two month_day values is problematic - have I missed something else?

**Comment by beached** [comment]
I suspect it was because it doesn’t make sense without a year. For example Feb 27 + 2 days

**Comment by sibecker** [comment]
I don't think that's the reason.  By using element-wise addition `(feb/27) + days{2}` we could get `feb/29` unambiguously.  This seems to me very similar to the way we can add months to a year_month_day value using the same element-wise principle even when it doesn't create correspond to a valid date: `(jan/29/2001) + months{1}` equates to `feb/29/2001`.

**Comment by HowardHinnant** [comment]
This is an excellent question, and I am currently trying to collect the rationale for the various design decisions.  So answering this is definitely helpful to me, and I hope it will be for you as well.

None of the calendrical types support `days` arithmetic except for `day`.  The reason for that is that many clients would expect the arithmetic on the `day` field to impact the value of the `month` and `year` field (if it existed).  This is impossible for `month_day`, and expensive for `year_month_day`.

See https://github.com/HowardHinnant/date/wiki/FAQ#day_arithmetic for more about `day` arithmetic on `year_month_day`.

If you want to do `days` arithmetic just on the `day` field of one of these types, that is still easily and efficiently done, and in such a way that it becomes clear that it only impacts the day field:

```
#include "date/date.h"
#include <iostream>

int
main()
{
    using namespace std;
    using namespace date;
    auto md = September/27;
    md = md.month()/(md.day() + days{2});
    cout << md << '\n';
}
```

This adds 2 days to Sep/27 and outputs Sep/29.

On the question of adding/subtracting `months` to `month_day`.  This was a tougher call, and in the end, I created myself a guideline as to when to add calendrical arithmetic:

>  If the type can be viewed as a "time point", it has calendrical arithmetic, else it does not.  For example `year_month` can be viewed as a time point with months precision.  But `month_day` can not be viewed as a time point because the year is ambiguous.

An exception to this rule is made for single field types such as `month` and `day` as they not only have many obvious use cases, but they are also needed if one wants to do field arithmetic on the components as described above for `month_day` + `days`.

And if really wanted, it can still be done as with `days`:

```
md = (md.month()+months{11})/md.day();
```

The above adds 11 months to a `month_day`.

**Comment by sibecker** [comment]
Thank you, Howard.  Your explanation regarding whether a type is a time point or not is enlightening.
