### ISSUE TITLE
Please add us to the list of projects using this library section in README.md

### ISSUE THREAD

**Issue by gknisely** [HowardHinnant/date#402]
@HowardHinnant Please add [Valhalla](https://github.com/valhalla) (Open Source Routing Library/Service) to the list of projects using your library.  We recently removed boost date_time library in favor of yours and it is working really great.  Thank you so much.

**Comment by HowardHinnant** [comment]
That's great to hear, thanks!  Done: 4b46deb4f981975d628e49916aa21762822812aa
