### ISSUE TITLE
How to get the number of the month instead of "jan"?

### ISSUE THREAD

**Issue by suhasghorp** [HowardHinnant/date#403]
I am trying something like below and do not know how to get the month number using date library.
Thanks.
<pre>
#include "date.h"
#include <iostream>

using namespace date;
using namespace std::chrono;
int main()
{
    year_month_day d1 = 2012_y/jan/10 ;
    
    std::cout << d1.month() << std::endl;
    std::cout << d1.day() << std::endl;
    // is day >= 20
    int i = d1.day() >= 20 ? 1 : 0;
    std::cout << i << std::endl;
    // see https://colinlegg.wordpress.com/2012/06/04/how-to-calculate-the-next-imm-date/ for the below logic
    int new_month = -1 * (int)((-1 * d1.month() - i)/3) * 3 //need month number here    
    year_mont_day next_IMM_date = d1.year()/d1.new_month/20;
    std::cout << next_IMM_date << std::endl;
    
}
</pre>

**Comment by HowardHinnant** [comment]
You can turn a `date::month` into an `unsigned` in the range of `[1, 12]` with:

```
unsigned{d1.month()}
```

Some older compilers won't accept this syntax, but you can use `()` instead:

```
unsigned(d1.month())
```

You can then cast this `unsigned` to an `int`.  Here is your full code with this fix (and a few others):

```
int main()
{
    year_month_day d1 = 2012_y/jan/10 ;
    
    std::cout << d1.month() << std::endl;
    std::cout << d1.day() << std::endl;
    // is day >= 20
    int i = d1.day() >= day{20};
    std::cout << i << std::endl;
    // see https://colinlegg.wordpress.com/2012/06/04/how-to-calculate-the-next-imm-date/ for the below logic
    int new_month = -1 * (int)((-1 * (int)unsigned{d1.month()} - i))/3 * 3; //need month number here    
    year_month_day next_IMM_date = d1.year()/new_month/20;
    std::cout << next_IMM_date << std::endl;
    std::cout << approximate_next_imm(d1) << '\n';
    std::cout << next_imm(d1) << '\n';
}
```

This doesn't get the desired answer for me.  I recommend a much simpler logic that is easy to inspect for correctness:

```
year_month_day
approximate_next_imm(year_month_day d1)
{
    if (d1 < March/20/d1.year())
        return March/20/d1.year();
    if (d1 < June/20/d1.year())
        return June/20/d1.year();
    if (d1 < September/20/d1.year())
        return September/20/d1.year();
    if (d1 < December/20/d1.year())
        return December/20/d1.year();
    return March/20/(d1.year() + years{1});
}
```

One can also easily get the version that targets Wednesdays, instead of the 20th:

```
year_month_day
next_imm(year_month_day d)
{
    sys_days d1 = d;
    sys_days imm = March/Wednesday[3]/d.year();
    if (d1 < imm)
        return imm;
    imm = June/Wednesday[3]/d.year();
    if (d1 < imm)
        return imm;
    imm = September/Wednesday[3]/d.year();
    if (d1 < imm)
        return imm;
    imm = December/Wednesday[3]/d.year();
    if (d1 < imm)
        return imm;
    return year_month_day{March/Wednesday[3]/(d.year() + years{1})};
}
```

**Comment by suhasghorp** [comment]
Perfect! Thank you. I needed to get a bunch of IMM dates from a given start date. Here is what I came up with based on your feedback. Hopefully helps someone some day.
<pre>
#pragma once
#include "date.h"
#include <iostream>
#include <vector>
using namespace date;

year_month_day approximate_next_imm(year_month_day d1)
{
	if (d1 < March / 20 / d1.year())
		return March / 20 / d1.year();
	if (d1 < June / 20 / d1.year())
		return June / 20 / d1.year();
	if (d1 < September / 20 / d1.year())
		return September / 20 / d1.year();
	if (d1 < December / 20 / d1.year())
		return December / 20 / d1.year();
	return  March / 20 / (d1.year() + years{ 1 });

}

year_month_day approximate_prev_imm(year_month_day d1)
{
	if (d1 > March / 20 / d1.year())
		return March / 20 / d1.year();
	if (d1 > June / 20 / d1.year())
		return June / 20 / d1.year();
	if (d1 > September / 20 / d1.year())
		return September / 20 / d1.year();
	if (d1 > December / 20 / d1.year())
		return December / 20 / d1.year();
	return  March / 20 / (d1.year() - years{ 1 });

}

year_month_day approximate_next_imm_roll(year_month_day d1)
{
	year_month_day approx;
	approx = approximate_next_imm(d1);
	//Below is a constant historic date, things changed after this date
	year_month_day semi_annual_roll_start_date = 2015_y / dec / 20;
	if (approx >= semi_annual_roll_start_date) {
		if (unsigned{ approx.month() } == 3 || unsigned{ approx.month() } == 9) {
			return approximate_prev_imm(approx);
		}
	}
	return approx;
}

std::vector std::string  get_imm_dates(std::string start_date, std::vector double tenors) {
	// the tenors vector should look like {0.5, 1, 2, 3, 4, 5, 7, 10 etc}
	//start date is string dd/mm/yyyy
	std::vector<std::string> imm_dates;
	std::istringstream in{ start_date };
	date::sys_days sd;
	in >> date::parse("%d/%m/%Y", sd);
	date::year_month_day start_ymd = sd;

	for (auto &tenor : tenors) {
		date::year_month_day temp_ymd = start_ymd + months{ static_cast<int>(tenor * 12) };
		year_month_day imm_date = approximate_next_imm_roll(temp_ymd);
		std::string output = date::format("%d/%m/%Y", imm_date);
		imm_dates.push_back(output);
	}	
	return imm_dates;

}
</pre>

**Comment by HowardHinnant** [comment]
Glad I could help.

Two further comments (a bug fix and a style nit):

1.  `approximate_prev_imm` should check the dates in reverse order.  Otherwise it gets the wrong answer.  For example July 1 return March 20, instead of June 20.

2.  `if (unsigned{ approx.month() } == 3 || unsigned{ approx.month() } == 9)` can be restated as:

    `if (approx.month() == March || approx.month() == September)`

**Comment by suhasghorp** [comment]
Thank you so much. I have fixed the code as you suggested.
<pre>
year_month_day approximate_prev_imm(year_month_day d1)
{
	if (d1 > December / 20 / d1.year())
		return December / 20 / d1.year();
	if (d1 > September / 20 / d1.year())
		return September / 20 / d1.year();
	if (d1 > June / 20 / d1.year())
		return June / 20 / d1.year();
	if (d1 > March / 20 / d1.year())
		return March / 20 / d1.year();
	return  December / 20 / (d1.year() - years{ 1 });

}

year_month_day approximate_next_imm_roll(year_month_day d1)
{
	year_month_day approx;
	approx = approximate_next_imm(d1);
	//Below is a constant historic date, things changed after this date
	year_month_day semi_annual_roll_start_date = 2015_y / dec / 20;
	if (approx >= semi_annual_roll_start_date) {
		if (approx.month()  == March || approx.month() == September) {
			return approximate_prev_imm(approx);
		}
	}
	return approx;
}
</pre>
