### ISSUE TITLE
year::is_leap should be CONSTCD14 in islamic.h

### ISSUE THREAD

**Issue by bolry** [HowardHinnant/date#404]
Compiling in C++11 mode with "islamic.h" I get a compiler error for use of `constexpr islamic::year::is_leap() const` not a return-statement on line 1074.

Seems `CONSTCD11` should be `CONSTCD14` this implementation has two return statements in the implementation instead of one (supported by C++11).

Of course the implementation could be refactored to C++11 standard.

**Comment by HowardHinnant** [comment]
Thanks, fixed: https://github.com/HowardHinnant/date/commit/a22125ca406c4bd7aa690b97626778a0e06bd1a7
