### ISSUE TITLE
std::chrono::system_clock::now() returns time in GMT zone

### ISSUE THREAD

**Issue by juandent** [HowardHinnant/date#406]
I know this is not a problem with your library but forgive me that I place the question here: how can we deal with the now() function giving an answer as if one was in Greenwich Mean Time? This gives a non-intuitive result -- I expected a local time calculation...

**Comment by HowardHinnant** [comment]
It is actually a good thing that `system_clock` is UTC.  That means that your system clock doesn't have to be reset as your mobile computer traverses the world.  This adds all kinds of stability to your system timestamps for files, emails, etc.  `sys_time` can be translated into local time when it is time to display it for human consumption.

My [time zone library](https://howardhinnant.github.io/date/tz.html) can be used to convert UTC to your local time:

`auto local_time = date::make_zoned(date::current_zone(), std::chrono::system_clock::now());`

**Comment by juandent** [comment]
Good, I see.
I included tz.h and recompiled but get this error:

date\tz.h(1651): error C2512: 'date::zoned_time<std::chrono::seconds,const date::time_zone *>': no appropriate default constructor available

The referenced code is:

`inline
zoned_time<std::chrono::seconds>
make_zoned()
{
    return zoned_time<std::chrono::seconds>();
}
`


Using VS2017 ver 15.9.3

What could be wrong?

**Comment by HowardHinnant** [comment]
Within the past week or two I pushed a couple of commits which attempted to deal with this problem.  However I don't have VS to test with and haven't gotten any feedback yet on these latest commits.

If `git log -1` does not produce:
```
commit 5f34c4052377b390976dc93efaa143c678b7ee59 (HEAD -> master, origin/master)
Author: Howard Hinnant <howard.hinnant@gmail.com>
Date:   Sun Nov 25 17:04:27 2018 -0500

    More patches for VS-2017 compatiblity
```

for you, could you try to pull the latest from git@github.com:HowardHinnant/date.git ?  If you already have the latest, let me know that too, and I will try harder to get this fixed.

Thanks.

**Comment by HowardHinnant** [comment]
Choose your preferred first day of the week (e.g. Sunday), and then subtract the target weekday from that day, which results in `days`.  Then you can extract the `count()` from that `duration`:

```
auto index = (wd - Sunday).count();
```

It is on my to-do list to put back in two named conversion member functions:  https://github.com/HowardHinnant/date/pull/380/commits/9af4783a32dc024ad8aa59409d219fed36fa8416

**Comment by juandent** [comment]
great! thank you!

**Comment by juandent** [comment]
`auto local_time = date::make_zoned(date::current_zone(), std::chrono::system_clock::now());`

I infer local_time is a time_point. How can I obtain a year_month_day from it?

I am yet to uderstand your tz.h library --- will look into it when I have more time...

Regards,
Juan

**Comment by juandent** [comment]
One question: for a quick solution while I get the time to look into tz.h, how can I subtract 6 hours from the time_point returned by: 

`auto n = std::chrono::system_clock::now();`

See, I am in Central Standard Time and no Daylight savings ever, so it is 6 hours less than UTC.

**Comment by juandent** [comment]
Is this the correct approach:

`		auto n = std::chrono::system_clock::now(); // .time_since_epoch().count();
		auto since_epoch = n.time_since_epoch();	// a duration in seconds
		since_epoch -= std::chrono::hours{ 6 };
`
?

**Comment by HowardHinnant** [comment]
> `auto local_time = date::make_zoned(date::current_zone(), std::chrono::system_clock::now());`
> 
> I infer local_time is a time_point. How can I obtain a year_month_day from it?

The type of `local_time` is `zoned_time<system_clock::duration>`.  This is essentially a pair of a `local_time` and a `time_zone`.  A `local_time` is a `chrono::time_point`, but outside of a `zoned_time`, not associated with any particular `time_zone`.  Consequently there is no clock or `now()` function associated with `local_time`.

One can extract the `local_time` from a `zoned_time`.  This operation will use the `time_zone` to get a UTC offset from the `sys_time` in the `zoned_time`:

`auto lt = local_time.get_local_time();`

Then `lt` can be truncated to days precision and then converted to a `year_month_day`:

`year_month_day ymd{floor<days>(lt)};`

And finally `year_month_day` has `year()`, `month()` and `day()` getters.

**Comment by juandent** [comment]
Beautiful, thank you so much!! It's just a lot to take in and I have so many other issues in my mind that need attention!

Truly grateful!!

**Comment by HowardHinnant** [comment]
> One question: for a quick solution while I get the time to look into tz.h, how can I subtract 6 hours from the time_point returned by:
> 
> `auto n = std::chrono::system_clock::now();`
> 
> See, I am in Central Standard Time and no Daylight savings ever, so it is 6 hours less than UTC.

One can just `n - 6h` to directly subtract 6 hours (you'll need a using namespace std::chrono_literals` to make the `h` suffix visible).  However if there is an IANA time zone name (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) for your time zone, it is better to use that and form a `zoned_time`:

`auto zt = make_zoned("Etc/GMT+6", system_clock::now());`

Now you can print `zt` out directly, convert it to other time zones, or extract the `local_time` from it for further arithmetic.

**Comment by juandent** [comment]
One last issue: I downloaded the database from IANA (a version from 2018g) and copied the WindowsZones.xml from the web site. However there was a bug reading this xml file. Specifically:

```
        if (mapZonePos != std::string::npos)
        {
            mapZonePos += mapZoneOpeningTagLen;
            detail::timezone_mapping zm{};
            //std::size_t pos = read_attribute("other", zm.other, mapZonePos);
			std::size_t pos = read_attribute("type", zm.type, mapZonePos);
            pos = read_attribute("territory", zm.territory, pos);
            //read_attribute("type", zm.type, pos);
			read_attribute("other", zm.other, pos);
            mappings.push_back(std::move(zm));

            continue;
        }
```

inside function `load_timezone_mappings_from_xml_file(const std::string& input_path)`. The order of the attributes was wrong...

**Comment by HowardHinnant** [comment]
Curious.  I'm seeing `{other, territory, type}` at http://unicode.org/repos/cldr/trunk/common/supplemental/windowsZones.xml

**Comment by juandent** [comment]
Yes - the problem is the browser I was using (Microsoft Edge). It inverses the order of the attributes inside the XML elements. If I look at the doc with Chrome it appears in `{other,territory,type}` order. I just could not download the XML file so I did a copy/paste from Edge and got it inverted. Strange...
Do you have any idea why Chrome does not give me the option to download an XML file?

Microsoft Edge is strange indeed...
