### ISSUE TITLE
How i can solve this three problems with datetime?

### ISSUE THREAD

**Issue by prsolucoes** [HowardHinnant/date#407]
Hi,

**First problem:**
- Can i use this library in mobile?

**Second problem:**
I have a problem that in our library that work with date and time:
https://github.com/ezored/dependency-datetime/blob/master/build/source/cpp/ezored/time/DateTime.cpp#L8

We receive datetime as string, but already in UTC. But when i use on the above method i got time in my current time zone, instead of a chrono object in UTC.

Example:

```
#include <iostream>
#include <string>
#include <chrono>
#include <sstream>
#include <iomanip>
#include <cstdint>
#include <ctime>

int main()
{
    std::tm tm = {};
    std::stringstream ss("2018-12-07 20:00:00");
    ss >> std::get_time(&tm, "%Y-%m-%d %H:%M:%S");
    auto dt = std::chrono::system_clock::from_time_t(std::mktime(&tm));

    std::cout << (dt.time_since_epoch().count() / 1000000) << std::endl;
    
    // 1544212800 - 20:00 - correct (in utc)
    // 1544223600 - 11:00 - wrong (returned by count)

    return EXIT_SUCCESS;
}
```

I don't know how to solve it with pure c/c++.

**Third problem:**
How can i solve my problem above using this current library? It it works well i will convert all methods in my library to use this library.

https://github.com/ezored/dependency-datetime/blob/master/build/source/cpp/ezored/time/DateTime.cpp

Im searching for a solution a lot of time, but without solution now.

**Comment by HowardHinnant** [comment]
> * Can i use this library in mobile?

Though I didn't personally write any porting code, others have contributed ports to iOS and Android.  If it isn't working for you, let me know, and maybe we can figure something out.  If it is working, let me know so I can assure others it is working on your platform.

> We receive datetime as string, but already in UTC. But when i use on the above method i got time in my current time zone, instead of a chrono object in UTC.

_Not_ using timezones is the simplest thing of all with this library.  The base library is in date.h and deals _only_ in UTC (and has parsing and formatting functionality).  date.h is header-only.

_If_ you need timezone support (including your local timezone), that is in an additional library layered on top of date.h.  It has a header and a source: tz.h / tz.cpp.

To parse a UTC timepoint into a `chrono::time_point`:

#include "date/date.h"

```
#include <chrono>
#include <iostream>
#include <sstream>
#include <string>

int
main()
{
    std::chrono::system_clock::time_point dt;
    std::stringstream ss{"2018-12-07 20:00:00"};
    ss >> date::parse("%F %T", dt);

    using date::operator<<;
    std::cout << dt << '\n';
    std::cout << date::floor<std::chrono::seconds>(dt.time_since_epoch()) << '\n';
}
```
This outputs:
```
2018-12-07 20:00:00.000000
1544212800s
```
On your system the number of trailing `0` after the `.` may vary.  It will be to whatever precision your `system_clock::time_point` is.

**Comment by HowardHinnant** [comment]
I'll hold off answering your SO question since I've answered it here.  There _are_ other options.  But none as good as this library.  For bonus points, this library has been voted into the draft C++20 spec, and so it is likely to become standard by the end of 2020.

**Comment by prsolucoes** [comment]
Ok, i will integrate it into my library and post here the results if it work on mobile. I like this library a lot.

I made all functions that i need, can you only check my code to see if is correct, if i need use floor or other thing?

https://wandbox.org/permlink/wrhZynWfIoS7Yc3O

Thanks if you can help me revising it.

**Comment by prsolucoes** [comment]
Im running on Android without problems im my first test. But on database the date/time is with this format:

```%F %T => 2018-12-07 23:08:31.919000```

There is any way to remove the part ".919000"?

Thanks.

**Comment by HowardHinnant** [comment]
Thanks for the info.  Just reviewed your code and it looks fine to me.

You can remove fractional seconds by truncating your `time_point` to `seconds` prior to formatting (or printing) it.  If you have C++17, you can use `std::chrono::floor<std::chrono::seconds>(tp)` to do this.  If you don't have C++17, there's a `date::floor` available.

**Comment by prsolucoes** [comment]
I put the credits for your library in our library README:
https://github.com/ezored/dependency-datetime

Any problem?

**Comment by HowardHinnant** [comment]
On the first function it is correct, but maybe not doing what you want, I'm not sure.  This will parse fractional seconds from `value` and then discard the fractional seconds.  If `value` is known to never contain fractional seconds, then you can skip the `floor`.  All the `floor` does is divide by a million, and then the return (conversion back to `system_clock::time_point`) multiplies by a million.

Second function looks fine.  This will always discard fractional seconds in `value` and output with "whole unit" seconds.

The third and fourth functions aren't doing what you want.  Support for local time implies time zone support, and you'll need the time zone library for this:  https://howardhinnant.github.io/date/tz.html

This does require some installation, one source: tz.cpp.

Here are the installation instructions: https://howardhinnant.github.io/date/tz.html#Installation

On Android you probably want to compile with `-DUSE_OS_TZDB=1`.  This tells the time zone library to use the time zone database supplied by the Android OS.

Once you have "tz.h", here is the third function:
```
std::string DateTime::getLocalDateTimeAsString() {
    using namespace std::chrono;
    auto dt = date::floor<seconds>(system_clock::now());
    date::zoned_seconds zt{date::current_zone(), dt};
    return date::format("%F %T", zt);
}
```
`zoned_seconds` is a pair of `time_zone` and a seconds-precision `system_clock::time_point`.  `current_zone()` returns a pointer to your current local time zone, and applies the UTC offset to get `local_time`.

The fourth function is problematic.  `system_clock::time_point` is a type-safe type that means UTC.  `getLocalDateTime` is returning a type that means UTC, and not local time.  Now perhaps you intend to represent the local time as a `system_clock::time_point` that has had a UTC offset applied to it.  

My library puts this idea into a separate type: `local_time<Duration>`, or just `local_seconds` for your application.  This type is a `chrono::time_point`, but it has no clock and no `now()` associated with it.  This prevents you from accidentally mixing UTC and local time and creating run time errors from such a mix.  Using this design `getLocalDateTime` would look like:
```
date::local_seconds DateTime::getLocalDateTime() {
    using namespace std::chrono;
    auto dt = date::floor<seconds>(system_clock::now());
    date::zoned_seconds zt{date::current_zone(), dt};
    return zt.get_local_time();
}
```

**Comment by HowardHinnant** [comment]
I love credits, thank you! :-)

**Comment by prsolucoes** [comment]
Hi, thanks.

I think names is confusing after update to your library, so i have changed all and make a new implementation, because functions will work only with UTC (the iOS and Android object already return dates in correct timezone):

https://github.com/ezored/dependency-datetime/blob/master/build/source/cpp/ezored/time/DateTime.cpp

Now i think that make more sense and in my tests it works, but i need your approve.

**Comment by HowardHinnant** [comment]
That looks good to me, but doesn't truncate to seconds-precision if you want that.

**Comment by prsolucoes** [comment]
Ah ok, in the first function, is better i let the original data:

```
std::chrono::system_clock::time_point DateTime::getDateTimeFromString(const std::string & value) {
    std::chrono::system_clock::time_point dt;
    std::stringstream ss{value};
    ss >> date::parse("%F %T", dt);
    return dt;
}
```

And on the 4th function i remove too:

```
std::chrono::system_clock::time_point DateTime::getCurrentDateTime() {
    return std::chrono::system_clock::now();
}
```

Is this that you mean?

**Comment by HowardHinnant** [comment]
Yes, those look good to me.

**Comment by juandent** [comment]
Where is the documentation for date::parse?

**Comment by prsolucoes** [comment]
@juandent https://howardhinnant.github.io/date/tz.html#parse

@HowardHinnant, man i prefer don't include timezone now, since for desktop i see that need curl (macos). I will leave with UTC functions only. Thanks for all.

**Comment by HowardHinnant** [comment]
For Android tz can be configured to not use curl (`-DHAS_REMOTE_API=0 -DUSE_OS_TZDB=1`).  This tells the lib to only use the OS's time zone database, and you can't download a new one, or even check what the latest version is.  That being said, if you don't need timezone support, then you don't want all that extra code in your app, so sticking with date.h is best.

**Comment by HowardHinnant** [comment]
@juandent I think you're looking for this: https://howardhinnant.github.io/date/date.html#from_stream_formatting

**Comment by prsolucoes** [comment]
There is any way to get all database information and put inside C++ code to don't need download anything?

**Comment by HowardHinnant** [comment]
Linux-based OS's ship with a copy of the database in binary form.  `-DUSE_OS_TZDB=1` instructs the tz lib to not download and use the OS's db off of your local disk.

**Comment by prsolucoes** [comment]
Yes, im checking the code. Im thinking about import all timezones in code format without need get it from disk. Im thinking in a global way to do this.

**Comment by prsolucoes** [comment]
Maybe we can use a flag to use in memory timezone data instead of get from any OS database, but for all platforms.

**Comment by HowardHinnant** [comment]
You're not the first to want to encode the database into the code, as opposed to reading it off disk.  The downside of this is that the db changes relatively often.  We're on the 7th version for 2018 right now.  That about once every other month.

**Comment by prsolucoes** [comment]
O.O   I didn't know that is changes frequently. Sorry. 
What change inside the file? Maybe the informations that change we don't need. It is not the zone and offset?

**Comment by prsolucoes** [comment]
You can mark it as solved and close if you want. It is working fine for desktop, android and iOS (date.h).

**Comment by HowardHinnant** [comment]
Bone-headed politicians change the rules for DST all the time, and sometimes with very little notice.  That's most of the reason for the changes.  Every 18 months or so an update is needed for a new leap second.
