### ISSUE TITLE
Downloading produces error message on read only filesystem

### ISSUE THREAD

**Issue by Thalhammer** [HowardHinnant/date#409]
My application is running inside a container where root is mounted read only. I have a writeable network sharre where I store my database and now the tzdb. I set the location using `date::set_install("/mypath");` and it worked fine. However on first start I get an error on my console:

`mkdir: can't create directory '//Downloads': Read-only file system`

However the download worked fine and everything is working.

I guess there is an logic error either here:
https://github.com/HowardHinnant/date/blob/5f34c4052377b390976dc93efaa143c678b7ee59/src/tz.cpp#L3262
or here:
https://github.com/HowardHinnant/date/blob/5f34c4052377b390976dc93efaa143c678b7ee59/src/tz.cpp#L311
As you check and try to create a download folder, but the file is downloaded to the install directory anyway.
So either it gets downloaded to the wrong directory or the directory is created for no reason.
I think instead of the download folder the code should check and create the install folder, but I might be totally wrong.

**Comment by HowardHinnant** [comment]
I _think_ what is happening is that you are compiling with `-DAUTO_DOWNLOAD=1` (likely as a default), and the library tries to download the tzdb from the IANA website on first use.  But you don't need that functionality.  Indeed, you don't need the "remote API" at all (which is an API for managing the download).

Try compiling with `-DHAS_REMOTE_API=0`.

Details on these configuration flags are here:  https://howardhinnant.github.io/date/tz.html#Installation

**Comment by Thalhammer** [comment]
Yes I do compile with the remote api, and I like the fact that my tzdb gets updated automatically (I use libcurl anyway so it does not matter).

The problem I tried to state is that during download the library tries to create the folder `~/Downloads` *but never uses it*.

**Comment by HowardHinnant** [comment]
Thanks for your patience.  Try this: https://github.com/HowardHinnant/date/commit/0e85704e473c365e95ab4f55c804e08050c9ab0c

**Comment by NeroBurner** [comment]
@Thalhammer is the issue resolved? if so please close the issue
