### ISSUE TITLE
It is necessary to amend the tz.h file for compilation under MSVC

### ISSUE THREAD

**Issue by nvbogos** [HowardHinnant/date#41]
210        name_(std::move(src.name_)),
-211        zonelets_(std::move(zonelets_))
+211       zonelets_(std::move(src.zonelets_))
 

+           version(std::move(src.version)), 
 585        zones(std::move(src.zones)),
-586        links(std::move(links)),
+586        links(std::move(src.links)),
-587        leaps(std::move(leaps)),
+587        leaps(std::move(leaps)),
-588        rules(std::move(rules))
+588        rules(std::move(rules))
 589 #if TIMEZONE_MAPPING
 590        ,
-591        mappings(std::move(mappings)),
+591        mappings(std::move(mappings)),
-592        native_zones(std::move(native_zones))
+592        native_zones(std::move(native_zones))
        
+           version = std::move(src.version)); 
 598        zones = std::move(src.zones);
-599        links = std::move(links);
+599        links = std::move(src.links);
-600        leaps = std::move(leaps);
+600        leaps = std::move(src.leaps);
-601        rules = std::move(rules);
+601        rules = std::move(src.rules);
 602 #if TIMEZONE_MAPPING
-603        mappings = std::move(mappings);
+603        mappings = std::move(src.mappings);
-604        native_zones = std::move(native_zones);
+604        native_zones = std::move(src.native_zones);
 605 #endif

**Comment by HowardHinnant** [comment]
Is this still an issue for you, or has it been fixed by f3ce2210e67d8362992c1580a722a6845ddf8f07?

**Comment by nvbogos** [comment]
Thanks, I already fixed it.
