### ISSUE TITLE
parse %T

### ISSUE THREAD

**Issue by dfhljf** [HowardHinnant/date#414]
``` cpp
    stringstream ss("15:00:00");
    local_time<nanoseconds> time;
    from_stream(ss,"%T",time);
```
time.count()=0, should be 15\*60\*60*1e9?

**Comment by HowardHinnant** [comment]
After this call `ss.fail()` will return true, and `time` will not be changed.

`time.count()` is a compile time error because `time` is a `time_point`, not a `duration`.  If you change the type of `time` to `nanoseconds`, then you'll get the expected value.

**Comment by dfhljf** [comment]
thanks.
