### ISSUE TITLE
Do format(), parse(), from/to_stream... work with locals libraries other than std::locale?

### ISSUE THREAD

**Issue by lkpcampion** [HowardHinnant/date#415]
I need to maintain ICU locale compatibility for I/O in the application, so need to explore boost::locale as an option. Documentation only show std::locale as a formatting/parsing option. Can this work with other locale libraries as well?

**Comment by HowardHinnant** [comment]
This does not work with other locale libraries.  However it does support time zone abbreviations, UTC offsets and a wide variety of formatting and parsing options.  But its only access to locale information is via `std::locale` (for local ymd ordering, names of weekdays and months, etc).

**Comment by lkpcampion** [comment]
Thanks. Local ymd ordering, names etc. are what I need from a locale. But  if I understand correctly (please let me know if I am wrong), std::locale support varies across OSes (both platform and OS versions). For my application that'd be a maintenance burden. 

If so, do you have any recommendations for interfacing with other locale libraries using your API? Do you have plans to add support for other libraries?
