### ISSUE TITLE
Clang sanitizer runtime error

### ISSUE THREAD

**Issue by coin-au-carre** [HowardHinnant/date#42]
> date.hpp:2461:40: runtime error: negation of 9 cannot be represented in type 'unsigned int'
> SUMMARY: AddressSanitizer: undefined-behavior

Line concerned is `auto const m = mp + (mp < 10 ? 3 : -9u);                           // [1, 12]`

Used with Clang 3.7.1. with `-fsanitize=address`. If needed I can take time to see what exactly produces this error.

**Comment by HowardHinnant** [comment]
Does this silence it?
https://github.com/HowardHinnant/date/commit/f73c4aa486f100796e3fb7ff4d91294ef4bdec9e

**Comment by coin-au-carre** [comment]
Yes problem solved thank you !
