### ISSUE TITLE
"Obtaining y/m/d h:m:s components from a time_point" on MSVC is not optimal

### ISSUE THREAD

**Issue by ujos** [HowardHinnant/date#422]
Hello,

The recipe how to obtain time and date components described on [Wiki](https://github.com/HowardHinnant/date/wiki/Examples-and-Recipes#obtaining-ymd-hms-components-from-a-time_point) is not optimal if compiled with MS VC++ 15.9.5. 

Compiler does not recognize your intention to get integral and reminder from `now / 24h` expression. As result assembly for the following code:
```cpp
static std::tuple<date::sys_days, std::chrono::system_clock::duration> split1( std::chrono::system_clock::time_point tp ) noexcept {
    using namespace std::chrono_literals;

    auto const d = date::floor<date::days>( tp );
    auto const t = tp - d;

    return std::tuple {d, t};
}

template<typename dt, typename tt>
static void __declspec(noinline) foo( dt d, tt t ) {
    std::cout << &d << t.count() << std::endl;
}

int main() {
    auto now1 = std::chrono::system_clock::now();
    auto[ d1, t1 ] = split1( now1 );
    foo( d1, t1 );
}
```
looks like following:
```asm
     auto now1 = std::chrono::system_clock::now();
00007FF739551006  call        qword ptr [__imp__Xtime_get_ticks (07FF7395520B8h)]  
00007FF73955100C  mov         r9,rax  
    auto[ d1, t1 ] = split1( now1 );
00007FF73955100F  mov         rbx,0C92A69C000h  
00007FF739551019  cqo  
00007FF73955101B  idiv        rax,rbx  
00007FF73955101E  movsxd      rcx,eax  
00007FF739551021  mov         r8,rax  
00007FF739551024  imul        rcx,rbx  
00007FF739551028  cmp         r9,rcx  
00007FF73955102B  jge         main+30h (07FF739551030h)  
00007FF73955102D  dec         r8d  
00007FF739551030  movsxd      rax,r8d  
    foo( d1, t1 );
00007FF739551033  mov         ecx,r8d  
    auto[ d1, t1 ] = split1( now1 );
00007FF739551036  imul        rax,rbx  
00007FF73955103A  sub         r9,rax  
    foo( d1, t1 );
00007FF73955103D  mov         rdx,r9  
00007FF739551040  call        foo<std::chrono::time_point<std::chrono::system_clock,std::chrono::duration<int,std::ratio<86400,1> > >,std::chrono::duration<__int64,std::ratio<1,10000000> > > (07FF739551060h)  
```

Consider extra `imul` instruction. It is required to convert days back to `time_point`

I've tried to improve `split1` function and for the following code
```cpp
static std::tuple<date::sys_days, std::chrono::system_clock::duration> split2( std::chrono::system_clock::time_point tp ) noexcept {
    using namespace std::chrono_literals;
    auto const tse = tp.time_since_epoch();
    constexpr auto sys_24h = std::chrono::duration_cast<std::chrono::system_clock::duration>(24h);
    auto const d = tse.count() / sys_24h.count();
    auto const t = tse.count() % sys_24h.count();
    return std::tuple {date::sys_days{date::days{d}}, std::chrono::system_clock::duration{t}};
}
```

got following assembly
```asm
    auto now2 = std::chrono::system_clock::now();
00007FF739551045  call        qword ptr [__imp__Xtime_get_ticks (07FF7395520B8h)]  
    auto[ d2, t2 ] = split2( now2 );
00007FF73955104B  cqo  
00007FF73955104D  idiv        rax,rbx  
    foo( d2, t2 );
00007FF739551050  mov         ecx,eax  
00007FF739551052  call        foo<std::chrono::time_point<std::chrono::system_clock,std::chrono::duration<int,std::ratio<86400,1> > >,std::chrono::duration<__int64,std::ratio<1,10000000> > > (07FF739551060h)  
```

I do not know how it will look like on G++ or another version of the MSVC++. To be secure I believe extra function should be introduced like `split2` above.

Thanks
Dima

**Comment by HowardHinnant** [comment]
One thing people have to be careful about is understanding their domain and if they need to handle dates prior to 1970-01-01:
```
auto now1 = sys_days{1969_y/December/31} + 23h + 59min + 59s + 132us;
```
`split1` and `split2` have different behavior for this value.

**Comment by ujos** [comment]
I think it is Clock dependent. If Clock's epoch starts at 1970-01-01 but in your app you need to work with timestamp before 1970-01-01, you should define your Clock and convert from system_clock to your Clock.

**Comment by ujos** [comment]
Actually Epoch can start at 5:00am. Why not... but in standard there is no information about that...

**Comment by HowardHinnant** [comment]
The draft C++20 spec currently fixes the `system_clock` epoch to 1970-01-01 00:00:00 UTC, excluding leap seconds (Unix Time).  This is also the current practice among all implementations.

Assuming the draft C++20 spec survives standardization, what algorithm do you recommend for someone who has to deal with a large range of times, say between the years 1700 to 2200?

**Comment by ujos** [comment]
In this case `system_clock` will never return value less than `1970-01-01`. So we do not need to overcomplicate `split2` function for the `system_clock`. This function will cover 99% of requirements (I guess) and it will work as fast as possible.

From other side, if app should support dates from 1700y (or less), then library can provide extended version of the `split` function, which accepts `custom_clock::time_point` and `clock::epoch`. Performance can be a bit worse, but it is cost which user will take.

**Comment by HowardHinnant** [comment]
Sorry, I can't introduce a function that fails at run time only rarely.

However I do fully support educating people in that if they don't need to traffic in pre-1970 time stamps, then they may realize superior code generation with something like `split2`, or this simpler variant:
```
std::tuple<sys_days, std::chrono::system_clock::duration>
split1( std::chrono::system_clock::time_point tp ) noexcept
{
    auto const d = std::chrono::time_point_cast<days>( tp );
    auto const t = tp - d;

    return std::tuple{d, t};
}
```

**Comment by ujos** [comment]
> or this simpler variant
`split2` produced better output on MSVC. I posted many requests to Microsoft. 

> Sorry, I can't introduce a function that fails at run time only rarely.
Is negative duration valid value?

**Comment by HowardHinnant** [comment]
Here's a godbolt summary: https://gcc.godbolt.org/z/2Cu-xf

Yes, negative durations are both legal and useful (as long as the `duration::rep` supports negative values).  All of the "built-in" durations (nanoseconds, etc) are signed.  This was done so that subtracting them would be less error prone (get a negative instead of under/overflow).  But people do create unsigned durations sometimes.

**Comment by HowardHinnant** [comment]
Whatever solution you come up with, it will cost something.  You'll have to decide if it costs more or less than `floor`.

tz.h has example clocks with different epochs that you could explore.  For example `tai_clock` has an epoch of 1958-01-01.  VS's upcoming `file_clock` will have an epoch of 1601-01-01.  Here is example code that converts to/from that epoch: https://github.com/HowardHinnant/date/wiki/Examples-and-Recipes#fILETIME

My advice is to start simple and set up a benchmark rig.  Measure instead of guess.  The expensive pain points are likely to be cache misses and broken pipelines.  The difference between these algorithms may not have much of either.

**Comment by ujos** [comment]
I have micro benchmark. With the 'split2' function and simplified `date::make_time` function my code works 2% faster and is 12% smaller. 

I also wonted to simplify `year_month_day::from_days` function. But it seems you worked hard on that and there is nothing to improve there.

**Comment by ujos** [comment]
I think we can close the issue
