### ISSUE TITLE
Do you parse zone.tab file?

### ISSUE THREAD

**Issue by weiqj** [HowardHinnant/date#423]
My code needs to be deployed to an embedded system built with Yocto. I just looked through the root file system. It appears to me that my tzdata has a lot of aliases defined in zone.tab file.

A quick look through your code I found that zone.tab is simply ignored. Can you confirm it?

Thanks for the good work.

**Comment by HowardHinnant** [comment]
That is correct.  My  library completely ignores zone.tab (and zone1970.tab).  These files map country code and latitude/longitude coordinates to a time zone name, and my library is completely ignorant of country codes and latitude/longitude coordinates.

If your program uses these files to look up time zone names by country code or latitude/longitude, then my library would deal with the resultant time zone name properly.

If you wanted to eliminate these files from your database to save space, it would not impact my library.
