### ISSUE TITLE
date.h(3768): warning C4127: conditional expression is constant

### ISSUE THREAD

**Issue by ujos** [HowardHinnant/date#424]
On Visual Studio 15.9.5 with `/W4` parameter I get following warning:
```
date.h(3768): warning C4127: conditional expression is constant
date.h(3768): note: consider using 'if constexpr' statement instead
```

The reason is that `decimal_format_seconds::width` variable is a `constexpr`. Thus `width > 0` can be evaluated at compile time as well.

**Comment by HowardHinnant** [comment]
Unfortunately `if constexpr` isn't yet in my toolbox.  If there's a scoped way of disabling this warning, I'll take it.

**Comment by ujos** [comment]
```cpp
#include <iostream>

#if __cplusplus >= 201703
#  define IF_CONSTEXPR(expr) if constexpr ((expr))
#else 
#  define IF_CONSTEXPR if ((expr))
#endif

constexpr auto x = 10;


int main() {
    IF_CONSTEXPR( x > 0 ) {
        std::cout << "???" << std::endl;
    }

    
    std::cout << __cplusplus << std::endl;
}
```

Probably for `#if __cplusplus` directive should be extended with `|| _MSC_VER >= 201703` in case if `/Zc:__cplusplus ` parameter is not passed to the MS C++ compiler. i.e.

```cpp
#if __cplusplus >= 201703 || || _MSC_VER >= 201703
#  define IF_CONSTEXPR(expr) if constexpr ((expr))
#else 
#  define IF_CONSTEXPR if ((expr))
#endif
```

The only thing is I do not have previous version of the MSVC compiler to check compatibility

**Comment by ujos** [comment]
Accoring to [MSDN](https://docs.microsoft.com/en-us/cpp/cpp/if-else-statement-cpp?view=vs-2017#-if-constexpr-statements) first version of the VS, which supports `if constexpr` is Visual Studio 15.3. 

Thus
#if __cplusplus >= 201703 || _MSC_VER >= 1911
#  define IF_CONSTEXPR(expr) if constexpr ((expr))
#else 
#  define IF_CONSTEXPR if ((expr))
#endif

**Comment by ujos** [comment]
Following should work for any VS version regardless of passed flags
```
#if __cplusplus >= 201703 || (defined(_MSVC_LANG) && _MSVC_LANG >= 201703)
#  define IF_CONSTEXPR(expr) if constexpr ((expr))
#else 
#  define IF_CONSTEXPR(expr) if ((expr))
#endif
```

**Comment by ujos** [comment]
`cl /std:c++14 /W4` command still issues this warning. 

There is bug report created year ago O_O and still Under Investigation.... Maybe it is better to add 
```cpp
//
// Top of the date.h
//
#ifdef _MSC_VER
#   pragma warning(push)  
// warning C4127: conditional expression is constant
#   pragma warning(disable : 4127)
#endif

//
// Bottom of the date.h
//
#ifdef _MSC_VER
#   pragma warning(pop)  
#endif
```

**Comment by HowardHinnant** [comment]
Fixed: https://github.com/HowardHinnant/date/commit/d5e96f099182f3a7a763d86c48fab0598d1b65e6

Thanks.
