### ISSUE TITLE
File conflict with IANA timezone-data package

### ISSUE THREAD

**Issue by zeule** [HowardHinnant/date#426]
`/usr/lib/libtz.a` is installed by the timezone-data package (tzdata in some distributions, maybe goes by other names too. It is the package which contains the zic, zdump, and tselect utils)  and this library tries to install the library file with the same name. Due to the file conflict it is impossible to install this library.

**Comment by ainola** [comment]
What was the reasoning for trying to install this in such a place?

**Comment by de-vri-es** [comment]
This is quite a big problem. It basically prevents installing as a system library or packaging this library :(

How about simply renaming the compiled library to `libdate-tz.{a.so}` or similar?

**Comment by HowardHinnant** [comment]
I invite anyone to take over the cmake build/packaging system.  I didn't write it.  Don't understand it.  Never use it myself.

**Comment by mellery451** [comment]
how about this? https://github.com/mellery451/date/commit/ada47039e35655dfd4cb06293d05e54f3094f9f5 ? If it looks fine to @de-vri-es and @zeule, I can submit a PR

**Comment by de-vri-es** [comment]
Looks good to me. Only did a quick check to see if `cmake/dateConfig.cmake` would also need changes, but I believe it does not.
