### ISSUE TITLE
date::make_zoned takes a long time - how can we call it in a separate thread?

### ISSUE THREAD

**Issue by juandent** [HowardHinnant/date#429]
I propose the following to call date::make_zoned asynchronously:

```
		auto zone_current = date::current_zone();
		auto right_now = std::chrono::system_clock::now();
		auto f = std::async( std::launch::async, &date::make_zoned, zone_current,right_now );
```

but I get  this errors:

> error C2672: 'std::async': no matching overloaded function found

> error C2783: 'std::future<_Invoke_traits<void,_Callable,decay<_ArgTypes>::type...>::type> std::async(std::launch,_Fty &&,_ArgTypes &&...)': could not deduce template argument for '_Fty'

This is in Visual Studio 2017 v15.9.9. What am I doing wrong?

Thanks,
Juan

**Comment by HowardHinnant** [comment]
I'm guessing this is because `make_zoned` is a templated function and it doesn't know which templates to use.

But all `make_zoned` does is construct a `zoned_time` and return it.  So I'm not sure continuing in this direction would do what you want anyway.  If this did work, it would construct the `zoned_time`, then destruct the `zoned_time`, and then end the async task, accomplishing nothing.

**Comment by juandent** [comment]
I tend to disagree. Calling this function initializes the tz library so I am not really interested in getting a zoned_time, just making future calls to the tz library fast... What template parameters should I pass to make_zoned?

**Comment by HowardHinnant** [comment]
Here's my favorite way to asynchronously initialize the tz lib:
```
std::thread{date::get_tzdb}.detach();
```
You could also throw `date::get_tzdb` into `std::async`.  No template parameters to worry about.

**Comment by juandent** [comment]
Great!! Very grateful - works like a charm!
BTW is compound foreign keys already supported in the current master branch? If not, when?

**Comment by HowardHinnant** [comment]
I'm afraid I don't know what "compound foreign keys" means (so I guess not ;-) ).

**Comment by juandent** [comment]
sorry - wrong site. Thanks for the tip on how to initialize the tz lib asynchronously.
