### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by Tobaloidee** [HowardHinnant/date#432]
hi @HowardHinnant Good day! I am [Tobaloidee](https://steemit.com/@tobaloidee) a graphic artist..I would like to contribute to your project by designing a logo of it. If you will permit me, I'll begin drafting. Thanks and best regards!

**Comment by HowardHinnant** [comment]
That's very generous of you.  However this project doesn't really need a logo.

This project has already achieved its purpose and is winding down.  The software has been voted into the draft C++20 specification and will become available to developers via their std::lib vendors within about 18 months.  This repository will live on only for compatibility purposes for those not able to migrate to C++20 for a few more years.

**Comment by Tobaloidee** [comment]
Oh, okay Sir! Congratulations to the project. If ever you need a logo just notify me in the future.Thanks again! :)
