### ISSUE TITLE
String view error in date.h for Visual Studio 2015 and 2017

### ISSUE THREAD

**Issue by acgetchell** [HowardHinnant/date#434]
```bash
In file included from C:\Tools\vcpkg\installed\x64-windows\include\date/tz.h:110:
C:\Tools\vcpkg\installed\x64-windows\include\date/date.h(65,11):  fatal error: 'string_view' file not found
# include <string_view>
          ^~~~~~~~~~~~~
7544 warnings and 1 error generated.
ninja: build stopped: subcommand failed.
```

Visual Studio 2015:
https://ci.appveyor.com/project/acgetchell/cdt-test/build/job/6tltjqyu37oan89v#L93593

Visual Studio 2017:
https://ci.appveyor.com/project/acgetchell/cdt-test/build/job/vilpx5cj0vyltwje#L93594

https://github.com/HowardHinnant/date/pull/330
@qis

**Comment by qis** [comment]
This is required to correctly detect and enable `string_view` detection in MSVC:

https://github.com/HowardHinnant/date/pull/330#issuecomment-475621811
