### ISSUE TITLE
Unable to get Timezone database version from /root/Downloads/tzdata/

### ISSUE THREAD

**Issue by roger-blain** [HowardHinnant/date#438]
We encountered this problem this morning when we upgraded our application, residing in kubernetes pod's, which don't keep a copy of the tz_database, which means they need to pull it on an initial use.

Stepping through the issue with gdb, the root cause appears to be in: 

`download_to_string("https://www.iana.org/time-zones",str)`

The result form CURL was:

```
gdb) p str
$17 = "Status 403 Forbidden: User-Agent required. Contact iana@iana.org with questions."
```

This results in the above message. Which are face value seems to be an issue on the IANA site ?

Our code has been working flawlessly for several months with no change in os or build environment.

Should the system not consider reporting the real result from CURL ?

The workaround has been to install the tz_database manualy in /root/Downloads/tzdata/

Keen to hear your thoughts ?

**Comment by elvisoric** [comment]
We also have the same issue. It seems that IANA  have changed something on their side, so `User-Agent` header field is now mandatory in request. Curl command line tool by default sets `User-Agent`. By removing `User-Agent` header field using command `curl -H "User-Agent:" https://www.iana.org/time-zones` is going to produce the same error. 

Easy fix is to set `User-Agent` option in function `download_to_string` using 
`curl_easy_setopt(curl.get(), CURLOPT_USERAGENT, "curl");`

There will be pull request with these changes.

**Comment by HowardHinnant** [comment]
Wow, first I've heard of this.  Thanks for the report @roger-blain.   And thanks for the fix @elvisoric!

https://github.com/HowardHinnant/date/commit/9e3a22f3d200447059502b0e642a29475bb75e9d

**Comment by HowardHinnant** [comment]
Oh, sorry @elvisoric.  I pushed before seeing your P/R.

**Comment by HowardHinnant** [comment]
Ok, I think I've fixed it with a force-push.

**Comment by HowardHinnant** [comment]
Fixed with https://github.com/HowardHinnant/date/commit/429d9ba739184ee1eb3aac446d3a2c7c5024434e

**Comment by roger-blain** [comment]
Thanks @HowardHinnant and @elvisoric for your prompt resolution
