### ISSUE TITLE
Releases?

### ISSUE THREAD

**Issue by rbock** [HowardHinnant/date#45]
Dear Howard,

We'd like to use your date library in our company. For this it would be helpful to have a FreeBSD package for the library. We can handle the package maintenance. It would be easier if you had release tags in git, though.

Do you have any plans to add release tags?

Best,

Roland

**Comment by HowardHinnant** [comment]
I guess it is about that time.  Done.  Thanks for your support.

**Comment by rbock** [comment]
That was quick! Thanks :-)

**Comment by emsr** [comment]
This thing is so tight..  Is there any chance of bringing it up in Finland?

**Comment by HowardHinnant** [comment]
Thanks for the encouragement Ed.  I still need to write a proposal...

**Comment by viboes** [comment]
+1 for a proposal :)

**Comment by rbock** [comment]
It would be absolutely wonderful to have date.h in the standard! iso_week.h and tz would also be cool, but I would see them as separate proposals. Just my 2ct.

**Comment by HowardHinnant** [comment]
100% agreed.

And one of these days I need to upload the julian, coptic and ethiopian calendars, and maybe get a few others written.  I've held off uploading calendars that I haven't written tests for.
