### ISSUE TITLE
C4005 warning with Visual Studio 2019

### ISSUE THREAD

**Issue by shanepowell** [HowardHinnant/date#450]
I'm getting:

warning C4005: '_SILENCE_CXX17_UNCAUGHT_EXCEPTION_DEPRECATION_WARNING': macro redefinition

due to it already being defined somewhere else in the project which causes the above warning.

Is it possible to change your setup to so something like:

#ifndef _SILENCE_CXX17_UNCAUGHT_EXCEPTION_DEPRECATION_WARNING
#define _SILENCE_CXX17_UNCAUGHT_EXCEPTION_DEPRECATION_WARNING
#endif

So as to not generate the warnings please.

**Comment by HowardHinnant** [comment]
Sure, it's on tip-of-master now.

**Comment by shanepowell** [comment]
Thanks, that worked for me (once the #endif was fixed) 👍
