### ISSUE TITLE
master build error

### ISSUE THREAD

**Issue by NickYang1988** [HowardHinnant/date#452]
Hi,

When I use `sqlpp11` which depends `date`, and I built `date` with the master branch and found some errors, I don't know this issue because of my compiler or something else.

My g++ version is v7.3.1.

Here is the error:
```text
In file included from /data/TSG/date/include/date/tz.h:108:0,
                 from /data/TSG/date/include/date/tz_private.h:31,
                 from /data/TSG/date/src/tz.cpp:86:
/data/TSG/date/include/date/date.h:1:0: error: unterminated #ifndef
 #ifndef DATE_H
 
^Cmake[2]: *** [CMakeFiles/tz.dir/src/tz.cpp.o] Interrupt
make[1]: *** [CMakeFiles/tz.dir/all] Interrupt
make: *** [all] Interrupt
```

Then I use release version 2.4.1 and everything is OK.

So I'm confused, could someone can check this problem?

Thanks at all.

**Comment by HowardHinnant** [comment]
My bad.  It's fixed now.

**Comment by NickYang1988** [comment]
Good job, thanks for the quick reply.
