### ISSUE TITLE
Minor Changes

### ISSUE THREAD

**Issue by qis** [HowardHinnant/date#47]
Had to add a few headers and change a for loop index type to build without errors and warnings in VS2015 Update 2.

```
--- orig/tz.h	2016-04-07 10:29:17.087771500 +0200
+++ include/tz.h	2016-04-07 10:28:34.009325700 +0200
@@ -62,6 +62,8 @@ Technically any OS may use the mapping p
 #include <cstdint>
 #include <istream>
 #include <locale>
+#include <memory>
+#include <mutex>
 #include <ostream>
 #include <ratio>
 #include <sstream>
@@ -718,7 +720,7 @@ format(const std::locale& loc, std::stri
 
     using namespace std;
     using namespace std::chrono;
-    for (auto i = 0; i < format.size(); ++i)
+    for (std::size_t i = 0; i < format.size(); ++i)
     {
         if (format[i] == '%' && i < format.size()-1)
         {
```

**Edit**: Nevermind, there are other things that are broken in `tz.h` on Windows. Mostly `make_time` related.

**Comment by HowardHinnant** [comment]
These look like good changes anyway, and I'd be glad to accept more to get things working with VS2015 Update 2.  Do you have a093521890c7de705b645a8b5bc7ea76050565a7 which also fixed up some things for VS2015 Update 2?   I'm happy to either make these changes myself, or accept a pull request from you so that you get credit in the git history.

**Comment by qis** [comment]
I will deal with `tz.h` later. Right now I only need `date.h`.

Another issue is the removal of `floor`, `ceil`, `abd` and `round` functions from the VS2015 Update 2 `date.h` version. I fixed it by adding an `#else` case:

```
// VS Update 2 provides floor, ceil, round, abs in chrono.
#if _MSC_FULL_VER < 190023918
// ...
#else  // _MSC_FULL_VER < 190023918

using std::chrono::floor;
using std::chrono::ceil;
using std::chrono::round;
using std::chrono::abs;

#endif  // _MSC_FULL_VER < 190023918
```

**Comment by HowardHinnant** [comment]
That looks like a good change too.  Would you like me to make it, or would like to submit a pull request?

**Comment by qis** [comment]
Sorry, not much time on my hands. Also, it's not worth any credit, so please change it if you agree that it will improve usability. /)

**Comment by HowardHinnant** [comment]
No problem, I know the feeling.  I'll address this this weekend.  Thanks for your feedback.

**Comment by qis** [comment]
I've noticed that your `operator<<` for `year_month` uses the american format. Since you're already using the ISO 8601 for `year_month_day`, wouldn't it be reasonable to use the same international standard for `year_month` as well?

```
inline
std::ostream&
operator<<(std::ostream& os, const year_month& ym)
{
    detail::save_stream _(os);
    os.fill('0');
    os.flags(std::ios::dec | std::ios::right);
    os << ym.year() << '-';
    os.width(2);
    os << static_cast<unsigned>(ym.month());
    return os;
}
```

P.S.: Are capitalized names for months and weekdays set in stone? Any particular reason why?

**Comment by qis** [comment]
Another matter is a warning in MSVC for the following line:

```
const unsigned long long cl10 = std::ceil(log10(Period::den));
```

Since this cast is intentional and difficult to avoid, I think it should be made explicit:

```
const auto cl10 = static_cast<unsigned long long>(std::ceil(log10(Period::den)));
```

**Comment by HowardHinnant** [comment]
Full-blown formatting capabilities are relegated to the tz library: http://howardhinnant.github.io/tz.html#Formatting
That being said, the convenience streamers are mainly there for debugging purposes and not set in stone.

**Comment by HowardHinnant** [comment]
Thanks for the comment about the cast.  I will put that in.

**Comment by HowardHinnant** [comment]
I'm not following your comment regarding `time_point`.  `time_point` is supplied by the std `<chrono>` header, and is set in stone.  It has the operators you speak of.  Are you perhaps referring to `time_of_day`?

**Comment by HowardHinnant** [comment]
The syntax for defaulting to 24h mode is simply:
````
auto time = make_time(9h + 53min + 16s);
auto time2 = make_time(h + m + s);
````
where the second one is variables with units hours, minutes and seconds.

**Comment by HowardHinnant** [comment]
Closing.  Those parts that are going to be fixed have been fixed now.  If you wish to follow up with other points, please open a new issue for each point so it can be easily found.
