### ISSUE TITLE
Timezones rules

### ISSUE THREAD

**Issue by LesnyRumcajs** [HowardHinnant/date#473]
Is it possible using this library to get DST rules in a format represented in the `boost` library? (https://github.com/boostorg/date_time/tree/develop/data)

Namely extracting `DST Start Date rule` as e.g. "-1;5;9" - Last Friday of September or "2;1;3" - Second Monday of March. Same for the `DST End Date rule`. An addition to that the number of hours past midnight to add to these two.

I'm struggling to find such API that would expose it to me so I could update their data in a consistent manner.

**Comment by HowardHinnant** [comment]
Sorry, no there isn't.  The problem is that the UTC offset changes in the IANA database don't always follow such regular rules.  Sometimes they are just a one-time date for example.

I don't know if this helps, but given a UTC or local time point, and a time zone, you can find out the start date/time and end date/time for which that UTC offset / abbreviation pair is valid.

For example:
```
#include "date/tz.h"
#include <iostream>

int
main()
{
    using namespace date;
    using namespace std;
    using namespace std::chrono;
    auto info = current_zone()->get_info(system_clock::now());
    cout << "My current offset is " << info.offset << '\n';
    if (info.save == 0s)
        cout << "I am not in a daylight saving period.\n";
    else
        cout << "I am in a daylight saving period.\n";
    cout << "The current abbreviation is " << info.abbrev << '\n';
    cout << "This offset/abbreviation is valid in the range ["
         << info.begin << " UTC to " << info.end << " UTC)\n";
}
```
Which just output for me:
```
My current offset is -14400s
I am in a daylight saving period.
The current abbreviation is EDT
This offset/abbreviation is valid in the range [2019-03-10 07:00:00 UTC to 2019-11-03 06:00:00 UTC)
```

**Comment by mheiskan** [comment]
https://github.com/fmidev/smartmet-timezones/tree/master/bin has a script for creating the Boost timezone database from system tzdata.

**Comment by LesnyRumcajs** [comment]
@HowardHinnant Thanks for the explanation. That would explain weird errors I had with some timezones. Good to know.

@mheiskan Perfect, that's what I needed. Not sure however if changing the invented timezones to numeric ones will not break anything - but it's on IANA side. Thanks!
