### ISSUE TITLE
1 test is failing

### ISSUE THREAD

**Issue by HemilTheRebel** [HowardHinnant/date#496]
Just cloned the repo. This is what i did:

```
git clone https://github.com/HowardHinnant/date.git
cd date
mkdir build && cd build
cmake ../
cmake --build . --target testit -j4
```

Test 37 fails. The output is:
```
Start  37: date_test_pass_parse_test
 37/103 Test  #37: date_test_pass_parse_test ....................................Child aborted***Exception:   0.23 sec
```

I am on Fedora 30 running linux kernel 5.2.17 if that's something of interest

**Comment by HowardHinnant** [comment]
There are known bugs in gcc's libstdc++ `std::time_get` that can cause parse failures.  One way to work around them (if your application needs to) is to build with the macro ONLY_C_LOCALE defined to be 1.  This limits everything to the "C" locale, but avoids using `std::time_get`.

**Comment by HemilTheRebel** [comment]
I don't absolutely need it right now. Though i would use clang if I need it. Closing the issue.
