### ISSUE TITLE
error compiling with VStudio 2015 update 2

### ISSUE THREAD

**Issue by juandent** [HowardHinnant/date#50]
The following code:

```C++
CONSTCD11
inline
time_of_day<std::chrono::minutes>
make_time(std::chrono::hours h, std::chrono::minutes m, unsigned md) NOEXCEPT
{
    return time_of_day<std::chrono::minutes>(h, m, md);
}
```
gives me the following error:

**no suitable user-defined conversion from "std::chrono::hours" to "date::time_of_day<std::chrono::minutes>" exists		c:\Users\juan_\Documents\GitHub\date\date.h	3694**

**Comment by HowardHinnant** [comment]
Thanks for the report.  It sounds like VS-2015 may not be ready for inheriting constructors.  Does your code work if you adjust: https://github.com/HowardHinnant/date/blob/master/date.h#L3660 such that the `#else` clause is selected?

**Comment by juandent** [comment]
Yes indeed!! By avoiding inheriting the constructors the problem goes away!!

I just did this:

```C++
#if FALSE //!defined(_MSC_VER) || (_MSC_VER >= 1900)
    using base::base;
#else
```

**Comment by juandent** [comment]
So, it is a limitation for the current C++ compiler from Microsoft (VStudio 2015 Update 2)...
The fix is simple as per last comment.

**Comment by HowardHinnant** [comment]
Yes, I think so.  I will likely update the master branch later today with something along the lines of:
````
- #if !defined(_MSC_VER) || (_MSC_VER >= 1900)
+ #ifndef _MSC_VER
````
