### ISSUE TITLE
year, month day to std::chrono::system_clock::time_point

### ISSUE THREAD

**Issue by berge2007** [HowardHinnant/date#502]
I have a year, month, day number and I would like to convert on the fastest and simpliest way with this date library to std::chrono::system_clock::time_point

I have read the wiki and the documentation but I have not found any staightforward solution to this simple task.

Could you show me a way or relations how could I get time point from date components?

**Comment by HowardHinnant** [comment]
This will do it:
```c++
#include "date/date.h"

int
main()
{
    int y = 2019;
    int m = 10;
    int d = 30;
    std::chrono::system_clock::time_point tp = date::sys_days{date::year{y}/m/d};
}
```

**Comment by berge2007** [comment]
Thank you so much! This was an incredibly fast response.
