### ISSUE TITLE
PUBLIC_HEADER issue

### ISSUE THREAD

**Issue by MaximNM** [HowardHinnant/date#504]
Hello,

I'm facing with a PUBLIC_HEADER issue.

CMake Error at CMakeLists.txt:75 (set_target_properties):
  INTERFACE_LIBRARY targets may only have whitelisted properties.  The
  property "PUBLIC_HEADER" is not allowed.

How to resolve it?

**Comment by HowardHinnant** [comment]
Personally I don't use CMake for this library.  It introduces far more problems than it solves.  However there are others that might have some good ideas on how to fix this.  Hopefully they will chime in.

**Comment by elohim-meth** [comment]
Property PUBLIC_HEADERS for INTERFACE_LIBRARY is supported in cmake from version 3.15.
Until that you have to manually install header files:

```cmake
if(${CMAKE_VERSION}` VERSION_GREATER_EQUAL "3.15.0")
    set_target_properties( date PROPERTIES PUBLIC_HEADER include/date/date.h )
endif()

if(${CMAKE_VERSION} VERSION_LESS "3.15.0")
    install(
        FILES "${CMAKE_CURRENT_SOURCE_DIR}/include/date/date.h"
        DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/date )
endif()
```

**Comment by MaximNM** [comment]
@elohim-meth Thanks a lot!

@HowardHinnant Can somebody prepare a patch for it?

**Comment by HowardHinnant** [comment]
Yes please. ;-)
