### ISSUE TITLE
Feature request: Support for platform default wide char ( wchar_t )

### ISSUE THREAD

**Issue by pip3dr3am** [HowardHinnant/date#51]
First of all thank you Howard for your library - it solved my "calendrical programming hurdles" without a hickup. Nevertheless I think that the library should have intrinsic wchar_t support. In other words in adddition to the ostream overloads e.g 

std::ostream& operator<<(std::ostream& os, const day& d);
it should provide
std::wostream& operator<<(std::wostream& os, const day& d);

I was really surprised that simple code like:

auto ymd = 2016_y/feb/29
std::wcout << ymd << '\n';  // BOOM !

blew up on me. I found an (fast'n'ugly) workaround involving ostringstream and a conversion function 
char->wide char - but seriously - IMHO that shouldn't happen to your library users.
Especially since you might consider putting it up for Standardization ( ISO C++ ).

**Comment by HowardHinnant** [comment]
Ok, thanks for the feedback.  I was actually wondering if anyone would ever notice the lack of wide stream support.  Wide streams seem rarely used and I had actually started to wonder if anyone used them.  You have proven to me that somebody does. :-)  I will add wide stream support.

**Comment by pip3dr3am** [comment]
Wow! That's good news indeed! Looking forward to it :-) I think the main reason that nobody has come up with requesting wide char support is that most of your "users" are non Windows users. Every system call to the Windows OS is done in Unicode (UTF-16 LE => wchar_t in Windows). If you call the ANSI version of the OS call it will be translated to the Unicode version before being issued to the OS. If you have a lot of them (whatever the critical mass may be) it will make the application "slower". So I just code everything in wchar_t, live with the wasted one byte, but enjoy faster speed since I directly call the Unicode functions and avoid costly translations....

**Comment by HowardHinnant** [comment]
See if https://github.com/HowardHinnant/date/commit/76bef1fe014712c08bd0942c662613024e39d786 meets your needs.

**Comment by HowardHinnant** [comment]
Fixed.
