### ISSUE TITLE
Feature request : default constructor

### ISSUE THREAD

**Issue by coin-au-carre** [HowardHinnant/date#52]
Is it possible to make the default constructors available for some classes ? For instance, calling `date::year_month_day foo;` is not possible. 
I need this feature for serialization purpose.

The following changes work for my cases: 
```
class year_month_day
{
    date::year  y_{0};
    date::month m_{0};
    date::day   d_{0};

public:
    CONSTCD11 year_month_day() NOEXCEPT = default;
    [etc...]
```

If there is a good reason to prevent default ctor ? If yes, is there a workaround to achieve what I need ? Thanks!

**Comment by HowardHinnant** [comment]
Could you elaborate on why this doesn't work:
````
date::year_month_day foo = 0_y/0/0;
````

**Comment by coin-au-carre** [comment]
Indeed this works and I could avoid non default constructor by using something such as [this](http://www.boost.org/doc/libs/1_61_0/libs/serialization/doc/serialization.html#constructors).

However, for convenience and make the serialization works directly on the year_month_day structure, it would be very nice to provide a default constructor so that `date::year_month_day d;` can be called directly.

**Comment by HowardHinnant** [comment]
I appreciate your concern.  I am trying to balance that against the design this library takes which is to minimize the possibility for run time errors.  I'm concerned that the introduction of  a default constructor opens the door to a new category of run-time errors (uninitialized values).

**Comment by qis** [comment]
The values will be initialized, just not always to a valid state. It's a trade off and sometimes required. I had to add default constructors to be able to use them in conjunction with `std::optional` and `soci`.

https://gist.github.com/qis/9cb1e2654906c6d362a8819a55782397

Notice line 18-20. I can't see a way to work around it.

**Comment by HowardHinnant** [comment]
Thanks for the example.  The only way I see to work around it would be to specialize `type_conversion<std::optional<date::year_month_day>>`, which I would agree would be a bit laborious.

**Comment by qis** [comment]
Yes, and by adding default constructors, we can use the simple query API:

    date::year_month_day ymd;  // Don't have to provide a default value.
    sql << "SELECT birthday FROM users WHERE id = :id", into(ymd), use(id);
    // Throws if null since 'ymd' is not an std::optional.

**Comment by HowardHinnant** [comment]
If I add default constructors, I'm tempted to do them `chrono::duration` style:
````
date::year_month_day ymd1;  // uninitialized
date::year_month_day ymd2{};  // zero-uninitialized
````
Rationale:  I want `vector<year_month_day>(N)` to be fast, and having it write to all those bytes is no more correct.  Use `vector<year_month_day>(N, 1970_y/1/1)` if you want to pay for initialization.

**Comment by qis** [comment]
This looks like a very good solution.

**Comment by HowardHinnant** [comment]
Addressed in https://github.com/HowardHinnant/date/commit/b2df8cade5672d672a6f38830f937f7c9431f384
