### ISSUE TITLE
Should clock_cast be constexpr?

### ISSUE THREAD

**Issue by nanoric** [HowardHinnant/date#520]
Currently, clock_cast is not constexpr. But it can be.
Isn't it a good choice to make it constexpr?
In fact, besides clock_cast, lots of functions in tz.h can be constexpr.

**Comment by nanoric** [comment]
If constexpr is acceptable. I am happy to open an PR.

**Comment by HowardHinnant** [comment]
In general `clock_cast` can't be computed at compile-time because the conversion between `system_clock` and `utc_clock` depends on the list of leap seconds which is read in at run-time (and potentially even updated at run-time).

**Comment by nanoric** [comment]
There are not only system_clock and utc_clock.
For example I have a customize clock `` `MyClock```, which can convert to system_clock at compile-time.
But clock_cast prohibit me from doing so.

I am not a C ++ expert, here is my opinon:
Adding constexpr to clock_cast has no effect to the conversion between `` `utc_clock``` and` `` system_clock```. But enables compile-time conversion between `` `MyClock``` and` `` system_clock```.

Do you agree with it?

**Comment by HowardHinnant** [comment]
Have you implemented this?  What happens when you try to clock_cast from MyClock to utc_clock or gps_clock?

**Comment by nanoric** [comment]
Nothing happeded, just converted.
But since I know little about utc and gps time, I don't know if the result is correct.
Of cause, I can't use constexpr to specific the variable of  ```utc_clock```.
Here's my code snippet:
```c++
TEST(MyClock, clock_cast) {
    using namespace date;

    // 1970-1-1 09:30:00.000100
    constexpr date::sys_time<MicroSeconds> sys = make_sys_time(1970, 1, 1, 9, 30, 00, 100);
    constexpr std::chrono::time_point<MyClock, MicroSeconds> my =
        clock_cast<MyClock>(sys);
    /*constexpr */utc_time<MicroSeconds> utc = clock_cast<utc_clock>(my);
    /*constexpr */gps_time<MicroSeconds> gps = clock_cast<gps_clock>(my);
    cout << "utc: " << utc << endl;
    cout << "sys: " << sys << endl;
    cout << "gps: " << gps << endl;
    ASSERT_EQ(my.time_since_epoch().count(), 100);
    cout << "my: " << my.time_since_epoch().count() << endl;
}

```

Output:
```log
[----------] 1 test from MyClock
[ RUN      ] MyClock.clock_cast
utc: 1970-01-01 09:30:00.000100
sys: 1970-01-01 09:30:00.000100
gps: 1970-01-01 09:29:51.000100
my: 100
[       OK ] MyClock.clock_cast (24 ms)
[----------] 1 test from MyClock (24 ms total)
```

**Comment by HowardHinnant** [comment]
I'm happy to review a PR.  I don't yet know if this is something I want to do or not (sorry).  But at the very least, it is interesting, so thanks. :-)
