### ISSUE TITLE
Getting comma in year from date::format

### ISSUE THREAD

**Issue by xsacha** [HowardHinnant/date#525]
This does not seem like the correct formatting for a date and causes some of my tests to fail.

Relevant Setup:
```C++
    // Hack for Boost not supporting UTF-8 by default
    // Grab system locale
    auto localLocale = std::locale(""); // "en_US.UTF-8"
    std::locale::global(localLocale);
    boost::filesystem::path::imbue(localLocale);
```

Test that fails:
```C++
using namespace std::chrono;
const int64_t time = 1414586576382;
auto mtime = date::sys_time<milliseconds>((milliseconds)time);
date::format("%FT%T", mtime);
```

ValueOf: date::format("%FT%T", mtime);
Actual: "2,014-10-29T12:42:56.082"
Expected: "2014-10-29T12:42:56.082"

From the docs:
The %F I use expands to %Y.. where %Y has the issue
> %Y | The year as a decimal number. The modified command %NY where N is a positive decimal integer specifies the maximum number of characters to read. If not specified, the default is 4. Leading zeroes are permitted but not required. The modified command %EY interprets the locale's alternative representation.

It would seem I need %EY to get the locale's variant of the decimal number?

Am I doing something wrong?

Git hash: 48433b9892ac5741f8d4d8753beb76e49c57f7c8
OS: Amazon Linux 2 clean install, x64 with Clang 7

Workaround:
```C++
date::format(std::locale::classic(), "%FT%T", mtime);
```

**Comment by HowardHinnant** [comment]
You aren't doing anything wrong.  Thanks for the report!  Fixed on master tip-of-trunk.
