### ISSUE TITLE
Release plans

### ISSUE THREAD

**Issue by tegoo** [HowardHinnant/date#533]
I want to use the library, but I'm uncertain if I should use release sources tarball 2.4.1 or master branch. 2.4.1 was released almost 2 years ago and library is evolving. Do you plan to make new releases or should one just stick to master branch?

Thanks for the efforts put into the library. I'm looking forward to have it in my STL distribution, but unfortunately even LLVM version contains very restricted version for the moment.

**Comment by HowardHinnant** [comment]
My recommendation is to use tip-of-branch master.  I do my best to not allow any commit to break everyone's code.  If a breaking change does go in, it is fixed within hours.

**Comment by tegoo** [comment]
@HowardHinnant, thanks for the response. Clear. I close the ticket then.

**Comment by tegoo** [comment]
@HowardHinnant , as you suggested, I will stick to master branch. I have forked the repo, so that I will manually pull upstream changes to my project. Nevertheless, it would be much more better to have source code releases tarballs. I understand, that it requires regular effort from your side for executing release process. May be I could contribute some automation (cmake routines / ci scripts) to make it easier? Do you see anything I can help with here? Or have you decided not to do releases because of other reasons?

The reason I personally like tarball releases is that I can much more hard freeze dependency with integrity check:
```
fetch_lib(googletest
  URL "https://github.com/google/googletest/archive/release-1.10.0.tar.gz"
  HASH SHA256=9dc9157a9a1551ec7a7e43daea9a694a0bb5fb8bec81235d8a1e6ef64c716dcb
) 
```
