### ISSUE TITLE
date::parse() %b and %B have inconsistent functionality

### ISSUE THREAD

**Issue by connorjak** [HowardHinnant/date#539]
Contrary to the info here: [https://howardhinnant.github.io/date/date.html#from_stream_formatting](https://howardhinnant.github.io/date/date.html#from_stream_formatting), the %b and %B characters in the parse() format string have different functionality.

Code:

```
  using std::string;
  using namespace date;
  using namespace std::chrono;

  string timeStr = "2020-Jan-25 1:30:00";
  std::istringstream stream{ timeStr };
  sys_time<nanoseconds> tChosen;
  stream >> parse("%Y-%B-%d %T", tChosen);
  if (stream.fail())
      output->perror("[Timekeeper] Input time failed to parse: " + stream.str());
```

%b:
* "2020-Jan-25 1:30:00" parses
* "2020-January-25 1:30:00" does not parse successfully

%B:
* "2020-Jan-25 1:30:00" does not parse successfully
* "2020-January-25 1:30:00" parses

This may or may not come from me using `date.h` without using `tz.h`.
I'm compiling with CMake with C++14, gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1).

**Comment by HowardHinnant** [comment]
This is a bug in the gcc `std::get_time` function.  Please feel free to file one with them.  I do not recall if it is a duplicate or not at this point.

If you want to work around this bug, compile with `-DONLY_C_LOCALE`.  But this workaround is only effective if you are happy with the "C" locale.  The workaround assumes you only want results in the "C" locale and does _not_ call `std::get_time` to obtain the results.

FAQ:  https://github.com/HowardHinnant/date/wiki/FAQ#week_day_parse_bug

Here is the spec for `strptime`, which the spec for `std::get_time` reference for its detailed definition: https://pubs.opengroup.org/onlinepubs/009695399/functions/strptime.html

**Comment by connorjak** [comment]
Ok, thanks!

I wasn't able to find much more documentation/discussion about -DONLY_C_LOCALE. Will specifying that result in side effects outside of the date library?

**Comment by connorjak** [comment]
Also, found the GCC bug report: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=78714

**Comment by HowardHinnant** [comment]
No side effects that I'm aware of.

**Comment by connorjak** [comment]
Ok, good.

**Comment by HowardHinnant** [comment]
Bug report link:  Thanks!  I've added that to the FAQ.
