### ISSUE TITLE
Build fails on VS2019 when /Zc:__cplusplus defined

### ISSUE THREAD

**Issue by oviano** [HowardHinnant/date#542]
With VS2019, it's not enough to just set the project to C++17.

You also have to define the above (reference https://devblogs.microsoft.com/cppblog/msvc-now-correctly-reports-__cplusplus/)

This leads to a correct definition for __cplusplus, but then date.h fails with errors like this one:

`
template <class CharT>
CONSTCD14
inline
std::enable_if_t
<
    std::is_same<CharT, char>{},
    string_literal<char, 3>
>
msl(std::micro) NOEXCEPT
{
    return string_literal<char, 3>{"\xC2\xB5"};
}
`

syntax error: '<end Parse>'
syntax error: missing ';' before '{'

It seems to be referering to the line "std::is_same<CharT, char>{}" above.

**Comment by oviano** [comment]
Ok so the issue is in a couple of places std::is_same<>{} needs changing to std::is_same_v<>.

After that it builds.

I assume this is Microsoft not adhering to the C++17 standard or something?

This is VS2019, with std:c++17 and /Zc:__cplusplus.

**Comment by HowardHinnant** [comment]
Sounds like it's `constexpr` is still not conforming to C++11.  I'm going to guess that `std::is_same<>::value` also works (and is C++11-compatible).  Thanks for the report!  I didn't know about the need for `/Zc:__cplusplus`.

**Comment by oviano** [comment]
Yes the /Zc:__cplusplus caught me by surprise too, some other code was not working due to it, and of course Sod's law is that when I added the flag this code broke as a result :)

Anyway, seems like a trivial enough fix. Thanks.

**Comment by anarthal** [comment]
Hitting the same issue here. In my case the some other code was Boost.Asio, which also employs __cplusplus for feature detection.
