### ISSUE TITLE
Linker error when building with Visual Studio 2019 C++14

### ISSUE THREAD

**Issue by arginite** [HowardHinnant/date#544]
Have the following code in Visual Studio 2019 c++ 14 test project 
```
#include <iostream>
#include <date/date.h>
#include <date/tz.h>

int main()
{
    using namespace date;
    using namespace std::chrono;
    auto utc = system_clock::now();
    auto berlin = make_zoned("Europe/Berlin", utc);
    auto local = make_zoned(current_zone(), berlin);
    auto utc2 = berlin.get_sys_time();
    std::cout << format("%F %T %Z", utc) << '\n';
    std::cout << format("%F %T %Z", berlin) << '\n';
    std::cout << format("%F %T %Z", local) << '\n';
    std::cout << format("%F %T %Z", utc2) << '\n';

    std::cout << "Hello World!\n";
}
```

I get the following linker error
```
1>DateTest.cpp
1>DateTest.obj : error LNK2019: unresolved external symbol "class date::time_zone const * __cdecl date::locate_zone(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?locate_zone@date@@YAPEBVtime_zone@1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) referenced in function "public: static class date::time_zone const * __cdecl date::zoned_traits<class date::time_zone const *>::locate_zone(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?locate_zone@?$zoned_traits@PEBVtime_zone@date@@@date@@SAPEBVtime_zone@2@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
1>C:\Users\Administrator\source\repos\DateTest\x64\Debug\DateTest.exe : fatal error LNK1120: 1 unresolved externals
1>Done building project "DateTest.vcxproj" -- FAILED.
```

When I build the same project with c++17 it builds without issue.

Is there something I have missed to allow me to use date with c++ 14?

**Comment by HowardHinnant** [comment]
Here is where that function is defined in src/tz.cpp:

https://github.com/HowardHinnant/date/blob/master/src/tz.cpp#L3549-L3557

Either you are not compiling and linking to tz.cpp, or your compiled tz.cpp is using `HAS_STRING_VIEW == 1` and your `main` is using `HAS_STRING_VIEW == 0`.  This mismatch changes the signature of `locate_zone` between taking a `string` and a `string_view`.

**Comment by arginite** [comment]
Installed using vcpkg date::x64-windows-static.

**Comment by HowardHinnant** [comment]
Sorry, I can't help with vcpkg as I don't use it.

**Comment by mellery451** [comment]
the `date` CMake file picks c++17 by default so that's most likely what vcpkg got when it built/installed it. That means client code is going to have to use c++17 to be compatible. In theory, you can override `CMAKE_CXX_STANDARD` when configuring, but I'm not sure if there is an easy way to convince vcpkg to pass along this option (maybe a custom toolchain?).

**Comment by arginite** [comment]
Thanks guys it's a vcpkg package issue not date.
Fixed by changing CMAKE_CXX_STANDARD to 14 in the CMakeLists.txt for the package before building it

**Comment by HowardHinnant** [comment]
Thanks for this information!
