### ISSUE TITLE
zoned_time::get_local_time throws "Unknown error -1"

### ISSUE THREAD

**Issue by bambuk6** [HowardHinnant/date#553]
The following code (specifically, get_local_time()) throws an exception that says "Unknown error -1".

int main()
{
    auto current_time = std::chrono::system_clock::now();
    auto la = date::zoned_time{"America/Los_Angeles", current_time};
    auto sy = date::zoned_time{"Australia/Sydney", current_time};
    std::cout << date::format("%T\n", sy.get_local_time() - la.get_local_time());
}

**Comment by HowardHinnant** [comment]
What OS are you on?  If it is linux or mingw, try adding `-lpthread` to your compile.

**Comment by bambuk6** [comment]
Adding -lpthread fixes it.
