### ISSUE TITLE
Is it possible to build single tz.lib that can be linked with gccstdlib, libcxx, msvc stdlib?

### ISSUE THREAD

**Issue by denchat** [HowardHinnant/date#559]
I suspect that tz.lib design embeds std type in its template specialization.
```
lld-link: error: undefined symbol: private: struct date::sys_info __cdecl date::time_zone::get_info_impl(class std::__1::chrono::time_point<class std::__1::chrono::system_clock, class std::__1::chrono::duration<__int64, class std::__1::ratio<1, 1>>>) const
>>> referenced by C:\Users\User\AppData\Local\Temp\tz1-6368c9.obj:(main)
```
So tz.lib can't be linked with other std than one that built it.

Is it possible to have single tz.lib that can be linked with other std than one that built it?

**Comment by HowardHinnant** [comment]
Only if the two implementations promised ABI compatibility.  I don't think any of them do.

**Comment by denchat** [comment]
Okey. You may close this then.
