### ISSUE TITLE
date/tz.h date::zoned_time throws exception on calling any method

### ISSUE THREAD

**Issue by Alphastrick** [HowardHinnant/date#561]
I try to use `date/tz.h` and compiled tz.cpp as well as the example usage from the documentation.
Executing the example code leads to an error (std::system_error) at `std::cout << t << '\n';`

Is this error related to the build / system or do I miss something?

Using a differnt compile configuration (`AUTO_DOWNLOAD=1 HAS_REMOTE_API=1`) does work, but is not the way I want to go.

Example: 
```
#include "date/tz.h"
#include <iostream>

int
main()
{
    using namespace date;
    using namespace std::chrono;
    auto t = make_zoned(current_zone(), system_clock::now());
    std::cout << t << '\n';
}
```

Compiled library with
`g++ -Wall -g tz.cpp -I "../include" -DAUTO_DOWNLOAD=0 -DHAS_REMOTE_API=0 -DINSTALL=. -DUSE_OS_TZDB=1 -c -o libtz.a`

Compiled example with
`g++ -Wall -g main.cpp -I "../include" -L. -ltz -o app`

Exception
`Unknown error -1`

Used version
`latest master`

**Comment by HowardHinnant** [comment]
Try adding `-lpthread`.  More build instructions are here:  https://howardhinnant.github.io/date/tz.html#Installation

**Comment by Alphastrick** [comment]
Thank you very much. I missed it; Sorry.

**Comment by HowardHinnant** [comment]
Glad I could help.  Don't hesitate to ask if you have more questions.
