### ISSUE TITLE
Parsing fails when input subseconds are finer than time_point resolution

### ISSUE THREAD

**Issue by ecorm** [HowardHinnant/date#568]
This fails for me:
```c++
using TimePoint = std::chrono::system_clock::time_point;
std::string input{"2000-01-01T01:00:00.1234567Z"}; // 7 subsecond digits
std::istringstream iss{input};
TimePoint tp;
using Period = typename TimePoint::period;
std::cout << Period::num << ":" << Period::den << "\n"; // Outputs 1:1000000 (micro)
iss >> date::parse("%FT%TZ", tp);
assert(!!iss);
```
whereas it works when `input` is `2000-01-01T01:00:00.1234567Z` (6 subsecond digits).

Is this behavior intentional, to signal when the parser fails to process all subsecond digits? Is there an easy way I can discard the unusable subsecond digits gracefully? I don't care if it truncates or rounds the unused part (as long as it's consistent). My motivation is to use this in a communications protocol where there's nothing that guarantees all hosts will have the same subsecond resolution.

I came up with this workaround where I use `date::parse` to parse down to the minutes, then manually parse the seconds and `Z` suffix:
```c++
using TimePoint = std::chrono::system_clock::time_point;
std::string input{"2000-01-01T01:00:00.1234567Z"};
std::istringstream iss{input};
TimePoint tpDownToMinutes;
iss >> date::parse("%FT%H:%M:", tpDownToMinutes);
double secs = {};
char zone = {};
iss >> secs >> zone;
if (zone != 'Z')
    iss.setstate(std::ios::failbit);
auto seconds = std::chrono::duration<double>{secs};
using TimePointDuration = typename TimePoint::duration;
auto tp = tpDownToMinutes + std::chrono::duration_cast<TimePointDuration>(seconds);
std::cout << date::format("%FT%TZ", tp) << "\n";
assert(!!iss);
```

**Comment by HowardHinnant** [comment]
An easier way to do this is to parse into a `sys_time<nanoseconds>` and then round/truncate that into a `system_clock::time_point`.  I chose nanoseconds as that is the finest precision that any implementation uses for `system_clock::time_point`.

This will parse a _maximum_ of 9 fractional digits.  If there are less digits than that in the input, parsing of the fractional seconds stops without error, and proceeds to parse the `Z`.

```c++
using UniversalTimePoint = date::sys_time<std::chrono::nanoseconds>;
std::string input{"2000-01-01T01:00:00.1234567Z"}; // 7 subsecond digits
std::istringstream iss{input};
UniversalTimePoint utp;
iss >> date::parse("%FT%TZ", utp);
auto tp = date::round<TimePoint::duration>(utp);
```

To truncate into `system_clock::time_point` you can use any of:

*  `time_point_cast<system_clock::duration>(utp)`  // truncate towards the epoch
*  `floor<system_clock::duration>(utp)`  // truncate towards the past
*  `ceil<system_clock::duration>(utp)`  // truncate towards the future
*  `round<system_clock::duration>(utp)`  // truncate towards the nearest, to even on tie

**Comment by ecorm** [comment]
That should do nicely, thanks. Can you confirm that the parser failing when it finds unusable subsecond digits is the intended behavior? I can't find any mention of this in your documentation page, nor on cppreference.

**Comment by HowardHinnant** [comment]
Yes, it is the correct behavior, but not exactly for the reason you believe.  For example when `system_clock::duration` is `microseconds`, and there are 7 fractional seconds digits, a _maximum_ of 6 fractional digits are read.  So far no error.  Then the parser tries to parse the `Z` and finds a digit instead.  _That's_ what causes the error.  Without the `Z` on the end, the parse succeeds, and the last digit isn't consumed.

**Comment by ecorm** [comment]
I'm afraid this behavior of not consuming all significant digits is not consistent with the way regular floating point numbers are parsed via `std::istream`:
```
std::string input{"3.1415926535897932384626433832795028841971693Z"};
float pi; char zone;
std::istringstream iss{input};
iss >> pi >> zone;
std::cout << pi << zone << "\n"; // 3.14159Z
assert(!!iss);
```
But if the current `date::parse` behavior is already baked into the standard, then I guess my objections are moot. :smile:

**Comment by HowardHinnant** [comment]
I just checked the standard, and yes, this is baked in.  But while doing so I stumbled across a second solution that I had forgotten about:

```c++
using TimePoint = std::chrono::system_clock::time_point;
std::string input{"2000-01-01T01:00:00.1234567Z"}; // 7 subsecond digits
std::istringstream iss{input};
TimePoint tp;
iss >> date::parse("%FT%H:%M:%12SZ", tp);
```

This uses a "width modifier" on the `%S` command that says read up to 12 digits.  2 for the whole seconds, 1 for the decimal separator, and 9 for the fractional part.  With this technique, round-to-nearest is baked in.

**Comment by ecorm** [comment]
Awesome! I might increase it from 12 to the maximum digits possible from a 64-bit IEEE float.

**Comment by HowardHinnant** [comment]
I just reviewed the implementation.  It is using a `std::string` as a temporary input buffer, so it will handle however many digits you want.  But once the buffer grows beyond your small-string-optimization it will allocate memory geometrically to hold additional digits.  It does not reserve, so even if there is a large width specifier, it won't actually allocate until the input supplies the digits that require such allocation.

**Comment by ecorm** [comment]
Thanks for checking the implementation. The string growing "penalty" would only apply for pathological cases where the host formats the seconds with more precision than necessary. For Javascript hosts, it will likely be in milliseconds, and C++ hosts in milliseconds (or nanoseconds at the most).
