### ISSUE TITLE
An Efficient Way to Continually Check Timezone Difference as Time Passes

### ISSUE THREAD

**Issue by kevinkreiser** [HowardHinnant/date#569]
First off a huge thanks to @HowardHinnant and the contributors of this library. If it didn't exist our routing project would have been a failure. Now onto the question!

I'm here to ask about any possible tips for handling the issue mentioned in the title. More specifically, we have a router which computes time-dependent routes. In order to do so it must track the time of day as the router encounters streets in the road graph. The way this is implemented, we basically get the zoned start time of the route and increment it as we traverse and encounter new streets. Each time we encounter one we ask the question: do we need to offset the time of day in addition to the elapsed time because of our change in location (timezone changed). We need to know what the local time is so we can proprerly adhere to timed access or turn restrictions and look up things like transit schedules or historical traffic information. As you can see, knowing the local time as you move around the globe from an initial location at an initial time is crucial to our project's proper functioning.

I've recently been working on a long term performance optimization. This involves adding time tracking to another faster/more flexible algorithm. In doing so I noticed a severe degredation in performance once I did so but only when the time offset code was triggered by a change in timezone (lets ignore changes in DST for now). After looking into a bit I found that the primary culpret was continued calls to `get_info_impl` from a zoned timepoint. More information here: https://github.com/valhalla/valhalla/pull/2278#issuecomment-612319292

So I thought about it a little bit and tried to write a cache that should have a high hit ratio for my problem space. Specifically our algorithms evolve time either forward or backward from a time point and generally not by huge amounts. The characteristics of the algorithm mean that the elapsed time doesnt increase monotonically but you shouldn't usually be in any one timezone for more than a smaller number of hours generally always less than a day. Which means we are only concerned with 1 and very rarely 2 zonelets of a particular timezone. Anyway here is what my sample program looks like:

```c++
// g++ -std=c++14 -DUSE_CACHE -O2 tz_diff_cache.cpp third_party/date/src/tz.cpp -Ithird_party/date/include -lcurl
#include <cstdint>
#include <date/date.h>
#include <date/tz.h>
#include <unordered_map>

// for any one timezone we only expect usually a single sys_info in extreme cases near a change in
// time rules we could see 2 but its very unlikely
std::unordered_map<const date::time_zone*, std::vector<date::sys_info>> cache;

// use a cache to store already constructed sys_info's since they aren't cheap
const date::sys_info& from_cache(const auto& tp, const date::time_zone* tz) {
  // check if we have anything for this timezone in the cache
  auto tz_it = cache.find(tz);
  if (tz_it != cache.cend()) {
    // we have something in the cache, see if one of the infos has the particular time point in range
    auto st = date::floor<std::chrono::seconds>(tp.get_sys_time());
    auto info_it =
        std::find_if(tz_it->second.begin(), tz_it->second.end(), [&st](const date::sys_info& info) {
          return info.begin <= st && st <= info.end;
        });

    // if it was in the cache we return it
    if (info_it != tz_it->second.cend()) {
      // TODO: this is likely not the exact same timepoint that was used to construct this sys_info
      // TODO: do we need to modify the sys_info to account for the difference in timepoints
      // TODO: specifically is this needed to account for DST differing between the two timepoints
      return *info_it;
    }
  }

  // either this timezone is new or the right info for the range was missing so lets get it
  auto& infos = tz_it == cache.cend() ? cache.emplace(tz, std::vector<date::sys_info>{}).first->second
                                      : tz_it->second;
  infos.emplace_back(tp.get_info());
  return infos.back();
}

// given a time and two timezones, what is the offset in seconds between them
int64_t timezone_diff(const uint64_t epoch_seconds,
                      const date::time_zone* origin_tz,
                      const date::time_zone* dest_tz) {

  if (!origin_tz || !dest_tz || origin_tz == dest_tz) {
    return 0;
  }

  std::chrono::seconds dur(epoch_seconds);
  std::chrono::time_point<std::chrono::system_clock> tp(dur);
  const auto origin = date::make_zoned(origin_tz, tp);
  const auto dest = date::make_zoned(dest_tz, tp);

// The difference between using and not using cache is about 10x
#ifdef USE_CACHE
  const auto& origin_info = from_cache(origin, origin_tz);
  const auto& dest_info = from_cache(dest, dest_tz);
#else
  const auto origin_info = origin.get_info();
  const auto dest_info = dest.get_info();
#endif

  return std::chrono::duration_cast<std::chrono::seconds>(dest_info.offset - origin_info.offset)
      .count();
}

int main() {
  // for a really long route that crosses many timezone we end up doing a lot of tz diffing
  // the tuple is: number of calls, origin tz index, destination tz index
  // 0 is reserved for no timezone so we shift down by one to use them with the tzdb
  std::vector<std::tuple<int, int, int>> test_cases = {
      {6452, 335, 162},   {3645, 335, 168},   {5069, 335, 172},  {10504, 335, 178},
      {1018, 335, 183},   {2135, 335, 185},   {12963, 335, 19},  {11185, 335, 192},
      {3111, 335, 206},   {1376, 335, 215},   {879, 335, 224},   {15, 335, 225},
      {6, 335, 282},      {2, 335, 283},      {42752, 335, 292}, {721, 335, 293},
      {316, 335, 294},    {24172, 335, 295},  {40214, 335, 296}, {222265, 335, 297},
      {34260, 335, 298},  {31236, 335, 299},  {41881, 335, 3},   {22906, 335, 300},
      {3801, 335, 301},   {12679, 335, 302},  {10275, 335, 303}, {124, 335, 304},
      {15081, 335, 305},  {70057, 335, 306},  {2644, 335, 307},  {25880, 335, 308},
      {63690, 335, 310},  {236131, 335, 311}, {5204, 335, 312},  {198463, 335, 313},
      {1734, 335, 314},   {24245, 335, 315},  {327, 335, 316},   {52221, 335, 317},
      {47325, 335, 318},  {294048, 335, 319}, {31134, 335, 320}, {6659, 335, 321},
      {162188, 335, 322}, {1293, 335, 324},   {1810, 335, 325},  {7024, 335, 326},
      {22842, 335, 327},  {3140, 335, 328},   {3130, 335, 329},  {16, 335, 330},
      {832, 335, 331},    {45630, 335, 332},  {14803, 335, 333}, {1678, 335, 334},
      {952, 335, 336},    {26620, 335, 337},  {12772, 335, 5},   {20213, 335, 6},
      {123, 335, 7},      {2, 335, 8},
  };

  // for each test case
  const auto& db = date::get_tzdb();
  for (const auto& test_case : test_cases) {
    // the first part is how many iterations/calls to the diff method
    for (int i = 0; i < std::get<0>(test_case); ++i) {
      // the second two parts of the tuple are the origin tz index and the destination tz index
      auto d = timezone_diff(1586579654 + i * 15, &db.zones[std::get<1>(test_case) - 1],
                             &db.zones[std::get<2>(test_case) - 1]);
    }
  }

  return 0;
}
```

Basically I just check if I already got a `sys_info` whose range is valid for the current timepoint in the current zone, and if so I reuse it rather than try to get it again. My test case takes about 8 seconds to run without using the cache and takes about 800ms with the cache. Basically an order of magnitude improvement. Ok now, finally the questions:

1. Is this a reasonable approach or is there a better way to work around the overhead in `get_info`? I do have another option in my routing algorithm that would require a relatively large amount of extra storage so I'd rather not go with that approach if I can get caching or something else working.

2. What about DST? If I really wanted to handle DST properly would I need to modify the cached `sys_info` from a previous timepoint so that the differencing of the `offset` would work properly? I looked at how the `sys_info` is constructed but I'm not exactly sure how I would modify one from an existing timepoint to match a different timepoint that is in the same zonelet rule range (see the TODO in the sample code).

Thanks again for the amazing work, I can't wait to see its inclusion in the STL some day!

**Comment by HowardHinnant** [comment]
Very interesting!

This is a reasonable approach.

---

Rarely occurring bug:

```c++
return info.begin <= st && st <= info.end;
```

Should be:

```c++
return info.begin <= st && st < info.end;
```

`[info.begin, info.end)` is a half-open range.  `info.end` is the start of the _next_ valid range.

---

```c++
// TODO: this is likely not the exact same timepoint that was used to construct this sys_info
// TODO: do we need to modify the sys_info to account for the difference in timepoints
// TODO: specifically is this needed to account for DST differing between the two timepoints
```

You're ok here.  You can remove the `TODO`s.  When the DST changes (or more generally, when the UTC offset changes) for a `time_zone`, then a new `sys_info` is formed with a new `[begin, end)` for which that `offset` is valid.

---

Does your platform supply a zic-compiled binary time zone database?  This is commonly done on linux, macOS, BSD, android, iOS, ... really everything except Windows.

If not, can you use the code at https://www.iana.org/time-zones to compile the tz database into binary form and ship that instead of the text form of the database?  If it is supplied it may be somewhere such as `/usr/share/zoneinfo` and contain files such as:

```
+VERSION	CET		Eire		GMT0		Japan		Navajo		Turkey		posixrules
Africa		CST6CDT		Etc		Greenwich	Kwajalein	PRC		UCT		zone.tab
America		Canada		Europe		HST		Libya		PST8PDT		US
```

If these files come on your platform, or if you can install them, they will give you a large performance boost.  You can access them (if they exist) by compiling with `-DUSE_OS_TZDB`.  My experiments are showing a factor of 5x faster than with `-DUSE_CACHE`, so there's a big carrot there.

**Comment by kevinkreiser** [comment]
Thanks for the pointer on the half-open range!

And thank you very much for clearing up my TODOs on the DST. I tricked myself when debugging how the zonelets were used. I was looking at the changes in rules that they represent and noticed the dates when the rules went into and out of effect. For some reason these dates stuck in my mind as the values for `sys_info::begin` and `sys_info::end`, but now I realize that when the `sys_info` is constructed from the zonelets rule information it must account for the beginning and end of DST and set them using that information.

Wow,  yeah I just tried `-DUSE_OS_TZDB` and its another order of magnitude faster! For those platforms that wouldn't have this data, is there a way to configure the date library to look in a specific place for it or even bundle it as an in memory vector of bytes I could feed in? I guess my main question would be, what would you recommend on windows or the like? I suppose in the very worst case I could do a hack like before where I turn the binary into a header and monkey patch tz.cpp to use it to load the db information from the string in the header. Unless you reckon windows wont suffer from any performance issues with its xml tz db?

Thanks again for all of your help!

**Comment by HowardHinnant** [comment]
Currently the library isn't set up to handle a user-located binary database.  All of the code is there (the binary reader).  But there is only code to look for the binary database in places where the OS would put it.  And on Windows the binary reader is currently completely @ifdef'd out.

I don't currently have a good recommendation for Windows.  With any luck the VS team is busy implementing this for C++20 at this time (I don't know that).  Once your C++ vendor provides it, this library can be relegated to the dustbin.

On Windows the only use of the xml file is to translate a Windows time zone name to a IANA time zone name, and this only happens under `current_zone()`.  I.e. when you call `current_zone()`, the library asks windows what it's current time zone is, and then uses the xml file to translate that name to a close approximation IANA name.  Then from there on out the IANA database is used.  At least in your test you never call `current_zone()`, and so you never interact with the xml file at all.

**Comment by kevinkreiser** [comment]
Make sense to me, thanks again for all of your help!

**Comment by kevinkreiser** [comment]
I shouldnt have closed this! I have 2 more questions:

1. if i compile with `USE_OS_TZDB` on windows should everything still work? even if i also specify: `HAS_REMOTE_API=0` and `AUTO_DOWNLOAD=0`?
2. are the indices of a particular tz in the tzdb the same across platforms? or do they depend on the data source?

**Comment by HowardHinnant** [comment]
No worries!

1.  I doubt it will compile on Windows with `USE_OS_TZDB=1`, however I don't have a Windows machine to try this on, so I'm not 100% positive.  If it does compile, it definitely won't work.  You would get a run-time error the first time the time zone database is accessed because it won't be able to find the OS-supplied binary database.

2.  The indices aren't portable.  With `USE_OS_TZDB=0`, the indices would be portable as long as the database version remains the same.  But the indices are not portable across database versions.  With `USE_OS_TZDB=1`, different platforms zic-compile the database differently, and they all add their own little tweaks.  This will impact things like custom esoteric timezones that a platform might add or remove, subsequently impacting the number of timezones in the database, and thus their indices.

**Comment by kevinkreiser** [comment]
Ok cool, that answers my questions completely, thank you once again for all of your help!
