### ISSUE TITLE
test/iso_week tests fails in GCC when using explicit conversion operator { }

### ISSUE THREAD

**Issue by nico-engels** [HowardHinnant/date#57]
The files weekday.pass.cpp, weeknum.pass.cpp and year.pass.cpp have [explicit conversions](http://en.cppreference.com/w/cpp/language/explicit) using the [braced-init-list (C++11)](http://en.cppreference.com/w/cpp/language/explicit_cast), which gcc does not support. Generating erros like the following:

`year.pass.cpp:89:33: error: cannot convert ‘iso_week::year’ to ‘int’ in initialization
     static_assert(int{year{2015}} == 2015, "");`

Changing that to `static_cast<T>()` resolves the "problem". Like is done in test/date_test/day.pass.cpp:71. Clang accepts the code, that I think is the correct behavior but I am not totaly certain. There is a [bug report 51553](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=51553) on gnu-bugzilla.

Is this change ok? If you let me, I can make a PR... Thank you, the lib is awesome!
Oh.. I am using GCC 5.3 on Mingw64

Nicolas

**Comment by HowardHinnant** [comment]
Thanks Nicolas!  I've been wavering between keeping it as it is to encourage it to get fixed by gcc, and working around it here to encourage adoption of `date`.  The bug is so old I'm surprised they haven't fixed it yet.

**Comment by HowardHinnant** [comment]
Here is the original of this issue: https://github.com/HowardHinnant/date/issues/39
