### ISSUE TITLE
format sets stream exception mask

### ISSUE THREAD

**Issue by ecorm** [HowardHinnant/date#570]
I was surprised to notice that `format` sets the exception ~~flags~~ mask on `std::basic_ostream` behind my back. I don't think this is acceptable from a user perspective. I'm trying to find what the C++20 standard says about this, but I can't find the relevant text.

**Comment by ecorm** [comment]
First instance where format sets the exception mask: https://github.com/HowardHinnant/date/blob/a2fdba1adcb076bf9a8343c07524afdf09aa8dcc/include/date/date.h#L6006

**Comment by HowardHinnant** [comment]
This is consistent with how C++98-C++17 treats formatting errors: http://eel.is/c++draft/ios.iostate#tab:ios.iostate

But it is inconsistent with C++20's `std::format`.  This library has not been integrated with the `fmt` library.

**Comment by ecorm** [comment]
I'm sorry, I don't see anything mentioned about the **exception mask** in the text you cited.

To be clear, it's not the setting of the `std::ios::failbit` I have a problem with, it's the forced enabling of **exceptions** on the `basic_ostream`.

**Comment by ecorm** [comment]
I apologize, I meant to say "exception mask" in my original post, not "exception flags".

**Comment by ecorm** [comment]
Sorry again, huge brainfart on my part. :stuck_out_tongue:   I thought

```c++
os.exceptions(std::ios::failbit | std::ios::badbit);
```
was setting the exception mask on `std::cout`, but I see now that it's setting the exception mask on the basic_ostringstream you use **internally** to generate the formatted string.

**Comment by ecorm** [comment]
I will close this train wreck of an issue and will open a new one about `date::format` throwing a `std::ios::failure`.

**Comment by ecorm** [comment]
New issue: #571
