### ISSUE TITLE
Incorrect ISO 8601 UTC offet sign parsing

### ISSUE THREAD

**Issue by Masterkatze** [HowardHinnant/date#586]
Hello

When using date::parse, if the offset is negative and specified only in minutes then the minus sign is not taken into account

```
auto Parse(const std::string &str) {
  std::istringstream in{str};
  date::sys_seconds time_point;
  in >> date::parse("%FT%T%Ez", time_point);
  return time_point.time_since_epoch().count();
}

std::cout << Parse("2019-04-02T13:15:39+01:11") << std::endl; // 1554206679 ok
std::cout << Parse("2019-04-02T13:15:39-01:11") << std::endl; // 1554215199 ok
std::cout << Parse("2019-04-02T13:15:39+00:11") << std::endl; // 1554210279 ok
std::cout << Parse("2019-04-02T13:15:39-00:11") << std::endl; // 1554210279 wrong

```

**Comment by HowardHinnant** [comment]
Hi.

I'm guessing that you have a checkout that does not contain this commit: https://github.com/HowardHinnant/date/commit/5d15157bbb980817b532b2b96d8b19964204ab78

This commit is about two years old.  I recommend pulling tip-of master.

**Comment by Masterkatze** [comment]
Oh, I was using tag v2.4.1 (latest at the moment of project starting). In v3.0.0 this bug is fixed, thanks!
