### ISSUE TITLE
constexpr in "decimal_format_seconds::width" 

### ISSUE THREAD

**Issue by lsmith999999** [HowardHinnant/date#587]
Should "constexpr" be changed to CONSTDATA instead?

**Comment by HowardHinnant** [comment]
Good catch.  Fixed with fe2f9c7eacae8cbe4633d9821581e7caebfc40e9

**Comment by lsmith999999** [comment]
Thanks (and for the quick turnaround), but can't take credit. Testing your library with various compilers and an earlier one choked on it (Visual Studio 2013).

Nice contribution BTW (appreciate it!)
