### ISSUE TITLE
error: operator '!' has no right operand (ONLY_C_LOCALE)

### ISSUE THREAD

**Issue by nschloe** [HowardHinnant/date#589]
I get some weird errors when trying to compile with date.h:
```
/usr/include/date/date.h:3783:19: error: operator '!' has no right operand
 3783 | #if !ONLY_C_LOCALE
[...]
```
(For full details: https://launchpadlibrarian.net/488835127/buildlog_ubuntu-focal-amd64.waybar_0.9.2-202007161902-0fe0a856-1focal1_BUILDING.txt.gz.)

Seems like the `ONLY_C_LOCALE` is not defined, but I see
```c++
  #ifndef ONLY_C_LOCALE
  #  define ONLY_C_LOCALE 0
  #endif
```
towards the top of `date.h`.

Any idea what might be wrong?

**Comment by HowardHinnant** [comment]
This is a bug in the build system.  Search for "`-DONLY_C_LOCALE=` in the build log you have.  This is setting `ONLY_C_LOCALE` to "".  The header date.h expects it to be set to 0 or 1, and if not defined, defaults it to 0.

**Comment by nschloe** [comment]
You're right, thanks for looking into it!

**Comment by nschloe** [comment]
Will need to reopen this. Can it be that the faulty definition comes from
```cmake
target_compile_definitions( date INTERFACE
    #To workaround libstdc++ issue https://github.com/HowardHinnant/date/issues/388
    ONLY_C_LOCALE=$<IF:$<BOOL:${COMPILE_WITH_C_LOCALE}>,1,0>
    $<$<BOOL:${DISABLE_STRING_VIEW}>:HAS_STRING_VIEW=0> )
```
in date's `CMakeLists.txt`?

**Comment by HowardHinnant** [comment]
Could be.  I don't really know CMake and personally avoid it whenever I can.  If you've got a fix for this, I'd be happy to take it.

**Comment by nschloe** [comment]
I need to create a Debian build for date which includes `tz.h`. Doing as if there were only `.c` and `.h` will create the need for a lot of extra code that I'd rather avoid (because I don't know Debian's build system well enough).

**Comment by nschloe** [comment]
Okay, in the output `dateTargets.cmake`, one finds
```cmake
INTERFACE_COMPILE_DEFINITIONS "ONLY_C_LOCALE=\$<IF:\$<BOOL:OFF>,1,0>;\$<\$<BOOL:OFF>:HAS_STRING_VIEW=0>"
```
which looks really fishy. This should probably be
```cmake
INTERFACE_COMPILE_DEFINITIONS "ONLY_C_LOCALE=0"
```
