### ISSUE TITLE
operator<< prints milliseconds if time_point is returned from function

### ISSUE THREAD

**Issue by igagis** [HowardHinnant/date#591]
Consider the following test program

```cpp
#include <iostream>

#include "date.h"

std::chrono::system_clock::time_point get_now(){
    using date::floor;
    return floor<std::chrono::seconds>(std::chrono::system_clock::now());
}

int main(int argc, const char** argv){
    using date::floor;
    using date::operator<<;

    std::cout << "now = " << floor<std::chrono::seconds>(std::chrono::system_clock::now()) << std::endl;
    std::cout << "get_now() = " << get_now() << std::endl;

    return 0;
}
```

Expected result:
```
now = 2020-07-17 11:00:54
get_now() = 2020-07-17 11:00:54
```

Actual result:
```
now = 2020-07-17 11:00:54
get_now() = 2020-07-17 11:00:54.000000000
```

Testing with `g++`:
```
$ g++ --version
g++ (Debian 8.3.0-6) 8.3.0
```

**Comment by HowardHinnant** [comment]
In:
```c++
std::chrono::system_clock::time_point
get_now()
{
    using date::floor;
    return floor<std::chrono::seconds>(std::chrono::system_clock::now());
}
```

you are converting from `nanoseconds`-precision to `seconds`-precision with the `floor`, and then implicitly converting back to `nanoseconds`-precision in converting to the return type: `std::chrono::system_clock::time_point`.

The fix is to correct your return type.  There are two easy ways to do this:

1.  If you are using C++14 or better, the return type can be `auto`.

```c++
auto
get_now()
{
    using date::floor;
    return floor<std::chrono::seconds>(std::chrono::system_clock::now());
}
```
2.  Or you can explicitly specify a `seconds`-precision `time_point`:

```c++
date::sys_seconds
get_now()
{
    using date::floor;
    return floor<std::chrono::seconds>(std::chrono::system_clock::now());
}
```

**Comment by igagis** [comment]
Ok, understood. I though that `operator<<()` chooses formatting based on some heuristics, like checking if milliseconds are 0 then do not print those.

This is actually confusing that `floor()` function changes the type. I'd expect that `floor()` returns the same type as its argument, but 'floored' value of it.

Then there would be a type conversion constructor `sys_seconds(const time_point&)` to convert it to that type for `operator<<` to avoid printing milliseconds.

**Comment by HowardHinnant** [comment]
Think of `floor` as the same as `time_point_cast`, except that `time_point_cast` rounds up towards the epoch for values prior to the epoch, and `floor` rounds down towards the past for values prior to the epoch.  `floor` (and `round` and `ceil`) are just alternative rounding modes for `time_point_cast` and `duration_cast`.

**Comment by igagis** [comment]
Sure, I understand that. But my point was that people would not expect that functions with names `floor()`, `ceil()` and `round()` perform any type casting.

I have just started using the library and it seems good, but so far my impression is that a bit more verbosity to function and type names would make it even better.
