### ISSUE TITLE
Why aren't members "y_", "m_" and "d_" in classes "year", "month" and "day" initialized to zero in the default constructor

### ISSUE THREAD

**Issue by lsmith999999** [HowardHinnant/date#594]
Unless the rules have changed in recent years, class members of fundamental (non-class) type aren't initialized by default constructors. Members "y_", "m_" and "d_" for these particular classes will therefore contain random values (garbage) after default construction (so calls to "Ok()" won't be reliable for instance). Other classes that encapsulate these members (most notably "year_month_day") are therefore impacted as well. Use of the "default" keyword on default constructor declarations doesn't change the situation AFAIK (but I haven't double-checked the standard - I wouldn't think so though).

If I'm missing something you'll let me know of course, though my testing with MSFT compilers for instance does seem to confirm the situation (these members contain random values after default construction, though other compilers I tested usually set them to zero - unless I'm wrong about the "default" keyword though, the language doesn't mandate that, assuming things haven't changed in recent years).

Thanks.

**Comment by HowardHinnant** [comment]
The rationale is to give you the choice between "not initialized" and "zero initialized".  This is also consistent with the design of `std::chrono::duration`, but unfortunately not `time_point` (my fault).

Here is the syntax to choose "not initialized":
```c++
year y;
```

Here is the syntax to choose "zero initialized":
```c++
year y{};
```

It is the use of `= default` that makes this choice possible to offer.  And the design is viral in that it propagates up:

```c++
year_month_day ymd;    // not initialized
year_month_day ymd{};  // 0_y/month{0}/day{0}
```

**Comment by lsmith999999** [comment]
Ah, I see, thanks. Issue seemed so glaring it was hard to believe you would have missed it (but initializing built-in members was drilled into me so many years ago now that it automatically raised a red flag the moment I saw it).

Anyway, thanks for setting me straight.
