### ISSUE TITLE
Wiki Page for Recipes and Examples

### ISSUE THREAD

**Issue by ecorm** [HowardHinnant/date#6]
@HowardHinnant , what do you think of creating a [Wiki page](https://github.com/HowardHinnant/date/wiki) for users to share examples and recipes? I already have a couple of (trivial) examples I'd be willing to share. This recipes page could be an incubation area for future algorithms to be added to the library.

The wiki area for this repo already allows GitHub members to make changes (you can change those permissions, BTW). But I thought it would be polite to ask before adding stuff to the wiki.

**Comment by HowardHinnant** [comment]
That's an awesome idea!  Can you set that up, or do you need me to start it?  (I'm still a github newbie).

**Comment by ecorm** [comment]
I went ahead and set it up. Click on the little book icon on the right to view the Wiki home page.

Feel free to reorganize things and improve on my examples. GitHub has an online editor for Wiki pages, which supports Markdown format.

**Comment by HowardHinnant** [comment]
Looks good to me, thanks!  Do you think it would be a good idea to "sign" your examples by putting a link back to your github page?  That might encourage others to contribute, and it will also let them know that it is ok to do so.

**Comment by ecorm** [comment]
Yes, that's a good idea. I'll go ahead and do that.

**Comment by ecorm** [comment]
There should also be some notice that by adding a contribution, they agree that their contribution is henceforth released under some license of your choosing (CC BY 4.0, I presume). I would prefer if you wrote that notice yourself, if you don't mind.

**Comment by ecorm** [comment]
I can add the following footer to the Wiki page:

> This work is licensed under a Creative Commons Attribution 4.0 International License. (CC logo)

Do you want me to go ahead and add that?

**Comment by HowardHinnant** [comment]
Sure, that sounds good, thanks.

**Comment by ecorm** [comment]
Done.
