### ISSUE TITLE
parse for seconds fraction as per 8601/3339

### ISSUE THREAD

**Issue by ranjithpp** [HowardHinnant/date#606]
what is the format to pass in the parse function so to work with timesec fraction
example time given, as below
  1. 1985-04-12T23:20:50.**52**Z {this is in UTC with second fraction where second fraction
                              can be 1*DIGIT as per ABNF, means minimum 1 DIGIT and max can be any}

**Comment by HowardHinnant** [comment]
You'll have to choose a maximum number of fractional digits.  I recommend that maximum be no higher than 9.  9 fractional digits gives you nanosecond precision.  And as a practical matter, unless you take special care, this `time_point` is going to be stored with signed 64 bits.  At nanoseconds precision, you've got a range of +/-292 years centered on 1970-01-01.  If you try another digits, forming 1/10 nanosecond precision, your range drops to +/-29.2 years centered on 1970-01-01, making overflow inevitable.

```c++
#include "date/date.h"
#include <iostream>
#include <sstream>

int
main()
{
    using namespace date;
    using namespace std;
    using namespace std::chrono;

    istringstream in{"1985-04-12T23:20:50.52Z"};
    sys_time<nanoseconds> tp;
    in >> parse("%FT%TZ", tp);
    cout << tp << '\n';
}

```

Output:

```
1985-04-12 23:20:50.520000000
```

If the +/-292 year range is not large enough for your application, you will either need to coarsen the precision (which drops the max allowable number of digits), or you will need to create a duration with a greater range and use that, e.g.:

```c++
    using picoseconds = duration<__int128_t, pico>;
    sys_time<picoseconds> tp;
    // ... as before
```

**Comment by ranjithpp** [comment]
Thanks for supersonic fast response! and details. it really helps. and this library is a gem !
I found this https://github.com/HowardHinnant/date/issues/511  and about to close the  issue.
