### ISSUE TITLE
Sub-seconds dropped when parsing to sys_time<duration<double>>

### ISSUE THREAD

**Issue by ecorm** [HowardHinnant/date#613]
Given the following:

```
std::string str{"1970-01-01T00:00:01.123456"};
std::istringstream iss(str);
date::sys_time<std::chrono::duration<double>> t;
iss >> date::parse("%FT%H:%M:%9S", t);
std::cout << "ticks: " << std::fixed << t.time_since_epoch().count() << "\n";
```
The output is `1.000000` where I would expect it to be `1.123456`, given the `double` representation.

The loss of sub-second digits seems to be caused by the `round` function on this line: https://github.com/HowardHinnant/date/blob/3cbfa4318fc6b43c27e0d1302a2a59cfea4b6e68/include/date/date.h#L7019

and again on this line: https://github.com/HowardHinnant/date/blob/3cbfa4318fc6b43c27e0d1302a2a59cfea4b6e68/include/date/date.h#L7767

The parsing implementation seems to be "unaware" of a floating point representation being more precise than the `duration`'s period.

At those two lines, if I conditionally use `duration_cast` instead of `round` when `std::chrono::treat_as_floating_point` is true, then I get the expected result.

**Comment by ecorm** [comment]
Probably related to this: when parsing to `sys_time<duration<double, ratio<3600>>`, the minutes and seconds are ignored.

If the importance of parsing to a floating-point representation is in question, keep in mind that Javascript uses floating point numbers to represent time points. A C++ server may wish to use the same floating point representation, for whatever reason.

**Comment by HowardHinnant** [comment]
I think I need a different compile-time branch to parse double-based seconds.  `round` must be used when `Duration` is integral-based, and must _not_ be used when `Duration` is floating-point based.

**Comment by ecorm** [comment]
In my own code, I use something called `round_if_integral` that either `round`s or `duration_cast`s depending on `std::chrono::treat_as_floating_point` using `true_type` / `false_type` tagged dispatching. That may (hopefully) be only be the place you need to compile-time branch when parsing.

The reason why I have `round_if_integral` is that I have a "fallback to the fallback" in my (in-progress) serialization library that reverts to parsing via `std::get_time` if neither C++20 date or hinnant/date is detected. I then use your [days_from_civil](https://howardhinnant.github.io/date_algorithms.html#days_from_civil) to do the conversion to `sys_time`.

**Comment by HowardHinnant** [comment]
Yes, that's the approach I'm working on now.  Though the `duration_cast` is unnecessary when floating is true.  I'm calling it `detail::round_i`.  More cryptic name, but not part of the public API anyway.

**Comment by ecorm** [comment]
Does the `duration_cast` get optimized away when used unnecessaraily when floating is true? Not asking for your `detail::round_i` implementation, but for my `round_if_integral` implementation.

**Comment by HowardHinnant** [comment]
Not optimized away, but applied implicitly.  So removing the `duration_cast` won't change the generated code.  It just simplifies the source.

**Comment by ecorm** [comment]
Thanks! I can confirm that the fix works for me with floating point reps, and didn't break my parsing to integrals reps.

**Comment by ecorm** [comment]
I'll contribute some test cases for floating point formatting/parsing when I have the chance.

**Comment by HowardHinnant** [comment]
That'd be great, thanks!
