### ISSUE TITLE
spack recipe

### ISSUE THREAD

**Issue by gmgunter** [HowardHinnant/date#615]
Would you mind if I submitted a recipe for date to the [spack](https://github.com/spack/spack) package manager?

This is what I'm intending to contribute: 
https://github.com/gmgunter/spack/blob/date-pkg/var/spack/repos/builtin/packages/date/package.py

**Comment by HowardHinnant** [comment]
I don't mind at all.

**Comment by gmgunter** [comment]
Great, thanks!

https://github.com/spack/spack/pull/19515
