### ISSUE TITLE
negative months added

### ISSUE THREAD

**Issue by user1095108** [HowardHinnant/date#617]
I have been having issues with date::year_month_day, when adding negative month durations. The issue was resolved by subtracting positive month durations, but it may be this is undesired.

**Comment by HowardHinnant** [comment]
Good you give an example?

**Comment by user1095108** [comment]
I have these 2 functions:

```
using cperiod_t = std::chrono::seconds;
using tp_t = std::chrono::system_clock::time_point;

tp_t add(cperiod_t cp, tp_t tp) noexcept;
tp_t sub(cperiod_t cp, tp_t tp) noexcept;
```
I implemented sub() by adding negative cp, which caused problems with monthly and yearly periods. Then I implemented sub() by changing all additions into subtractions and everything started to work, seemed like some sort of overflow issue. I didn't look into this further but I'll do so now.

**Comment by HowardHinnant** [comment]
If you could give me just one concrete example where you added or subtracted two values, and tell me what you got and what you expected, that would be most helpful, thanks.  If it is a bug, I'll fix it.  If it isn't a bug, I'll explain why.

**Comment by user1095108** [comment]
After poking around a bit, it seems it was my code, that got confused with a negative duration. The problem was in comparing the provided duration, with positive durations and obviously a negative duration is smaller than all of them. After comparing with an absolute value duration everything started working. I'll look into my problem more deeply before posting here next time. Thank you.

**Comment by HowardHinnant** [comment]
Thanks for the update.  And no problem posting here, just for questions on using this stuff.
