### ISSUE TITLE
`date::format` not printing fractional seconds as expected (or parsing negative dates on Linux)

### ISSUE THREAD

**Issue by ddevienne** [HowardHinnant/date#621]
Hi. I'm using `date::format("%Y-%m-%dT%T", tp)`, where
> %T | Equivalent to %H:%M:%S.

and given (from https://howardhinnant.github.io/date/date.html#to_stream_formatting):
> %S | Seconds as a decimal number. If the number of seconds is less than 10, the result is prefixed with 0. If the precision of the input can not be exactly represented with seconds, then the format is a decimal floating point number with a fixed format and a precision matching that of the precision of the input (or to a microseconds precision if the conversion to floating point decimal seconds can not be made within 18 fractional digits). The character for the decimal point is localized according to the locale. The modified command %OS produces the locale's alternative representation.

I was expecting:

1. No fractional seconds for time-points which can be represented exactly with seconds
2. At most 6 digits for time-points which have micro-seconds precision, not 7.

I'm using VS2019 (16.7.6) in C++17 and warning-as-error mode, and #include as below:
```
#define HAS_STRING_VIEW 1
#define HAS_UNCAUGHT_EXCEPTIONS 1
#include <date/date.h>
```

Am I using the library incorrectly?
Or is the doc wrong?
Shouldn't the results be portable across platforms/compilers?

The test below passes on Win10 with VC2019, but the `date::format()` is not behaving exactly as I was expecting,
from reading the documentation, as described above.

I also tried the same test on Red-Hat 7.5 with GCC 9 in C++17 mode as well, and there I get
different results, 9 fractional digits instead of 7 (breaking the test as written), but worse,
the negative date test yields different results:
```
/.../ChronoUtilsTests.cpp(103): error: in "ChronoUtilsTests/test_date_parse_and_format": check out == tc.expected_out has failed [2016-06-13T09:36:34.000000000 != 2016-06-13T09:36:34.0000000]
...
"ChronoUtilsTests/test_date_parse_and_format": check out == tc.expected_out has failed [2016-06-13T09:36:34.123456000 != 2016-06-13T09:36:34.1234560]
...
/.../ChronoUtilsTests.cpp(97): error: in "ChronoUtilsTests/test_date_parse_and_format": -2001-10-26T21:32:52: 3840374087966861 != -125286834428000000
/.../ChronoUtilsTests.cpp(103): error: in "ChronoUtilsTests/test_date_parse_and_format": check out == tc.expected_out has failed [2091-09-11T18:34:47.966861312 != -2001-10-26T21:32:52.0000000]
...
```

```
const struct {
    std::string input;
    int64_t expected_val; // -1 for expected to fail
    std::string expected_out;
} test_cases[] {
    // From https://sqlite.org/forum/forumpost/4a658e3adc?t=h
    { "2016-06-13T09:36:34",            1'465'810'594'000'000
    , "2016-06-13T09:36:34.0000000" },
    { "2016-06-13T09:36:34Z",           1'465'810'594'000'000
    , "2016-06-13T09:36:34.0000000" },
    { "2016-06-13T09:36:34.123Z",       1'465'810'594'123'000
    , "2016-06-13T09:36:34.1230000" },
    { "2016-06-13T09:36:34.123456Z",    1'465'810'594'123'456
    , "2016-06-13T09:36:34.1234560" },

    // From http://books.xmlschemata.org/relaxng/ch19-77049.html
    { "2001-10-26T21:32:52",            1'004'131'972'000'000
    , "2001-10-26T21:32:52.0000000" },
    { "2001-10-26T21:32:52+02:00",      1'004'131'972'000'000 // TZ info "lost" I guess
    , "2001-10-26T21:32:52.0000000" },
    { "2001-10-26T21:32:52.12679",      1'004'131'972'126'790
    , "2001-10-26T21:32:52.1267900" },

    { "2001-10-26T19:32:52Z",           1'004'124'772'000'000
    , "2001-10-26T19:32:52.0000000" },
    { "2001-10-26T19:32:52+00:00",      1'004'124'772'000'000
    , "2001-10-26T19:32:52.0000000" },

    { "-2001-10-26T21:32:52",        -125'286'834'428'000'000
    , "-2001-10-26T21:32:52.0000000" },

    // The following values are invalid:
    { "2001-10-26",                 -1, "" }, // all the parts must be specified
    { "2001-10-26T21:32",           -1, "" }, // all the parts must be specified
    { "2001-10-26T25:32:52+02:00",  -1, "" }, // the hours part (25) is out of range
    { "01-10-26T21:32",             -1, "" }, // all the parts must be specified
};

BOOST_AUTO_TEST_CASE(test_date_parse_and_format) {
    for (const auto& tc : test_cases) {
        std::chrono::system_clock::time_point tp;
        std::istringstream ss{ tc.input };
        ss >> date::parse("%Y-%m-%dT%T", tp);
        if (tc.expected_val == -1) {
            BOOST_CHECK_MESSAGE(ss.fail(), tc.input); // failed to parse
            continue;
        }
        BOOST_CHECK(!ss.fail());
        std::chrono::system_clock::duration ts = tp.time_since_epoch();
        std::chrono::microseconds usec = std::chrono::duration_cast<std::chrono::microseconds>(ts);
        BOOST_CHECK_MESSAGE(
            usec.count() == tc.expected_val,
            tc.input << ": " << usec.count() << " != " << tc.expected_val
        );

        std::string out = date::format("%Y-%m-%dT%T", tp);
        BOOST_CHECK_EQUAL(out, tc.expected_out);

        // We round-trip correctly (in text) up to the second at least
        BOOST_CHECK_EQUAL(out.substr(0, 19), tc.input.substr(0, 19));
    }
}
```

**Comment by HowardHinnant** [comment]
The documentation for %S refers to the precision of the _type_ of the input, not the precision of the value.  For example if the `time_point` type has precision nanoseconds, then the output will always contain 9 decimal places, even if the value is an integral number of seconds.

To control the precision, you can truncate or convert the input `time_point` to the desired precision.  For example:

```c++
format("%Y-%m-%dT%T", floor<milliseconds>(tp)) // will have 3 decimal places
```

In VS, `system_clock::time_point` has a precision of 1/10 microseconds, thus the 7 fractional digits (by default) in formatting.  gcc's `system_clock::time_point` has a precision of nanoseconds.

The negative test failure on linux is the result of underflow of the nanosecond-precision `time_point` that is being parsed into.  This `time_point` is not capable of representing -2001-10-26T21:32:52.

Here is a short program that explores the minimum representable `time_point`s using 64 bit integral representations and at various precisions:

```c++
#include "date/date.h"
#include <iostream>

int
main()
{
    using namespace date;
    using namespace std::chrono;
    using windows_precision = duration<long long, std::ratio<1, 10'000'000>>;

    std::cout << "1/10 us : " << sys_time<windows_precision>::min() << '\n';
    std::cout << "1 ns    : " << sys_time<nanose1conds>::min() << '\n';
}
```
Output:
```
1/10 us : -27258-04-19 21:11:54.5224192
1 ns    : 1677-09-21 00:12:43.145224192
```
So Windows can represent -2001-10-26T21:32:52 in a `system_clock::time_point` and Linux can't.  But one can parse into `sys_time<microseconds>` or `sys_time<windows_precision>` on Linux.

`sys_time<Duration>` is just a convenience type-alias for `time_point<system_clock, Duration>`.

One has to be careful with the above program in formatting the `min` for coarser `time_point`s as the calendrical structures used to do the formatting are limited to the range [-32767-01-01, 32767-12-31].  See https://howardhinnant.github.io/date/date.html#range for a more thorough treatment of range vs precision.

**Comment by ddevienne** [comment]
Hi Howard. Thanks for your answer. Not sure what I'm doing wrong, but even with `floor<>` I'm getting 7 digits on Windows. E.g.

```
D:/.../ChronoUtilsTests.cpp(198): error: in "ChronoUtilsTests/test_roundTripExtendedIsoDateTime": check out_milli == tc.expected_out_3_3 has failed [2016-06-13T09:36:34.0000000 != 2016-06-13T09:36:34.000]
D:/.../ChronoUtilsTests.cpp(203): error: in "ChronoUtilsTests/test_roundTripExtendedIsoDateTime": check out_micro == tc.expected_out_6_6 has failed [2016-06-13T09:36:34.0000000 != 2016-06-13T09:36:34.000000]
```
where the test code is
```
        std::string out_milli = formatIsoDateTime(
            floor<std::chrono::milliseconds>(tp)
        );
        BOOST_CHECK_EQUAL(out_milli, tc.expected_out_3_3);

        std::string out_micro = formatIsoDateTime(
            floor<std::chrono::microseconds>(tp)
        );
        BOOST_CHECK_EQUAL(out_micro, tc.expected_out_6_6);
```

And `formatIsoDateTime()` a small wrapper
```
std::string formatIsoDateTime(
    const std::chrono::system_clock::time_point& tp
) {
    return date::format("%Y-%m-%dT%T", tp);
}
```

Did I misunderstand something?

**Comment by HowardHinnant** [comment]
This truncates `tp` to `milliseconds` precision, and then implicitly converts it back to `system_clock::duration` precision to match the parameter type of `formatIsoDateTime`.

**Comment by ddevienne** [comment]
Our comments crossed-wire. You are right of course. User (developer) error. Thank you again for your time.

**Comment by HowardHinnant** [comment]
Perhaps some of these examples will help:
https://github.com/HowardHinnant/date/wiki/Examples-and-Recipes
https://github.com/HowardHinnant/date/wiki/Boost-datetime-Examples-Translated
