### ISSUE TITLE
Warning using `date::format` with VS2019 and without `HAS_UNCAUGHT_EXCEPTIONS`

### ISSUE THREAD

**Issue by ddevienne** [HowardHinnant/date#622]
It seems like `__cplusplus` is not _accurate_ on VS2019 in C++17 mode, perhaps detection of that compiler could be enhanced?

```
1>D:\...\date\date.h(1066,19): error C2220: the following warning is treated as an error
1>D:\..\date\date.h(1066,19): warning C4996: 'std::uncaught_exception': warning STL4006: std::uncaught_exception() is deprecated in C++17. It is superseded by std::uncaught_exceptions(), plural. You can define _SILENCE_CXX17_UNCAUGHT_EXCEPTION_DEPRECATION_WARNING or _SILENCE_ALL_CXX17_DEPRECATION_WARNINGS to acknowledge that you have received this warning.
```

**Comment by HowardHinnant** [comment]
It is a design decision of this library to by default use `uncaught_exception()` in C++11/14/17, and `uncaught_exceptions()` beyond C++17.  The rationale for this decision is that upon initial testing some clients wanted to compile for C++17 and yet found their programs would not port to older platforms which do not ship `uncaught_exceptions()`.  Use of the deprecated `uncaught_exception()` is safe for the use cases this library has.

That being said, this default behavior can be overridden by setting `HAS_UNCAUGHT_EXCEPTIONS=1` or `HAS_UNCAUGHT_EXCEPTIONS=0`.  Using clang or gcc this is best done on the command line like so: `-DHAS_UNCAUGHT_EXCEPTIONS=1`.  If you use an IDE such as Visual Studio, there are forms in the IDE where user-defined macros can be set: https://docs.microsoft.com/en-us/cpp/build/working-with-project-properties?view=msvc-160#user-defined-macros

**Comment by ddevienne** [comment]
Fair enough. I'm okay with overriding the default myself. Thanks Howard.
