### ISSUE TITLE
Parsing month-year or year-month doesn't work

### ISSUE THREAD

**Issue by sharkapotomus** [HowardHinnant/date#631]
Passing in a date with only a year and a month (order doesn't matter) doesn't parse correctly. 
note: formatting back to a month and year works fine, so this seems to be an issue with parse() only.

```
#include "tz.h"
#include <iostream>

int main()
{
	std::chrono::system_clock::time_point dt;

	std::istringstream ss{ "Feb 2020" }; //month and year only
	ss >> date::parse("%b %Y", dt);		 //does not work
	std::cout << dt.time_since_epoch().count(); 

	std::istringstream ss{ "01 Feb 2020" };
	ss >> date::parse("%d %b %Y", dt);	//works now that we added a day
	std::cout << dt.time_since_epoch().count();
}
```

My expected behavior is that it would assume the day value to be be the 1st.

**Comment by HowardHinnant** [comment]
It isn't working on purpose.  The design rationale is that if a parse can't completely specify the value being parsed, the parse fails (no defaults).  But this problem can be solved:

```c++
#include "date/date.h"
#include <iostream>
#include <sstream>

int
main()
{
    using namespace date;
    using namespace std;

    year_month ym;
    istringstream ss{ "Feb 2020" };
    ss >> parse("%b %Y", ym);
    cout << ym << '\n';
}
```

By parsing into a `year_month`, the data combined with the format string `"%b %Y"` completely specify everything in `ym`.  The `year_month` can then be combined with whatever defaults you would like to give it, for example:

```c++
system_clock::time_point dt = sys_days{ym/1};
```

**Comment by sharkapotomus** [comment]
Alright, but assuming the format string and the date string are dynamically specified by the user during runtime, is there a way to default all the potential fields?

**Comment by HowardHinnant** [comment]
Sorry, nope.

**Comment by sharkapotomus** [comment]
Thanks for the quick responses!
