### ISSUE TITLE
How to use date::parse to read a time_point without a year?

### ISSUE THREAD

**Issue by joudinet** [HowardHinnant/date#632]
Hi,
I'm using date::parse to read a time_point from a log file but it doesn't contain a year. Is there a way to circumvent this limitation other than manually adding the year to every line I read?
```
#include <iostream>
#include <sstream>
#include <chrono>
#include "date/date.h"
int main() {
  std::istringstream ss("Dec 21 14:45:04.989303");
  std::chrono::sys_time<std::chrono::microseconds> tp;
  using namespace date;
  ss >> parse("%b %d %T", tp);
  std::cout << format("%b %d %T", tp);
}
```
I've tried to initialize `tp` to `std::chrono::years{2020}` but it still does not output the expected value. Is there a way to tell date::parse to use a default year?

**Comment by HowardHinnant** [comment]
You can parse into two objects:

1.  A `month_day`.
2. A `microseconds` duration.

Then you can combine those two things along with a chosen `year` to create a complete `sys_time<microseconds>`.  That might look like:

```c++
#include <iostream>
#include <sstream>
#include <chrono>
#include "date/date.h"

int
main()
{
  std::istringstream ss("Dec 21 14:45:04.989303");
  std::chrono::microseconds tod;
  date::month_day md;
  using namespace date;
  ss >> parse("%b %d", md) >> parse(" %T", tod);
  std::cout << sys_days{md/2020} + tod << '\n';
}
```

Output:

```
2020-12-21 14:45:04.989303
```

**Comment by joudinet** [comment]
Nice. Thanks.
