### ISSUE TITLE
Rebase library on C++20's chrono

### ISSUE THREAD

**Issue by eyalroz** [HowardHinnant/date#634]
If possible, it would probably be a good idea, in the long run, to rebase the Date library(/ies) on top of C++20 rather than C++11, so that users can enjoy the additional functionality as they transition their code to the newer language standard.

**Comment by ecorm** [comment]
C++20 already integrates the features of this library. I don't understand what you're asking.

I (and I suspect many others) need this library to support C++11 so that we have a "fallback" implementation when the build environment doesn't support C++20.
