### ISSUE TITLE
Uncaught Exceptions Flag

### ISSUE THREAD

**Issue by saadrtc** [HowardHinnant/date#635]
Line 141 should use greater than **and equal to** operators to indicate std::uncaught_exceptions are valid since C++17.

From: `#  if __cplusplus > 201703 || (defined(_MSVC_LANG) && _MSVC_LANG > 201703L)`
To: `#  if __cplusplus >= 201703 || (defined(_MSVC_LANG) && _MSVC_LANG >= 201703L)`

**Comment by HowardHinnant** [comment]
Duplicate of #622
