### ISSUE TITLE
`make_zoned()` template substitution failure on old Windows MinGW

### ISSUE THREAD

**Issue by DavisVaughan** [HowardHinnant/date#643]
On a very old version of Windows MinGW, I get the following template substitution error:

```cpp
zoned-time.cpp:266:63: error: no matching function for call to 'make_zoned(const date::time_zone*&, date::sys_time<std::chrono::duration<long long int> >&)'
     reference_val = date::make_zoned(p_time_zone, reference_st);
                                                               ^
```

Looking in the list of template substitution candidates, I found the one I thought it would use, but it failed with:

```cpp
In file included from clock.h:8:0,
                 from duration.h:4,
                 from zoned-time.cpp:1:
../inst/include/date/tz.h:1815:1: note: template<class Duration, class TimeZonePtr, class> date::zoned_time<typename std::common_type<Duration, std::chrono::duration<long long int, std::ratio<1ll, 1ll> > >::type, TimeZonePtr> date::make_zoned(TimeZonePtr, date::sys_time<Duration>&)
 make_zoned(TimeZonePtr zone, const sys_time<Duration>& st)
 ^
../inst/include/date/tz.h:1815:1: note:   template argument deduction/substitution failed:
../inst/include/date/tz.h:1806:13: error: 'constexpr std::integral_constant<_Tp, __v>::operator std::integral_constant<_Tp, __v>::value_type() const [with _Tp = bool; _Tp __v = true; std::integral_constant<_Tp, __v>::value_type = bool]' used before its definition
           , class = typename std::enable_if
             ^
```

My usage of `make_zoned()` is not particularly weird. It looks like this, with `const date::time_zone* p_time_zone` as an argument to the function this is called from, and `reference_val` is a `date::zoned_time<std::chrono::seconds>`:

```cpp
const std::chrono::seconds reference_dur = reference_duration[0];
const date::sys_time<std::chrono::seconds> reference_st{reference_dur};
reference_val = date::make_zoned(p_time_zone, reference_st);
```

Some information about the build that should be useful:

- Compiling with C++11
- This is MinGW with GCC 4.9 (very old, with partial C++11 support) (it is what ships with slightly old versions of R on Windows)
- This failure happens when building the i386 arch build. I am not sure if it fails for x86 as well, that builds after the i386 one in my test setup, and it never gets there because of this

Additionally, it _passes_ on a Windows build with a newer version of R which ships a newer version of MinGW with GCC 8.3.0. Which leads me to believe it is some fault of the old compiler that got fixed.

Here is the full build output. You can also see other builds on the left hand side that pass without issue:
https://github.com/DavisVaughan/clock/runs/1831301369?check_suite_focus=true

Regarding the code, here is the line in the PR where this was introduced:
https://github.com/DavisVaughan/clock/pull/98/files#diff-62a396c1cb87d2b7d15fd9d959c4d83b0d91ee8126249e662bcf028977fae58bR266

The oddest thing about this is that, before this PR, I was already using `make_zoned()` in one other place without any issues. Here is usage of it in my master branch which passes without any issues. The usage looks the same as what I added in the PR, and is even in the same file, so I'm not sure what is happening:
https://github.com/DavisVaughan/clock/blob/708e78b167ec91712dc1d49f022729f6836be64b/src/zoned-time.cpp#L101-L106

If you have any thoughts / advice on what might be happening, I'd appreciate it!

**Comment by HowardHinnant** [comment]
My advice is to migrate away from the use of `make_zoned()`.  Instead use `zoned_seconds`, or create a type alias for whatever precision you want, or just explicitly specify the template arguments:  `zoned_time<milliseconds>()`.

`make_zoned()` is not part of C++20, so if you ever migrate up from gcc 4.9, it will be easier to do so if you're no longer using `make_zoned()`.

**Comment by DavisVaughan** [comment]
Using the `zoned_time` constructor directly worked great! I forgot I could do that, for some reason I thought I had to use `make_zoned()` on C++11. All is passing now. Thank you!
