### ISSUE TITLE
convert from unix timestamp (sec.ns) functionality

### ISSUE THREAD

**Issue by zalmoxis2019** [HowardHinnant/date#645]
Hello,

 Can you add to lib an efficient way to convert a unix timestamp of this shape "1613466103.2977877" [SEC.NS] to time_point?
Or is there a FORMAT specification already, that does that?

```
stringstream ss("1613466103.2977877");
system_clock::time_point tp;

if (date::from_stream(ss, "%FORMAT?", tp)) { ... }
..
```

thank you

**Comment by HowardHinnant** [comment]
I can't add it to the lib.  However it is pretty easy to write:
```c++
#include "date/date.h"
#include <chrono>
#include <iostream>
#include <sstream>

std::chrono::system_clock::time_point
convert(std::string const& s)
{
    using namespace std;
    using namespace std::chrono;
    using namespace date;

    istringstream in{s};
    in.exceptions(ios::failbit);
    int sec, ns;
    char decimal_point;
    in >> sec >> decimal_point >> ns;
    if (decimal_point != '.')
        in.setstate(ios::failbit);
    return time_point_cast<system_clock::duration>(
        sys_time<nanoseconds>{seconds{sec} + nanoseconds{ns}});
}

int
main()
{
    using date::operator<<;
    std::cout << convert("1613466103.2977877") << '\n';
}
```
Output:
```
2021-02-16 09:01:43.002977
```
Just parse the string yourself into `int`s, doing as much or little syntax checking as you want.  Convert the `int`s to `seconds` and `nanoseconds` as appropriate, and then convert that to a `sys_time<nanoseconds>`.

The final `time_point_cast` is unnecessary on gcc/linux as `system_clock::duration` is `nanoseconds` on that platform.  On other platforms, `system_clock::duration` is coarser than `nanoseconds` and so the explicit truncation is necessary.  Or you could just return it un-truncated and let the client truncate it if and how they want.

**Comment by zalmoxis2019** [comment]
Thank you for taking the time to write the conversion code. I wrote it too, but i was actually hoping to find it under a fancy date::from_stream(...format) method in your lib. So that i can use the lib everywhere for all date & time related stuff i need, instead of just bits and parts from here and there and then some more custom code on top of it :p

regards!
