### ISSUE TITLE
Calls to toupper() might should cast to unsigned char first

### ISSUE THREAD

**Issue by DavisVaughan** [HowardHinnant/date#647]
`scan_keyword()` has two calls to `toupper()` in it, both can be seen here:

https://github.com/HowardHinnant/date/blob/bf79dd5a810a1c6afd57d708f5e91597c05d584e/include/date/date.h#L4782-L4795

`ic` is likely an `int` in many cases, and `(*ky)[indx]` will often be a `char`.

The documentation for `std::toupper()` states that it is recommended to pass an `unsigned char` to this function
https://en.cppreference.com/w/cpp/string/byte/toupper

This stackoverflow post quotes the C standard, saying that any input not representable as an unsigned char is undefined behavior
https://stackoverflow.com/questions/21805674/do-i-need-to-cast-to-unsigned-char-before-calling-toupper-tolower-et-al

I realize that this has never bitten you here since `month_names()` and friends all use char values that are positive. However, in clock where I've extract out bits of the parser and customized it, I've ended up passing in UTF-8 month name strings used in other locales (like Japan) and they do indeed use negative char values if you iterate over the string one char at a time.

I've made a change directly to my copy of `date.h` here, but would you be willing to change this in date itself?
https://github.com/r-lib/clock/pull/173

**Comment by HowardHinnant** [comment]
Sure.  Would you like to make a PR?
