### ISSUE TITLE
Idea: basic_year and basic_year_month_day

### ISSUE THREAD

**Issue by ecorm** [HowardHinnant/date#656]
I can understand the motivation to make `year` 16-bits so that a `year_month_day` can be a compact data type. However this limits the year's range to [-32767, 32767] (according to cppreference). This is plenty of range for business use, but probably not for scientific applications.

I ran into this problem while writing generic serialization code for a `std::tm`, where the `std::tm::tm_year` range far exceeds that of `date::year`. I had to resort to doing the Gregorian calendar computations myself (with the help of http://howardhinnant.github.io/date_algorithms.html).

An astronomical application, for example, may want to compute Gregorian calendar dates past the year 32767. I'm not working on any such project, but it's one use case that I can think of.

I know it's too late to change the underlying integer type used by `year`. But perhaps as an extension, and as a future incorporation into the standard, how about making `year` an instantiation of a template that takes the underlying integer type? For example:

```c++
template <class Rep>
struct basic_year {...};

using year = basic_year<short>;

template <class YearRep>
struct basic_year_month_day {...};

using year_month_day = basic_year_month_day<short>;
```

Perhaps the C++ std-proposals mailing list would be a better place to discuss this, but I figured that I'd test the waters here first.

**Comment by HowardHinnant** [comment]
The Gregorian calendar itself models the solar system to about 1 day in 4000 years.  So talking about time points with 1-day precision out at [-32767, 32767] is already questionable.  For dealing with grand time scales it might make more sense to create a mega_years unit and divide by that:
```c++
using Myears = duration<double, ratio_multiply<mega, years::period>>;
cout << sys_time<milliseconds>::min().time_since_epoch()/Myears{1} << '\n';  // -292.277
```
The `sys_time<milliseconds>` type can reach back 292 million years.

**Comment by ecorm** [comment]
Sounds reasonable to me. I guess I should have done a little research before proposing this. You may re-open this issue if you find it has merit (I no longer think it does).
