### ISSUE TITLE
Why does `from_stream()`-ing into a time point round rather than floor? 

### ISSUE THREAD

**Issue by DavisVaughan** [HowardHinnant/date#657]
When using `from_stream()` to parse into a `sys_time` or `local_time` that is less precise than the original string, these two lines round, but I expected a floor.
https://github.com/HowardHinnant/date/blob/9a9a42db74df6320e7896282c9d2fe64cf3a674c/include/date/date.h#L8010
https://github.com/HowardHinnant/date/blob/9a9a42db74df6320e7896282c9d2fe64cf3a674c/include/date/date.h#L8028

Is there a reason for this?

Here is a result of this behavior. This R code wraps `from_stream()`, so hopefully it's easy enough for you to translate to C++

```r
library(clock)

sys_time_parse("2019-12-31 11:59:59", format = "%Y-%m-%d %H:%M:%S", precision = "second")
#> <time_point<sys><second>[1]>
#> [1] "2019-12-31 11:59:59"

# rounds down
sys_time_parse("2019-12-31 11:59:59", format = "%Y-%m-%d %H:%M:%S", precision = "day")
#> <time_point<sys><day>[1]>
#> [1] "2019-12-31"

sys_time_parse("2019-12-31 22:59:59", format = "%Y-%m-%d %H:%M:%S", precision = "second")
#> <time_point<sys><second>[1]>
#> [1] "2019-12-31 22:59:59"

# rounds up - not what i expected
sys_time_parse("2019-12-31 22:59:59", format = "%Y-%m-%d %H:%M:%S", precision = "day")
#> <time_point<sys><day>[1]>
#> [1] "2020-01-01"
```

**Comment by HowardHinnant** [comment]
The rationale for the `round` is to support precisions that can't be exactly represented by less than 18 decimal digits.  For example to round trip a precision of 1/3 seconds, round has to be used.

I suggest either parsing the full precision out of the file (i.e. `sys_seconds`), and then truncating that in the desired direction, or to parse the date / time in two steps, throwing away the second step:
```c++
    sys_days tp;
    seconds s;
    in >> parse("%F", tp) >> parse(" %T", s);
```

**Comment by DavisVaughan** [comment]
Okay thanks!
