### ISSUE TITLE
License for "Low-Level Date Algorithms" code

### ISSUE THREAD

**Issue by ecorm** [HowardHinnant/date#658]
I need to use the low-level date algorithms from https://howardhinnant.github.io/date_algorithms.html.

More specifically, I need them for dealing with `std::tm`, where its not possible to use HowardHinnant/date due to the `std::tm::tm_year` member exceeding the range of `date::year`.

For those who are wondering why I need this, I'm working on (yet another) general-purpose C++ serialization library, and I want to support `std::tm` as a serializable entity.

Can you please provide a permissive or public domain license for the code snippets in the low-level date algorithms document? Just the code, that is, not your prose.

**Comment by HowardHinnant** [comment]
Way down in the [Summary section](http://howardhinnant.github.io/date_algorithms.html#Summary) there's a note that I consider these in the public domain.  I don't feel qualified to license them as I've seen bits and pieces of these equations in many places elsewhere my entire adult life (and I'm _old_ ;-) ).  So please just use them.  A credit back to http://howardhinnant.github.io/date_algorithms.html is appreciated but not required.

Also be aware that @cassioneri has done some really impressive work on [optimizations of these algorithms](https://github.com/cassioneri/calendar), though for some of them at the sacrifice of some range.  I don't know the specifics on how much range, and with you wanting a lot of it, be forewarned.  But maybe they would be useful for you as well.

**Comment by ecorm** [comment]
A link back to your awesome paper was already a given. Thanks!

That library from cassioneri is licensed under the GPL, so it's a deal breaker for me, unfortunately. Folks concerned about speed will probably not be using `std::tm` anyway. I just want to support it for the sake of completeness.
