### ISSUE TITLE
Trouble storing dates in a std::vector

### ISSUE THREAD

**Issue by gazzatav** [HowardHinnant/date#664]
with g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0 and C++17 set in target_compile_feature (cmake)

I'm working on a project to retrieve some data from an api over the past month.  I create a vector of dates like this:-

`std::vector<std::chrono::time_point<std::chrono::system_clock, date::days>> hist_dates;`

and create a day duration like this:-

`date::days a_day(1);`

Then I push_back dates like this in a loop where i is the index:-

// As Howard says the off by one index has something to do with it but is it the whole story?  See output below.
`for(int i(1);i<33;++i){`
`auto days_to_subtract = a_day * i;`
`auto my_date = date::floor<date::days>(std::chrono::system_clock::now() - days_to_take);`
`hist_dates.push_back(my_date)}`

at which point `hist_dates[i] == my_date` compares false!

At each stage output with std::cout is sane for every value except hist_dates[i].  Any ideas - like don't bother with a vector?

**Comment by HowardHinnant** [comment]
My best guess is that you are assuming that vector indexing is 1-based instead of 0-based.  Try comparing to `hist_dates[i-1]`.

**Comment by gazzatav** [comment]
Damn! I was going to change that before anyone saw it.  Thanks for answering Howard - I'm honoured. Yes I just thought that myself. Unfortunately I don't think it's the complete answer though, here is some sequential output.  Look at the historical date - even comparing dates with the next one down or the one above there's something odd here.  Yet when I change it back to a zero index start it works fine.
Output:
Day to store: 2021-03-31, alternative: 2021-03-31
historical date: 1970-01-01
Different
Today is: 2021-04-27
Days to subtract: 28d
Days to take: 28d
Day to store: 2021-03-30, alternative: 2021-03-30
historical date: 5946-06-16
Different
Today is: 2021-04-27
Days to subtract: 29d
Days to take: 29d
Day to store: 2021-03-29, alternative: 2021-03-29
historical date: 1970-04-19
Different
Today is: 2021-04-27
Days to subtract: 30d
Days to take: 30d
Day to store: 2021-03-28, alternative: 2021-03-28
historical date: -16747-01-06
Different
Today is: 2021-04-27
Days to subtract: 31d
Days to take: 31d
Day to store: 2021-03-27, alternative: 2021-03-27
historical date: 2029-10-27
Different
Today is: 2021-04-27
Days to subtract: 32d
Days to take: 32d
Day to store: 2021-03-26, alternative: 2021-03-26
historical date: 1970-01-01

**Comment by gazzatav** [comment]
Derr silly me it was referencing memory not yet written to.  How could I make such a noob error and get all those types right!

**Comment by HowardHinnant** [comment]
Fwiw, `date::sys_days` is a type alias for `std::chrono::time_point<std::chrono::system_clock, date::days>`

**Comment by gazzatav** [comment]
Yes, thanks, but too much auto and such leaves me unable to read compiler errors :)  When it's in my head better I can back off the verbosity.
