### ISSUE TITLE
Adoption into C++ 20 of this library does not include date::format() - how to deal with this or is it available under another name?

### ISSUE THREAD

**Issue by juandent** [HowardHinnant/date#674]
I am used to using date::format to obtain a string representation of a time_point (usually a sys_days) as in this function:

```C++
inline std::string SysDaysToString(std::chrono::sys_days pt) {
	auto ret = date::format("%F", pt);
	// auto r = std::chrono::format("%F", pt);
	return ret;
}
```

When Microsoft released the latest C++ compiler (VS 2019 v16.10.0) it included types in date.h such as year_month_day and functions like std::chrono::parse() but for some reason they did not include the date::format() function which is extremely useful to change time_points to strings. Is it maybe present in another namespace or under another name?

Regards,
Juan Dent

**Comment by HowardHinnant** [comment]
I'm not sure where the Microsoft implementation is on this, but there's good news in this area for C++20.  The popular [fmt library](https://github.com/fmtlib/fmt) was standardized in C++20, and the functionality of `date::format` was merged into [`std::format`](http://eel.is/c++draft/format).

**Comment by juandent** [comment]
Yet I cannot see a std::format(sys_days) while I do see year_month_day struct??

**Comment by HowardHinnant** [comment]
This looks like the hook for it: https://github.com/microsoft/STL/blob/main/stl/inc/chrono#L6395-L6408

**Comment by juandent** [comment]
Never mind I found it!
I was missing {}... one format that works is " {%F}...

**Comment by HowardHinnant** [comment]
Oh, right.  And actually I thought it was `"{:%F}"`.

**Comment by juandent** [comment]
Sorry you are right @HowardHinnant, it is "{:%F}"
