### ISSUE TITLE
Question regarding compilation on RHEL7/Centos gcc 4.8.5

### ISSUE THREAD

**Issue by DavisVaughan** [HowardHinnant/date#678]
Hi @HowardHinnant, I received this report from a user who couldn't compile date through clock
https://github.com/r-lib/clock/issues/234. It looks to be the same as https://github.com/HowardHinnant/date/issues/264.

I was looking at your suggested fix here https://github.com/HowardHinnant/date/issues/264#issuecomment-349669656, and was wondering if patching that line in the copy of date that I ship is still the correct thing to do? i.e. is that patch up to date or should there be different defaults now?

Here are the relevant lines in date.h as of now:
https://github.com/r-lib/tzdb/blob/bf6c79a0f53f39e4eedbef951af0fe4e1335a4c5/inst/include/date/date.h#L4798-L4808

Is there any way this could be patched in date itself?

Finally, do you think that adding `CONSTDATA weekday nanwd{8u};` like `nanyear`, and then using that as the default value of `wd` in `struct fields` would also "fix" it?

I believe I also found the specific bug report to gcc here:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=58930

Thanks!

**Comment by HowardHinnant** [comment]
I've just pushed a commit to master that I believe makes the patch for gcc 4.8.  If this doesn't work, let me know and I'll try again.
