### ISSUE TITLE
Dual locate_zone APIs causes linker errors when mixing language modes

### ISSUE THREAD

**Issue by ecorm** [HowardHinnant/date#681]
The `locate_zone` [function](https://github.com/HowardHinnant/date/blob/fb2554a7e00b24d23838b57a4db4121e148edb5c/src/tz.cpp#L3631) takes either a `std::string` or a `std::string_view`, depending on the `HAS_STRING_VIEW` macro.

When the tz library is compiled in C++11 mode, it cannot be used with applications compiled in C++17 mode, because the C++17 app will see a different `tzdb::locate_zone` signature in the tz.h header than what was used to compile the library. This results in linker errors.

The same problem occurs when the tz library is compiled in C++17 mode and the application is compiled in C++11 mode.

A workaround is for the application to forcefully define the `HAS_STRING_VIEW` macro to match what was used for compiling the tz library.

This problem could be avoided if the `locate_zone` function and `tzdb::locate_zone` method were converted to inline functions defined entirely in the `tz.h` header file. Is there a reason why these must be defined in the cpp file? They only access the `tzdb::zones` public member vector in a read-only manner and don't reference any internal symbols.

**Comment by HowardHinnant** [comment]
While date.h has small enough functions to be made header-only, no attempt has been made to make tz header-only because it isn't practical due to the amount of code in the implementation.

`tzdb::locate_zone` in particular is way too big to be inlined.  The `throw` statement alone makes it too big.

The design is that tz is not a header-only library, and that the client and tz are compiled with the same configuration macros.  This is one of the reasons I find CMake more trouble than it is worth, and point people to these build instructions: 
 https://howardhinnant.github.io/date/tz.html#Installation.

For those situations where separate compilation is required for reasons outside the control of this library, date configuration macros are designed to be overridable, exactly as you have described for `HAS_STRING_VIEW`.  I would've called the ability to forcefully define it a feature as opposed to a workaround.  The library goes to extra effort to ensure that such configuration macros have defaults _and_ that those defaults can be overridden.

```c++
#ifndef HAS_STRING_VIEW
    // ... details to default HAS_STRING_VIEW if and only if the client hasn't already specified it
#endif  // HAS_STRING_VIEW
```

**Comment by ecorm** [comment]
> tzdb::locate_zone in particular is way too big to be inlined. The throw statement alone makes it too big.

One way to keep the bulk of the code non-inline is use something like this in the tz.cpp file:

```c++
const time_zone*
tzdb::locate_zone_impl(const char* tz_name, std::size_t len) const
{
    //...
}
```

where if `HAS_STRING_VIEW == 0`, the comparisons are done with either `std::char_traits<char>::compare` or a hand-written version of `std::lexicographic_compare`. However, I admit the resulting code would not be as tidy as what's in there now.

An inline `locate_zone` function and an inline `tzdb::locate_zone` method could then call the non-inline `tzdb::locate_zone_impl`. You could have overloads taking `std::string` be always present, and add `std::string_view` overloads when `HAS_STRING_VIEW == 1`. That way, C++11 users can always count on the `std::string` overload being present regardless of which mode the library was compiled in. An extra `const char*` overload would be needed to avoid ambiguity when both `std::string_view` and `std::string` overloads are present.

> I would've called the ability to forcefully define it a feature as opposed to a workaround.

Fair enough. :-)

> The library goes to extra effort to ensure that such configuration macros have defaults and that those defaults can be overridden.

I'm glad you made is configurable by the library user. I guess I'm going to have to configure the `HAS_STRING_VIEW` macro myself, which should be no big deal. My reason for needing this is that I have separate unit tests compiled in different C++ modes to maximize test coverage (I have a lot of preprocessor logic that enables fallback code when C++14/17/20 features are not detected). Alternatively, I could compile two versions of your library and make the build script pick the right one.

**Comment by ecorm** [comment]
> They only access the tzdb::zones public member vector in a read-only manner and don't reference any internal symbols

It just occurred to me I can write the `locate_zone` function myself in my project and bypass the problem entirely.

**Comment by ecorm** [comment]
In writing my own `locate_zone` function, I'm now vexed with the problem that the layout of `tzdb` depends on how the `USE_OS_TZDB` macro was defined during library compilation. You see, in my serialization library project, I allow the user to provide their own *date* library implementation.

This is not insurmountable, as the user can do `-DUSE_OS_TZDB=X` when including my library (which is header-only). At least this is more stable than `HAS_STRING_VIEW` which changes according to the C++ mode.

It would be preferable to me if the `tzdb::links` and `tzdb::rules` were always present but left empty if unused. Is there any chance of making the `links` and `rules` fields always present?

**Comment by HowardHinnant** [comment]
Would using the custom timezone feature work in your case?  There's a very simplistic description and example here: https://howardhinnant.github.io/date/tz.html#Examples

And here's a full featured example:  https://github.com/HowardHinnant/date/blob/master/include/date/ptz.h

Here's an example use of the latter, using C++17 syntax:

```c++
#include "date/ptz.h"
#include <iostream>

int
main()
{
    using namespace date;
    using namespace std;
    using namespace std::chrono;

    auto now = system_clock::now();
    auto tzp = Posix::time_zone{"EST5EDT,M3.2.0,M11.1.0"};
    cout << zoned_time{tzp, now} << '\n';
    cout << zoned_time{current_zone(), now} << '\n';
}
```
Output:
```
2021-07-15 18:10:03.027251 EDT
2021-07-15 18:10:03.027251 EDT
```

**Comment by ecorm** [comment]
I don't think so. I ultimately need something that parses and formats `zoned_time`s in the `2000-01-23T12:23:45+01:00[Foo/Bar]` format. I'd rather not have to rewrite all the tz database parsing code that you already have. I also want to use a date API similar to the C++20 standard.

If necessary, I can live with the user of my library having to do `-DUSE_OS_TZDB=X`.

**Comment by HowardHinnant** [comment]
Would it do harm if I made `links` available but not `rules`?  My motivation is to follow the C++20 spec.

**Comment by ecorm** [comment]
Unless you also remove the `#if !USE_OS_TZDB` condition around `rules` (or remove `rules` entirely), it would not help the problem I describe because the application doesn't know what `sizeof(time_zone)` really is, unless `-DUSE_OS_TZDB=X` is passed to the build. That's because `sizeof(time_zone)` determines the address stride when iterating though the `std::vector<time_zone>`.

If you still need `rules`, I suggest making it private (along with `mappings` and `next`) and always present (just leave it empty if unused).

I don't even know what the `rules` member is for, so I don't personally care if it's removed or hidden as private. I can't speak for everyone, though.

The `mappings` one shouldn't matter in terms of `sizeof(time_zone)`, because a library compiled on Windows wouldn't be used on a non-Windows platform.
