### ISSUE TITLE
Parsing unused subseconds fails at 0.5 seconds before midnight

### ISSUE THREAD

**Issue by ecorm** [HowardHinnant/date#683]
See following code which reproduces the problem:

```c++
void test_parse(const std::string& timestamp)
{
    date::sys_time<std::chrono::seconds> time;
    std::istringstream iss{timestamp};
    iss >> date::parse("%FT%H:%M:%6S", time);
    std::cout << "Parsing " << timestamp
              << (bool(iss) ? " passed\n" : " failed\n");
}

int main()
{
    test_parse("2000-01-01T23:59:59.999999"); // Fails
    test_parse("2000-01-01T23:59:59.500000"); // Fails
    test_parse("2000-01-01T23:59:59.499999"); // Passes
    test_parse("2000-01-01T23:59:58.999999"); // Passes
    return 0;
}

```

What happens in the first two test cases is `fields<Duration>::tod::s_` ends up getting set to `60`, which results in the `fds.tod.in_conventional_range()` check failing.

Due to #568, I actually use `%37S` in my serialization library to flush out all possible subsecond digits that would be produced by a quad-precision float (plus one decimal point). I changed it to `%6S` in the test code above.

I'm now considering just parsing the seconds myself as a `double` and manually adding it to the the `time_point` value parsed down to the minutes.

**Comment by HowardHinnant** [comment]
How about parsing into a `sys_time<duration<double>>` and then truncating that to a `sys_seconds` in whatever direction you want?

```c++
#include "date/tz.h"
#include <chrono>
#include <iostream>
#include <sstream>

void
test_parse(const std::string& timestamp)
{
    date::sys_time<std::chrono::duration<double>> dtime;
    std::istringstream iss{timestamp};
    iss >> date::parse("%FT%H:%M:%37S", dtime);
    date::sys_seconds time = floor<std::chrono::seconds>(dtime);
    using date::operator<<;
    std::cout << "Parsing " << timestamp
              << (bool(iss) ? " passed : " : " failed : ") << time << '\n';
    
}

int
main()
{
    test_parse("2000-01-01T23:59:59.999999"); // Passes
    test_parse("2000-01-01T23:59:59.500000"); // Passes
    test_parse("2000-01-01T23:59:59.499999"); // Passes
    test_parse("2000-01-01T23:59:58.999999"); // Passes
}
```

**Comment by DavisVaughan** [comment]
Similar underlying problem to https://github.com/HowardHinnant/date/issues/667, I think

**Comment by ecorm** [comment]
In my serialization library, users can deserialize ISO8601 timestamps into any arbitrary `std::chrono::time_point` type, and I want to be liberal in the precision that's accepted in received ISO8601 timestamps.

If I parse via `sys_time<duration<double>>` as you suggest, then I have to consider the risk of loss of precision. I prefer not having to rely on `long double` being available. I'll think about it some more when I get the chance (busy with personal stuff right now).

My library already makes use of https://github.com/fastfloat/fast_float, so there might be a performance gain if I parse the seconds myself as floating point (versus the relatively slow `std::istream-based` parsing that's outside the _date_ library's control).

**Comment by HowardHinnant** [comment]
Just fyi, the date.h implementation uses `long double` to parse seconds, and then rounds that to the `duration` requested by the parse.

https://github.com/HowardHinnant/date/blob/master/include/date/date.h#L7266
https://github.com/HowardHinnant/date/blob/master/include/date/date.h#L6525-L6534
https://github.com/HowardHinnant/date/blob/master/include/date/date.h#L6359-L6409

**Comment by ecorm** [comment]
By having date.h parse everything into a `sys_time<duration<double>>`, around 11 decimal digits of precision is consumed for the total number of seconds (2021×365.25×86400 = 63777909600). Only around 4 decimal digits of precision then remain for the sub-seconds portion. Heh, I guess this explains why Javascript's `Date` has a resolution in milliseconds.

It seems I'll pretty much have to parse the ISO8601 seconds separately as floating point. Whether I have date.h do it, or just extract it from the input stream myself and check its range, is an implementation detail on my end at this point.

It's too bad `date::parse` and `std::chrono::parse` don't accept the rounding mode as some sort of parameter (yeah, I know, hindsight is 20/20).

Thanks for all your help. If the weird  I reported in my original post is by design and is not really fixable, then you may close this issue.

**Comment by pedro-vicente** [comment]
Apologies for inserting in this thread, but a I have a compile error on a call similar to

`iss >> date::parse("%FT%H:%M:%6S", time);`

above gives this on Visual Studio 2019, 

> error C2893: Failed to specialize function template 'unknown-type date::parse(const CharT *,Parsable &)'
> message : see declaration of 'date::parse'
> message : With the following template arguments:
> message : 'Parsable=std::chrono::time_point<std::chrono::system_clock,std::chrono::seconds>'
> message : 'CharT=char'

**Comment by ecorm** [comment]
What is the rationale for `from_stream` doing round-to-nearest when obtaining the seconds from `%S`? Wouldn't it be better if it did `floor` instead (that is, `floor_i` instead of `round_i`)? The _time.parse_ section of the C++ standard draft mentions nothing about rounding.

**Comment by ecorm** [comment]
Even if `floor` were used for parsing integral seconds, I still have the problem that it rejects `60.x` as a valid `%S` field when parsing into a `sys_time`. You see, both ISO 8601 and RFC3339 allow `60.x` to appear as a leap second.

A naive way to handle the parsing of `60.x` seconds into a `sys_time` would be to subtract 1 second so that the calendar date doesn't roll over prematurely, but this would break applications that expect a sequence of deserialized times to be sorted chronologically. A similar discontinuity can happen if I simply add the `60.x` seconds value as-it to the computed `sys_time`. I'm not sure what to do in this special case.

I could parse into a `utc_time` before `clock_cast`ing to a `sys_time`, but my then library would then have a hard dependency on `tz.h`. My serialization library currently only has an optional dependency on `tz.h`, needed only if clients want to serialize times involving `utc_clock`, `tai_clock`, `gps_clock`, `local_time`, or time zones.

**Comment by ecorm** [comment]
> I'm not sure what to do in this special case.

I see now that I can simply mimic the behavior of `utc_clock::to_sys`:

> If `t` represents a time point during a leap second insertion, the last representable value of `sys_time` prior to the insertion of the leap second is returned.

... with the exception that I can't check if it's really a valid leap second.

**Comment by ecorm** [comment]
Closing as duplicate of #667.

**Comment by HowardHinnant** [comment]
Sorry to be slow.  Answering the first question:

> What is the rationale for from_stream doing round-to-nearest when obtaining the seconds from %S? 

```c++
#include "date/date.h"
#include <cassert>
#include <chrono>
#include <sstream>

int
main()
{
    using namespace date;
    using namespace std;
    using namespace std::chrono;

    using one_third = duration<int, ratio<1, 3>>;
    auto x = sys_time<one_third>{one_third{2}};
    stringstream file;
    file << format("%F %T", x);
    x = {};
    file >> parse("%F %T", x);
    assert(x.time_since_epoch() == one_third{2});
}
```

When the units can't be represented by a finite number of fractional decimal digits, `round` is necessary to make a loss-less round trip possible.

That being said, answering this question exposed a bug which I've just fixed:  https://github.com/HowardHinnant/date/commit/d57d764707050fa85fc3a6f824c666ed4550b1b4

**Comment by HowardHinnant** [comment]
The rationale for not parsing 60.x seconds into a `sys_time` is that the policy is that parsing checks for invalid dates and times.  This is the policy the majority of my users seem to want.  And 60.x seconds is always invalid for `sys_time` as `sys_time` can not represent leap seconds.  The only way to parse such time points is with `utc_time`.  And then _only_ actual leap seconds can be parsed with 60.x.  If 60.x shows up on a non-leap-second, it will also flag an error.

**Comment by ecorm** [comment]
Thanks for the clarifications. I guess you can't please everyone. I think the real life use cases for parsing into resolutions other than 1:10^(3*N) or 86400:1 would be quite rare, and that parsing finer resolutions into coarser ones would be more common.

My needs are more from a network communications interoperability perspective: parsing ISO8601 (or RFC3339) timestamps in a C++ peer where the other peer may not even be written in C++, with native time types differing in resolution depending on the programming language.

Because I'm writing a general-purpose serialization library, I cannot assume the resolution or representation type when deserializing an RFC3339 string into an arbitrary `sys_time<duration<R, P>>`. I also don't want to application the sacrifice the range or resolution of the received time by parsing into an intermediate time with finer resolution.  I also want it to _Just Work_ given any valid RFC3339 string (which may include `60.x` seconds), without placing any burden on the client application to provide an environment with a working `utc_clock` and a leap second database.

I have written a working generic parsing function that uses date.h to parse RFC3339 strings down to the minute. I parse the seconds myself as a double, and have figured out how to clamp `60.x` seconds to just before `60.0` like you do in your `utc_clock::to_sys`. Please be assured that I'm not "stuck".

**Comment by ecorm** [comment]
Another pain point I've found with `from_stream` is that (unless I'm mistaken) it can't treat the `Z` suffix of an ISO 8601 string as an offset of zero minutes. I therefore have to `peek()` the character following the seconds to see if it's a `Z` or a +/- offset.

**Comment by ecorm** [comment]
After manually parsing the seconds, and `peek()`ing for the presence of `+`/`-`, I'm unable to parse the offset using `"%Ez"` because it requires that the time of day be present.

Do you foresee any problems if I "abuse" `%H:%M` for parsing the offset, after manually parsing the `+`/`-`? According to [Wikipedia](https://en.wikipedia.org/wiki/List_of_UTC_time_offsets), the westernmost offset is `-12:00` and the easternmost is `+14:00`.

**Comment by HowardHinnant** [comment]
I'd have to see a working example to know for sure.

One other option I've used and seen other use is to parse one full format string, and check for `.fail()` on the stream.  If failed, just roll back the stream and try another format string.  https://stackoverflow.com/a/62801456/576911

**Comment by ecorm** [comment]
My working example currently uses a bunch of symbols from my serialization library and is a bit convoluted due to being able to use either your date library or C++20 std::chrono features. I'll try to reduce it to a minimal compilable example that only depends on your date library.

I'm not keen on attempting multiple parses with different format strings due to inefficiency, but I thank you anyway for presenting it as an option.

**Comment by ecorm** [comment]
Here's a compilable example: https://gist.github.com/ecorm/8878c5075cf8557994983540a13557bc

Line 120 is where I "abuse" `%H:%M` to parse the offset.

**Comment by HowardHinnant** [comment]
This looks like correct, high quality code to me.  I see no problems at all.  👍
