### ISSUE TITLE
`set_install()` isn't friendly to wide strings on Windows

### ISSUE THREAD

**Issue by DavisVaughan** [HowardHinnant/date#690]
Hi Howard,

I have a Windows user who is having issues with `set_install()` (full info [here](https://community.rstudio.com/t/cannot-load-clock-on-win11-error-utc-is-not-a-known-time-zone/111477)). The issue is that they unfortunately have an accent mark in their root file path, which I can't have control over. They end up with an error like this:

```r
#> Error: Timezone database not found at "C:/Users/mlyons/OneDrive - COMPANY Namé/Documents-ML/R/win-library/4.1/tzdb/tzdata"
```

I think the issue is that `set_install()` only supports `std::string`, but really `std::wstring` is needed here? For example, I can sort of reproduce this with the following on a Windows computer (compiling with [these defines](https://github.com/r-lib/tzdb/blob/169567f4e35fb8ba8abfa42a16cf24efd53167b7/src/Makevars#L31-L35)):

```cpp
#include <date/tz.h>

void tzdb_test_cpp() {
  std::string path = "C:\\Users\\smwhi\\Documents\\RStudio Projects\\problèm\\tzdata";
  date::set_install(path);
  const date::tzdb& db = date::get_tzdb();
}
```

The `date::get_tzdb()` call will throw the "Timezone database not found" error (notice the accent in the "problem" folder) 

I think I really need to do something like:

```cpp
std::wstring path = L"C:\\Users\\smwhi\\Documents\\RStudio Projects\\problèm\\tzdata"
```

but I can't pass that to `set_install()`.

If you do try and support this, I've also been told that `file_exists()` should use `_waccess()` rather than `_access()` for those wide strings.
https://github.com/HowardHinnant/date/blob/d57d764707050fa85fc3a6f824c666ed4550b1b4/src/tz.cpp#L2839

**Comment by DavisVaughan** [comment]
@HowardHinnant I just wanted to followup and see if you had any thoughts about this issue. Normally I'd never followup like this, but I borked the issue when I opened it originally and that may have caused you to not see it.

**Comment by HowardHinnant** [comment]
Sorry, just been really busy elsewhere.

**Comment by DavisVaughan** [comment]
No problem at all!

**Comment by DavisVaughan** [comment]
Fixed by https://github.com/HowardHinnant/date/commit/529a09267f6f4b1f3ac0ab11864ef452be92dd10
