### ISSUE TITLE
format() can return wrong results due to silent overflow

### ISSUE THREAD

**Issue by pitrou** [HowardHinnant/date#695]
Simple reproducer:
```c++
void overflow() {
  const auto epoch = date::sys_days{date::jan / 1 / 1970};
  // Ok ("-32767-01-01", "32767-12-31")
  std::cout << date::format("%F", epoch + std::chrono::seconds{-1096193779200LL}) << std::endl;
  std::cout << date::format("%F", epoch + std::chrono::seconds{971890963199LL}) << std::endl;
  // Silent wraparound ("32767-01-02", "-32767-12-30")
  std::cout << date::format("%F", epoch + std::chrono::seconds{-1096193779200LL - 2 * 365 * 86400}) << std::endl;
  std::cout << date::format("%F", epoch + std::chrono::seconds{971890963199LL + 2 * 365 * 86400}) << std::endl;

  // Throws exception because year -32768 is a forbidden value
  std::cout << date::format("%F", epoch + std::chrono::seconds{-1096193779200LL - 365 * 86400}) << std::endl;
}
```

It would be nice if an exception was always consistently raised.
Also, it would be nicer if the exception and its error message was more distinctive and explanatory than currently:
```
terminate called after throwing an instance of 'std::__ios_failure'
  what():  basic_ios::clear: iostream error
```

**Comment by pitrou** [comment]
By the way, you may mention that Arrow C++ (https://arrow.apache.org/, https://github.com/apache/arrow/) is currently using this library.

**Comment by HowardHinnant** [comment]
Excellent, Arrow C++ added.

**Comment by HowardHinnant** [comment]
Ultimately the overflow properties of the date lib have followed the design principles of the C++11 chrono design:

1. Document what your limits are.
2. Make the limits ridiculously large.
3. Don't check for overflowing the limits, but don't prevent the client from adding such checks.

Here is where the range limits on `year_month_day` are documented: http://eel.is/c++draft/time.cal.ymd.members#20:
```
[days{-12687428}, days{11248737}]
```
Conversions between `sys_time` and `year_month_day` that are outside of this range have unspecified behavior (purposefully not _undefined_ behavior).

These limits correspond to the civil calendar range [-32767y/1/1, 32767y/12/31].  The civil calendar itself models the solar system with an accuracy of about 1 day in 4000 years.  So use of the calendar in the range beyond +/-30000 years is likely a logic error.

If you would like your formatting to check this range, I recommend adding such checks prior to the calls to `format`.

The value of `year` -32768y is set aside in case a client needs a nan-like value which means not-a-year.  This is in effect an alternative to `optional<year>`.

**Comment by pitrou** [comment]
I see, thank you. Checking for values out of range is what we ended up doing (see https://github.com/apache/arrow/pull/10988).
