### ISSUE TITLE
Should year/month/day have a nested rep typedef?

### ISSUE THREAD

**Issue by ecorm** [HowardHinnant/date#7]
Should `year`, `month`, and `day` have a nested `rep` typedef? The integer types used in their APIs are currently "hard-coded" to `int` and `unsigned`. By having a nested `rep` typedef, `year`, `month`, and `day` would be more consistent with their `std::chrono::hours`, `minutes`, and `seconds` analogs.

I understand that `hours`, `minutes`, and `seconds` represent durations, whereas `year`, `month`, and `day` do not, so perhaps my question is not really valid.

**Comment by HowardHinnant** [comment]
Do you have a motivating use case?
I've recently being playing with invalid month and day values, and there might be a motivating use case there.  E.g. So of course `day` can hold values [1, 31].  But what other values can it hold?  How far can I push `d + days{n}`?

**Comment by ecorm** [comment]
I was writing a function that converts `std::chrono::time_point` to calendar/time components and vice-versa. The components are to be packaged in this struct:

```c++
struct DateTimeComponents
{
    using Year    = int;
    using Month   = unsigned;
    using Day     = unsigned;
    using Hour    = std::chrono::hours::rep;
    using Minutes = std::chrono::minutes::rep;
    using Seconds = std::chrono::seconds::rep;
    
    Year year;
    Month mon;
    Day day;
    Hour hour;
    Minutes min;
    Seconds sec;
};
```

As you can see, the integer types used by `std::chrono::hours`, `minutes`, and `seconds` are defined by the standard library, whereas the ones for `date::year`, `month`, and `day` are not explicitly defined anywhere. There's also no way to use a `decltype` expression to deduce the `year`/`month`/`day` integer types.

I admit that this is a pretty weak use case. I just raised the question to make sure the lack of nested typedefs was not an oversight. I you feel they are unnecessary, then you may close this issue. :-)

**Comment by ecorm** [comment]
Perhaps `year`, `month`, `day` should have a `count()` getter similar to `std::chrono::duration`? That way, one could use `std::result_of`.

For example:
```c++
struct DateTimeComponents
{
    using Year    = std::result_of<decltype(&date::year::count)>::type;
    :::
    using Hour    = std::chrono::hours::rep;
    :::
};
```

**Comment by HowardHinnant** [comment]
I've about convinced myself on proceeding with your `rep` suggestion.  Though `rep` should accurately represent the actual storage used, and not the integral type it converts to and from.  This will allow the client to use `std::numeric_limits<day::rep>::max()` (for example) to learn what values can be stored.

As currently implemented this will be:
````
year::rep        == short
month::rep     == unsigned char
day::rep         == unsigned char
weekday::rep == unsigned char
````
I'm still wavering on `weekday_indexed`, which stores both a `weekday` and an `index`.  `weekday_indexed::rep` could represent the storage for the index, and would be `unsigned char`.  My hesitation is that this might be confusing.

**Comment by ecorm** [comment]
Perhaps `weekday_indexed::index_rep` and `weekday_indexed::weekday_rep`? The downside of this idea is that it's not consistent with the `rep` typedef used in other classes.

**Comment by HowardHinnant** [comment]
This has been open for over a year, and there's no fix on the horizon.  Closing as "not going to fix."  Feel free to re-open this issue if you see value in doing so.
