### ISSUE TITLE
Extracting current timezone fails on SLES

### ISSUE THREAD

**Issue by JaroslawMelzer** [HowardHinnant/date#708]
Running date library on SLES 11.4 I've encountered a following issue. Call to current_zone() returns "TIMErica/Chicago". I've debugged why and it turns out that zone extraction falls back to the code parsing /etc/sysconfig/clock file. But instead of ZONE="America/Chicago" there is TIMEZONE="America/Chicago". I'm attaching patch that should fix the issue and /etc/sysconfig/clock file for reproduction.

[clock.txt](https://github.com/HowardHinnant/date/files/7353108/clock.txt)
[sysconfig.clock.diff.txt](https://github.com/HowardHinnant/date/files/7353110/sysconfig.clock.diff.txt)

**Comment by HowardHinnant** [comment]
Very elegant fix, thanks!

I'm happy to push that patch.  Or would you like to do it with a PR?

**Comment by JaroslawMelzer** [comment]
Go ahead an push the patch. Happy to help!
