### ISSUE TITLE
date::set_install doesn't work for unicode paths on windows

### ISSUE THREAD

**Issue by hsdk123** [HowardHinnant/date#712]
As stated in title. Seems to cause failures in
```
if (!file_exists(install))
```

**Comment by DavisVaughan** [comment]
Likely would be fixed by https://github.com/HowardHinnant/date/pull/710 if you are compiling in a similar way

**Comment by hsdk123** [comment]
@DavisVaughan Oh neat, when will this be in upstream? @HowardHinnant

**Comment by HowardHinnant** [comment]
Sorry, I've been slow.  I will try to get this merged today.

**Comment by HowardHinnant** [comment]
#710 has been merged.
