### ISSUE TITLE
date::make_zoned: Wrong conversion

### ISSUE THREAD

**Issue by charno** [HowardHinnant/date#719]
Hi,

I'm using the date/tz library on an embedded system, and I have a problem with time conversions:

```C++
std::cout << "UTC: " << date::make_zoned("UTC", system_clock::now()) << std::endl << date::current_zone()->name() << ": " << date::make_zoned(date::current_zone(), system_clock::now()) << std::endl;
```

results in

```
UTC: 2021-11-18 10:46:40.019466000 UTC
Europe/Zurich: 2021-11-18 12:46:40.019660666 CEST
```

Which is wrong. Correct would be:

```
# timedatectl 
               Local time: Thu 2021-11-18 12:01:39 CET
           Universal time: Thu 2021-11-18 11:01:39 UTC
                 RTC time: Thu 2021-11-18 11:01:39    
                Time zone: Europe/Zurich (CET, +0100) 
```

For me this looks like CEST is used instead of CET. If CEST would be the current time, this would be correct.

I did build the library from `master` with cmake parameters `-DUSE_SYSTEM_TZ_DB=on -DBUILD_SHARED_LIBS=on -DBUILD_TZ_LIB=on` to use the local zonefiles.

About the system configuration:

```
ls -l /etc/localtime 
lrwxrwxrwx    1 root     root            33 Nov 11 15:26 /etc/localtime -> /usr/share/zoneinfo/Europe/Zurich
```

This link seems to be interpreted, since the name of the tz is correct.

I have two different Zonefiles which I attached as [Zurich.zip](https://github.com/HowardHinnant/date/files/7562278/Zurich.zip):
- Zurich-buggy is the one currently installed by the OS (yocto with package tzdata-europe)
- Zurich-working is an older version of the same file which is working.

The files are basically just downloaded from iana, and put through zic.

Can you have a look at the files and tell me if there is a problem with these files, of if it's a problem with the library?

Thanks in advance
Charno

**Comment by charno** [comment]
Sorry, duplicate of https://github.com/HowardHinnant/date/issues/614

**Comment by charno** [comment]
FYI: zic seems to have changed it's standard behavour. From the Changelog (https://data.iana.org/time-zones/releases/tzcode2021d.tar.gz, file NEWS)

```
Release 2020b - 2020-10-06 18:35:04 -0700
[...]
zic now defaults to '-b slim' instead of to '-b fat'.
```

**Comment by HowardHinnant** [comment]
Right.  And my parser doesn't currently handle `-b slim`.
