### ISSUE TITLE
After change zone, how to convert zoned_time to time_point

### ISSUE THREAD

**Issue by xjsxujingsong** [HowardHinnant/date#720]
As described.
time_point t = system_clock::now();
auto zone = date::locate_zone("Australia/Sydney");
zoned_time tt = make_zoned(zone, t);
How to convert tt back to time_point?

**Comment by HowardHinnant** [comment]
Doing some drive-by simplifications:
```c++
auto t = system_clock::now();
auto zone = date::locate_zone("Australia/Sydney");
zoned_time tt{zone, t};
t = tt.get_sys_time();  // UTC time_point
auto lt = tt.get_local_time();  // local time_point
```

**Comment by xjsxujingsong** [comment]
Hi @HowardHinnant  Thanks for your prompt response. 
I would like to convert zoned_time to chrono::time_point<system_clock> (back to standard C++ format)

**Comment by xjsxujingsong** [comment]
Just found it. 
Thanks. 
auto cc = clock_cast<system_clock>(t);
auto dd = clock_cast<system_clock>(lt);

**Comment by HowardHinnant** [comment]
Just `tt.get_sys_time();` is all you need.
