### ISSUE TITLE
format and parse functions in tz/date

### ISSUE THREAD

**Issue by gabm** [HowardHinnant/date#73]
For a project built with C++11 I'd like to use your date-library. It is very useful and provides a really convenient API. I'm specially interested in the parsing and (string-)formating of time_points.

Unfortunately *all* of the format(...) and parse(...) functions reside in tz.h which also means that one would have to use and include tz.h. In my case im pretty sure, that i don't need the full timezone support.

After looking at the code in tz.h i asked myself: Wouldn't it be possible to move the format and parse functions regarding local_time to date.h so that users without tz.h could use them? I don't see all the impact but that would be definately useful...

Of course it would be possible using tz.h as well, but that in turn needs the tzdata download which i cannot distribute to our PCs...

**Comment by HowardHinnant** [comment]
That's a good suggestion, thanks.  I'll see what I can do.

**Comment by HowardHinnant** [comment]
Done: https://github.com/HowardHinnant/date/commit/2e148737e4e509ae6c80820b129a91c89340c210

**Comment by HowardHinnant** [comment]
Actually I amended the commit message, so: https://github.com/HowardHinnant/date/commit/ebc20c139ba888600a39d8bf8214c5938037e37c

**Comment by gabm** [comment]
Thanks for your fast help. Please see my pull request #75 to fix some minor issues. Not sure, but I think they are because of the restructutring...
