### ISSUE TITLE
Embarcadero

### ISSUE THREAD

**Issue by jcurru** [HowardHinnant/date#730]
Hello!

I am trying to use your library with Embarcadero C++ Builder. The 64-bit compiler is supposed to be of type clang, but the case is that errors occur in the compilation. One of them occurs in this code (line 4516 of date.h):

```
template <class CharT>
CONSTCD11
inline
string_literal<CharT, 2>
msl(std::atto) NOEXCEPT
{
    return string_literal<CharT, 2>{'a'};
}

[bcc64 Error] date.h(4520): constexpr function's 1st parameter type 'std::atto' (aka 'ratio<1, (long long long)1000000000 * 1000000000>') is not a literal type.

[bcc64 Hint] ratio(100): 'ratio<1, 1000000000000000000000000000000>' is not literal because it is not an aggregate and has no constexpr constructors other than copy or move constructors
```

Any ideas on how to fix this?
Thanks in advance!
Best regards.

**Comment by HowardHinnant** [comment]
What value do __cplusplus and __clang_major__ and __clang_minor__ have?

**Comment by jcurru** [comment]
__cplusplus = 201703L (C++17)
__clang_major__ = 5__clang_minor__ = 0__clang_patchlevel__ = 2

José Antonio Carmena Flores
 

    En viernes, 1 de abril de 2022, 02:20:14 CEST, Howard Hinnant ***@***.***> escribió:  
 
 


What value do __cplusplus and clang_major and clang_minor have?

**Comment by jcurru** [comment]
[]([ratio.txt](https://github.com/HowardHinnant/date/files/8397466/ratio.txt))
Thank you for your response.
Find attached <ratio> (renamed to ratio.txt because otherwise I can't attach it).

First: I changed your code by:
[#elif __cplusplus >= 201402
// C++14
#  define CONSTDATA const // constexpr const 
#  define CONSTCD11 // constexpr
#  define CONSTCD14 // constexpr
#  define NOEXCEPT noexcept
](url)
and clang has stopped displaying compilation errors

Second: I had to disambiguate this code by adding date:: before floor:

                    if (U != not_a_week_num)
                    {
                        auto start = sys_days(Sunday[1]/January/ymd.year());
                        auto U_trial = date::floor<weeks>(sys_days(ymd) - start).count() + 1;
                        if (U != U_trial)
                            goto broken;
                    }
                    if (W != not_a_week_num)
                    {
                        auto start = sys_days(Monday[1]/January/ymd.year());
                        auto W_trial = date::floor<weeks>(sys_days(ymd) - start).count() + 1;
                        if (W != W_trial)
                            goto broken;
                    }

**Comment by jcurru** [comment]
Thank you for your response.

First: I changed your code by:

```
[#elif __cplusplus >= 201402
// C++14
define CONSTDATA const // constexpr const
define CONSTCD11 // constexpr
define CONSTCD14 // constexpr
define NOEXCEPT noexcept
](url)
```

and clang has stopped displaying compilation errors

Second: I had to disambiguate this code by adding date:: before floor:

```
                if (U != not_a_week_num)
                {
                    auto start = sys_days(Sunday[1]/January/ymd.year());
                    auto U_trial = date::floor<weeks>(sys_days(ymd) - start).count() + 1;
                    if (U != U_trial)
                        goto broken;
                }
                if (W != not_a_week_num)
                {
                    auto start = sys_days(Monday[1]/January/ymd.year());
                    auto W_trial = date::floor<weeks>(sys_days(ymd) - start).count() + 1;
                    if (W != W_trial)
                        goto broken;
                }
```

Third: find <ratio> attached (renamed to ratio.txt because otherwise I can't attach it).
[ratio.txt](https://github.com/HowardHinnant/date/files/8397575/ratio.txt)

**Comment by jcurru** [comment]
By the way: I need to transform GPS time to system_clock::time_point.
Does you library have something to accomplish this task?
Thanks again!

**Comment by HowardHinnant** [comment]
Ah, this is the Dinkumware std::lib.  The cause of the error is this constructor in `<ratio>`:

```c++
	ratio()
		{	// test constraints
		_STATIC_ASSERT2(_Dx != 0,
			"zero denominator");
		_STATIC_ASSERT2(-INTMAX_MAX <= _Nx,
			"numerator too negative");
		_STATIC_ASSERT2(-INTMAX_MAX <= _Dx,
			"denominator too negative");
		}
```

I believe that if you either mark this constructor with `constexpr` (it could use `noexcept` too), then the error will disappear.  Equivalently you could also just comment out that constructor.  It doesn't do anything but run some compile-time checks which always pass.

If this std::lib defines some identifying macro, such as a version (that no other std::lib implementation defines), then that could be used at https://github.com/HowardHinnant/date/blob/master/include/date/date.h#L98-L136 to target this environment.  It would mean that the date lib is inoperable for any complie-time computation (no `constexpr` functionality).

**Comment by HowardHinnant** [comment]
Here is an example program that converts `gps_time` to `sys_time`:

```c++
#include "date/tz.h"
#include <iostream>

int
main()
{
    using namespace date;
    using namespace std;
    using namespace std::chrono;

    auto tp_gps = gps_clock::now();
    cout << tp_gps << '\n';
    auto tp_sys = clock_cast<system_clock>(tp_gps);
    cout << tp_sys << '\n';
}
```
This just output for me:
```
2022-04-01 12:32:49.512020
2022-04-01 12:32:31.512020
```
Note the 18s difference, which is due to the leap seconds inserted since 1980-01-01.  `tp_gps` has type `std::chrono::time_point<date::gps_clock, std::chrono::microseconds>` and `tp_sys` is a `system_clock::time_point`.

This uses the "time_zone" part of the library which has a source file that needs to be compiled: tz.cpp.  Here are instructions for doing that:  https://howardhinnant.github.io/date/tz.html#Installation

This also requires the IANA time zone database (for the list of leap seconds).  It can either be downloaded, manually or automatically, or on many non-Windows platforms, comes installed with your OS.  The installation instructions linked previously detail these different options.

**Comment by jcurru** [comment]
> I believe that if you either mark this constructor with `constexpr` (it could use `noexcept` too), then the error will disappear. Equivalently you could also just comment out that constructor. It doesn't do anything but run some compile-time checks which always pass.

Right!

**Comment by jcurru** [comment]
> identifying macro

**Comment by jcurru** [comment]
> If this std::lib defines some identifying macro, such as a version (that no other std::lib implementation defines), then that could be used at https://github.com/HowardHinnant/date/blob/master/include/date/date.h#L98-L136 to target this environment. It would mean that the date lib is inoperable for any complie-time computation (no `constexpr` functionality).

My Dinkumware std::lib has _CPPLIB_VER = 803 as identifying macro. I couldn't tell you if the same problem will arise with different versions of the library
