### ISSUE TITLE
Consider making floor round to multiple of unit and with adjustable origin

### ISSUE THREAD

**Issue by rok** [HowardHinnant/date#777]
We've implemented [ceil/floor/round kernels in Arrow](https://github.com/apache/arrow/blob/589a847545da9c7164e99a58343bd44f187bcbee/cpp/src/arrow/compute/kernels/scalar_temporal_unary.cc#L740-L806) that round to an arbitrary multiple of units (physical or calendrical). We also allow for setting "temporal origin" from which to round to multiples. Would this be something you would consider implementing in `date.h` or accepting a PR?

**Comment by HowardHinnant** [comment]
Hi rok.  This looks very interesting and useful.  I am pleased that you were able to build this on top of `date.h`.

To date `date.h` has served as field experience for the C++20 additions to the std `<chrono>` library.  It is currently tracking the [std specification](http://eel.is/c++draft/#time) and not accepting any API not in this specification.

Should you propose your additions to the C++ committee and get them accepted, I would reconsider in order to continue to track the [std specification](http://eel.is/c++draft/#time).

**Comment by rok** [comment]
Hi Howard,

First of all thank you for developing and pushing `date.h` upstream!

I am not familiar with what submitting such a a proposal would encompass and how realistic it is to be accepted. My main motivation for proposing this be upstreamed is that I found it nontrivial to implement and test (especially when rounding in local time).
Could you comment on whether such a functionality makes sense in std?

**Comment by HowardHinnant** [comment]
To get something standardized is a huge investment involving years of commitment and almost certainly thousands of dollars in travel costs.  It begins with a [written proposal](https://isocpp.org/std/submit-a-proposal).  Such a proposal would include a specification of the proposed API.

Before I could comment on https://github.com/apache/arrow/blob/589a847545da9c7164e99a58343bd44f187bcbee/cpp/src/arrow/compute/kernels/scalar_temporal_unary.cc#L740-L806 I would need to see its documentation which should include some example uses.

**Comment by rok** [comment]
That's quite a process. Perhaps let's first discuss the motivation.

Documentation for the floor kernel (or rather it's Python wrapper) is here [1], C++ tests are here [2] and Python tests here [3].
The reason we implemented this was that Arrow compute kernels are looking to provide functions equivalent to ones provided in Python's Pandas [4] and R's lubridate [5]. These kernels are then exposed to C++ users as well as through Python/R/Ruby/Java wrappers.
As Pandas and Lubridate are numerical computation libraries I can't really say how used these features are, but I imagine groupbys on arbitrary time intervals are commonly done.

[1] https://arrow.apache.org/docs/python/generated/pyarrow.compute.floor_temporal.html
[2] https://github.com/apache/arrow/blob/0e752c8655685a0108c3eed3de27e7981db688c7/cpp/src/arrow/compute/kernels/scalar_temporal_test.cc#L2766-L2956
[3] https://github.com/apache/arrow/blob/589a847545da9c7164e99a58343bd44f187bcbee/python/pyarrow/tests/test_compute.py#L2211-L2235
[4] https://pandas.pydata.org/docs/reference/api/pandas.Timestamp.floor.html
[5] https://lubridate.tidyverse.org/reference/round_date.html

**Comment by HowardHinnant** [comment]
I don't know that such a functionality makes sense in the std.  I'm not familiar with Python's Pandas or R's lubridate.  And I'm not clear that if there are sufficiently large use cases where the rounded-to units must be run-time as opposed to compile-time information.

My approach to standardizing the C++20 chrono additions was to create a stand-alone library in its own namespace that added functionality to `std::chrono`, then see if the field experience was positive, negative, or largely ignored.  Perhaps you could use that approach as well.  I spent several years in the "gathering field experience" phase, where I also tried to inform the public of the library's existence through [public speaking](https://www.youtube.com/watch?v=tzyGjOm8AKo).

**Comment by rok** [comment]
> I don't know that such a functionality makes sense in the std. I'm not familiar with Python's Pandas or R's lubridate. And I'm not clear that if there are sufficiently large use cases where the rounded-to units must be run-time as opposed to compile-time information.

Unit choice should probably happen at compile time (in Arrow we needed to do it at run-time). Given your experience in the matter your opinion makes me reluctant to pursue the idea further until seeing more interest in the community.

> My approach to standardizing the C++20 chrono additions was to create a stand-alone library in its own namespace that added functionality to `std::chrono`, then see if the field experience was positive, negative, or largely ignored. Perhaps you could use that approach as well. I spent several years in the "gathering field experience" phase, where I also tried to inform the public of the library's existence through [public speaking](https://www.youtube.com/watch?v=tzyGjOm8AKo).

Thank you for outlining a potential approach, it's definitely one I'd pursue. In that vein - would you consider adding a "round to multiple" example to [Examples and Recipes](https://github.com/HowardHinnant/date/wiki/Examples-and-Recipes#get-milliseconds-since-the-local-midnight)? If there's some interest I would proceed making a small library and go from there. If it turns out this problem is too obscure a recipe could still help the few that encounter the problem.

**Comment by HowardHinnant** [comment]
I can do you one better.  :-)  The [Examples and Recipes](https://github.com/HowardHinnant/date/wiki/Examples-and-Recipes) is page is public-writable.  Most of the examples are mine, but a few are authored by others.  I just ask that you sign your article as the existing ones are signed.  Feel free to add any example here that you feel might be helpful to others.  I don't need to approve it.

**Comment by rok** [comment]
Perfect! I'll close this issue and chime back once I add a recipe. Thank you for the discussion!

**Comment by DavisVaughan** [comment]
I actually implemented exactly this in [clock](https://clock.r-lib.org/) as well

``` r
library(clock)

x <- as_sys_time(c(
  year_month_day(2019, 3, 4, 4),
  year_month_day(2019, 3, 5, 2),
  year_month_day(2019, 3, 6, 4)
))
x
#> <clock_sys_time[3]>
#> [1] "2019-03-04T04" "2019-03-05T02" "2019-03-06T04"

# Default origin of 1970-01-01 (i.e. 0)
time_point_floor(x, "day", n = 2)
#> <clock_sys_time[3]>
#> [1] "2019-03-03" "2019-03-05" "2019-03-05"


origin <- as_sys_time(year_month_day(2019, 3, 4))
origin
#> <clock_sys_time[1]>
#> [1] "2019-03-04"

time_point_floor(x, "day", n = 2, origin = origin)
#> <clock_sys_time[3]>
#> [1] "2019-03-04" "2019-03-04" "2019-03-06"
```

I went one layer deeper and ended up adding multi-unit rounding to _durations_ as well (without an `origin` argument). 

``` r
library(clock)

x <- duration_months(1:5)

duration_floor(x, "month", n = 2)
#> <duration<month>[5]>
#> [1] 0 2 2 4 4
```

Which means that time point flooring with an `origin` is just:
- Subtract off the origin
- Do (possibly multi unit) duration flooring
- Add origin back

as shown here https://github.com/r-lib/clock/blob/64c1a53a7df0b3f4c04555a03a6472450f8745ce/R/time-point.R#L726-L735
