### ISSUE TITLE
mkdir: cannot create directory ‘//Downloads’: Permission denied   

### ISSUE THREAD

**Issue by TomGarden** [HowardHinnant/date#781]
my environment , debian on docker container
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```

On my understand tzdata be download on first usage . 
the default download path is `~/Downloas/tzdata`
On my system `~/Downloas/tzdata` is exists . 
when I build new executable  , and run  , got the error . 
```
mkdir: cannot create directory ‘//Downloads’: Permission denied   
Timezone database not found at "//Downloads/tzdata"
```

about the executable which no crash ; 
I use cmmand line build to `project/build` directory . 

about the executable which with crash ;
I use clion build to `project/cmake-debug-build` directory

I don't know why , please try help me .  thanks .

**Comment by TomGarden** [comment]
Now  , I'm realy understand , but the reason is 
```
$ stat executable.run
  File: executable.run
  Size: 106749592       Blocks: 234632     IO Block: 4096   regular file
Device: 89h/137d        Inode: 2538530     Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (  501/ UNKNOWN)   Gid: (   20/ dialout)
Access: 2023-03-21 21:08:28.628214273 +0800
Modify: 2023-03-21 21:08:26.003557201 +0800
Change: 2023-03-21 21:08:26.004796823 +0800
 Birth: -
```
the Uid Gid , no permission operate `/home/username/Downloads`

**Comment by TomGarden** [comment]
result  , config clion toolchains , resolve my problem : https://www.jetbrains.com/help/clion/clion-toolchains-in-docker.html#sample-dockerfile

**Comment by HowardHinnant** [comment]
Thanks for the update.  Sorry I couldn't help.
