### ISSUE TITLE
[Question] Why are there two adjacent space characters (`0x20`) in the `what()` message of `ambiguous_local_time`?

### ISSUE THREAD

**Issue by JMazurkiewicz** [HowardHinnant/date#782]
Repro:

```c++
#include <chrono>
#include <date/tz.h>
#include <iostream>

int main() {
  using namespace date;
  using namespace std::chrono_literals;
  try {
    auto zt = zoned_time{"America/New_York",
                         local_days{Sunday[1] / November / 2016} + 1h + 30min};
  } catch (const ambiguous_local_time &e) {
    std::cout << e.what() << '\n';
  }
}
```

Result:

```console
$ g++ main.cpp -std=c++20 -I../include ../build/libdate-tz.a
$ ./a.out
2016-11-06 01:30:00 is ambiguous.  It could be
2016-11-06 01:30:00 EDT == 2016-11-06 05:30:00 UTC or
2016-11-06 01:30:00 EST == 2016-11-06 06:30:00 UTC
```

Why are there two space characters between *"ambiguous."* and *"It could"*? Is there any reason or is it just a typo?

If it is a typo:
* It looks like is has been here since the beginning: https://github.com/HowardHinnant/date/blame/master/include/date/tz.h#L265-L266,
* This typo made it into C++ standard: [[time.zone.exception.ambig]/3](http://eel.is/c++draft/time.zone.exception.ambig#3),
* https://github.com/microsoft/STL/pull/3650 should probably be closed without merging.

**Comment by HowardHinnant** [comment]
Blame it on my 2nd grade teacher ... and this: https://www.gocomics.com/bloom-county/2015/10/04

**Comment by JMazurkiewicz** [comment]
Thanks for explanation folks, to be honest I've never seen two spaces separating sentences (only one).

**Comment by JMazurkiewicz** [comment]
Thanks for explanation, to be honest I've never seen two spaces separating sentences (only one).
