### ISSUE TITLE
Month value off by one in year_month_day::from_day_point

### ISSUE THREAD

**Issue by ecorm** [HowardHinnant/date#8]
`year_month_day::from_day_point` computes the month in the range of [0, 11], at line [2220](https://github.com/HowardHinnant/date/blob/master/date.h#L2220). However, January is defined as having value 1 at line [1076](https://github.com/HowardHinnant/date/blob/master/date.h#L1076).

I assume that this is a simple off-by-one error, and that it wasn't intentional to have different value ranges for the month.

**Comment by HowardHinnant** [comment]
It isn't an error.  See http://howardhinnant.github.io/date_algorithms.html#civil_from_days for a painfully detailed description of this algorithm.

In this other section of the same paper: http://howardhinnant.github.io/date_algorithms.html#Yes,%20but%20how%20do%20you%20know%20this%20all%20really%20works?  the algorithm `civil_from_days` is unit tested for every day in the range of  +/- 1 million years (from `0000_y`), using months in the range [1, 12], corresponding to [Jan, Dec].

**Comment by ecorm** [comment]
D'oh! I'm sorry, it turned out to be a [Code 18](http://www.urbandictionary.com/define.php?term=Code+18) error. The error was in my conversion routines, and I had wrongly assumed that it came from `from_day_point` when I saw [0, 11]. I now see two lines over (at 2222) that is gets transformed to a range [1, 12].

I apologize for wasting your time.
