### ISSUE TITLE
Undefined symbol

### ISSUE THREAD

**Issue by amontse** [HowardHinnant/date#801]
Hello,

I am a user extensively using this date library for years. It is the first time I come across an undefined symbol issue. The demangled symbol of the undefined symbol is below:

date::time_zone::get_info_impl(std::__1::chrono::time_point<date::local_t, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> > >) const

It would be grateful if anyone can advise anything I have missed or incorrect in my usage. Thank you.

Best Regards,
Amon

**Comment by HowardHinnant** [comment]
This indicates that you are not compiling and/or linking against tz.cpp.

Here are the best instructions on how to do that, including specialized instructions for Apple OS's.

https://howardhinnant.github.io/date/tz.html#Installation
