### ISSUE TITLE
Consolidate detection of C++17 features like `std::chrono::floor`

### ISSUE THREAD

**Issue by ja11sop** [HowardHinnant/date#81]
Commit 59d9cfa breaks gcc 6+ and clang 3.8+ when `--std=c++1z` is set because the `_cplusplus` macro is defined as `201500` and `201406` respectively. In other words not whatever value it will be to indicate C++17 support. That `libc++` (I haven't checked) might already offer some of those features should be detected for separately, so the work-arounds in date.h are still provided for gcc and clang that build against `libstdc++`. (running Linux).

**Comment by HowardHinnant** [comment]
Thanks!  Please reopen this issue if this is not addressed by https://github.com/HowardHinnant/date/commit/845ce25bb7b715d5d53d8b2d14bb135c40082f94
