### ISSUE TITLE
Transform date::local_seconds and timezone offset to struct tm

### ISSUE THREAD

**Issue by iFuSiiOnzZ** [HowardHinnant/date#819]
Hi,

I was looking at the documentation but there seems to be no conversion between the `date::local_senconds` and `C data structure tm`. Using `std::localtime(local_time.time_since_epoch().count())` is not working properly. Any suggestions on how to achieve it?

Thank you!

**Comment by HowardHinnant** [comment]
Here's a brief article on interfacing with the C API: https://github.com/HowardHinnant/date/wiki/Examples-and-Recipes#Ccompatiblity
