### ISSUE TITLE
Opposite inner 'if' condition leads to a dead code block

### ISSUE THREAD

**Issue by tipok006** [HowardHinnant/date#822]
https://github.com/HowardHinnant/date/blob/0e65940a7fbc4ed617a1ee111a60311eccbead9a/include/date/date.h#L7751
https://github.com/HowardHinnant/date/blob/0e65940a7fbc4ed617a1ee111a60311eccbead9a/include/date/date.h#L7770

**Comment by HowardHinnant** [comment]
Fixed, thank you!
