### ISSUE TITLE
Could a new official version be released?

### ISSUE THREAD

**Issue by TheStormN** [HowardHinnant/date#828]
The last release is from 2021 - version 3.0.1.

Could we have another release please? We are using package management system and using a git hash id from the master branch is possible, but it will be much easier to track versions if we have another public release.

P.S. Be sure to also update CMakeLists.txt with the latest version tag if a new release is issued.

**Comment by tinloaf** [comment]
I especially think that the fix for #826 merits a new release. People who build with the latest compilers are currently unable to use a released version of this library.

**Comment by DDoS** [comment]
Yes please release a new version! If the library has been changed to "live at head" versioning, please let us know so I can update vcpkg to the new scheme.

**Comment by HowardHinnant** [comment]
I highly recommend "live at head".  "head" is always kept in a shippable state.

That being said, I will try to get one last release out in the next week.

**Comment by basilgello** [comment]
Bark bark :)

I would really like to skip 50 patches from kodi source tree just because the version is not tagged :(

**Comment by HowardHinnant** [comment]
I hear you.  Giving the parsing fixes some time to gel.  And trying to find time to review the most critical PR's first.  And I'm technically unable to review those PR's which involve make files.

Or I could just tag master as is...

**Comment by basilgello** [comment]
I can help you with make and cmake if needed

**Comment by HowardHinnant** [comment]
I'll take it.  Any PR tagged with CMake is yours.

**Comment by basilgello** [comment]
I managed to complete xbmc/xbmc#18727 and getting back here as promised last week:

* https://github.com/HowardHinnant/date/pull/808 - LGTM
* https://github.com/HowardHinnant/date/pull/806 - needs your opinion
* https://github.com/HowardHinnant/date/pull/795 - check in progress

I will be updating this post while progressing :)

**Comment by basilgello** [comment]
Thanks for new 3.0.2 tag @HowardHinnant ! This issue can be closed I think :)

**Comment by basilgello** [comment]
@Tachi107 Please upload new version to Debian :)

**Comment by basilgello** [comment]
@Tachi107 Makes sense to add #851 as a Debian patch for now, too!
