### ISSUE TITLE
Visual Studio 2013 compatibility

### ISSUE THREAD

**Issue by saschazelzer** [HowardHinnant/date#83]
Currently, the tz code compiles with Visual Studio 2015 but not with the 2013 version. Is Visual Studio 2013 compatibility something you would accept a PR for?

I have it compiling locally with mostly minor modifications. However, the fact that the `std::vector` implementation coming with VS 2013 does not support incomplete types as first template argument requires a little bit more surgery for the `zonelet` class. Let me know if you would accept such a PR in principle. Thanks!

**Comment by HowardHinnant** [comment]
I actually thought I did have VS-2013 compatibility (modulo constexpr).  If the compatibility doesn't make a complete mess of things, yes, I'm interested.  Though I fear the `zonelet` issue.  What's your plan there?

**Comment by saschazelzer** [comment]
Currently, the only way I can see is making the `zonelet` class declaration visible inside the `tz.h` header. In order to not duplicate the declaration, I would declare it inside a `detail` namespace in the `tz_private.h` header instead of using a nested class. Then that header can be included in `tz.h` in case we are using VS2013. In all other cases, the `tz_private.h` header would not be visible in the public API and header include directives would stay as they are now.

**Comment by HowardHinnant** [comment]
Currently `tz_private.h` depends on `tz.h`.  Can't set up a circular dependency.  However I see where you're going.  I just noticed that `Rule` is incomplete here:

https://github.com/HowardHinnant/date/blob/master/tz.h#L680

Is VS-2013 also unhappy about that?

**Comment by saschazelzer** [comment]
Yes, I would need to break that circular dependency. So for VS2013, the dependency would be other way around.

You are right, it is also unhappy about `std::vector<Rule>`. Basically everything in `tz_private.h` would need to be exposed inside `tz.h`.

**Comment by HowardHinnant** [comment]
If you can do that reverse dependency for VS-2013 only, I think that would be acceptable.  I'm ok with renaming `time_zone::zonelet` to `detail::zonelet`.  I just don't want to expose the `zonelet` and `Rule` API to "modern" compiler clients.

**Comment by saschazelzer** [comment]
Okay, that's also how I thought to do things. Thanks.
