### ISSUE TITLE
as is, the `date::format` cannot honour required precision for fractional seconds

### ISSUE THREAD

**Issue by acolomitchi** [HowardHinnant/date#85]
Low priority, can get around, but perhaps worth a note in documentation <br>(anyway, that was a "tasty" one to diagnose) 

Scenario exposing the issue: model a wallclock that ticks every quarter of a second<sup>_++_</sup> and list the ticks through `date::format` with _two decimal places_. <br>_++_ this implies the requirement of _between consecutive ticks, just increment the tick-count by one_

Code:

<pre>
using custom_dtype=
      std::chrono::duration&lt;std::uintmax_t, std::ratio<25,100>>
  // --------- picking the precision here, you see? ------^
;

template&lt;class Duration>
void tickTockThroughTheDay(
  date::local_time<Duration> startOfDay,
  std::uintmax_t tacks
) {
  startOfDay+=Duration{tacks};
  std::cout << date::format("%F %T", startOfDay) << std::endl;
}

int main() {
  std::cout << "-----" << std::endl;
  auto now=std::chrono::system_clock::now();
  auto sodTp=date::floor&lt;date::days>(now);
  date::local_time&lt;custom_dtype> startOfDay{sodTp.time_since_epoch()};
  for(uint i=0; i<4; i++) {
    tickTockThroughTheDay(startOfDay, i);
  }
}
</pre>

Note the seconds going like this:

<pre>
  {date} 00:00:00.0  < - oops loss of precision
  {date} 00:00:00.2  < - 
  {date} 00:00:00.5  < - 
  {date} 00:00:00.7  < -
</pre>

---

Analysis: the issue was traced in the

<pre>
    template<class CharT, class Traits>
    friend
    std::basic_ostream<CharT, Traits>&
    operator<<(std::basic_ostream<CharT, Traits>& os, const time_of_day_storage& t)
</pre>

operator, more specifically in the part which computes the required width for the decimal part of the seconds - the one making use of `ceil_log10/pow10` (currently around lines 2780-2790 of the `date.h` file). The algorithm is correct, however it is based on the assumption that the `duration::period::den` is a _reliable_ source for the required precision.<br>This assumption fails due to the CPP specification for the `std::ratio`, [namely the requirement of](http://en.cppreference.com/w/cpp/numeric/ratio/ratio)

> Both numerator and denominator are automatically reduced to the lowest terms. 

Honouring the requirement, the compiler (in my case `g++ 5.4.1 20160904` on ubuntu 14.04) reduces the `custom_dtype` to `std::chrono::duration&lt;std::uintmax_t, std::ratio<1,4>>` - even if the debug info (visible through variable listing while debugging) lists the type as declared - (I needed to insert 'spy writes' capturing the `num/dem` to understand what's happening).

---

Possible solutions:
1. do nothing but insert a note into documentation; _and/or_
2. adjust the `date::format` function to receive somehow the precision required by the user (extra argument or refining the format string to accept the precision for the `%S`/`%T` specifiers; Note: other programming languages/libs do provide such refinements); _and/or_
3. persuade the C++ standard committee that the use of `reducible ratios`may be improper in some areas (where the reducing operation may cause irrecoverable loss of semantics associated with a ratio). Perhaps a `stable ratio` or whatever-one-would-like-to-call-such-ratios which the compiler does not reduce may be created for such purposes (purpose of a `stable_ratio`: carry some user-intended semantics together with the `num/den` members.)

**Comment by HowardHinnant** [comment]
I'll try to document this better.  The fix here is to create a "precision duration" that represents the decimal-precision you want to format with, and convert to that on the way out to the format statement:
````
using precision = std::chrono::duration<typename Duration::rep, std::centi>;
std::cout << date::format("%F %T", date::floor<precision>(startOfDay)) << std::endl;
````

**Comment by acolomitchi** [comment]
> The fix here is to create a "precision duration" 
But of course. _If one is aware about the need_, the workaround is obvious.

**Comment by HowardHinnant** [comment]
Now fixed with a `format` rewrite.
