### ISSUE TITLE
Including Windows.h before date.h causes compile error

### ISSUE THREAD

**Issue by gabm** [HowardHinnant/date#87]
I'm working with VS2015 Update 3 in Visual C++. When I write:

```
#include <Windows.h>
#include "date.h"
```

I get an error here:
```
class year
{
    short y_;

public:
    explicit CONSTCD11 year(int y) NOEXCEPT;

    CONSTCD14 year& operator++()    NOEXCEPT;
    CONSTCD14 year  operator++(int) NOEXCEPT;
    CONSTCD14 year& operator--()    NOEXCEPT;
    CONSTCD14 year  operator--(int) NOEXCEPT;

    CONSTCD14 year& operator+=(const years& y) NOEXCEPT;
    CONSTCD14 year& operator-=(const years& y) NOEXCEPT;

    CONSTCD11 bool is_leap() const NOEXCEPT;

    CONSTCD11 explicit operator int() const NOEXCEPT;
    CONSTCD11 bool ok() const NOEXCEPT;

    static CONSTCD11 year min() NOEXCEPT; // <-------- error is here...
    static CONSTCD11 year max() NOEXCEPT;
};
```

```
warning C4003: not enough actual parameters for macro 'min'
date.h(323): error C2059: syntax error: '('
date.h(323): error C2143: syntax error: missing ',' before '?'
```

I'm not sure whether this is a relevant bug, because similar things also happen with other libraries. Switching the order of the includes solves the problem (date before Windows)

**Comment by nabijaczleweli** [comment]
`#define NOMINMAX` before `#include <windows.h>` or `#undef min# and `#undef max` after

**Comment by gabm** [comment]
Do you think, that date.h should solve this problem on its own by:

```
#ifdef min
   #undef min
#endif
#ifdef max
   #undef max
#endif
```

I'd provide a pull request if you want...

**Comment by HowardHinnant** [comment]
I'd rather not go down this path.  There are an infinite number of troublesome macros that various OS's can define (Windows is not alone in this insanity, Apple has done stupid stuff like this too).

**Comment by nabijaczleweli** [comment]
Agreed, this should be dealt with by usercode

**Comment by gabm** [comment]
Ok, I see your point. Makes sense...
