### ISSUE TITLE
date::format should implement an ostream version for convenience/performance reasons 

### ISSUE THREAD

**Issue by acolomitchi** [HowardHinnant/date#88]
Following issue #82, it would be desirable the `date::format` function gets an overload taking and returning an `ostream` parameter.

The implementation should keep into account Howard's notes on the problem

> The 2nd form also doesn't respect width and adjustfield formatters. And even if I create the 2nd form, it will still have to create ostringstream internally for %z and for %S and %T when the precision is finer than seconds (somewhat nullifying the performance argument).

**Comment by acolomitchi** [comment]
I just finished testing such a solution in a fork. Will publish and trigger a PR shortly.

**Comment by HowardHinnant** [comment]
This is now done with `to_stream`: https://howardhinnant.github.io/date/tz.html#to_stream
