### ISSUE TITLE
Timezone database did not install correctly

### ISSUE THREAD

**Issue by ksze** [HowardHinnant/date#94]
I just compiled my application with `-lcurl` and default options on Linux, which means:

- `INSTALL=~/Downloads`
- `HAS_REMOTE_API=1`
- `AUTO_DOWNLOAD=1`

But for some reason it is unable to automatically install tzdata correctly.

This is the error message I get when I run my application for the first time:

```
unreachable 0
: No such file or directory
terminate called after throwing an instance of 'std::runtime_error'
  what():  Timezone database version "2016f" did not install correctly to "/home/k_sze/Downloads/tzdata"
Aborted (core dumped)
```

I can see that the application downloaded tzdata2016f.tar.gz; it also automatically created the `~/Downloads/tzdata/` directory, but the directory is empty:

```
$ ls -l ~/Downloads/tzdata2016f.tar.gz
-rw-rw-r-- 1 k_sze k_sze 313286 Sep 28 18:12 /home/k_sze /Downloads/tzdata2016f.tar.gz
$ ls -al ~/Downloads/tzdata
total 8
drwxrwxr-x 2 k_sze k_sze 4096 Sep 28 18:12 .
drwxr-xr-x 5 k_sze k_sze 4096 Sep 28 18:12 ..
```

**Comment by HowardHinnant** [comment]
Sounds like problem with the untar phase.  Can you try compiling with `-DUSE_SHELL_API=1`?

**Comment by HowardHinnant** [comment]
Also please update at least to the commit made a couple hours ago labeled "Get local version from NEWS instead of Makefile".  Failure to do so will lead to excessive downloading of the tz database from the IANA website.

**Comment by ksze** [comment]
Ah, so the problem is that it's not finding the tar executable. Got it.

**Comment by HowardHinnant** [comment]
Hoping that's the problem.  If that isn't it, try me again. I'd love for this to work out of the box without hassles such as these.

**Comment by ksze** [comment]
I also tried adding something like this in tz.cpp:

```
#ifndef TAR_PATH
#define TAR_PATH "/usr/bin/tar"
#endif
```

And I can override the default tar path using a `-DTAR_PATH=\"/bin/tar\"` compiler flag. :)

**Comment by HowardHinnant** [comment]
And did that get you operational?

**Comment by ksze** [comment]
Yep

**Comment by ksze** [comment]
I just added an option to override the path to the tar binary here: https://github.com/ksze/date/commit/37677b709cbd571d3e3f67472308b649a1025384

**Comment by robert-git** [comment]
I ran into the same problem, tracked it down, and "fixed" it by adding a symlink from `/usr/bin/tar` to `/bin/tar`, and it worked, but that's not clean at all.   I like ksze's solution better, but even better than that would be if **tz.cpp** finds the path to `tar` automatically.  On a bash command line you can find the path to `tar` by typing `which tar`, but is there a C/C++ equivalent to the `which` command that can be used in `get_download_gz_file()` to automatically set `prog` to the actual path of `tar`?

**Comment by HowardHinnant** [comment]
Thanks for the patch Robert.

What are your thoughts about fixing this problem by just defaulting `USE_SHELL_API == 1`?  This causes `std::system` to be used and it will automatically find `tar` where ever it is.

**Comment by robert-git** [comment]
I missed that flag previously, but I just tried recompiling the library with that flag (`-DUSE_SHELL_API`), and it worked.  It was able to download and extract the TZ database file with no errors.  I'm wondering, why wouldn't that `USE_SHELL_API` flag be set by default?  Is it to discourage use of `std::system`?

**Comment by HowardHinnant** [comment]
That was the original intent, and now I am thinking that was a mistake.

**Comment by HowardHinnant** [comment]
I've defaulted `USE_SHELL_API` to 1 here:
https://github.com/HowardHinnant/date/commit/887d7574b197545a61dfd9d24cfab03f9053cd8d

**Comment by robert-git** [comment]
Howard,

I hadn't paid attention to that flag previously, but I just tried
recompiling the library with that flag (-DUSE_SHELL_API), and it worked.
It was able to download and extract the TZ database file with no errors,
using your original (unpatched) code.  I'm wondering, why wouldn't that
USE_SHELL_API flag be set by default?  Is it to discourage use of
std::system?

**Comment by HowardHinnant** [comment]
Yes, but I think that was a mistake.  `USE_SHELL_API == 1` is now the default.
