### ISSUE TITLE
date::format should throw std::logic_error instead of std::runtime_error

### ISSUE THREAD

**Issue by mdrost** [HowardHinnant/date#97]
`date::format` should throw `std::logic_error` instead of `std::runtime_error`. It should be `std::invalid_argument` or `std::domain_error`.

**Comment by HowardHinnant** [comment]
That's weird.  I know I wrote an explanation for closing this and now I don't see it.

The explanation went something like:

I'm using `logic_error` for to detect bugs in the implementation of this library, and `runtime_error` to detect bugs in client code (precondition violations).  The `logic_error` throws should eventually disappear as confidence is gained that they can't happen.

**Comment by mdrost** [comment]
> precondition violations

This is the exact purpose of `std::invalid_argument`. If you want your library to be part of the standard, then you should follow standard.

**Comment by HowardHinnant** [comment]
I'll give this more thought.

**Comment by jaakristioja** [comment]
Note that since `std::logic_error` most probably needs to copy the string passed to it during construction, it might also throw non-`logic_error` memory allocation exceptions in contexts where these are not expected. I apologize for being too pedantic and/or trolling.

**Comment by HowardHinnant** [comment]
Not at all, your input is appreciated.  `runtime_error` can also be translated into `bad_alloc` under the same conditions though.

**Comment by jaakristioja** [comment]
You're correct. Because of this tricky nature I've avoided the use of `<stdexcept>` exceptions in critical production code since when I discovered this issue.

**Comment by HowardHinnant** [comment]
A preliminary review for standardization pointed out that for consistency with other std-defined streaming, no exception should be throw, but instead `failbit` should be set.  I've done that here:  https://github.com/HowardHinnant/date/commit/ec412a1de044cbc97e5759b9f652d0696aeec911

**Comment by ecorm** [comment]
`std::format` throws `std::format_error` for invalid format strings, which derives from `std::runtime_error`.

When `date::format` sets `failbit`, it currently results in an `std::ios_base::failure` exception being thrown. See #570.
